In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
polls = pd.read_excel('data/polls/Rawpolls_040626.xlsx')
polls.head()

,poll_id_nate,question_id_538,race,year,location,type_simple,type_detail,pollster,pollster_rating_id,partisan,...,margin_poll,electiondate,cand1_actual,cand2_actual,margin_actual,error,bias,rightcall,advancedplusminus,comment
0,3306,3709.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,American Research Group,9,NaN,...,4.0,2008-01-03,34.95,31.23,3.72,0.28,NaN,0.0,-2.683431,NaN
1,3307,3711.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,Zogby Analytics,395,NaN,...,4.0,2008-01-03,34.95,31.23,3.72,0.28,NaN,1.0,-2.318028,for Reuters | C-SPAN
2,3326,3708.0,2008_Pres-R_IA,2008,IA,Pres-P,Pres-R,American Research Group,9,NaN,...,5.0,2008-01-03,34.41,25.23,9.18,4.18,NaN,1.0,-0.231506,NaN
3,3327,3710.0,2008_Pres-R_IA,2008,IA,Pres-P,Pres-R,Zogby Analytics,395,NaN,...,6.0,2008-01-03,34.41,25.23,9.18,3.18,NaN,1.0,-0.842899,for Reuters | C-SPAN
4,5847,17773.0,2012_Pres-R_IA,2012,IA,Pres-P,Pres-R,InsiderAdvantage,243,NaN,...,-5.0,2012-01-03,24.61,24.58,0.03,5.03,NaN,0.0,-1.336469,NaN

In [19]:
polls['rv'] = polls['comment'].str.contains(r'among registered voters').fillna(False)
polls['all_adu'] = polls['comment'].str.contains(r'among all adults').fillna(False)
polls['v'] = polls['comment'].str.contains(r"among 'voters'").fillna(False)
polls.head(2)

,poll_id_nate,question_id_538,race,year,location,type_simple,type_detail,pollster,pollster_rating_id,partisan,...,error,bias,rightcall,advancedplusminus,comment,rv,all_adu,sponsor,population,v
0,3306,3709.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,American Research Group,9,NaN,...,0.28,NaN,0.0,-2.683431,NaN,False,False,NaN,LV,False
1,3307,3711.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,Zogby Analytics,395,NaN,...,0.28,NaN,1.0,-2.318028,for Reuters | C-SPAN,False,False,Reuters | C-SPAN,LV,False

In [12]:
polls['sponsor'] = polls['comment'].str.extract(r'for ([A-za-z\.\s\,\-\d\|]+).*')
polls.head()

,poll_id_nate,question_id_538,race,year,location,type_simple,type_detail,pollster,pollster_rating_id,partisan,...,cand2_actual,margin_actual,error,bias,rightcall,advancedplusminus,comment,rv,all_adu,sponsor
0,3306,3709.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,American Research Group,9,NaN,...,31.23,3.72,0.28,NaN,0.0,-2.683431,NaN,False,False,NaN
1,3307,3711.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,Zogby Analytics,395,NaN,...,31.23,3.72,0.28,NaN,1.0,-2.318028,for Reuters | C-SPAN,False,False,Reuters | C-SPAN
2,3326,3708.0,2008_Pres-R_IA,2008,IA,Pres-P,Pres-R,American Research Group,9,NaN,...,25.23,9.18,4.18,NaN,1.0,-0.231506,NaN,False,False,NaN
3,3327,3710.0,2008_Pres-R_IA,2008,IA,Pres-P,Pres-R,Zogby Analytics,395,NaN,...,25.23,9.18,3.18,NaN,1.0,-0.842899,for Reuters | C-SPAN,False,False,Reuters | C-SPAN
4,5847,17773.0,2012_Pres-R_IA,2012,IA,Pres-P,Pres-R,InsiderAdvantage,243,NaN,...,24.58,0.03,5.03,NaN,0.0,-1.336469,NaN,False,False,NaN

In [15]:
np.unique(polls['sponsor'].astype(str))

array(['7News', 'AARP | Las Vegas Review-Journal', 'ABC27 News', 'AP',
       'AP | AOL News', 'AP | The Clarion-Ledger', 'AP | Yahoo News',
       'Abbot Academy Fund', 'Al Gross', 'Alabama Education Association',
       'Alaina Shearer', 'Alan LaPolice', 'Albuquerque Journal',
       'Alexi Giannoulias', 'American Association of Health Plans',
       'American Civics Exchange', 'Andrew Rocky Raczkowski',
       'Angie Craig', 'Angie Paccione', 'Ann Kirkpatrick',
       'Annette Taddeo', 'Argus Leader | KELO-TV',
       'Arizona Daily Star | KVOA', 'Arizona State',
       'Arthur N. Rupe Foundation | Reason Magazine', 'Aspiration',
       'Associated Industries of Florida', 'Atlanta Journal-Constitution',
       'Augusta Chronicle', 'Augusta Chronicle | Savannah Morning News',
       'Austin American-Statesman', 'Auto Alliance', 'Axiom Strategies',
       'Axios', 'BUSR', 'Babbage Cofounder', 'Baltimore Sun',
       'Baltimore Sun | University of Baltimore', 'Bangor Daily News',
       'Bangor Daily News | FairVote', 'Barbara Goolsbee Bollier',
       'Barney Frank', 'Bay News 9', 'Bay News 9 | News 13',
       'Bay News 9 | News 13  | Miami Herald | St. Petersburg Times',
       'Bay News 9 | Tampa Bay Times',
       'Bay News 9 | Tampa Bay Times | News 13  | Miami Herald | El Nuevo Herald',
       'Ben Ray Luj', 'Benjamin L. Cardin', 'Betty Sutton',
       'Big League Politics', 'Bill Cassidy', 'Bill Foster',
       'Bill McBride', 'Bill McCollum', 'Bloomberg',
       'Bloomberg | Newsweek', 'Bloomington Pantagraph | WEEK-TV',
       'Bluegrass Freedom Action', 'Bob Beauprez', 'Bob Clement',
       'Bob Franks', 'Bob Inglis', 'Bob Schaffer', 'Bob Turner',
       'Boston Globe', 'Boston Globe | USA Today',
       'Boston Globe | WBZ-TV', 'Boston Herald',
       'Boston Herald | Franklin Pierce University',
       'Boston Herald | Franklin Pierce University | NBC10 Boston | Telemundo Boston | NECN',
       'Brandwatch', 'Breitbart News', 'Brendan P. Doherty',
       'Brian P. Bilbray', 'Brookings Institute | CATO Institute',
       'Bruce L. Braley', 'Bruce Lunsford', 'Brynne S. Kennedy',
       'CBS News', 'CBS News | New York Times', 'CNBC', 'CNN',
       'CNN | LA Times | Politico', 'CNN | Time',
       'COMPETE_ | AMM Political Strategies', 'CT Examiner',
       'California Teachers Association', 'Calvin M. Dooley',
       'Capitol Fax', 'Carly Fiorina', 'Cedric Richmond',
       'Center for American Greatness', 'Charles Bass',
       'Charles D. Baker', 'Charles E. Schumer', 'Charlie Melancon',
       'Cheddar', 'Cheri Bustos', 'Chet Culver', 'Chicago Sun-Times',
       'Chicago Tribune', 'Chicago Tribune | WGN', 'Chip Cravaack',
       'Chris Christie', 'Chris Mitchum', 'Christine L. Jennings',
       'Christopher Murphy', 'Christopher P. Carney',
       'Christopher P. Gibson', 'Chuck Enderlin', 'Civitas Institute',
       'Claire McCaskill',
       'Claremont McKenna College Rose Institute of State and Local Government',
       'College of William and Mary', 'Commonwealth Network',
       'Consumer Energy Alliance', 'Cook Political Report',
       'Crooked Media', 'Daily Kos', 'Dallas Morning News',
       'Dallas Morning News | Houston Chronicle', 'Dan Debicella',
       'Dan Moody', 'Dan Sullivan', 'Daniel B. Maffei',
       'Daniel J. Halloran', 'Daniel Mongiardo', 'Danny O',
       'Darryl Roberts', 'Data for Progress', 'Deb Fischer',
       'Decision Desk HQ', 'Democratic Governors Association',
       'Denver Post', 'Denver Post | KUSA-TV ', 'Des Moines Register',
       'Des Moines Register | Bloomberg',
       'Des Moines Register | Mediacom', 'Deseret News',
       'Deseret News | Hinckley Institute of Politics',
       'Deseret News | KSL-TV', 'Desiree Tims', 'Detroit Free Press',
       'Detroit Free Press | WLNS TV 6 | WOOD TV 8 | WJRT ',
       'Detroit Free Press | WXYZ-TV ', 'Detroit News',
       'Detroit News | WDIV-TV', 'Detroit News | WXYZ-TV ',
       'Diageo | Hotline', 'Diane Benson', 'Diane D. Denish', 'Don Bacon',
       'Donald C. Bolduc', 'Doug R. Cloud', 'Downs Center',
       'E. Scott Rigell', 'East Tennessee State University', 'Economist',
       'Education Reform Now', 'Elections Daily', 'Eliot R. Cutler',
       'Elise M. Stefanik', 'Elizabeth H. Esty', 'Emily Ann Cain',
       'Erskine Bowles', 'FOX 13 Tampa Bay | FOX35 Orlando', 'FOX News',
       'FOX26 Houston | FOX7 Austin | Fox4 Dallas-Fort-Worth',
       'FOX35 Orlando', 'FairVote', 'Faith Horizon', 'First Coast News',
       'FiveThirtyEight', 'Florida Politics', 'Florida State University',
       'Florida Times-Union | FOX 13 Tampa Bay',
       'Florida Times-Union | FOX 13 Tampa Bay | FOX35 Orlando',
       'Fox 10 Phoenix', 'Fox 12 | Oregon Public Broadcasting',
       'Fox 12 | Oregon Public Broadcasting | Portland Tribune',
       'Fox 2 News Detroit', 'Fox 2 News Detroit | MIRS News Service',
       'Fox 29 Philadelphia WTXF', 'Fox 5 Atlanta',
       'Fox 5 Atlanta | Morris News Service', 'Fox 5 DC', 'Fox 8 ',
       'Francis Conole', 'Francisco R. Canseco',
       'Franklin Pierce University', 'Gabriel E. Gomez', 'Gannett',
       'Gary Anthony Hofmeister', 'George B. Fearing',
       'George K. Phillips', 'George Washington University',
       'George Washington University | Politico',
       'Georgia Newspaper Partnership', 'Glenn C. Nye',
       'Gordon Douglas Jones', 'Gray Television',
       'Gray Television | Alabama Daily News', 'Gretchen Whitmer',
       'Harold E. Ford Jr.', 'Harry E. Mitchell', 'Hartford Courant',
       'Hartford Courant | Sacred Heart University Institute for Public Policy and Civic Engagement',
       'Harvard CAPS', 'Hawaii News Now | The Honolulu Star-Advertiser',
       'Hayride',
       'Hearst Connecticut Media | Sacred Heart University Institute for Public Policy and Civic Engagement',
       'Heat Street', 'Heather A. Wilson', 'Heidi Ganahl',
       'Heidi Heitkamp', 'Herschel Junior Walker',
       'High Point University', 'Hiral Tipirneni',
       'Hofstra University Kalikow Center for the Study of the American Presidency',
       'Honolulu Civil Beat', 'Honolulu Star-Bulletin | KITV ',
       'Houston Chronicle', 'Houston Public Media',
       'Howey Politics Indiana',
       'Howey Politics Indiana | WTHR Channel 13', 'Huffington Post',
       'Human Events', 'IdahoPoliticsWeekly.com', 'Independent Women',
       'IndyPolitics.org', 'Inside Elections', 'Inside Michigan Politics',
       'Insider Advantage', 'Investor', 'Inweekly',
       'Iowa State University', 'J.D. Scholten', 'Jaime Harrison',
       'James D. Esch', 'James D. Oberweis', 'James E. Sherow',
       'James Marshall', 'James T. Walsh', 'Jeb Hensarling',
       'Jeff Fortenberry', 'Jessica Morse', 'Jim Bognet', 'Jim Bunning',
       'Jim Costa', 'Jim Hood', 'Jim Martin', 'Jim Renacci', 'Jim Ryan',
       'Jim Talent', 'Joe Donnelly', 'Joe Manchin, III', 'Joe Monahan',
       'Joel B. Pollak', 'John Fleming', 'John Hall', 'John James',
       'John Katko', 'John Kennedy', 'John Kitzhaber', 'John Koster',
       'John L. Mica', 'John R. Gregg', 'Jon Ossoff', 'Jon Tester',
       'Jonathan L. Barela', 'Josh Hawley', 'Josh Mandel',
       'Joyce Ann Elliott', 'Just the News', 'Justice At Stake',
       'Justin Amash', 'KAAL-TV', 'KABC-TV ', 'KAET-TV',
       'KARE-TV | St. Paul Pioneer Press | Minnesota Public Radio',
       'KATU-TV Portland', 'KATU-TV Portland | KING TV ', 'KCCI ',
       'KCRG-TV | Cedar Rapids Gazette', 'KCTS9', 'KCTV-TV Kansas City',
       'KCTV-TV Kansas City | KMOX 1120 Radio St. Louis', 'KDKA-TV ',
       'KELO-TV', 'KELO-TV | The Hill', 'KFOR-TV ', 'KFSN-TV Fresno',
       'KGTV-TV ', 'KHQ-TV', 'KING TV ', 'KLAS-TV Las Vegas',
       'KLAS-TV Las Vegas | The Hill',
       'KMOV-TV | KYTV-TV | KCTV-TV Kansas City | KOAM | KRCG-TV | KFVS | KYOU | WGEM',
       'KNXV-TV', 'KOB-TV ', 'KOCO-TV',
       'KOTA-TV Rapid City | KSFY-TV Sioux Falls | Aberdeen American News',
       'KPIX-TV ', 'KQED', 'KRQE-TV', 'KSDK-TV St. Louis',
       'KSDK-TV St. Louis | KCTV-TV Kansas City',
       'KSDK-TV St. Louis | KSHB | KSPR | KYTV-TV', 'KSN-TV Wichita',
       'KSN-TV Wichita | KOLR10', 'KSTP-TV Minneapolis',
       'KSTP-TV Minneapolis | KAAL-TV',
       'KSTP-TV Minneapolis | KAAL-TV | WDIO-TV Duluth',
       'KTHV-TV Little Rock', 'KTNV-TV 13', 'KTVM NBC Montana',
       'KTVT-CBS 11', 'KUSA-TV ', 'KUTV 2News', 'KVBC-TV Las Vegas',
       'KWCH-TV Wichita', 'KWTV-DT Oklahoma City',
       'KWTV-DT Oklahoma City | KOTV-DT Tulsa', 'KXAS-TV ', 'KYW-TV ',
       'Kansas City Star', 'Kathy C. Hochul', 'Kean University',
       'Ken Harbaugh', 'Ken Salazar', 'Kevin Cramer', 'Kevin Stitt',
       'KeystoneReport.com', 'Kirsten E. Gillibrand', 'Kristen Carlson',
       'L. Scott Bruun', 'LA Times', 'LA Times | USC', 'Lamar Alexander',
       'Larry Hogan', 'Las Vegas Review-Journal',
       'Las Vegas Review-Journal | KLAS-TV Las Vegas',
       'Las Vegas Sun | KNPR | Channel 8', 'Lee Enterprises',
       'Leonard L. Boswell', 'Leonard Lance', 'Let Freedom Ring',
       'Lexington Herald-Leader | AP | Bowling Green Daily News',
       'Liberty Nation', 'Lois Frankel', 'Lois Murphy',
       'Louisiana Association of Health Plans', 'Lucy McBath',
       'Lynn Jenkins', 'M. Michael Rounds', 'MIRS News Service',
       'MPR News', 'Maine Sunday Telegram', 'Mandela Barnes',
       'Mariannette Miller-Meeks', 'Mark Edward Souder', 'Mark Fernald',
       'Mark S. Critz', 'Mark Udall', 'Martha Coakley', 'Martin Heinrich',
       'Martin O', 'Mary Jo Kilroy', 'Mary L. Landrieu',
       'MassLive.com | WSHM', 'Matthew A. Doheny', 'Maurice D. Hinchey',
       'Max Burns', 'Maxine B. Moul', 'McClatchy Newspapers',
       'McClatchy Newspapers | MSNBC', 'Meg Whitman', 'Melissa Bean',
       'Miami Herald', 'Michael F. Feeley', 'Michael Ferguson',
       'Michael G. Fitzpatrick', 'Michael Peter Skelly',
       'Michelle Lujan Grisham', 'Mike Braun', 'Mike Pence',
       'Mimi Walters', 'MinnPost', 'Minneapolis Star Tribune',
       'Minneapolis Star Tribune | MPR News', 'Minuteman PAC',
       'Miranda Devine',
       'Missouri Newspapers | St Louis Post-Dispatch | Kansas City Star',
       'Missouri Scout', 'Missouri Times', 'Mitch McConnell',
       'Mobile Register | Birmingham News | Huntsville Times',
       'Mobile Register | WHNT-TV | Birmingham News',
       'Monmouth College  | KBUR', 'Morning Call', 'Morris Durham Davis',
       'NBC 4 California | KFI AM640', 'NBC 4 New York', 'NBC News',
       'NBC News | McClatchy Newspapers',
       'NBC News | Wall Street Journal',
       'NBC News | Wall Street Journal | NBC 4 New York', 'NPR',
       'NPR | PBS NewsHour', 'NY1', 'NY1 | NBC News', 'Nan Hayworth',
       'Nancy E. Boyda', 'Nancy Mace', 'Nate McMurray',
       'Nathan I. Shinagawa', 'National Journal', 'New Hampshire Journal',
       'New London Day', 'New York Daily News | WABC-TV ',
       'New York Post | Fox 5 New York', 'New York Times', 'NewsNation',
       'Newsday', 'Newsday | News 12', 'Newsmax', 'Newsweek', 'Nexstar',
       'Nexstar | NBC 4 Ohio', 'Nicholas Leibham', 'Nicholas V. Lampson',
       'Norm Coleman', 'Norma Smith', 'North State Journal',
       'Northstar Campaign Systems', 'Omaha World-Herald',
       'Omidyar Network', 'OnSight Public Affiars', 'PIX 11',
       'Painter Communications', 'Patricia R. Keever',
       'Patrick J. Murphy', 'Patrick Murphy', 'Patty Wetterling',
       'Paul Chabot', 'Paul Clements', 'Paul J. Carmouche',
       'Peter A. DeFazio', 'Peter Jacob', 'Pfizer', 'Philip English',
       'Pittsburgh Tribune-Review',
       'Pittsburgh Tribune-Review | WPXI-TV ', 'Piyush Amrit Jindal',
       'PoliticalIQ', 'Politico', 'Poll Project USA', 'PollSmart MR',
       'Portland Press Herald | Maine Sunday Telegram',
       'Portland Tribune',
       'Press-Register | Birmingham News | Huntsville Times',
       'Providence Journal', 'Puerto Rico Herald', 'Radio Isla 1320',
       'Ralph Lee Abraham', 'Randy Bryce', 'Raul Ruiz',
       'Raycom Media | KPLC', 'Raycom Media | WBRC-TV', 'Reboot Illinois',
       'Red Racing Horses', 'Reid | Cook Political Report', 'Reuters',
       'Reuters | C-SPAN', 'Reuters | Houston Chronicle | C-SPAN',
       'Reuters | MSNBC', 'Reuters | Reid | Cook Political Report',
       'Reuters | U. Virginia Center for Politics',
       'Reuters | Wall Street Journal', 'Rhode Island College',
       'Richard A. Hill', 'Richard Carmona', 'Richard Keller',
       'Richard Mourdock', 'Richard Renzi', 'Richard Stallings',
       'Rick Berg', 'Rick Scott', 'Robert C. Hayes', 'Robert Ehrlich Jr.',
       'Robert Hurt', 'Robert P. Casey Jr.', 'Robert R. Simmons',
       'Robert Stefanowski', 'Robert Y. Cornilles', 'Robin Carnahan',
       'Rocky Mountain Poll', 'Rod Blagojevich', 'Rod Blum', 'Roll Call',
       'Ron DeSantis', 'Ron Johnson', 'Ron Kirk', 'Ron Klein',
       'Ron Lewis', 'Roosevelt Strategy Group', 'Rosetta Stone',
       'Ross Spano', 'Roy Cho',
       'San Diego Union-Tribune | University of San Diego', 'Sarah Palin',
       'Savannah Morning News', 'Saxby Chambliss', 'Sayfie Review',
       'Scott DesJarlais', 'Scott Kirkland', 'Scott Kleeb', 'Scott Milne',
       'Scott Perry', 'Scott Peters', 'ScottRasmussen.com',
       'Sean Patrick Maloney', 'Sean S. Eldridge', 'Shelley Berkley',
       'Shelli Yoder', 'Simpson College',
       'Southern California News Group | KABC-TV ', 'Spectrum News',
       'Spectrum News | Syracuse.com', 'St Louis Post-Dispatch',
       'St Louis Post-Dispatch | KMOV-TV',
       'St Louis Post-Dispatch | WDAF-TV | Kansas City Star',
       'Stanford University', 'Stephen Daniel', 'Stephen Lee Fincher',
       'Stephens Media Group | Arkansas News Bureau',
       'Stephens Media Group | Arkansas News Bureau | KATV-TV ',
       'Stevan Pearce', 'Steve King', 'Steven Palazzo',
       'Sunshine State News', 'Susan Wright', 'Susana Martinez',
       'Suzanne Haik Terrell', 'Syracuse.com',
       'TCPalm.com | WPTV | FL Democracy 2012', 'TEGNA | WFAA-TV',
       'TSG Consulting', 'Talk Business ', 'Tammy Baldwin',
       'Tammy Duckworth', 'Tari Renner', 'Terry Hayes', 'Texas Tribune',
       'Texas Tribune | University of Texas',
       'The Absolute Truth with Emerald Robinson', 'The Arizona Republic',
       'The Canadian Press', 'The Courier-Journal', 'The Guardian',
       'The Hill', 'The Hill | KRQE-TV', 'The Hill | Nexstar',
       'The Hill | PIX 11', 'The Hill | WFRV-TV', 'The Hill | WGHP',
       'The Hill | WJBF', 'The Hill | WTNH',
       'The Honolulu Star-Advertiser',
       'The Honolulu Star-Advertiser | News 8 Hawaii',
       'The Illinois Observer', 'The Independent',
       'The Ledger | 10 News WTSP', 'The Nevada Independent',
       'The Oklahoman', 'The Oregonian', 'The Oregonian | KGW-TV',
       'The Philadelphia Inquirer', 'The Post and Courier',
       'The Post and Courier | WCIV-TV', 'The Salt Lake Tribune',
       'The Spokesman-Review', 'The Times Leader', 'The Times-Picayune',
       'The Town Talk', 'The Washington Post', 'The Washington Times',
       'Thomas E. Hayhurst', 'Thomas Edwards', 'Thomas J. Rooney',
       'Thomas M. Barrett', 'Thomas Reiser', 'Thomas Roland Tillis',
       'Tim Burns', 'Tim Griffin', 'Tim Johnson', 'Tim Walberg', 'Time',
       'Time Warner Cable News', 'Timothy H. Bishop', 'Tina Kotek',
       'Todd Akin', 'Todd Lally',
       'Toledo Blade | Pittsburgh Post Gazette',
       'Toledo Blade | WTVG-TV ', 'Tom Daschle', 'Tom Emmer',
       'Tom Latham', 'Tom McClintock', 'Tom S. Perriello', 'Tom Steyer',
       'Tom Vilsack', 'Tommy Tuberville', 'Tracy Mitrano',
       'Travis W. Childers', 'Tulsa World', 'Tulsa World | KOTV-DT Tulsa',
       'U.S. News ', 'UC Berkeley', 'UMass Amherst',
       'UMass Amherst | WBZ-TV', 'UMass Amherst | WCVB-TV', 'UPI',
       'USA Today', 'USA Today | CNN', 'USC Dornsife', 'USC Price',
       'University of Delaware', 'University of Denver',
       'University of Houston',
       'University of Maryland Program on International Policy Attitudes',
       'University of Massachusetts - Lowell',
       'University of Pennsylvania', 'University of Texas Dallas',
       'University of Wisconsin', 'Univision',
       'Univision | Arizona State University Center for Latina',
       'Univision | El Vocero',
       'Univision | Northern Arizona University Department of Politics and International Affairs | Arizona State University Center for Latina',
       'Univision | The Washington Post', 'Univision | UnidosUS',
       'Univision | University of Houston', 'Valley News Live',
       'Van Tran', 'Vanderbilt', 'Vermont Public Radio', 'Vern Buchanan',
       'Voter.com', 'WABC-TV ', 'WABE 90.1', 'WANF | WPCH-TV', 'WAPT-TV ',
       'WBRE-TV | WYOU-TV', 'WBUR', 'WBZ-TV', 'WCAU-TV Philadelphia',
       'WCAU-TV Philadelphia | WABC-TV ',
       'WCAU-TV Philadelphia | WMAR-TV ', 'WCAX', 'WCMH-TV Columbus',
       'WCMH-TV Columbus | WCPO-TV Cincinnati | WKYC-TV Cleveland',
       'WCPO-TV Cincinnati', 'WCSC-TV Charleston | WSPA-TV Greenville',
       'WCSH-TV ', 'WDBJ-TV ', 'WFAA-TV', 'WFLA-TV', 'WFLA-TV | WKRG-TV ',
       'WFLA-TV | WPTV | WPLG-TV ', 'WFLD-FOX 32 Chicago', 'WFMZ-TV',
       'WGAL | Philadelphia Daily News', 'WGBH News', 'WGN | The Hill',
       'WGRZ-TV', 'WGRZ-TV | Buffalo News',
       'WGRZ-TV | Journal News | Rochester Democrat ', 'WHAS-TV',
       'WHAS-TV | The Courier-Journal', 'WHAS-TV | WCPO-TV Cincinnati',
       'WHAS-TV | WLEX-TV ', 'WHEC-TV', 'WHO-HD', 'WHO-TV ',
       'WHTM-TV | The Hill', 'WJAR ', 'WJLA-TV ', 'WKRG-TV ',
       'WKYT-TV | Lexington Herald-Leader',
       'WKYT-TV | Lexington Herald-Leader | WHAS-TV | The Courier-Journal',
       'WLBT ', 'WLNS TV 6', 'WMOV Radio', 'WMUR', 'WMUR | CNN',
       'WMUR | FOX News | WCVB-TV', 'WNBC', 'WNYT-TV',
       'WNYT-TV | WGRZ-TV | WHEC-TV | WABC-TV ',
       'WNYT-TV | WHEC-TV | WABC-TV ', 'WOAI-TV ', 'WOOD TV 8', 'WPRI-TV',
       'WPRI-TV | Roger Williams University', 'WPRI-TV | WNAC-TV',
       'WPTV | WFTX-TV ', 'WRAL News',
       'WRBL News 3 | Columbus Ledger-Enquirer | PMB Broadcasting',
       'WRC-TV ', 'WRGB-TV ', 'WSB-TV',
       'WSB-TV | Atlanta Journal-Constitution', 'WSB-TV | Rosetta Stone',
       'WSLS-TV ', 'WSMV', 'WSOC-TV', 'WSVN', 'WTHR Channel 13',
       'WTHR Channel 13 | Indianapolis Star', 'WTMJ-TV ',
       'WTVD-TV Raleigh', 'WTVD-TV Raleigh | WBTV ', 'WWL-TV',
       'WWNY-7 News', 'WXIA-TV', 'WXIA-TV | WLTX-TV ',
       'WXIA-TV | WMAZ-TV', 'WXYZ-TV ', 'WZZM 13', 'WZZM 13 | WDIV-TV',
       'Wall Street Journal', 'Wall Street Journal | NBC 4 New York',
       'Walt Minnick', 'Washington Free Beacon', 'Watchdog.org',
       'Wayne A. Allard', 'Wesley Hunt', 'West Virginia MetroNews',
       'William E. Hedrick', 'William F. Owens', 'William Gordon Ball',
       'William L. Owens', 'Winsome Sears', 'Wisconsin Public Radio',
       'Wisconsin Public Radio | WISC-TV ',
       'Wisconsin Public Radio | Wisconsin Public Television | Wisconsin State Journal | WISC-TV ',
       'Wish-TV | WSBT', 'Women', 'Xochitl Torres Small', 'Y',
       'Yahoo News', 'Young Kim', 'Zach Nunn', 'lehighvalleylive.com',
       'nan', 'unspecified Democratic sponsor',
       'unspecified Republican sponsor', 'zpolitics'], dtype=object)

In [10]:
polls['rv'].value_counts()

rv
False    11782
True       568
Name: count, dtype: int64

In [20]:
polls['population'] = polls.apply(lambda x: 'A' if x['all_adu'] == True else ('RV' if x['rv'] == True else 
                                                                              ('V' if x['v'] == True else 'LV')), axis=1)
polls.head()

,poll_id_nate,question_id_538,race,year,location,type_simple,type_detail,pollster,pollster_rating_id,partisan,...,error,bias,rightcall,advancedplusminus,comment,rv,all_adu,sponsor,population,v
0,3306,3709.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,American Research Group,9,NaN,...,0.28,NaN,0.0,-2.683431,NaN,False,False,NaN,LV,False
1,3307,3711.0,2008_Pres-D_IA,2008,IA,Pres-P,Pres-D,Zogby Analytics,395,NaN,...,0.28,NaN,1.0,-2.318028,for Reuters | C-SPAN,False,False,Reuters | C-SPAN,LV,False
2,3326,3708.0,2008_Pres-R_IA,2008,IA,Pres-P,Pres-R,American Research Group,9,NaN,...,4.18,NaN,1.0,-0.231506,NaN,False,False,NaN,LV,False
3,3327,3710.0,2008_Pres-R_IA,2008,IA,Pres-P,Pres-R,Zogby Analytics,395,NaN,...,3.18,NaN,1.0,-0.842899,for Reuters | C-SPAN,False,False,Reuters | C-SPAN,LV,False
4,5847,17773.0,2012_Pres-R_IA,2012,IA,Pres-P,Pres-R,InsiderAdvantage,243,NaN,...,5.03,NaN,0.0,-1.336469,NaN,False,False,NaN,LV,False

In [21]:
polls['population'].value_counts()

population
LV    11695
RV      568
V        49
A        38
Name: count, dtype: int64