In [191]:
import warnings
warnings.filterwarnings('ignore')

In [192]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import ast

In [193]:
pd.set_option('display.max_columns', 200)

In [194]:
# Claude generated for 2012 dataset
dem_cand_stand = {
    'Adam B Schiff': 'Adam Schiff',
    'Andre Carson': 'André Carson',
    'Ann Mclane Kuster': 'Ann McLane Kuster',
    'Anna G Eshoo': 'Anna Eshoo',
    'Anthony J Flaccavento': 'Anthony Flaccavento',
    'Bennie G Thompson': 'Bennie Thompson',
    'Betty Mccollum': 'Betty McCollum',
    'Bill Pascrell Jr': 'Bill Pascrell',
    'Bobby L Rush': 'Bobby Rush',
    'C A Dutch Ruppersberger': 'Dutch Ruppersberger',
    'Carolyn B Maloney': 'Carolyn Maloney',
    'Charles Kendall Hatchett': 'Charles Hatchett',
    'Colleen W Hanabusa': 'Colleen Hanabusa',
    'Collin C Peterson': 'Collin Peterson',
    'Daniel B Maffei': 'Dan Maffei',
    'Daniel Lipinski': 'Dan Lipinski',
    'Daniel T Kildee': 'Dan Kildee',
    'Danny K Davis': 'Danny Davis',
    'David E Price': 'David E. Price',
    'David Loebsack': 'Dave Loebsack',
    'David N Cicilline': 'David Cicilline',
    'Debra Freidell Wirth': 'Debra Wirth',
    'Denny Heck': 'Dennis Heck',
    'Diana Degette': 'Diana DeGette',
    'Donald M Payne Jr': 'Donald Payne Jr.',
    'Donna F Edwards': 'Donna Edwards',
    'Donna M Mcaleer': 'Donna McAleer',
    'Doris O Matsui': 'Doris Matsui',
    'Elijah E Cummings': 'Elijah Cummings',
    'Filemon Vela': 'Filemon Vela Jr.',
    'Frank Pallone Jr': 'Frank Pallone',
    'G K Butterfield': 'G. K. Butterfield',
    'Gloria Bromell Tinubu': 'Gloria Tinubu',
    'Grace F Napolitano': 'Grace Napolitano',
    'Gregory W Meeks': 'Gregory Meeks',
    'Hakeem S Jeffries': 'Hakeem Jeffries',
    'James A Himes': 'Jim Himes',
    'James R Langevin': 'James Langevin',
    'Janice D Schakowsky': 'Jan Schakowsky',
    'Jerry Mcnerney': 'Jerry McNerney',
    'Jim Mcdermott': 'Jim McDermott',
    'John A Yarmuth': 'John Yarmuth',
    'John B Larson': 'John Larson',
    'John C Carney': 'John Carney',
    'John Conyers Jr': 'John Conyers',
    'John Delaney': 'John K. Delaney',
    'John Lewis': 'John Robert Lewis',
    'John P Sarbanes': 'John Sarbanes',
    'Jose E Serrano': 'Jose Serrano',
    'Joseph P Kennedy Iii': 'Joseph Kennedy III',
    'Kenneth S Stepp': 'Kenneth Stepp',
    'Linda T Sanchez': 'Linda Sánchez',
    'Louise Mcintosh Slaughter': 'Louise Slaughter',
    'Luis V Gutierrez': 'Luis Gutiérrez',
    'Manan M Trivedi': 'Manan Trivedi',
    'Mary M Headrick': 'Mary Headrick',
    'Matthew A Cartwright': 'Matt Cartwright',
    'Michael F Doyle': 'Mike Doyle',
    'Nick J Rahall Ii': 'Nick Rahall',
    'Nita M Lowey': 'Nita Lowey',
    'Pete P Gallego': 'Pete Gallego',
    'Peter A Defazio': 'Peter DeFazio',
    'Peter J Visclosky': 'Pete Visclosky',
    'Raul M Grijalva': 'Raúl Grijalva',
    'Richard Nolan': 'Rick Nolan',
    'Robert A Brady': 'Bob Brady',
    'Robert C \\"Bobby\\" Scott': 'Bobby Scott',
    'Rosa L Delauro': 'Rosa DeLauro',
    'Ruben Hinojosa': 'Rubén Hinojosa',
    'Sander M Levin': 'Sander Levin',
    'Sanford D Bishop Jr': 'Sanford Bishop',
    'Shirley J Mckellar': 'Shirley McKellar',
    'Steny H Hoyer': 'Steny Hoyer',
    'Stephen F Lynch': 'Stephen Lynch',
    'Steven A Horsford': 'Steven Horsford',
    'Susan A Davis': 'Susan Davis',
    'Suzan Delbene': 'Suzan DelBene',
    'Tawana W Cadien': 'Tawana Walter-Cadien',
    'Terri A Sewell': 'Terri Sewell',
    'Timothy H Bishop': 'Tim Bishop',
    'Timothy J Walz': 'Tim Walz',
    'Val B Demings': 'Val Demings',
    'William Bronson': 'Will Bronson',
    'William L Enyart': 'Bill Enyart',
    'William R Keating': 'Bill Keating',
    'William R Smith': 'William Smith',
    'Yvette D Clarke': 'Yvette Clarke',
}
 
rep_cand_stand = {
    'Andy Harris': 'Andrew P. Harris',
    'Candice S Miller': 'Candice Miller',
    'Cathy Mcmorris Rodgers': 'Cathy McMorris Rodgers',
    'Charles J \\"Chuck\\" Fleischmann': 'Chuck Fleischmann',
    'Charles K Djou': 'Charles Djou',
    'Charles W Dent': 'Charlie Dent',
    'Christopher H Smith': 'Chris Smith',
    'Christopher P Gibson': 'Chris Gibson',
    'Cynthia M Lummis': 'Cynthia Lummis',
    'Darrell E Issa': 'Darrell Issa',
    'David B Mckinley': 'David McKinley',
    'David G Reichert': 'Dave Reichert',
    'David G Valadao': 'David Valadao',
    'David P Joyce': 'David Joyce',
    'Doug La Malfa': 'Doug LaMalfa',
    'Duncan Hunter': 'Duncan D. Hunter',
    'E Scott Rigell': 'Scott Rigell',
    'Edward R Royce': 'Ed Royce',
    'F James Sensenbrenner Jr': 'Jim Sensenbrenner',
    'Frank A Lobiondo': 'Frank LoBiondo',
    'Frank C Guinta': 'Frank Guinta',
    'Frank D Lucas': 'Frank Lucas',
    'Gus M Bilirakis': 'Gus Bilirakis',
    'H Morgan Griffith': 'Morgan Griffith',
    'J Randy Forbes': 'Randy Forbes',
    'James B Renacci': 'Jim Renacci',
    'Janice E Arnold-Jones': 'Janice Arnold-Jones',
    'Jefferson L Byrd': 'Jeff Byrd',
    'John Abney Culberson': 'John Culberson',
    'John L Mica': 'John Mica',
    'John R Carter': 'John Carter',
    'Joseph J Heck': 'Joe Heck',
    'Joseph Mccray Sr': 'Joseph McCray Sr.',
    'Joseph R Pitts': 'Joseph R. Pitts',
    'K Michael Conaway': 'Mike Conaway',
    'Keith J Rothfus': 'Keith Rothfus',
    'Kristi L Noem': 'Kristi Noem',
    'Mark E Amodei': 'Mark Amodei',
    'Marlin A Stutzman': 'Marlin Stutzman',
    'Martha Mcsally': 'Martha McSally',
    'Mia B Love': 'Mia Love',
    'Michael C Burgess': 'Michael Burgess',
    'Michael G Fitzpatrick': 'Mike Fitzpatrick',
    'Michael G Grimm': 'Michael Grimm',
    'Michael K Simpson': 'Mike Simpson',
    'Michael R Turner': 'Mike Turner',
    'Michael T Mccaul': 'Michael McCaul',
    'Nan A S Hayworth': 'Nan Hayworth',
    'Patrick J Tiberi': 'Pat Tiberi',
    'Patrick Meehan': 'Pat Meehan',
    'Patrick T Mchenry': 'Patrick McHenry',
    'Paul A Gosar': 'Paul Gosar',
    'Peter J Roskam': 'Peter Roskam',
    'Peter T King': 'Peter T. King',
    'Raul R Labrador': 'Raul Labrador',
    'Reid J Ribble': 'Reid Ribble',
    'Renee L Ellmers': 'Renee Ellmers',
    'Richard B Nugent': 'Rich Nugent',
    'Richard R Tisei': 'Richard Tisei',
    'Robert B Aderholt': 'Robert Aderholt',
    'Robert E Latta': 'Bob Latta',
    'Robert J Dold': 'Bob Dold',
    'Robert J Wittman': 'Rob Wittman',
    'Robert T Schilling': 'Bobby Schilling',
    'Rodney Davis': 'Rodney L. Davis',
    'Rodney P Frelinghuysen': 'Rodney Frelinghuysen',
    'Ron Desantis': 'Ron DeSantis',
    'Scott Desjarlais': 'Scott DesJarlais',
    'Scott R Tipton': 'Scott Tipton',
    'Sean P Duffy': 'Sean Duffy',
    'Stephen Lee Fincher': 'Stephen Fincher',
    'Steve Southerland Ii': 'Steve Southerland',
    'Steven M Palazzo': 'Steven Palazzo',
    'Steven Pearce': 'Steve Pearce',
    'Thomas J Rooney': 'Tom Rooney',
    'Todd C Young': 'Todd Young',
    'Tom Mcclintock': 'Tom McClintock',
    'Walter B Jones': 'Walter B. Jones Jr.',
}

In [195]:
data = pd.read_csv('transformed/past_house_results.csv')
data = data[data['year'] == 2012]
data.head(10)

,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,dem_inc,rep_inc,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct
0,2012,Alabama,AL,False,1,NaN,196374.0,200676,[],Jo Bonner,[],True,[],564463.0,NaN,NaN,NaN,0.00,564463.00,564463.00,0.000000,100.000000
1,2012,Alabama,AL,False,2,103092.0,180591.0,283953,Therese Ford,Martha Roby,False,True,0,480059.23,283683.0,36.340563,63.659437,0.00,480059.23,480059.23,0.000000,100.000000
2,2012,Alabama,AL,False,3,98141.0,175306.0,273930,John Andrew Harris,Mike Rogers,False,True,1744.0,474560.95,273447.0,35.890319,64.109681,1744.00,474560.95,476304.95,0.366152,99.633848
3,2012,Alabama,AL,False,4,69706.0,199071.0,269118,Daniel H Boman,Robert B Aderholt,False,True,2400.0,534734.58,268777.0,25.934511,74.065489,2400.00,534734.58,537134.58,0.446815,99.553185
4,2012,Alabama,AL,False,5,101772.0,189185.0,291293,Charlie L Holley,Mo Brooks,False,True,33555.03,426014.35,290957.0,34.978365,65.021635,33555.03,426014.35,459569.38,7.301407,92.698593
5,2012,Alabama,AL,False,6,88267.0,219262.0,308102,Penny H Bailey,Spencer Bachus,False,True,22236.0,1128152.4,307529.0,28.702009,71.297991,22236.00,1128152.40,1150388.40,1.932912,98.067088
6,2012,Alabama,AL,False,7,232520.0,73835.0,306558,Terri A Sewell,Don Chamberlain,True,False,504236.47,4009.0,306355.0,75.898875,24.101125,504236.47,4009.00,508245.47,99.211208,0.788792
7,2012,Alaska,AK,False,0,82927.0,185296.0,289804,Sharon M Cissna,Don Young,False,True,13818.0,624494.86,268223.0,30.917185,69.082815,13818.00,624494.86,638312.86,2.164769,97.835231
8,2012,Arizona,AZ,False,1,122774.0,113594.0,251595,Ann Kirkpatrick,Jonathan Paton,False,False,1744948.48,954249.7,236368.0,51.941887,48.058113,1744948.48,954249.70,2699198.18,64.646920,35.353080
9,2012,Arizona,AZ,False,2,147338.0,144884.0,292279,Ron Barber,Martha Mcsally,False,False,1790921.28,1094326.27,292222.0,50.419886,49.580114,1790921.28,1094326.27,2885247.55,62.071668,37.928332

In [196]:
data.shape

(435, 22)

In [197]:
data['district_code'] = data['state_po'] + '-' + data['district'].map(lambda x: f'0{x}' if x < 10 else str(x))
data.head(3)

,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,dem_inc,rep_inc,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct,district_code
0,2012,Alabama,AL,False,1,NaN,196374.0,200676,[],Jo Bonner,[],True,[],564463.0,NaN,NaN,NaN,0.0,564463.00,564463.00,0.000000,100.000000,AL-01
1,2012,Alabama,AL,False,2,103092.0,180591.0,283953,Therese Ford,Martha Roby,False,True,0,480059.23,283683.0,36.340563,63.659437,0.0,480059.23,480059.23,0.000000,100.000000,AL-02
2,2012,Alabama,AL,False,3,98141.0,175306.0,273930,John Andrew Harris,Mike Rogers,False,True,1744.0,474560.95,273447.0,35.890319,64.109681,1744.0,474560.95,476304.95,0.366152,99.633848,AL-03

In [198]:
trainset = pd.read_csv('transformed/data_2014.csv')
trainset.head(8)

,Unnamed: 0,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,dem_inc,rep_inc,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,seat_number,prev_lean,prev2_lean,dem_2p_prev,dem_2p_prev2,generic_ballot_avg,ics,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,urban_pct,rural_pct,dem_2p_12,demo_cluster,district_id
0,0,2014,Alabama,AL,False,AL-01,48278.0,103758.0,152234,Burton R Leflore,Bradley Byrne,False,True,33474.0,914507.3,152036.0,31.754321,68.245679,33474.00,914507.30,947981.30,3.531082,96.468918,0.0,0.0,0.0,0.0,1,-14.281877,-14.995432,37.681985,38.693415,2.645942,88.8,36.667551,34.624569,25.603608,2.096047,0.000000,6.9,456228.0,226592.0,66.815266,33.184734,NaN,4,AL01
1,1,2014,Alabama,AL,False,AL-02,54692.0,113103.0,167952,Erick Wright,Martha Roby,False,True,6674.0,454019.64,167795.0,32.594535,67.405465,6674.00,454019.64,460693.64,1.448685,98.551315,0.0,0.0,0.0,0.0,2,-15.288962,-18.500155,36.674900,35.188692,2.645942,88.8,23.382560,35.232068,31.469761,9.353024,0.281294,6.3,373585.0,309235.0,54.712076,45.287924,NaN,4,AL02
2,2,2014,Alabama,AL,False,AL-03,52816.0,103558.0,156620,Jesse T Smith,Mike Rogers,False,True,2100.0,504511.67,156374.0,33.775436,66.224564,2100.00,504511.67,506611.67,0.414519,99.585481,0.0,0.0,0.0,0.0,3,-14.821901,-16.778726,37.141962,36.910121,2.645942,88.8,27.699719,35.246889,26.977118,15.134484,0.160578,6.7,343078.0,339741.0,50.244355,49.755645,NaN,4,AL03
3,3,2014,Alabama,AL,False,AL-04,NaN,132831.0,134752,[],Robert B Aderholt,[],True,[],419784.54,NaN,NaN,NaN,0.00,419784.54,419784.54,0.000000,100.000000,0.0,0.0,0.0,0.0,4,-27.698357,-27.856598,24.265506,25.832249,2.645942,88.8,15.701854,24.744608,53.234960,3.140371,0.189179,4.7,236405.0,446414.0,34.621913,65.378087,NaN,4,AL04
4,4,2014,Alabama,AL,False,AL-05,NaN,115338.0,154974,[],Mo Brooks,[],True,[],321615.19,NaN,NaN,NaN,0.00,321615.19,321615.19,0.000000,100.000000,0.0,0.0,0.0,0.0,5,-16.661366,-16.946410,35.302496,36.742437,2.645942,88.8,25.172678,28.127398,26.669225,14.716040,0.153492,7.9,447466.0,235353.0,65.532154,34.467846,NaN,4,AL05
5,5,2014,Alabama,AL,False,AL-06,42291.0,135945.0,178449,Mark Lester,Gary Palmer,False,False,143501.09,1618984.26,178236.0,23.727530,76.272470,143501.09,1618984.26,1762485.35,8.141973,91.858027,0.0,0.0,0.0,0.0,6,-27.045432,-28.445196,24.918430,25.243651,2.645942,88.8,28.215580,40.851449,20.788043,7.948370,0.000000,11.3,472327.0,210492.0,69.173090,30.826910,NaN,4,AL06
6,6,2014,Alabama,AL,False,AL-07,133687.0,NaN,135899,Terri A Sewell,[],True,[],434075.98,[],NaN,NaN,NaN,434075.98,0.00,434075.98,100.000000,0.000000,0.0,0.0,0.0,0.0,7,20.790182,18.069966,72.754044,71.758813,2.645942,88.8,17.401726,29.386385,36.481304,12.799616,0.000000,5.8,492715.0,190105.0,72.158841,27.841159,NaN,4,AL07
7,7,2014,Alaska,AK,False,AK-00,114602.0,142572.0,279741,Forrest Dunbar,Don Young,False,True,233131.98,461857.82,257174.0,44.562047,55.437953,233131.98,461857.82,694989.80,33.544662,66.455338,0.0,0.0,0.0,0.0,0,-9.279153,-14.753632,42.684710,38.935215,2.645942,88.8,22.930823,50.012280,16.815391,6.762178,0.777732,5.4,468893.0,241338.0,66.019788,33.980212,NaN,4,AK00

In [199]:
trainset.shape

(435, 47)

In [200]:
trainset = trainset[['district', 'demo_cluster', 'dem_2p_prev', 'dem_2p_prev2', 'prev_lean', 'prev2_lean']]
data = pd.merge(left=data, right=trainset, left_on='district_code', right_on='district', how='left')
data = data.rename({'district_x': 'seat_number'}, axis=1).drop(['district_y'], axis=1)
data.head()

,year,state,state_po,special,seat_number,dem,rep,totalvotes,dem_cand,rep_cand,dem_inc,rep_inc,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct,district_code,demo_cluster,dem_2p_prev,dem_2p_prev2,prev_lean,prev2_lean
0,2012,Alabama,AL,False,1,NaN,196374.0,200676,[],Jo Bonner,[],True,[],564463.0,NaN,NaN,NaN,0.00,564463.00,564463.00,0.000000,100.000000,AL-01,4,37.681985,38.693415,-14.281877,-14.995432
1,2012,Alabama,AL,False,2,103092.0,180591.0,283953,Therese Ford,Martha Roby,False,True,0,480059.23,283683.0,36.340563,63.659437,0.00,480059.23,480059.23,0.000000,100.000000,AL-02,4,36.674900,35.188692,-15.288962,-18.500155
2,2012,Alabama,AL,False,3,98141.0,175306.0,273930,John Andrew Harris,Mike Rogers,False,True,1744.0,474560.95,273447.0,35.890319,64.109681,1744.00,474560.95,476304.95,0.366152,99.633848,AL-03,4,37.141962,36.910121,-14.821901,-16.778726
3,2012,Alabama,AL,False,4,69706.0,199071.0,269118,Daniel H Boman,Robert B Aderholt,False,True,2400.0,534734.58,268777.0,25.934511,74.065489,2400.00,534734.58,537134.58,0.446815,99.553185,AL-04,4,24.265506,25.832249,-27.698357,-27.856598
4,2012,Alabama,AL,False,5,101772.0,189185.0,291293,Charlie L Holley,Mo Brooks,False,True,33555.03,426014.35,290957.0,34.978365,65.021635,33555.03,426014.35,459569.38,7.301407,92.698593,AL-05,4,35.302496,36.742437,-16.661366,-16.946410

In [201]:
data = data[(data['dem_cand'] != '[]') & (data['rep_cand'] != '[]')]
for party in ['dem', 'rep']:
    data[f'{party}_inc'] = data[f'{party}_inc'].map(lambda x: ast.literal_eval(x))
    data[f'{party}_inc_any'] = data[f'{party}_inc'].map(lambda x: x if not isinstance(x, list) else (True if True in x else False))
    data[f'{party}_inc_dummy'] = data[f'{party}_inc_any'].map(lambda x: 1 if x == True else 0)
data.head()

,year,state,state_po,special,seat_number,dem,rep,totalvotes,dem_cand,rep_cand,dem_inc,rep_inc,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct,district_code,demo_cluster,dem_2p_prev,dem_2p_prev2,prev_lean,prev2_lean,dem_inc_any,dem_inc_dummy,rep_inc_any,rep_inc_dummy
1,2012,Alabama,AL,False,2,103092.0,180591.0,283953,Therese Ford,Martha Roby,False,True,0,480059.23,283683.0,36.340563,63.659437,0.00,480059.23,480059.23,0.000000,100.000000,AL-02,4,36.674900,35.188692,-15.288962,-18.500155,False,0,True,1
2,2012,Alabama,AL,False,3,98141.0,175306.0,273930,John Andrew Harris,Mike Rogers,False,True,1744.0,474560.95,273447.0,35.890319,64.109681,1744.00,474560.95,476304.95,0.366152,99.633848,AL-03,4,37.141962,36.910121,-14.821901,-16.778726,False,0,True,1
3,2012,Alabama,AL,False,4,69706.0,199071.0,269118,Daniel H Boman,Robert B Aderholt,False,True,2400.0,534734.58,268777.0,25.934511,74.065489,2400.00,534734.58,537134.58,0.446815,99.553185,AL-04,4,24.265506,25.832249,-27.698357,-27.856598,False,0,True,1
4,2012,Alabama,AL,False,5,101772.0,189185.0,291293,Charlie L Holley,Mo Brooks,False,True,33555.03,426014.35,290957.0,34.978365,65.021635,33555.03,426014.35,459569.38,7.301407,92.698593,AL-05,4,35.302496,36.742437,-16.661366,-16.946410,False,0,True,1
5,2012,Alabama,AL,False,6,88267.0,219262.0,308102,Penny H Bailey,Spencer Bachus,False,True,22236.0,1128152.4,307529.0,28.702009,71.297991,22236.00,1128152.40,1150388.40,1.932912,98.067088,AL-06,4,24.918430,25.243651,-27.045432,-28.445196,False,0,True,1

In [202]:
data['dem_cand'] = data['dem_cand'].map(lambda x: dem_cand_stand[x] if x in dem_cand_stand.keys() else x)
data['rep_cand'] = data['rep_cand'].map(lambda x: rep_cand_stand[x] if x in rep_cand_stand.keys() else x)

In [203]:
data = data.rename({'district_code': 'district'}, axis=1)
data.head(1)

,year,state,state_po,special,seat_number,dem,rep,totalvotes,dem_cand,rep_cand,dem_inc,rep_inc,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct,district,demo_cluster,dem_2p_prev,dem_2p_prev2,prev_lean,prev2_lean,dem_inc_any,dem_inc_dummy,rep_inc_any,rep_inc_dummy
1,2012,Alabama,AL,False,2,103092.0,180591.0,283953,Therese Ford,Martha Roby,False,True,0,480059.23,283683.0,36.340563,63.659437,0.0,480059.23,480059.23,0.0,100.0,AL-02,4,36.6749,35.188692,-15.288962,-18.500155,False,0,True,1

In [204]:
data['dem_inc_dummy'].value_counts()

dem_inc_dummy
0    248
1    142
Name: count, dtype: int64

In [205]:
data.shape

(390, 32)

In [206]:
full_trainset = pd.read_csv('transformed/all_2p_house_races_trainset.csv')
full_trainset.head(2)

,Unnamed: 0,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,dem_inc,rep_inc,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,seat_number,prev_lean,prev2_lean,dem_2p_prev,dem_2p_prev2,generic_ballot_avg,ics,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,urban_pct,rural_pct,dem_2p_12,demo_cluster,district_id,no_dem_cand_flag,no_rep_cand_flag,dem_inc_any,rep_inc_any,dem_inc_dummy,rep_inc_dummy,pvi,census_region,dem_scandal_score,rep_scandal_score,net_scandal_score,Year,Geography,dem_stand,rep_stand,inc_dummy,polarization
0,0,2014,Alabama,AL,False,AL-01,48278.0,103758.0,152234,Burton LeFlore,Bradley Byrne,False,True,33474.0,914507.3,152036.0,31.754321,68.245679,33474.0,914507.30,947981.30,3.531082,96.468918,0.0,0.0,0.0,0.0,1,-14.281877,-14.995432,37.681985,38.693415,2.645942,88.8,36.667551,34.624569,25.603608,2.096047,0.000000,6.9,456228.0,226592.0,66.815266,33.184734,NaN,4,AL01,False,False,False,True,0,1,-14.460266,East South Central,0.0,0.0,0.0,2014.0,AL-01,Burton LeFlore,Bradley Byrne,-1,0.875383
1,1,2014,Alabama,AL,False,AL-02,54692.0,113103.0,167952,Erick Wright,Martha Roby,False,True,6674.0,454019.64,167795.0,32.594535,67.405465,6674.0,454019.64,460693.64,1.448685,98.551315,0.0,0.0,0.0,0.0,2,-15.288962,-18.500155,36.674900,35.188692,2.645942,88.8,23.382560,35.232068,31.469761,9.353024,0.281294,6.3,373585.0,309235.0,54.712076,45.287924,NaN,4,AL02,False,False,False,True,0,1,-16.091761,East South Central,0.0,0.0,0.0,2014.0,AL-02,Erick Wright,Martha Roby,-1,0.875383

In [207]:
incl_cols = ['year', 'state', 'district', 'dem_cand', 'rep_cand', 'dem', 'rep', 'dem_pct_2p', 'dem_inc_dummy', 'rep_inc_dummy', 'dem_2p_prev', 'dem_2p_prev2', 
             'dem_tot_funds', 'rep_tot_funds', 'dem_funds_2p_pct',
            'rep_funds_2p_pct', 'demo_cluster']
war_data = pd.concat([data[incl_cols], full_trainset[incl_cols]], axis=0)
war_data['is_midterm'] = war_data['year'].map(lambda x: 0 if x % 4 == 0 else 1)

## Utilizing Split Ticket's SHAVE data
## Source: https://split-ticket.org/house-generic-ballot-estimates-2008-2022-shave/
shave = {
    2012: -2.4,
    2014: 5.06,
    2016: 1.63,
    2018: -7.26,
    2020: -2.09,
    2022: 1.59,
    2024: 2.15
    
}
war_data['shave'] = war_data['year'].map(shave)
war_data.head()

,year,state,district,dem_cand,rep_cand,dem,rep,dem_pct_2p,dem_inc_dummy,rep_inc_dummy,dem_2p_prev,dem_2p_prev2,dem_tot_funds,rep_tot_funds,dem_funds_2p_pct,rep_funds_2p_pct,demo_cluster,is_midterm,shave
1,2012,Alabama,AL-02,Therese Ford,Martha Roby,103092.0,180591.0,36.340563,0,1,36.674900,35.188692,0.00,480059.23,0.000000,100.000000,4,0,-2.4
2,2012,Alabama,AL-03,John Andrew Harris,Mike Rogers,98141.0,175306.0,35.890319,0,1,37.141962,36.910121,1744.00,474560.95,0.366152,99.633848,4,0,-2.4
3,2012,Alabama,AL-04,Daniel H Boman,Robert Aderholt,69706.0,199071.0,25.934511,0,1,24.265506,25.832249,2400.00,534734.58,0.446815,99.553185,4,0,-2.4
4,2012,Alabama,AL-05,Charlie L Holley,Mo Brooks,101772.0,189185.0,34.978365,0,1,35.302496,36.742437,33555.03,426014.35,7.301407,92.698593,4,0,-2.4
5,2012,Alabama,AL-06,Penny H Bailey,Spencer Bachus,88267.0,219262.0,28.702009,0,1,24.918430,25.243651,22236.00,1128152.40,1.932912,98.067088,4,0,-2.4

In [208]:
war_data.shape, war_data.shape[0] - data.shape[0]

((2721, 19), 2331)

In [209]:
war_data.to_csv('transformed/war_data.csv')