In [130]:
import warnings
warnings.filterwarnings('ignore')

In [131]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [132]:
pd.set_option('display.max_columns', 100)

In [133]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [134]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        197  Republicans
1        289    Democrats
2        213  Republicans
3        194  Republicans
4        286    Democrats
...      ...          ...
19995    208  Republicans
19996    278    Democrats
19997    239    Democrats
19998    254    Democrats
19999    211  Republicans

[20000 rows x 2 columns]

In [135]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    149      1  0.005  Republicans
1    164      1  0.005  Republicans
2    173      1  0.005  Republicans
3    174      3  0.015  Republicans
4    175      1  0.005  Republicans

In [136]:
np.unique(seat_sims['seats']).shape[0]

182

In [137]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [138]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date           y       geo       type
0  2026-08-30  229.365800  US House      seats
1  2026-08-30   66.120000  US House     chance
2  2026-08-30   22.784344  US House   seats_sd
3  2026-08-30   44.972806     AK-AL     y_pred
4  2026-08-30    3.555839     AK-AL  y_pred_sd

In [139]:
chance_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="House Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser

In [140]:
seats_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 435 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 435]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser

In [141]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [142]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [143]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,19950,19951,19952,19953,19954,19955,19956,19957,19958,19959,19960,19961,19962,19963,19964,19965,19966,19967,19968,19969,19970,19971,19972,19973,19974,19975,19976,19977,19978,19979,19980,19981,19982,19983,19984,19985,19986,19987,19988,19989,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,-9.107892,0.375461,-6.581876,-13.023543,0.614911,-7.469856,1.790782,-8.667625,-1.095441,-1.207538,-7.045430,-3.809431,-5.009579,-7.330434,-2.285882,-2.546276,-5.074176,-1.041996,-1.718652,1.638223,-6.878743,-2.691045,-2.167959,1.126165,1.572196,-7.711679,-1.727211,-5.076876,-2.977361,-3.854745,-3.651434,-10.031806,-1.735207,-2.504762,-0.407036,-8.836717,-10.506282,-3.417921,-1.781283,-1.716638,-2.343982,-4.402340,-3.060108,-6.656297,-6.243533,1.551867,-3.651223,-2.520020,-5.554968,-8.647375,...,-6.627757,-2.892329,-2.218605,-6.320645,-4.322695,-5.466900,-2.282729,-6.478979,4.084197,-3.216320,-8.360403,-9.223521,-2.642913,-6.484963,-1.982682,-6.628716,1.410663,-7.036631,1.690185,-6.615467,-1.967608,-7.680140,-2.589894,-8.347997,-4.796244,-1.600209,-5.087639,-2.251706,-4.185268,-0.777548,-8.410985,0.552925,-10.241985,6.597507,-10.119850,-7.731213,-2.042542,-4.536454,-7.908208,-0.915415,-5.550874,-7.357292,-1.655981,-3.332395,-0.301500,-8.497471,-1.609185,-3.419157,-8.295815,-6.551337
AL-01,-20.199433,-5.016102,-18.851248,-19.769435,-8.163635,-16.810352,-6.564285,-19.893657,-7.428295,-10.784279,-16.782021,-14.620446,-11.869687,-8.263074,-12.503731,-13.359949,-11.696588,-11.744121,-14.604981,-12.945344,-17.422999,-9.473078,-12.278121,-8.932953,-6.112658,-17.915062,-8.093507,-18.030243,-15.592345,-11.871171,-17.965050,-20.366957,-13.442937,-14.108962,-12.130354,-13.392947,-18.249216,-12.609850,-14.635158,-4.201943,-12.857932,-12.833893,-11.067192,-15.418303,-18.701707,-8.118464,-18.889067,-10.049639,-13.100951,-15.477260,...,-15.212076,-11.455924,-10.697720,-12.135305,-13.023896,-13.841367,-7.601164,-18.644402,-6.690077,-15.261834,-14.555439,-16.010600,-8.275128,-16.684668,-9.412709,-20.379058,-5.646093,-16.068994,-10.195025,-16.376966,-8.833135,-13.317252,-9.861423,-13.659850,-14.337153,-12.369934,-13.468105,-7.344704,-13.552830,-9.797661,-17.099834,-9.208526,-22.428677,-4.014334,-16.873115,-18.622690,-13.362923,-14.351675,-17.470636,-12.268449,-13.124417,-19.630103,-11.736688,-13.240447,-12.192581,-17.112005,-8.288821,-14.513218,-7.633345,-17.011677
AL-02,-9.065520,6.710167,-6.459457,-4.724229,4.312850,-3.702151,-1.475977,-2.574689,3.161349,0.469346,0.008370,-0.287183,-3.070047,-1.529984,-2.749995,-1.064477,0.733520,-2.383413,2.072902,-0.646223,-5.500087,-1.930883,-1.058294,1.007476,3.397157,-6.720713,3.301013,-2.036976,-2.239431,4.363100,0.273707,-4.347394,-4.350828,2.637597,-3.291562,0.411819,-6.907964,-1.505375,-3.571566,2.523115,-0.960315,-1.170582,4.044876,-3.413693,-1.670431,7.138295,-6.872223,0.283148,-1.562873,-0.447891,...,3.191668,0.671374,0.470771,0.716419,-0.490202,-1.188392,-0.923466,-4.075499,0.595855,-0.701016,-2.894718,-4.711787,0.872580,-7.968061,2.445297,-7.061362,3.657091,-3.066347,2.173690,-0.001895,-1.827822,3.597351,3.657868,-1.934433,-4.077526,0.418447,-2.774687,2.132487,2.507841,2.695762,-8.183568,-2.858093,-6.965521,4.918562,-1.253383,4.392490,-0.717183,-3.916254,-2.748527,2.470901,-2.738364,-6.509855,-2.468625,0.206338,4.050299,-3.768119,4.273586,-2.537076,3.025407,-4.153968
AL-03,-23.989766,-16.433916,-25.074657,-26.690464,-16.942016,-22.975848,-14.609042,-18.066891,-16.880629,-18.435491,-17.483313,-20.818252,-19.701278,-14.550597,-19.461771,-17.945872,-21.147672,-21.445045,-21.281943,-15.536676,-24.850799,-18.045325,-18.156164,-12.323776,-12.367840,-26.375405,-14.498818,-24.235707,-23.564428,-19.085979,-21.543866,-24.007171,-15.618311,-21.113098,-15.307841,-17.162808,-24.777688,-17.064311,-21.972139,-17.763355,-22.021151,-20.375154,-17.673977,-22.081070,-21.822071,-15.557479,-21.427375,-17.369872,-20.663114,-27.160005,...,-22.182593,-18.175380,-17.872575,-21.874176,-19.445262,-18.896496,-20.024486,-25.837098,-13.046878,-21.756084,-24.343160,-23.305832,-15.770651,-22.408819,-12.309580,-25.968710,-15.311719,-18.136812,-14.607017,-25.030898,-16.876997,-18.497221,-16.018499,-22.626844,-20.989890,-15.302536,-17.470867,-18.705420,-21.585165,-18.536612,-24.173997,-16.406471,-26.531139,-10.601211,-26.788539,-25.352610,-18.740798,-17.574054,-23.656091,-18.309026,-17.543200,-25.150585,-19.374247,-21.710695,-15.485108,-25.348443,-15.251204,-19.053108,-18.179050,-23.077801
AL-04,-36.072248,-24.756421,-30.274447,-34.758503,-27.302210,-33.374903,-24.154726,-31.546415,-29.959347,-26.297765,-26.433672,-30.229953,-26.085655,-30.285633,-30.426727,-32.241160,-27.477419,-30.896562,-31.552872,-28.662895,-32.951222,-27.792677,-28.185675,-24.555201,-22.885884,-36.367293,-25.379045,-34.688903,-31.881469,-27.030761,-32.578971,-36.530722,-30.868014,-25.246082,-28.989466,-29.666336,-33.293244,-27.378718,-33.477758,-20.622022,-27.848800,-33.060929,-28.931168,-31.355130,-31.844658,-23.104684,-30.364513,-24.912060,-29.119548,-36.579003,...,-30.641687,-26.969626,-26.067023,-30.335688,-27.775743,-28.488595,-30.126398,-34.849556,-22.899068,-29.985644,-34.292868,-31.776409,-26.116271,-30.724296,-26.398024,-37.430284,-25.484426,-31.597557,-28.605817,-29.922442,-28.200189,-28.795712,-24.937436,-31.425049,-32.740577,-29.828304,-28.659057,-25.628282,-27.625690,-25.886583,-33.077202,-26.322436,-37.519864,-25.356023,-32.776798,-33.483734,-29.605954,-28.228169,-33.876098,-27.249617,-29.935779,-34.244820,-30.325787,-31.803850,-24.138467,-32.639417,-27.801015,-31.743136,-27.734308,-32.190504

In [144]:
sim_corr = post_untransp.corr()

In [145]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,...,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.713963,0.479269,0.734653,0.725253,0.715587,0.733318,0.492458,0.735138,0.737873,0.734227,0.737912,0.479991,0.484057,0.483822,0.497785,0.697845,0.718931,0.719812,0.720109,0.736593,0.697929,0.500840,0.506863,0.740230,0.729791,0.566042,0.505715,0.510143,0.503796,0.480516,0.694403,0.558361,0.501842,0.495595,0.700582,0.505206,0.738254,0.732114,0.505575,0.514699,0.703989,0.481619,0.507642,0.479359,0.517656,0.548515,0.506135,0.564346,0.507519,...,0.735300,0.718265,0.542050,0.505334,0.502085,0.702181,0.741172,0.699361,0.529846,0.502040,0.701501,0.520329,0.490758,0.493943,0.487975,0.729865,0.719220,0.719990,0.738308,0.548038,0.501860,0.474026,0.716857,0.725693,0.484040,0.505804,0.734219,0.484179,0.697697,0.527422,0.504365,0.507674,0.482032,0.700899,0.534771,0.480091,0.499005,0.505761,0.565417,0.490691,0.736220,0.536382,0.568981,0.732604,0.738388,0.697352,0.722609,0.731130,0.714253,0.696519
AL-01,0.713963,1.000000,0.486207,0.740705,0.732808,0.725222,0.739604,0.499493,0.738838,0.742748,0.740924,0.743213,0.486360,0.487622,0.495532,0.503099,0.701547,0.722808,0.723405,0.721196,0.738860,0.699697,0.505619,0.510205,0.746179,0.728667,0.569654,0.517914,0.512380,0.507773,0.493190,0.697363,0.566110,0.506452,0.506998,0.705389,0.512133,0.739052,0.732571,0.508892,0.516163,0.700378,0.485428,0.510210,0.483664,0.531801,0.560674,0.513522,0.575467,0.510401,...,0.736917,0.721344,0.556218,0.512941,0.502794,0.698932,0.746339,0.703745,0.541288,0.509458,0.704177,0.525864,0.496063,0.504984,0.493029,0.735317,0.724677,0.723917,0.742106,0.553149,0.513424,0.487655,0.711873,0.726967,0.483330,0.509370,0.741178,0.487144,0.705507,0.533965,0.505244,0.511617,0.484922,0.706822,0.541284,0.487895,0.504287,0.509916,0.573803,0.496586,0.739301,0.545053,0.575412,0.737150,0.746317,0.703818,0.722765,0.742689,0.720663,0.705126
AL-02,0.479269,0.486207,1.000000,0.489659,0.485398,0.477300,0.491023,0.699985,0.487459,0.495651,0.487722,0.496241,0.670751,0.665975,0.674484,0.690948,0.638291,0.475287,0.482117,0.475448,0.492425,0.630439,0.699454,0.706294,0.498202,0.487968,0.579366,0.697837,0.699183,0.520445,0.665959,0.633329,0.569129,0.695394,0.701862,0.635830,0.699797,0.492930,0.484459,0.705667,0.708717,0.634766,0.675107,0.701110,0.669106,0.536131,0.556207,0.704098,0.577397,0.706735,...,0.493882,0.480257,0.552488,0.700195,0.697403,0.631339,0.493679,0.635389,0.543897,0.696831,0.635078,0.534604,0.682702,0.680766,0.674331,0.485224,0.471241,0.478473,0.492844,0.552131,0.691046,0.666138,0.471856,0.482616,0.667200,0.708570,0.490668,0.668954,0.632462,0.540805,0.701172,0.698703,0.678094,0.639703,0.543554,0.663152,0.694763,0.694943,0.578102,0.683494,0.487042,0.544621,0.576619,0.488254,0.493400,0.636074,0.478977,0.493390,0.479415,0.640114
AL-03,0.734653,0.740705,0.489659,1.000000,0.754900,0.739730,0.765067,0.509811,0.753528,0.761376,0.759017,0.759593,0.497656,0.498115,0.500189,0.513967,0.717018,0.737300,0.736022,0.740272,0.760599,0.720293,0.515245,0.517646,0.761978,0.750426,0.577487,0.518049,0.525896,0.523220,0.498719,0.714551,0.571292,0.512188,0.512812,0.724871,0.520743,0.757785,0.751710,0.516551,0.526729,0.719219,0.498140,0.518977,0.495030,0.540718,0.570801,0.519252,0.581987,0.524390,...,0.757146,0.740227,0.558592,0.518220,0.514850,0.715499,0.766409,0.720090,0.543654,0.516046,0.721244,0.535868,0.502842,0.512633,0.502657,0.752578,0.740154,0.738595,0.759837,0.561067,0.514161,0.493043,0.735929,0.744020,0.494172,0.517732,0.758851,0.495793,0.721002,0.543012,0.517029,0.524585,0.489006,0.720937,0.551919,0.491510,0.508634,0.521983,0.581149,0.507526,0.757582,0.555363,0.579785,0.753417,0.761359,0.720722,0.741147,0.756329,0.735868,0.721467
AL-04,0.725253,0.732808,0.485398,0.754900,1.000000,0.731232,0.745406,0.507829,0.749749,0.746320,0.750099,0.749692,0.493047,0.492447,0.500169,0.504616,0.708691,0.727533,0.728961,0.728190,0.752179,0.709041,0.509547,0.517978,0.748661,0.735713,0.569752,0.518266,0.518693,0.514907,0.492819,0.704933,0.571642,0.511727,0.508795,0.715410,0.512854,0.745336,0.735509,0.514434,0.521430,0.712332,0.492050,0.517293,0.482996,0.532670,0.565459,0.513640,0.574717,0.521493,...,0.746074,0.729300,0.550189,0.515263,0.508068,0.708803,0.755364,0.715142,0.543054,0.514450,0.713276,0.525525,0.498784,0.504787,0.497288,0.740036,0.733276,0.727750,0.748925,0.554129,0.515092,0.485415,0.725048,0.737539,0.488385,0.512643,0.750501,0.494103,0.710120,0.537071,0.507408,0.518597,0.490569,0.713093,0.547138,0.489123,0.509776,0.516386,0.571570,0.497257,0.744610,0.547617,0.574616,0.745063,0.748474,0.710534,0.726777,0.745221,0.725922,0.711560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WI-07,0.697352,0.703818,0.636074,0.720722,0.710534,0.701718,0.716586,0.656478,0.717584,0.719170,0.714466,0.724205,0.644652,0.637165,0.646516,0.662301,0.842332,0.697436,0.709554,0.699478,0.720383,0.838992,0.665768,0.674739,0.724163,0.712221,0.551848,0.670591,0.676175,0.499092,0.638646,0.840493,0.545828,0.666163,0.665669,0.843512,0.670515,0.718449,0.708167,0.669284,0.680403,0.841991,0.642915,0.668479,0.638139,0.517069,0.541069,0.674898,0.554694,0.675091,...,0.720693,0.698759,0.532321,0.668636,0.662948,0.838895,0.725255,0.842402,0.522711,0.668199,0.843684,0.509463,0.653136,0.654571,0.651861,0.713581,0.704139,0.701325,0.722334,0.538698,0.668814,0.637173,0.697323,0.711451,0.636436,0.670779,0.721380,0.642123,0.842916,0.521458,0.667857,0.673573,0.642354,0.844992,0.529853,0.640475,0.663366,0.668456,0.556257,0.654044,0.718210,0.529895,0.556600,0.716274,0.724762,1.000000,0.702271,0.721389,0.694565,0.845406
WI-08,0.722609,0.722765,0.478977,0.741147,0.726777,0.717738,0.737310,0.496126,0.743655,0.741412,0.740093,0.743349,0.487052,0.490209,0.488427,0.497062,0.706581,0.722709,0.718184,0.718783,0.740624,0.703055,0.508789,0.506191,0.745021,0.737961,0.569091,0.509511,0.514255,0.510288,0.492272,0.698397,0.563816,0.507342,0.504904,0.705059,0.508158,0.738287,0.731718,0.511665,0.520869,0.705110,0.487072,0.507610,0.484182,0.529749,0.554532,0.511619,0.565702,0.515598,...,0.740715,0.721275,0.552628,0.509809,0.502428,0.702051,0.744508,0.704761,0.539826,0.503837,0.704715,0.525704,0.499467,0.504015,0.491544,0.733483,0.721905,0.723541,0.741643,0.555544,0.511109,0.483445,0.714543,0.728321,0.476163,0.508213,0.742578,0.487214,0.703832,0.530970,0.509127,0.517645,0.489215,0.707689,0.539147,0.484667,0.506716,0.512856,0.570370,0.499120,0.746093,0.557385,0.579571,0.742280,0.746084,0.702271,1.000000,0.735058,0.718704,0.701846
WV-01,0.731130,0.742689,0.493390,0.756329,0.745221,0.736096,0.758393,0.512632,0.750840,0.755418,0.753616,0.756783,0.500882,0.505556,0.504724,0.513065,0.719041,0.730161,0.739251,0.738036,0.754605,0.717783,0.523223,0.524801,0.761660,0.745942,0.580962,0.523660,0.522955,0.514728,0.501535,0.715524,0.573043,0.516970,0.517860,0.722101,0.524308,0.755044,0.745862,0.523243,0.531858,0.721834,0.500272,0.520202,0.493568,0.538427,0.568058,0.522238,0.581054,0.528579,...,0.757320,0.737441,0.562757,0.519451,0.515804,0.718050,0.761220,0.721661,0.548453,0.519860,0.721328,0.533132,0.510443,0.514175,0.502445,0.750939,0.736240,0.737775,0.758691,0.558513,0.521164,0.493721,0.728458,0.746594,0.494336,0.524489,0.758002,0.498782,0.719495,0.543359,0.519853,0.524702,0.494809,0.722832,0.551460,0.498374,0.511893,0.522930,0.581455,0.508143,0.756965,0.560113,0.578680,0.753205,0.760474,0.721389,0.735058,1.000000,0.744202,0.723241
WV-02,0.714253,0.720663,0.479415,0.735868,0.725922,0.715013,0.731092,0.496021,0.737171,0.742053,0.733718,0.743511,0.484936,0.480184,0.487241,0.502017,0.694558,0.719084,0.719514,0.716660,0.737197,0.697430,0.502503,0.510626,0.740445,0.723657,0.565429,0.507304,0.509451,0.508883,0.486043,0.692620,0.566073,0.500248,0.502071,0.698806,0.505154,0.740463,0.728530,0.502380,0.511398,0.697048,0.485095,0.507745,0.479711,0.528222,0.554259,0.508339,0.571355,0.510779,...,0.735612,0.723449,0.547880,0.506391,0.503580,0.698737,0.742054,0.696516,0.538761,0.505312,0.699309,0.524056,0.491427,0.499223,0.491555,0.726780,0.717378,0.718441,0.738961,0.550905,0.507695,0.480860,0.711886,0.724083,0.482431,0.506687,0.740620,0.486674,0.699562,0.530534,0.504583,0.510723,0.480117,0.699084,0.540691,0.486342,0.499047,0.510210,0.573592,0.496918,0.735475,0.546373,0.568015,0.732344,0.739867,0.694565,0.718704,0.744202,1.000000,0.698829
WY-AL,0.696519,0.705126,0.640114,0.721467,0.711560,0.701874,0.715775,0.656298,0.717786,0.721677,0.715671,0.727289,0.646181,0.638490,0.642878,0.661272,0.842746,0.698001,0.707835,0.700862,0.719027,0.838320,0.668171,0.671648,0.723660,0.710565,0.551370,0.672852,0.676949,0.495879,0.639521,0.838436,0.547496,0.664099,0.665150,0.843861,0.668165,0.717590,0.709692,0.666500,0.679581,0.842271,0.644015,0.669963,0.636987,0.515381,0.541451,0.671686,0.553912,0.677882,...,0.723290,0.700252,0.536567,0.670418,0.660496,0.837362,0.728164,0.847149,0.522336,0.668491,0.842495,0.506273,0.652857,0.658189,0.648855,0.711396,0.702345,0.704198,0.721484,0.535433,0.666491,0.635676,0.697505,0.714184,0.639653,0.670798,0.723490,0.643298,0.839727,0.526507,0.667694,0.676111,0.644393,0.844640,0.527969,0.641403,0.661077,0.667195,0.556826,0.648617,0.718528,0.530893,0.557560,0.714720,0.723085,0.845406,0.701846,0.723241,0.698829,1.000000

In [146]:
post.shape

(418, 20000)

In [147]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [148]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:32<00:00, 609.48it/s]

array(['MI-07', 'FL-07', 'FL-04', ..., 'FL-13', 'MI-10', 'MO-02'],
      shape=(20000,), dtype='<U32')

In [149]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.105615,1,0,46.957206,0.392099,46.963324,0.392099,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.392099,0.626178,0.006119,-3.937800,-19.716169,1,-39.432338,48.885649,3.446256,37.155,3,42.090683,55.628276
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,18.397008,0.000000,0.000000,0.000000,-36.536569,-45.710827,-1,-91.421653,30.535338,3.459723,0.000,4,23.806942,37.404627
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,8.220432,0.000000,0.000000,0.000000,-56.828664,-47.132870,-1,-94.265741,20.709933,3.504360,0.000,5,13.883614,27.610707

In [150]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.060
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.105615,1,0,46.957206,0.392099,46.963324,0.392099,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.392099,0.626178,0.006119,-3.937800,-19.716169,1,-39.432338,48.885649,3.446256,37.155,3,42.090683,55.628276,1.095
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,18.397008,0.000000,0.000000,0.000000,-36.536569,-45.710827,-1,-91.421653,30.535338,3.459723,0.000,4,23.806942,37.404627,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,8.220432,0.000000,0.000000,0.000000,-56.828664,-47.132870,-1,-94.265741,20.709933,3.504360,0.000,5,13.883614,27.610707,0.000

In [151]:
data.sort_values('tipping_point_prob', ascending=False).head(10)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
229,229,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE",no_match,2799701.44,0.00,2799701.44,100.000000,0.000000,North Carolina,NC-11,88.740422,3.902084,0.797632,1.120840,3.305854,24.807640,-7.843347,-4.057125,-5.003681,49.294326,45.192821,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.0,0.00000,0.00000,37,3711,3,10000.000000,0.000000,0.000000,0.000000e+00,-0.901746,50.000000,0,100.000000,51.589271,3.613653,67.065,230,44.516074,58.748038,3.040
98,98,FL-22,Pia Dandiya,Casey Askar,False,False,FL,22,"DANDIYA, PIA","ASKAR, CASEY",1965051.29,57760.00,2022811.29,97.144568,2.855432,Florida,FL-22,53.931205,26.984941,3.703933,0.199203,13.186062,27.190634,-0.817400,-4.551960,-3.618320,91.180168,44.697986,0.987401,-9.105615,0,0,46.286766,0.415907,44.430149,0.415907,South Atlantic,2026,0.0,0.00000,0.00000,12,1222,6,9437.067100,0.415907,0.644909,-1.856617e+00,1.868974,47.144568,0,94.289136,52.427660,3.601501,75.290,99,45.293277,59.581096,2.940
193,193,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",1135198.13,1290223.21,2425421.34,46.804162,53.195838,Michigan,MI-10,76.551128,2.316124,5.150984,0.123322,13.269372,29.340000,-2.765891,-2.592362,-2.635744,99.999226,46.657584,0.987401,-9.105615,0,0,45.000000,0.152447,45.000000,0.152447,East North Central,2026,0.0,0.00000,0.00000,26,2610,2,2190.629568,0.152447,0.390444,-1.460326e-07,3.834127,-3.195838,0,-6.391676,51.319194,3.595562,64.510,194,44.228325,58.409862,2.820
183,183,ME-02,Matt Dunlap,Paul LePage,False,False,ME,2,"DUNLAP, MATT","LEPAGE, PAUL",1181075.25,1415549.45,2596624.70,45.485019,54.514981,Maine,ME-02,94.623805,1.542589,0.598455,0.552005,0.848532,26.920000,-5.410176,-3.867301,-4.253020,26.830060,45.382645,0.987401,-9.105615,0,0,50.176071,1.938860,47.161521,1.938860,New England,2026,0.0,0.25284,-0.25284,23,2302,3,2068.886995,1.938860,1.392430,-3.014550e+00,0.599575,-4.514981,0,-9.029961,51.287048,3.599762,64.015,184,44.188119,58.443034,2.730
386,386,VA-01,Shannon Taylor,Rob Wittman,False,True,VA,1,"TAYLOR, SHANNON LEIGH","WITTMAN, ROBERT J. MR.",1687926.35,1442542.81,3130469.16,53.919277,46.080723,Virginia,VA-01,75.537803,4.124527,4.097593,0.133339,13.351012,46.900000,-5.404597,-1.752158,-2.665268,73.780628,47.497788,0.987401,-9.105615,0,1,49.033047,0.971263,46.241737,0.971263,South Atlantic,2026,0.0,0.00000,0.00000,51,5101,2,2907.288474,0.971263,0.985527,-2.791310e+00,3.775078,3.919277,-1,7.838555,51.682509,3.426151,68.960,387,45.001961,58.388819,2.630
123,123,IA-03,Sarah Trone Garriott,Zach Nunn,False,True,IA,3,"TRONE GARRIOTT, SARAH","NUNN, ZACH",4755754.76,1010301.85,5766056.61,82.478461,17.521539,Iowa,IA-03,86.341081,5.022950,2.732262,0.063009,3.929259,35.410000,-2.445778,-1.482072,-1.722998,77.628515,47.767874,0.987401,-9.105615,0,1,42.000000,0.001028,48.000000,0.001028,West North Central,2026,0.0,0.00000,0.00000,19,1903,2,6802.696551,0.001028,0.032058,6.000000e+00,5.659618,32.478461,-1,64.956922,52.310918,3.498273,74.595,124,45.422431,59.273163,2.580
273,273,NY-17,Cait Conley,Mike Lawler,False,True,NY,17,"CONLEY, CAIT","LAWLER, MICHAEL VINCENT",3706160.25,3186004.97,6892165.22,53.773526,46.226474,New York,NY-17,70.961924,14.978446,4.840493,0.059866,7.686273,48.490000,2.820018,1.029915,1.477441,87.206472,50.279862,0.987401,-9.105615,0,1,47.754428,1.678317,46.258603,1.678317,Mid-Atlantic,2026,0.0,0.00000,0.00000,36,3617,0,2891.592088,1.678317,1.295499,-1.495825e+00,12.060497,3.773526,-1,7.547052,51.806876,3.497878,69.810,274,45.032206,58.703703,2.495
37,37,CA-22,Randy Villegas,David Valadao,False,True,CA,22,"VILLEGAS, RANDY","VALADAO, DAVID",2396295.54,1423592.37,3819887.91,62.732090,37.267910,California,CA-22,22.131732,64.469110,4.924433,0.538078,6.308791,6.196120,6.443675,-0.178428,1.477097,85.545753,49.071518,0.987401,-9.105615,0,1,48.000000,0.026523,44.000000,0.026523,Pacific,2026,0.0,0.00000,0.00000,6,622,4,3935.315176,0.026523,0.162859,-4.000000e+00,12.059809,12.732090,-1,25.464181,51.930008,3.460294,71.380,38,45.099919,58.704411,2.460
190,190,MI-07,William Lawrence,Tom Barrett,False,True,MI,7,"LAWRENCE, WILLIAM","BARRETT, THOMAS MORE",1065694.20,3350486.21,4416180.41,24.131582,75.868418,Michigan,MI-07,85.239895,4.803904,1.944855,0.170025,5.279273,36.270000,-2.003691,0.098125,-0.427329,68.756305,49.348071,0.987401,-9.105615,0,1,48.971702,0.184932,46.971702,0.184932,East North Central,2026,0.0,0.00000,0.00000,26,2607,2,582.333253,0.184932,0.430037,-2.000000e+00,8.250957,-25.868418,-1,-51.736836,51.354613,3.504204,65.510,191,44.487518,58.273942,2.440
314,314,PA-07,Bob Brooks,Ryan Mackenzie,False,True,PA,7,"BROOKS, BOB","MACKENZIE, RYAN EDWARD",1942165.53,1493241.01,3435406.54,56.533790,43.466210,Pennsylvania,PA-07,75.458946,15.481046,2.435986,0.030199,4.952274,31.050000,-1.956264,-0.869379,-1.141100,81.633883,48.380567,0.987401,-9.105615,0,1,45.002910,0.702006,40.004365,0.702006,Mid-Atlantic,2026,0.0,0.00000,0.00000,42,4207,2,3196.069448,0.702006,0.837858,-4.998545e+00,6.823415,6.533790,-1,13.067581,51.807650,3.509670,69.865,315,44.871155,58.715131,2.415

In [152]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [153]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.060,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.105615,1,0,46.957206,0.392099,46.963324,0.392099,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.392099,0.626178,0.006119,-3.937800,-19.716169,1,-39.432338,48.885649,3.446256,37.155,3,42.090683,55.628276,1.095,Tilt R,"<b style=""color:#366bbf;"">Shomari Figures* (D)..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,18.397008,0.000000,0.000000,0.000000,-36.536569,-45.710827,-1,-91.421653,30.535338,3.459723,0.000,4,23.806942,37.404627,0.000,Safe R,"<b style=""color:#366bbf;"">Lee McInnis (D)</b> ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,8.220432,0.000000,0.000000,0.000000,-56.828664,-47.132870,-1,-94.265741,20.709933,3.504360,0.000,5,13.883614,27.610707,0.000,Safe R,"<b style=""color:#366bbf;"">Amanda Pusczek (D)</..."

In [154]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.060,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.105615,1,0,46.957206,0.392099,46.963324,0.392099,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.392099,0.626178,0.006119,-3.937800,-19.716169,1,-39.432338,48.885649,3.446256,37.155,3,42.090683,55.628276,1.095,Tilt R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R)

In [155]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.0,0.0,0.0,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.06,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.0,0.0,0.0,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.00,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,

In [156]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.060,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.6
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+25.7
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.105615,1,0,46.957206,0.392099,46.963324,0.392099,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.392099,0.626178,0.006119,-3.937800,-19.716169,1,-39.432338,48.885649,3.446256,37.155,3,42.090683,55.628276,1.095,Tilt R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+2.2

In [157]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.060,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.6,85.945,14.1,85.9,14.1%,85.9%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+25.7,99.995,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.105615,1,0,46.957206,0.392099,46.963324,0.392099,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.392099,0.626178,0.006119,-3.937800,-19.716169,1,-39.432338,48.885649,3.446256,37.155,3,42.090683,55.628276,1.095,Tilt R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+2.2,62.845,37.2,62.8,37.2%,62.8%

In [158]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.060,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.6,85.945,14.1,85.9,14.1%,85.9%,6.075425
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+25.7,99.995,0.0,100.0,<1%,>99%,10.600986
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.105615,1,0,46.957206,0.392099,46.963324,0.392099,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.392099,0.626178,0.006119,-3.937800,-19.716169,1,-39.432338,48.885649,3.446256,37.155,3,42.090683,55.628276,1.095,Tilt R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+2.2,62.845,37.2,62.8,37.2%,62.8%,12.235727

In [159]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.105615,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.0,0.0,0.0,-3.804990,-18.764506,-1,-37.529012,46.191150,3.551914,14.055,1,39.203291,53.151608,0.06,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.6,85.945,14.1,85.9,14.1%,85.9%,6.075425,D+6.1
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.105615,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.0,0.0,0.0,-25.768667,-38.923019,0,-77.846039,37.128257,3.556701,0.005,2,30.230478,44.143119,0.00,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+25.7,99.995,0.0,100.0,<1%,>99%,10.600986,D+10.6

In [160]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
413    5507
414    5508
415    5401
416    5402
417    5600
Name: geoid, Length: 418, dtype: int64

In [161]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['y_pred'] = np.full(dem_uclen, 100)
dem_uncont['swing_24_to_26'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_24_to_26_swing'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                      x['dem_inc_any'], x['rep_inc_any']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Mike Thompson/Eric J..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Doris Matsui/Mai Van..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Scott Weiner/Connie ..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Lateefah Simon* (D)<..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,True,False,CA,14,6,614,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Aisha Wahab/Melissa ..."

In [162]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['y_pred'] = np.full(rep_uclen, 0)
rep_uncont['swing_24_to_26'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_24_to_26_swing'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                       x['dem_inc_any'], x['rep_inc_any']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0,NaN,NaN,0%,100%,R+100,,"<b style=""color:#366bbf;"">Not Contested (D)</b..."

In [163]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'geoid', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 16)

In [164]:
tab_data = data[['cd', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Bill Hill', 'Kevin Kiley'] else x)
tab_data = tab_data.rename({
    'cd': 'District',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,District,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,AK-AL,Bill Hill (Ind),Nick Begich,Likely R,"<p style=""color:blue;"">14.1%</p>","<p style=""color:red;"">85.9%</p>",R+7.6,D+6.1,0.060
1,AL-01,Clyde Jones Jr.,Jerry Carl,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+25.7,D+10.6,0.000
2,AL-02,Shomari Figures,Rhett Marques,Tilt R,"<p style=""color:blue;"">37.2%</p>","<p style=""color:red;"">62.8%</p>",R+2.2,D+12.2,1.095
3,AL-03,Lee McInnis,Mike Rogers,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+38.9,D+8.1,0.000
4,AL-04,Amanda Pusczek,Robert Aderholt,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+58.6,D+8.4,0.000

In [165]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

5.92707212151052

In [166]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

                 vars           x
0     means_seats_tot  239.716000
1  chamber_win_chance   80.880000
0             sv_bias    5.927072

In [167]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [168]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 435 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Win Probability  Seat Share
0    Democrats            80.88     239.716
1  Republicans            19.12     195.284

In [169]:
## Alert when there's a rating change
rating_ts = output_ts[output_ts['type'] == 'chance']
rating_ts['rating'] = rating_ts['y'].map(get_rating)
rating_ts['date'] = pd.to_datetime(rating_ts['date'])
rating_ts.head()

today_date = rating_ts['date'].max()
yesterday = rating_ts[rating_ts['date'] != today_date]['date'].max()

today_ratings = rating_ts[rating_ts['date'] == today_date]
yester_ratings = rating_ts[rating_ts['date'] == yesterday]
compare_df = pd.merge(left=today_ratings, right=yester_ratings, on='geo', how='left', suffixes=['_t', '_y'])
compare_df.head()

,date_t,y_t,geo,type_t,rating_t,date_y,y_y,type_y,rating_y
0,2026-10-04,80.880,US House,chance,Likely D,2026-10-03,80.700,chance,Likely D
1,2026-10-04,14.055,AK-AL,chance,Likely R,2026-10-03,13.945,chance,Likely R
2,2026-10-04,0.005,AL-01,chance,Safe R,2026-10-03,0.005,chance,Safe R
3,2026-10-04,37.155,AL-02,chance,Tilt R,2026-10-03,36.935,chance,Tilt R
4,2026-10-04,0.000,AL-03,chance,Safe R,2026-10-03,0.000,chance,Safe R

In [170]:
## This is the cell that actually alerts when there's a rating change
if any(compare_df['rating_t'] != compare_df['rating_y']):
    changes_df = compare_df[compare_df['rating_t'] != compare_df['rating_y']][['geo', 'rating_y', 'rating_t']]
    print(changes_df)
else:
    print("No rating changes today!")

       geo       rating_y  rating_t
20   AZ-08  Very Likely R  Likely R
290  OH-07         Tilt D    Tossup
376  TX-32  Very Likely R  Likely R
409  WI-01         Tilt R    Tossup

In [171]:
changes_df.shape

(4, 3)

In [172]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')