In [161]:
import warnings
warnings.filterwarnings('ignore')

In [162]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [163]:
pd.set_option('display.max_columns', 100)

In [164]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [165]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        197  Republicans
1        285    Democrats
2        212  Republicans
3        195  Republicans
4        283    Democrats
...      ...          ...
19995    208  Republicans
19996    275    Democrats
19997    233    Democrats
19998    252    Democrats
19999    211  Republicans

[20000 rows x 2 columns]

In [166]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    147      1  0.005  Republicans
1    162      1  0.005  Republicans
2    168      1  0.005  Republicans
3    169      1  0.005  Republicans
4    171      2  0.010  Republicans

In [167]:
np.unique(seat_sims['seats']).shape[0]

184

In [168]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [169]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date           y       geo       type
0  2026-08-30  229.365800  US House      seats
1  2026-08-30   66.120000  US House     chance
2  2026-08-30   22.784344  US House   seats_sd
3  2026-08-30   44.972806     AK-AL     y_pred
4  2026-08-30    3.555839     AK-AL  y_pred_sd

In [170]:
chance_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="House Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser

In [171]:
seats_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 435 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 435]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser

In [172]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [173]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [174]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,19950,19951,19952,19953,19954,19955,19956,19957,19958,19959,19960,19961,19962,19963,19964,19965,19966,19967,19968,19969,19970,19971,19972,19973,19974,19975,19976,19977,19978,19979,19980,19981,19982,19983,19984,19985,19986,19987,19988,19989,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,-9.387384,0.092085,-6.861691,-13.303467,0.336418,-7.755908,1.509566,-8.946880,-1.377774,-1.491762,-7.326741,-4.087750,-5.287380,-7.612372,-2.561705,-2.822488,-5.361975,-1.321982,-1.999747,1.353412,-7.163436,-2.968832,-2.450078,0.845096,1.288220,-7.991387,-2.012704,-5.355815,-3.252159,-4.135598,-3.937032,-10.314584,-2.012832,-2.792189,-0.688415,-9.120576,-10.787070,-3.701281,-2.062515,-2.002188,-2.629675,-4.685869,-3.343098,-6.941249,-6.532277,1.274571,-3.931713,-2.801431,-5.838828,-8.932669,...,-6.914928,-3.173418,-2.507067,-6.604123,-4.604634,-5.753816,-2.560005,-6.755100,3.795758,-3.499964,-8.643877,-9.506981,-2.926646,-6.764981,-2.260917,-6.912746,1.124313,-7.324737,1.405918,-6.893345,-2.241609,-7.969716,-2.872620,-8.628754,-5.084062,-1.882936,-5.369609,-2.535404,-4.467780,-1.059855,-8.692370,0.274685,-10.527267,6.314626,-10.402618,-8.015118,-2.324923,-4.815366,-8.190463,-1.192032,-5.839821,-7.640465,-1.942339,-3.617049,-0.587946,-8.780715,-1.890840,-3.700591,-8.574932,-6.831449
AL-01,-20.478925,-5.299477,-19.131062,-20.049359,-8.442129,-17.096404,-6.845501,-20.172912,-7.710627,-11.068503,-17.063333,-14.898765,-12.147487,-8.545011,-12.779554,-13.636161,-11.984387,-12.024106,-14.886075,-13.230154,-17.707693,-9.750865,-12.560241,-9.214022,-6.396634,-18.194769,-8.379000,-18.309181,-15.867143,-12.152024,-18.250648,-20.649735,-13.720562,-14.396388,-12.411733,-13.676806,-18.530004,-12.893210,-14.916390,-4.487493,-13.143625,-13.117422,-11.350183,-15.703254,-18.990451,-8.395760,-19.169557,-10.331050,-13.384811,-15.762553,...,-15.499247,-11.737013,-10.986182,-12.418784,-13.305834,-14.128283,-7.878441,-18.920523,-6.978516,-15.545478,-14.838913,-16.294061,-8.558861,-16.964686,-9.690944,-20.663088,-5.932443,-16.357100,-10.479291,-16.654843,-9.107136,-13.606829,-10.144149,-13.940608,-14.624970,-12.652661,-13.750075,-7.628403,-13.835341,-10.079967,-17.381219,-9.486766,-22.713959,-4.297214,-17.155882,-18.906595,-13.645304,-14.630587,-17.752891,-12.545066,-13.413364,-19.913275,-12.023045,-13.525101,-12.479028,-17.395248,-8.570476,-14.794652,-7.912462,-17.291789
AL-02,-9.316985,6.443766,-6.684924,-4.906160,4.060082,-3.896830,-1.761317,-2.740499,2.911375,0.225005,-0.250564,-0.518362,-3.296530,-1.701835,-3.011658,-1.364586,0.544710,-2.633684,1.799259,-0.875086,-5.717677,-2.168076,-1.291739,0.783304,3.158105,-6.959052,3.069797,-2.286873,-2.427823,4.111877,0.040740,-4.552646,-4.591919,2.388843,-3.510029,0.167219,-7.108239,-1.764321,-3.831530,2.268935,-1.223038,-1.379134,3.784017,-3.623625,-1.825630,6.896372,-7.150823,0.040532,-1.823350,-0.692028,...,2.964589,0.438874,0.167247,0.439868,-0.746199,-1.448960,-1.118876,-4.306972,0.352131,-0.891028,-3.172270,-4.985016,0.693087,-8.261332,2.242095,-7.373342,3.439885,-3.261146,1.952450,-0.237244,-2.035360,3.348536,3.408649,-2.159681,-4.285676,0.219993,-3.048272,1.912836,2.313632,2.477974,-8.367145,-3.062734,-7.258274,4.706213,-1.539590,4.192508,-0.963787,-4.107588,-2.966446,2.212151,-2.956955,-6.744362,-2.714889,-0.004805,3.779701,-4.000072,4.060377,-2.782500,2.793803,-4.403903
AL-03,-24.269259,-16.717291,-25.354472,-26.970388,-17.220509,-23.261900,-14.890258,-18.346146,-17.162962,-18.719715,-17.764624,-21.096571,-19.979078,-14.832534,-19.737594,-18.222084,-21.435471,-21.725031,-21.563037,-15.821487,-25.135492,-18.323112,-18.438284,-12.604845,-12.651815,-26.655112,-14.784312,-24.514645,-23.839226,-19.366832,-21.829464,-24.289948,-15.895937,-21.400525,-15.589220,-17.446667,-25.058476,-17.347671,-22.253372,-18.048905,-22.306843,-20.658683,-17.956968,-22.366021,-22.110814,-15.834775,-21.707864,-17.651283,-20.946974,-27.445298,...,-22.469764,-18.456469,-18.161037,-22.157654,-19.727200,-19.183412,-20.301763,-26.113220,-13.335316,-22.039729,-24.626635,-23.589293,-16.054383,-22.688837,-12.587815,-26.252741,-15.598070,-18.424919,-14.891284,-25.308775,-17.150999,-18.786798,-16.301225,-22.907602,-21.277708,-15.585263,-17.752837,-18.989119,-21.867677,-18.818918,-24.455382,-16.684711,-26.816421,-10.884092,-27.071306,-25.636515,-19.023179,-17.852966,-23.938346,-18.585643,-17.832147,-25.433758,-19.660604,-21.995349,-15.771555,-25.631687,-15.532859,-19.334542,-18.458167,-23.357913
AL-04,-36.351740,-25.039796,-30.554262,-35.038426,-27.580704,-33.660955,-24.435942,-31.825670,-30.241680,-26.581989,-26.714984,-30.508271,-26.363455,-30.567570,-30.702550,-32.517373,-27.765218,-31.176548,-31.833966,-28.947705,-33.235915,-28.070464,-28.467795,-24.836270,-23.169860,-36.647000,-25.664538,-34.967842,-32.156267,-27.311614,-32.864569,-36.813499,-31.145640,-25.533508,-29.270846,-29.950195,-33.574032,-27.662078,-33.758991,-20.907572,-28.134493,-33.344458,-29.214158,-31.640081,-32.133402,-23.381980,-30.645003,-25.193471,-29.403408,-36.864297,...,-30.928858,-27.250715,-26.355485,-30.619166,-28.057682,-28.775511,-30.403675,-35.125677,-23.187506,-30.269289,-34.576343,-32.059869,-26.400003,-31.004314,-26.676259,-37.714314,-25.770776,-31.885664,-28.890083,-30.200320,-28.474191,-29.085289,-25.220162,-31.705807,-33.028395,-30.111032,-28.941026,-25.911981,-27.908202,-26.168889,-33.358588,-26.600676,-37.805146,-25.638903,-33.059565,-33.767639,-29.888335,-28.507081,-34.158354,-27.526235,-30.224726,-34.527992,-30.612145,-32.088504,-24.424914,-32.922661,-28.082670,-32.024570,-28.013424,-32.470616

In [175]:
sim_corr = post_untransp.corr()

In [176]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,...,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.713961,0.479350,0.734651,0.725256,0.715584,0.733310,0.492442,0.735136,0.737713,0.734220,0.737906,0.479976,0.483927,0.483797,0.497774,0.697838,0.718910,0.719802,0.720098,0.736588,0.697911,0.500829,0.506842,0.740222,0.730504,0.566022,0.505692,0.510125,0.503776,0.480488,0.694384,0.558343,0.501804,0.495574,0.700576,0.505186,0.738250,0.732101,0.505550,0.514673,0.703978,0.481605,0.507624,0.479338,0.517637,0.548499,0.506115,0.564334,0.507499,...,0.735292,0.718257,0.542029,0.505297,0.502066,0.702159,0.741166,0.699353,0.529822,0.502103,0.701495,0.520300,0.490720,0.493934,0.487956,0.729859,0.719219,0.719983,0.738978,0.547934,0.501832,0.473998,0.717507,0.731370,0.484037,0.505780,0.734215,0.484170,0.697681,0.527406,0.504338,0.507654,0.481663,0.700894,0.534742,0.480076,0.498972,0.505747,0.565399,0.490672,0.738415,0.536345,0.568954,0.732593,0.738369,0.697347,0.722638,0.731129,0.714252,0.696521
AL-01,0.713961,1.000000,0.486051,0.740714,0.732821,0.725230,0.739607,0.499497,0.738847,0.742750,0.740927,0.743217,0.486367,0.487684,0.495528,0.503109,0.701550,0.722854,0.723406,0.721195,0.738866,0.699690,0.505631,0.510206,0.746181,0.728843,0.569658,0.517914,0.512384,0.507775,0.493183,0.697354,0.566116,0.506390,0.506999,0.705394,0.512135,0.739132,0.732569,0.508889,0.516158,0.700378,0.485435,0.510213,0.483664,0.531805,0.560681,0.513524,0.575478,0.510403,...,0.736921,0.721346,0.556220,0.512873,0.502797,0.698920,0.746343,0.703748,0.541287,0.509484,0.704174,0.525857,0.496046,0.504995,0.493032,0.735321,0.724687,0.723920,0.742133,0.553173,0.513418,0.487650,0.711855,0.732466,0.483348,0.509368,0.741185,0.487155,0.705502,0.533970,0.505239,0.511618,0.485618,0.706827,0.541308,0.487901,0.504276,0.509923,0.573833,0.496587,0.739987,0.545158,0.575408,0.737150,0.746320,0.703823,0.722775,0.742699,0.720672,0.705138
AL-02,0.479350,0.486051,1.000000,0.489617,0.485411,0.477353,0.490977,0.699793,0.487486,0.495749,0.487731,0.496176,0.670567,0.665860,0.674315,0.690759,0.638077,0.475336,0.482044,0.475462,0.492421,0.630495,0.699271,0.706226,0.498234,0.488420,0.579314,0.697777,0.699000,0.520351,0.665816,0.633215,0.569040,0.695055,0.701680,0.635707,0.699649,0.493158,0.484418,0.705511,0.708437,0.634763,0.674896,0.700953,0.668831,0.536002,0.556154,0.703950,0.577293,0.706571,...,0.493808,0.480253,0.552441,0.699910,0.697221,0.631363,0.493627,0.635185,0.543971,0.696684,0.634960,0.534624,0.682479,0.680542,0.674161,0.485143,0.471238,0.478411,0.492917,0.551945,0.690944,0.665959,0.472233,0.486310,0.667091,0.708398,0.490581,0.668727,0.632314,0.540716,0.701082,0.698572,0.678480,0.639497,0.543617,0.662886,0.694603,0.694795,0.578047,0.683320,0.487874,0.544605,0.576475,0.488233,0.493435,0.635898,0.478915,0.493256,0.479530,0.639854
AL-03,0.734651,0.740714,0.489617,1.000000,0.754913,0.739737,0.765070,0.509816,0.753537,0.761310,0.759020,0.759598,0.497662,0.498099,0.500184,0.513978,0.717021,0.737322,0.736022,0.740271,0.760604,0.720285,0.515257,0.517647,0.761980,0.750962,0.577491,0.518048,0.525900,0.523221,0.498711,0.714541,0.571298,0.512162,0.512813,0.724875,0.520745,0.757831,0.751707,0.516548,0.526723,0.719218,0.498147,0.518980,0.495029,0.540722,0.570808,0.519254,0.581999,0.524391,...,0.757150,0.740228,0.558594,0.518158,0.514853,0.715486,0.766413,0.720092,0.543652,0.516090,0.721247,0.535861,0.502824,0.512644,0.502659,0.752582,0.740163,0.738597,0.760196,0.561041,0.514154,0.493037,0.736152,0.749318,0.494190,0.517730,0.758858,0.495805,0.720997,0.543017,0.517024,0.524586,0.489238,0.720942,0.551929,0.491516,0.508622,0.521991,0.581161,0.507528,0.759118,0.555420,0.579781,0.753417,0.761359,0.720727,0.741180,0.756338,0.735877,0.721480
AL-04,0.725256,0.732821,0.485411,0.754913,1.000000,0.731245,0.745414,0.507842,0.749763,0.746255,0.750107,0.749702,0.493062,0.492439,0.500174,0.504636,0.708699,0.727550,0.728966,0.728194,0.752189,0.709038,0.509568,0.517989,0.748668,0.736166,0.569767,0.518275,0.518707,0.514918,0.492821,0.704929,0.571658,0.511733,0.508806,0.715419,0.512865,0.745379,0.735510,0.514440,0.521434,0.712335,0.492066,0.517306,0.483005,0.532684,0.565476,0.513652,0.574739,0.521504,...,0.746082,0.729306,0.550201,0.515226,0.508080,0.708795,0.755373,0.715149,0.543061,0.514516,0.713282,0.525528,0.498776,0.504807,0.497300,0.740045,0.733290,0.727758,0.749267,0.554105,0.515095,0.485419,0.725509,0.743764,0.488412,0.512651,0.750513,0.494124,0.710119,0.537086,0.507412,0.518608,0.490773,0.713103,0.547158,0.489138,0.509774,0.516403,0.571580,0.497268,0.746014,0.547667,0.574622,0.745067,0.748474,0.710544,0.726829,0.745235,0.725936,0.711577
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WI-07,0.697347,0.703823,0.635898,0.720727,0.710544,0.701722,0.716585,0.656476,0.717589,0.719152,0.714466,0.724206,0.644652,0.637202,0.646509,0.662303,0.842332,0.697474,0.709551,0.699475,0.720386,0.838987,0.665770,0.674735,0.724162,0.712493,0.551844,0.670586,0.676173,0.499087,0.638637,0.840487,0.545826,0.666082,0.665666,0.843513,0.670512,0.718513,0.708160,0.669278,0.680396,0.841989,0.642914,0.668477,0.638135,0.517065,0.541069,0.674895,0.554697,0.675087,...,0.720693,0.698757,0.532315,0.668606,0.662945,0.838887,0.725256,0.842401,0.522702,0.668267,0.843684,0.509449,0.653121,0.654574,0.651858,0.713581,0.704145,0.701325,0.722522,0.538704,0.668806,0.637164,0.697190,0.715754,0.636443,0.670774,0.721384,0.642126,0.842912,0.521456,0.667850,0.673569,0.643014,0.844993,0.529869,0.640474,0.663355,0.668456,0.556281,0.654041,0.719136,0.529979,0.556588,0.716270,0.724774,1.000000,0.702275,0.721395,0.694571,0.845410
WI-08,0.722638,0.722775,0.478915,0.741180,0.726829,0.717851,0.737302,0.496135,0.743688,0.741357,0.740112,0.743357,0.487030,0.490062,0.488427,0.497069,0.706545,0.722828,0.718247,0.718821,0.740709,0.703118,0.508844,0.506233,0.745068,0.738791,0.569123,0.509526,0.514303,0.510285,0.492300,0.698430,0.563855,0.507263,0.504918,0.705058,0.508160,0.738400,0.731707,0.511679,0.520824,0.705187,0.487077,0.507649,0.484195,0.529791,0.554577,0.511660,0.565786,0.515624,...,0.740702,0.721288,0.552614,0.509785,0.502437,0.702112,0.744530,0.704739,0.539836,0.503920,0.704747,0.525656,0.499393,0.503950,0.491626,0.733513,0.721931,0.723561,0.742253,0.555524,0.511133,0.483457,0.714885,0.733226,0.476211,0.508226,0.742605,0.487259,0.703889,0.530962,0.509142,0.517667,0.488966,0.707671,0.539144,0.484681,0.506702,0.512895,0.570444,0.499148,0.748395,0.557468,0.579559,0.742294,0.746095,0.702275,1.000000,0.735098,0.718782,0.701836
WV-01,0.731129,0.742699,0.493256,0.756338,0.745235,0.736105,0.758396,0.512639,0.750850,0.755266,0.753620,0.756789,0.500891,0.505505,0.504722,0.513078,0.719045,0.730190,0.739253,0.738037,0.754611,0.717777,0.523237,0.524804,0.761664,0.745542,0.580968,0.523661,0.522962,0.514732,0.501530,0.715516,0.573052,0.516955,0.517864,0.722106,0.524312,0.755112,0.745860,0.523242,0.531855,0.721834,0.500281,0.520207,0.493570,0.538434,0.568068,0.522242,0.581068,0.528583,...,0.757325,0.737444,0.562761,0.519350,0.515809,0.718039,0.761225,0.721664,0.548454,0.519865,0.721305,0.533127,0.510428,0.514187,0.502450,0.750944,0.736250,0.737779,0.759118,0.558529,0.521159,0.493717,0.728586,0.751846,0.494356,0.524489,0.758011,0.498796,0.719491,0.543366,0.519850,0.524705,0.494794,0.722839,0.551478,0.498382,0.511884,0.522940,0.581464,0.508147,0.757767,0.560141,0.578678,0.753206,0.760491,0.721395,0.735098,1.000000,0.744211,0.723254
WV-02,0.714252,0.720672,0.479530,0.735877,0.725936,0.715021,0.731095,0.496025,0.737180,0.741957,0.733722,0.743516,0.484943,0.480147,0.487237,0.502027,0.694561,0.719072,0.719514,0.716660,0.737203,0.697423,0.502515,0.510627,0.740447,0.724222,0.565432,0.507304,0.509455,0.508885,0.486036,0.692612,0.566079,0.500297,0.502073,0.698811,0.505156,0.740476,0.728527,0.502377,0.511393,0.697047,0.485101,0.507749,0.479711,0.528226,0.554266,0.508341,0.571366,0.510781,...,0.735616,0.723451,0.547882,0.506310,0.503582,0.698725,0.742059,0.696519,0.538760,0.505353,0.699316,0.524050,0.491410,0.499233,0.491557,0.726784,0.717387,0.718444,0.739463,0.550836,0.507689,0.480854,0.712655,0.730728,0.482449,0.506685,0.740627,0.486686,0.699557,0.530539,0.504578,0.510724,0.480109,0.699090,0.540699,0.486348,0.499035,0.510217,0.573564,0.496919,0.737139,0.546373,0.568011,0.732344,0.739863,0.694571,0.718782,0.744211,1.000000,0.698842
WY-AL,0.696521,0.705138,0.639854,0.721480,0.711577,0.701885,0.715781,0.656305,0.717798,0.721658,0.715678,0.727298,0.646189,0.638528,0.642880,0.661283,0.842749,0.698063,0.707839,0.700866,0.719036,0.838318,0.668183,0.671655,0.723666,0.710652,0.551380,0.672857,0.676957,0.495887,0.639521,0.838433,0.547508,0.663995,0.665156,0.843865,0.668172,0.717681,0.709692,0.666504,0.679584,0.842272,0.644024,0.669971,0.636992,0.515391,0.541464,0.671693,0.553930,0.677888,...,0.723297,0.700257,0.536575,0.670355,0.660504,0.837358,0.728172,0.847152,0.522341,0.668532,0.842490,0.506273,0.652851,0.658200,0.648862,0.711404,0.702358,0.704204,0.721627,0.535479,0.666493,0.635677,0.697114,0.717844,0.639669,0.670803,0.723501,0.643311,0.839726,0.526519,0.667697,0.676118,0.645077,0.844644,0.527998,0.641412,0.661076,0.667205,0.556883,0.648623,0.719293,0.531009,0.557562,0.714723,0.723107,0.845410,0.701836,0.723254,0.698842,1.000000

In [177]:
post.shape

(418, 20000)

In [178]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [179]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:30<00:00, 646.40it/s]

array(['MO-02', 'SC-01', 'OH-07', ..., 'MI-10', 'MI-10', 'AR-02'],
      shape=(20000,), dtype='<U32')

In [180]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-8.46618,1,0,46.957206,0.565766,46.963324,0.565766,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.565766,0.752174,0.006119,-4.577235,-19.716169,1,-39.432338,48.654853,3.446924,34.710,3,41.858552,55.393353
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,18.397008,0.000000,0.000000,0.000000,-37.176003,-45.710827,-1,-91.421653,30.253001,3.459785,0.000,4,23.524393,37.123638
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,8.220432,0.000000,0.000000,0.000000,-57.468099,-47.132870,-1,-94.265741,20.427595,3.504481,0.000,5,13.602194,27.330026

In [181]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.110
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-8.46618,1,0,46.957206,0.565766,46.963324,0.565766,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.565766,0.752174,0.006119,-4.577235,-19.716169,1,-39.432338,48.654853,3.446924,34.710,3,41.858552,55.393353,1.285
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,18.397008,0.000000,0.000000,0.000000,-37.176003,-45.710827,-1,-91.421653,30.253001,3.459785,0.000,4,23.524393,37.123638,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,8.220432,0.000000,0.000000,0.000000,-57.468099,-47.132870,-1,-94.265741,20.427595,3.504481,0.000,5,13.602194,27.330026,0.000

In [182]:
data.sort_values('tipping_point_prob', ascending=False).head(10)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
229,229,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE",no_match,2799701.44,0.00,2799701.44,100.000000,0.000000,North Carolina,NC-11,88.740422,3.902084,0.797632,1.120840,3.305854,24.807640,-7.843347,-4.057125,-5.003681,49.294326,45.192821,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.0,0.00000,0.00000,37,3711,3,10000.000000,0.000000,0.000000,0.000000e+00,-1.541181,50.000000,0,100.000000,51.306934,3.613709,64.255,230,44.235068,58.466571,2.895
98,98,FL-22,Pia Dandiya,Casey Askar,False,False,FL,22,"DANDIYA, PIA","ASKAR, CASEY",1965051.29,57760.00,2022811.29,97.144568,2.855432,Florida,FL-22,53.931205,26.984941,3.703933,0.199203,13.186062,27.190634,-0.817400,-4.551960,-3.618320,91.180168,44.697986,0.987401,-8.46618,0,0,46.286766,0.600120,44.430149,0.600120,South Atlantic,2026,0.0,0.00000,0.00000,12,1222,6,9437.067100,0.600120,0.774674,-1.856617e+00,1.229540,47.144568,0,94.289136,52.161708,3.602608,72.765,99,45.012683,59.319639,2.820
193,193,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",1135198.13,1290223.21,2425421.34,46.804162,53.195838,Michigan,MI-10,76.551128,2.316124,5.150984,0.123322,13.269372,29.340000,-2.765891,-2.592362,-2.635744,99.999226,46.657584,0.987401,-8.46618,0,0,45.000000,0.219968,45.000000,0.219968,East North Central,2026,0.0,0.00000,0.00000,26,2610,2,2190.629568,0.219968,0.469007,-1.460326e-07,3.194693,-3.195838,0,-6.391676,51.039307,3.595543,61.530,194,43.946143,58.129897,2.770
273,273,NY-17,Cait Conley,Mike Lawler,False,True,NY,17,"CONLEY, CAIT","LAWLER, MICHAEL VINCENT",3706160.25,3186004.97,6892165.22,53.773526,46.226474,New York,NY-17,70.961924,14.978446,4.840493,0.059866,7.686273,48.490000,2.820018,1.029915,1.477441,87.206472,50.279862,0.987401,-8.46618,0,1,45.156078,0.153630,49.869935,0.153630,Mid-Atlantic,2026,0.0,0.00000,0.00000,36,3617,0,2891.592088,0.153630,0.391957,4.713858e+00,11.421063,3.773526,-1,7.547052,51.656830,3.493113,68.270,274,44.876291,58.565833,2.715
183,183,ME-02,Matt Dunlap,Paul LePage,False,False,ME,2,"DUNLAP, MATT","LEPAGE, PAUL",1181075.25,1415549.45,2596624.70,45.485019,54.514981,Maine,ME-02,94.623805,1.542589,0.598455,0.552005,0.848532,26.920000,-5.410176,-3.867301,-4.253020,26.830060,45.382645,0.987401,-8.46618,0,0,48.971316,0.911577,48.988696,0.911577,New England,2026,0.0,0.25284,-0.25284,23,2302,3,2068.886995,0.911577,0.954765,1.737987e-02,-0.039860,-4.514981,0,-9.029961,50.337309,3.596529,53.810,184,43.245482,57.481123,2.695
37,37,CA-22,Randy Villegas,David Valadao,False,True,CA,22,"VILLEGAS, RANDY","VALADAO, DAVID",2396295.54,1423592.37,3819887.91,62.732090,37.267910,California,CA-22,22.131732,64.469110,4.924433,0.538078,6.308791,6.196120,6.443675,-0.178428,1.477097,85.545753,49.071518,0.987401,-8.46618,0,1,48.000000,0.038271,44.000000,0.038271,Pacific,2026,0.0,0.00000,0.00000,6,622,4,3935.315176,0.038271,0.195629,-4.000000e+00,11.420375,12.732090,-1,25.464181,51.658212,3.459958,68.655,38,44.823181,58.428181,2.670
190,190,MI-07,William Lawrence,Tom Barrett,False,True,MI,7,"LAWRENCE, WILLIAM","BARRETT, THOMAS MORE",1065694.20,3350486.21,4416180.41,24.131582,75.868418,Michigan,MI-07,85.239895,4.803904,1.944855,0.170025,5.279273,36.270000,-2.003691,0.098125,-0.427329,68.756305,49.348071,0.987401,-8.46618,0,1,48.971702,0.266841,46.971702,0.266841,East North Central,2026,0.0,0.00000,0.00000,26,2607,2,582.333253,0.266841,0.516567,-2.000000e+00,7.611523,-25.868418,-1,-51.736836,51.151758,3.505314,63.225,191,44.274410,58.067168,2.500
123,123,IA-03,Sarah Trone Garriott,Zach Nunn,False,True,IA,3,"TRONE GARRIOTT, SARAH","NUNN, ZACH",4755754.76,1010301.85,5766056.61,82.478461,17.521539,Iowa,IA-03,86.341081,5.022950,2.732262,0.063009,3.929259,35.410000,-2.445778,-1.482072,-1.722998,77.628515,47.767874,0.987401,-8.46618,0,1,42.000000,0.001483,48.000000,0.001483,West North Central,2026,0.0,0.00000,0.00000,19,1903,2,6802.696551,0.001483,0.038509,6.000000e+00,5.020184,32.478461,-1,64.956922,52.023570,3.498182,72.060,124,45.132427,58.979356,2.485
71,71,CO-08,Manny Rutinel,Gabe Evans,False,True,CO,8,"RUTINEL, MANNY","EVANS, TIMOTHY GABRIEL JOSEPH",4220418.50,2098932.57,6319351.07,66.785631,33.214369,Colorado,CO-08,61.985014,30.668107,2.797756,0.346752,1.898138,27.960000,0.077260,-0.189970,-0.123163,93.243947,49.059976,0.987401,-8.46618,0,1,46.300000,0.533138,48.000000,0.533138,Mountain,2026,0.0,0.00000,0.00000,8,808,6,4460.320535,0.533138,0.730163,1.700000e+00,8.219855,16.785631,-1,33.571262,52.149496,3.539309,72.915,72,45.146308,59.119113,2.465
84,84,FL-07,Bale Dalton,Ryan Elijah,False,False,FL,7,"DALTON, BALE","ELIJAH, RYAN",1196852.72,221855.46,1418708.18,84.362150,15.637850,Florida,FL-07,66.558362,19.398792,2.991603,0.123627,9.057449,25.552545,-5.072419,-5.558666,-5.437104,94.888595,43.691280,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.0,0.00000,0.00000,12,1207,0,7116.972318,0.000000,0.000000,0.000000e+00,-2.408028,34.362150,0,68.724300,50.309440,3.612374,53.545,85,43.217684,57.412868,2.455

In [183]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [184]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.110,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-8.46618,1,0,46.957206,0.565766,46.963324,0.565766,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.565766,0.752174,0.006119,-4.577235,-19.716169,1,-39.432338,48.654853,3.446924,34.710,3,41.858552,55.393353,1.285,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,18.397008,0.000000,0.000000,0.000000,-37.176003,-45.710827,-1,-91.421653,30.253001,3.459785,0.000,4,23.524393,37.123638,0.000,Safe R,"<b style=""color:#366bbf;"">Lee McInnis (D)</b> ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,8.220432,0.000000,0.000000,0.000000,-57.468099,-47.132870,-1,-94.265741,20.427595,3.504481,0.000,5,13.602194,27.330026,0.000,Safe R,"<b style=""color:#366bbf;"">Amanda Pusczek (D)</..."

In [185]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.110,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-8.46618,1,0,46.957206,0.565766,46.963324,0.565766,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.565766,0.752174,0.006119,-4.577235,-19.716169,1,-39.432338,48.654853,3.446924,34.710,3,41.858552,55.393353,1.285,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R)

In [186]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.0,0.0,0.0,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.11,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.0,0.0,0.0,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.00,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,

In [187]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.110,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+8.2
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+26.3
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-8.46618,1,0,46.957206,0.565766,46.963324,0.565766,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.565766,0.752174,0.006119,-4.577235,-19.716169,1,-39.432338,48.654853,3.446924,34.710,3,41.858552,55.393353,1.285,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+2.7

In [188]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.110,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+8.2,87.535,12.5,87.5,12.5%,87.5%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+26.3,99.995,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-8.46618,1,0,46.957206,0.565766,46.963324,0.565766,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.565766,0.752174,0.006119,-4.577235,-19.716169,1,-39.432338,48.654853,3.446924,34.710,3,41.858552,55.393353,1.285,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+2.7,65.290,34.7,65.3,34.7%,65.3%

In [189]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.000000,0.000000,0.000000,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.110,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+8.2,87.535,12.5,87.5,12.5%,87.5%,5.510750
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.000000,0.000000,0.000000,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+26.3,99.995,0.0,100.0,<1%,>99%,10.036310
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-8.46618,1,0,46.957206,0.565766,46.963324,0.565766,East South Central,2026,0.0,0.0,0.0,1,102,5,917.110424,0.565766,0.752174,0.006119,-4.577235,-19.716169,1,-39.432338,48.654853,3.446924,34.710,3,41.858552,55.393353,1.285,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+2.7,65.290,34.7,65.3,34.7%,65.3%,11.774133

In [190]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-8.46618,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,975.656077,0.0,0.0,0.0,-4.444424,-18.764506,-1,-37.529012,45.908812,3.551840,12.465,1,38.920939,52.871007,0.11,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+8.2,87.535,12.5,87.5,12.5%,87.5%,5.51075,D+5.5
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-8.46618,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,122.699498,0.0,0.0,0.0,-26.408102,-38.923019,0,-77.846039,36.845919,3.556759,0.005,2,29.948260,43.859776,0.00,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+26.3,99.995,0.0,100.0,<1%,>99%,10.03631,D+10.0

In [191]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
413    5507
414    5508
415    5401
416    5402
417    5600
Name: geoid, Length: 418, dtype: int64

In [192]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['y_pred'] = np.full(dem_uclen, 100)
dem_uncont['swing_24_to_26'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_24_to_26_swing'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                      x['dem_inc_any'], x['rep_inc_any']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Mike Thompson/Eric J..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Doris Matsui/Mai Van..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Scott Weiner/Connie ..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Lateefah Simon* (D)<..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,True,False,CA,14,6,614,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Aisha Wahab/Melissa ..."

In [193]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['y_pred'] = np.full(rep_uclen, 0)
rep_uncont['swing_24_to_26'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_24_to_26_swing'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                       x['dem_inc_any'], x['rep_inc_any']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0,NaN,NaN,0%,100%,R+100,,"<b style=""color:#366bbf;"">Not Contested (D)</b..."

In [194]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'geoid', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 16)

In [195]:
tab_data = data[['cd', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Bill Hill', 'Kevin Kiley'] else x)
tab_data = tab_data.rename({
    'cd': 'District',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,District,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,AK-AL,Bill Hill (Ind),Nick Begich,Likely R,"<p style=""color:blue;"">12.5%</p>","<p style=""color:red;"">87.5%</p>",R+8.2,D+5.5,0.110
1,AL-01,Clyde Jones Jr.,Jerry Carl,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+26.3,D+10.0,0.000
2,AL-02,Shomari Figures,Rhett Marques,Lean R,"<p style=""color:blue;"">34.7%</p>","<p style=""color:red;"">65.3%</p>",R+2.7,D+11.8,1.285
3,AL-03,Lee McInnis,Mike Rogers,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+39.5,D+7.5,0.000
4,AL-04,Amanda Pusczek,Robert Aderholt,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+59.1,D+7.8,0.000

In [196]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

5.852313360630708

In [197]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

                 vars           x
0     means_seats_tot  236.935700
1  chamber_win_chance   77.780000
0             sv_bias    5.852313

In [198]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [199]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 435 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Win Probability  Seat Share
0    Democrats            77.78    236.9357
1  Republicans            22.22    198.0643

In [200]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')