In [98]:
import warnings
warnings.filterwarnings('ignore')

In [99]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [100]:
pd.set_option('display.max_columns', 100)

In [101]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [102]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        262    Democrats
1        217  Republicans
2        249    Democrats
3        241    Democrats
4        230    Democrats
...      ...          ...
19995    299    Democrats
19996    213  Republicans
19997    207  Republicans
19998    270    Democrats
19999    230    Democrats

[20000 rows x 2 columns]

In [103]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    163      1  0.005  Republicans
1    166      1  0.005  Republicans
2    168      1  0.005  Republicans
3    169      1  0.005  Republicans
4    171      1  0.005  Republicans

In [104]:
np.unique(seat_sims['seats']).shape[0]

189

In [105]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [106]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date           y       geo       type
0  2026-08-30  229.365800  US House      seats
1  2026-08-30   66.120000  US House     chance
2  2026-08-30   22.784344  US House   seats_sd
3  2026-08-30   44.972806     AK-AL     y_pred
4  2026-08-30    3.555839     AK-AL  y_pred_sd

In [107]:
chance_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="House Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser.add_vline(x=pd.to_datetime('2026-10-22').timestamp() * 1000, line_width=1, line_color='black',
                          annotation_text='Poll average methodology update', annotation_position='top right')
chance_time_ser

In [108]:
seats_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 435 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 435]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser.add_vline(x=pd.to_datetime('2026-10-22').timestamp() * 1000, line_width=1, line_color='black',
                          annotation_text='Poll average methodology update', annotation_position='top right')
seats_time_ser

In [109]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [110]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [111]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,19950,19951,19952,19953,19954,19955,19956,19957,19958,19959,19960,19961,19962,19963,19964,19965,19966,19967,19968,19969,19970,19971,19972,19973,19974,19975,19976,19977,19978,19979,19980,19981,19982,19983,19984,19985,19986,19987,19988,19989,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,0.429124,-4.644258,-2.635588,-7.518338,-4.317311,0.042573,-2.791330,-4.354242,-2.498037,-5.377025,0.359940,2.004243,1.290367,-8.955463,6.249702,0.420270,-5.863121,-2.991138,-0.120537,-0.034866,-6.659842,-7.821048,0.837801,-6.558683,-6.452337,-1.511739,-2.866402,-5.249043,-1.849604,-9.904104,-0.866953,-5.194950,-6.027905,1.587583,-2.834770,-3.884049,-5.493723,-5.418976,-2.744198,0.423591,-10.321779,-1.646443,-7.404251,-4.005102,-1.529205,-6.502730,-1.444210,-5.150677,-3.764285,-5.029013,...,-4.320466,-5.121164,-2.330245,-2.514789,-6.079384,-1.631700,-3.366742,-2.458635,-1.388352,-0.326763,-2.479036,-0.528016,-9.730745,2.752387,-3.116221,-6.401298,-0.176018,-1.538165,-1.550747,-4.085350,-3.540392,-4.635202,-2.308673,-6.557170,-2.647472,-3.370653,-0.281928,-4.837645,-0.352484,-7.316569,-1.624848,-3.792229,-2.387315,0.724261,-0.425510,-0.494431,-0.920128,-4.124068,-1.520985,-1.589340,-7.389604,2.841730,1.098370,-4.698563,-3.414089,2.819989,-10.267745,-9.020771,-3.538908,-4.274527
AL-01,-8.636806,-13.493101,-11.595470,-14.159670,-11.253382,-7.325878,-12.177260,-12.313167,-11.979183,-13.733935,-11.330841,-11.995718,-9.049617,-14.477362,-3.802735,-9.332871,-12.628421,-11.897616,-15.973566,-8.568499,-16.508787,-15.972373,-6.194718,-19.563765,-14.953570,-8.618647,-13.361654,-15.948960,-11.744378,-17.851798,-11.180358,-15.242427,-19.234172,-9.110563,-12.838986,-12.769925,-13.773214,-18.199069,-14.568899,-4.369388,-20.043476,-9.138706,-14.644439,-12.114524,-12.977134,-18.008796,-10.622922,-14.362276,-11.249493,-11.987671,...,-12.201153,-11.321534,-13.301802,-9.298005,-12.619721,-12.360541,-11.911106,-14.366242,-13.795819,-8.930415,-9.492596,-9.977824,-17.483829,-8.637995,-10.167921,-20.182549,-4.049440,-13.190568,-16.533475,-16.178982,-10.016764,-12.777637,-13.762653,-10.031802,-12.483260,-14.502257,-9.891894,-14.794727,-9.747612,-14.818119,-8.661075,-13.810198,-14.216402,-8.574624,-7.237678,-8.890039,-10.824388,-13.835200,-15.278347,-12.675769,-14.266201,-10.558119,-12.240454,-11.040423,-16.855276,-6.035891,-16.998184,-18.712993,-7.938386,-13.863933
AL-02,-0.548142,-0.438650,1.062140,1.504277,-4.371722,-3.891063,-2.141734,-1.035619,3.521829,-2.396772,0.075273,0.876991,0.953622,0.788089,-5.545614,-4.314686,4.634345,-4.707397,-1.065845,5.303457,-1.424602,-2.181147,2.346655,-4.075716,0.986831,-0.983565,5.999463,-2.683403,3.240392,-3.031803,0.691690,1.051384,-6.710723,2.241901,0.390606,-0.288460,-2.085043,-4.857673,-4.320120,8.964738,-8.289472,1.762388,-2.072643,-2.190439,-2.810450,1.346492,0.101100,-2.312452,-1.566071,6.097063,...,0.421990,0.415764,-0.984739,-0.167867,-0.162998,1.395993,4.185230,-9.151999,-7.506799,2.087639,0.589768,-2.632096,2.488444,-2.566557,-1.440846,-1.962237,0.900812,1.171216,1.089506,-2.276382,2.462986,-0.069183,1.287734,-2.698679,-9.400007,-1.173078,-0.783957,-0.643294,-0.153832,1.177415,-4.239848,-1.775510,-0.231108,-1.545297,1.316612,4.377060,2.689898,-2.309855,1.531727,1.685414,-1.410639,4.636644,11.124905,-6.658685,4.474653,4.538152,-2.057232,-5.585267,3.148748,-4.495180
AL-03,-16.180205,-23.143319,-18.558058,-22.442142,-21.592461,-15.203643,-19.937510,-14.767038,-20.814001,-20.908244,-15.510033,-16.563089,-14.653609,-21.015312,-11.750451,-14.407965,-22.666848,-21.286422,-20.002330,-15.363224,-23.268271,-23.751753,-15.290718,-21.625553,-22.448317,-17.553691,-20.063232,-23.640409,-20.359259,-25.179161,-16.943532,-17.366352,-22.423283,-14.398272,-20.338124,-13.773761,-22.303992,-20.364656,-20.754374,-15.860545,-29.069366,-19.877918,-20.568075,-18.795409,-19.697426,-23.612643,-15.905472,-21.857822,-17.989809,-22.375976,...,-19.201430,-20.389148,-19.032469,-18.345363,-20.695377,-16.213526,-20.759965,-21.392931,-21.217843,-16.496465,-19.220720,-16.344048,-25.413949,-13.619087,-13.765811,-26.648544,-14.169208,-17.459654,-23.484624,-20.680570,-19.389555,-21.275098,-17.035459,-22.068372,-19.223173,-15.731836,-14.046187,-23.842635,-17.494807,-25.108932,-16.829319,-18.566289,-18.320127,-15.145538,-17.670084,-16.478358,-19.514264,-17.778573,-20.407290,-16.664994,-20.287658,-12.690438,-16.969349,-22.488290,-21.408858,-15.084185,-22.966076,-24.062047,-17.151535,-20.785798
AL-04,-24.150149,-31.239834,-28.147455,-31.928689,-28.167946,-23.965387,-29.204421,-28.748883,-31.728616,-26.561018,-26.189558,-26.846215,-25.645309,-34.099746,-20.756484,-26.170005,-32.015399,-29.516328,-30.650786,-26.699933,-30.886000,-31.153138,-24.281364,-31.762166,-32.480626,-28.645539,-29.533654,-33.300862,-29.032667,-31.958586,-25.896347,-31.301735,-34.475643,-22.763247,-29.898918,-25.485755,-30.848647,-32.800853,-32.428436,-20.877793,-35.791193,-29.835518,-32.153729,-26.628731,-30.223369,-31.377732,-25.922279,-31.861302,-26.292058,-30.507752,...,-30.401609,-29.189132,-29.158722,-27.580282,-29.411221,-25.327542,-30.059526,-30.540940,-29.405332,-25.306372,-30.078036,-25.847721,-35.379818,-24.728467,-25.747946,-39.611264,-25.156468,-31.576117,-34.801927,-29.646194,-29.770536,-32.093070,-28.675328,-29.116571,-31.541392,-31.676542,-26.452717,-28.780972,-26.097547,-30.655135,-27.287286,-28.257804,-33.323050,-28.372716,-25.106036,-25.837844,-28.411333,-29.315748,-29.930415,-26.811698,-31.931842,-24.572761,-28.496821,-36.365204,-29.263483,-23.150530,-36.623453,-36.793047,-27.064568,-29.532400

In [112]:
sim_corr = post_untransp.corr()

In [113]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,...,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.723858,0.484268,0.742377,0.732982,0.718942,0.741344,0.498649,0.737345,0.746729,0.742651,0.739188,0.486999,0.486387,0.485197,0.505253,0.700630,0.720779,0.729796,0.725820,0.739929,0.703305,0.505367,0.516836,0.747417,0.738689,0.569010,0.507299,0.513560,0.514923,0.482620,0.698913,0.571788,0.506824,0.502741,0.701479,0.509571,0.748910,0.733703,0.510487,0.512657,0.704259,0.486798,0.510499,0.486503,0.525241,0.549629,0.511199,0.566239,0.511727,...,0.737353,0.718399,0.547411,0.510205,0.514973,0.701739,0.749489,0.700407,0.528830,0.503765,0.701527,0.535238,0.500876,0.487514,0.500217,0.733983,0.723084,0.724260,0.742956,0.551722,0.510095,0.482800,0.721734,0.739142,0.486067,0.511823,0.739789,0.482644,0.697837,0.531476,0.512042,0.513422,0.489266,0.702437,0.543523,0.487300,0.504944,0.512153,0.576356,0.497660,0.739174,0.544970,0.575440,0.739192,0.746623,0.698028,0.720791,0.736978,0.720615,0.698449
AL-01,0.723858,1.000000,0.494157,0.750386,0.742451,0.722413,0.745499,0.505136,0.745048,0.749890,0.744897,0.747993,0.493951,0.489200,0.488909,0.512338,0.708697,0.729640,0.733208,0.729248,0.745415,0.706643,0.510394,0.516662,0.749000,0.736882,0.565617,0.512930,0.519116,0.519754,0.493595,0.703646,0.569144,0.509322,0.509623,0.709779,0.513266,0.748949,0.734038,0.513599,0.518471,0.707277,0.488817,0.516026,0.487069,0.530079,0.547648,0.514898,0.569288,0.513533,...,0.742316,0.721833,0.550604,0.515359,0.518688,0.702269,0.751168,0.708163,0.539748,0.509272,0.709517,0.537253,0.499650,0.497062,0.500513,0.740128,0.725542,0.730521,0.748001,0.547932,0.509031,0.488554,0.725566,0.737599,0.492459,0.513820,0.742784,0.492757,0.705845,0.534681,0.514898,0.518194,0.488717,0.709724,0.538085,0.490684,0.508422,0.515166,0.580313,0.503711,0.746676,0.544495,0.572997,0.741916,0.751467,0.711763,0.719540,0.745907,0.726024,0.708858
AL-02,0.484268,0.494157,1.000000,0.506125,0.499071,0.486877,0.509671,0.704144,0.495615,0.505534,0.496226,0.502044,0.683735,0.677106,0.683388,0.700780,0.641646,0.487233,0.494337,0.490457,0.505622,0.639918,0.705638,0.713614,0.509555,0.502790,0.583474,0.705516,0.705685,0.526997,0.672547,0.644452,0.584618,0.703984,0.704725,0.645174,0.707120,0.510175,0.501979,0.711547,0.715125,0.646364,0.680205,0.705196,0.678463,0.552354,0.568582,0.710305,0.584737,0.712805,...,0.503071,0.492576,0.559801,0.706034,0.701945,0.642118,0.510907,0.639914,0.552651,0.701607,0.647244,0.550022,0.690181,0.684142,0.687951,0.501608,0.485199,0.495092,0.501912,0.561177,0.702457,0.676450,0.490047,0.502467,0.675081,0.712968,0.503184,0.680279,0.645272,0.542575,0.707898,0.707025,0.678722,0.645807,0.559593,0.670979,0.699664,0.706192,0.590224,0.694425,0.501593,0.557379,0.589355,0.500959,0.503321,0.646147,0.481949,0.505846,0.491264,0.643659
AL-03,0.742377,0.750386,0.506125,1.000000,0.761407,0.748190,0.773689,0.521282,0.765215,0.769703,0.763568,0.768955,0.505836,0.503282,0.500791,0.524232,0.724302,0.744506,0.746157,0.748766,0.765775,0.726193,0.525163,0.531217,0.768758,0.759463,0.582116,0.525437,0.533736,0.531169,0.503767,0.722533,0.584414,0.522174,0.524045,0.729623,0.525283,0.765888,0.753897,0.527700,0.531156,0.723742,0.501552,0.527609,0.502917,0.545656,0.566689,0.527422,0.582032,0.531887,...,0.761874,0.740928,0.563301,0.532539,0.530760,0.721111,0.773165,0.727201,0.547774,0.522646,0.727699,0.551168,0.515237,0.509694,0.515737,0.755022,0.740885,0.742553,0.768994,0.560125,0.521855,0.498028,0.744203,0.759479,0.504485,0.528193,0.765378,0.499014,0.723820,0.547645,0.527431,0.532890,0.504136,0.725538,0.561660,0.499696,0.523376,0.530880,0.591690,0.516664,0.762975,0.563852,0.587802,0.763857,0.768789,0.729729,0.741417,0.762007,0.745989,0.726657
AL-04,0.732982,0.742451,0.499071,0.761407,1.000000,0.737245,0.755286,0.512359,0.753589,0.756784,0.757514,0.755079,0.493847,0.498879,0.494845,0.516214,0.716763,0.735361,0.738344,0.738111,0.759462,0.716065,0.516633,0.525169,0.756711,0.746818,0.571981,0.521616,0.522076,0.521797,0.496973,0.713745,0.575867,0.515886,0.515666,0.720269,0.517795,0.757459,0.743774,0.524033,0.525051,0.716563,0.496075,0.522592,0.493485,0.535571,0.556621,0.515431,0.572352,0.525040,...,0.749339,0.732560,0.552691,0.527812,0.526747,0.713240,0.758671,0.719468,0.544450,0.517008,0.719462,0.542729,0.511121,0.502049,0.506297,0.747063,0.735484,0.739824,0.758340,0.554922,0.516011,0.493772,0.735204,0.753794,0.494350,0.522151,0.754454,0.493119,0.714286,0.542112,0.518605,0.525363,0.499727,0.717187,0.552008,0.497426,0.516832,0.523179,0.582732,0.508579,0.753385,0.553900,0.577750,0.753288,0.755781,0.716260,0.730666,0.750463,0.731855,0.717148
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WI-07,0.698028,0.711763,0.646147,0.729729,0.716260,0.707806,0.723624,0.663147,0.724829,0.728576,0.725349,0.728082,0.655003,0.653389,0.651749,0.673940,0.850236,0.708970,0.714114,0.710448,0.730906,0.846852,0.678184,0.684331,0.729847,0.720836,0.556132,0.677101,0.683478,0.513027,0.647300,0.847944,0.561971,0.679558,0.676574,0.850814,0.678208,0.729066,0.717663,0.681983,0.683059,0.849038,0.651635,0.678659,0.646512,0.525252,0.540043,0.685677,0.559839,0.681860,...,0.725788,0.706831,0.533632,0.679469,0.680823,0.845558,0.729935,0.849169,0.522898,0.674876,0.851250,0.519421,0.663174,0.655963,0.663512,0.719413,0.708006,0.709322,0.731014,0.536623,0.676809,0.649114,0.705306,0.721675,0.647354,0.681639,0.727085,0.648664,0.850371,0.520575,0.681901,0.682433,0.651128,0.851738,0.535184,0.647981,0.673990,0.680052,0.566099,0.666455,0.723393,0.535264,0.559704,0.722163,0.730736,1.000000,0.704369,0.726610,0.706961,0.851965
WI-08,0.720791,0.719540,0.481949,0.741417,0.730666,0.717352,0.739375,0.496875,0.746524,0.747548,0.741929,0.745229,0.483594,0.489997,0.486922,0.501652,0.705689,0.726468,0.728412,0.726303,0.742629,0.709516,0.509018,0.511858,0.745124,0.738734,0.559348,0.505277,0.515734,0.511864,0.488817,0.701702,0.563462,0.507000,0.501977,0.706407,0.510394,0.745190,0.732867,0.512389,0.514519,0.704765,0.485075,0.511491,0.488997,0.525306,0.544345,0.512080,0.560954,0.513980,...,0.739370,0.721615,0.548710,0.514466,0.513742,0.703717,0.744115,0.707590,0.531168,0.506385,0.705962,0.527350,0.500978,0.493681,0.503254,0.734679,0.720732,0.724579,0.744180,0.543798,0.507097,0.480855,0.724681,0.735066,0.482692,0.508358,0.742313,0.487956,0.703690,0.529712,0.510787,0.517434,0.486731,0.705864,0.540273,0.483075,0.507102,0.515293,0.573726,0.499345,0.743324,0.556619,0.577903,0.744081,0.746390,0.704369,1.000000,0.738789,0.721752,0.703972
WV-01,0.736978,0.745907,0.505846,0.762007,0.750463,0.741066,0.763427,0.515792,0.756991,0.765768,0.760894,0.763191,0.509509,0.509876,0.500348,0.522092,0.724074,0.741654,0.749481,0.750810,0.763236,0.723501,0.525060,0.533312,0.766144,0.753166,0.583913,0.523569,0.530051,0.529816,0.507144,0.718644,0.581800,0.522957,0.521448,0.727238,0.526868,0.761348,0.750179,0.531430,0.528686,0.724508,0.503062,0.527688,0.503049,0.546286,0.564373,0.524419,0.579105,0.532697,...,0.760475,0.739152,0.568010,0.528269,0.532525,0.717927,0.765364,0.723961,0.550555,0.523769,0.723106,0.549104,0.515647,0.507902,0.514613,0.754897,0.741468,0.740131,0.764971,0.563038,0.523620,0.498814,0.735254,0.757275,0.501133,0.534908,0.761923,0.499516,0.721912,0.545254,0.523382,0.532466,0.507994,0.725785,0.559993,0.501532,0.524067,0.529918,0.595647,0.517493,0.759606,0.566099,0.586283,0.760035,0.768558,0.726610,0.738789,1.000000,0.748921,0.725720
WV-02,0.720615,0.726024,0.491264,0.745989,0.731855,0.721828,0.740823,0.501176,0.739842,0.747866,0.741003,0.748851,0.496196,0.495596,0.488628,0.507560,0.706533,0.725849,0.731170,0.728538,0.743271,0.709035,0.510442,0.522911,0.747740,0.735782,0.566893,0.511588,0.519645,0.513453,0.492051,0.702412,0.567796,0.511036,0.507822,0.706925,0.511828,0.748657,0.732197,0.514521,0.514132,0.705099,0.488923,0.517946,0.489287,0.531645,0.549929,0.513893,0.567660,0.518128,...,0.744135,0.726917,0.546799,0.516310,0.517602,0.704071,0.748095,0.707726,0.537112,0.509037,0.709408,0.537154,0.501315,0.494391,0.502598,0.735946,0.718263,0.724134,0.748009,0.546936,0.511243,0.488804,0.722695,0.738224,0.495053,0.513632,0.746323,0.490301,0.705978,0.534553,0.512980,0.519266,0.492293,0.709530,0.539811,0.487684,0.509749,0.515746,0.577294,0.504202,0.743743,0.547851,0.567159,0.738234,0.742708,0.706961,0.721752,0.748921,1.000000,0.709458
WY-AL,0.698449,0.708858,0.643659,0.726657,0.717148,0.707047,0.723161,0.663598,0.724142,0.730181,0.723663,0.730552,0.653702,0.652132,0.645618,0.670408,0.850182,0.707455,0.711180,0.712584,0.727498,0.847224,0.677600,0.680513,0.729128,0.721076,0.552920,0.678275,0.684147,0.507504,0.651024,0.846408,0.558269,0.675887,0.670650,0.851003,0.675739,0.728242,0.719801,0.676191,0.680302,0.850047,0.651734,0.679096,0.646368,0.520640,0.539009,0.678748,0.557186,0.682152,...,0.726803,0.707079,0.533485,0.677360,0.677967,0.844918,0.732505,0.853253,0.520770,0.674491,0.850292,0.517836,0.660914,0.650389,0.657864,0.718909,0.704800,0.711410,0.730640,0.533054,0.672705,0.647262,0.708485,0.723777,0.647875,0.678094,0.729776,0.647743,0.848272,0.521278,0.679070,0.683822,0.654364,0.851083,0.531373,0.646500,0.671339,0.679561,0.563721,0.664154,0.725139,0.531935,0.558416,0.716934,0.727069,0.851965,0.703972,0.725720,0.709458,1.000000

In [114]:
post.shape

(418, 20000)

In [115]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [116]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:28<00:00, 710.60it/s]

array(['ME-02', 'NY-17', 'FL-07', ..., 'OH-15', 'CO-04', 'OH-07'],
      shape=(20000,), dtype='<U32')

In [117]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.000000,0.000000,0.000000,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.520,1,39.568068,53.708686
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.030,2,30.486193,44.646098
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.195947,1,0,46.957206,0.161048,46.963324,0.161048,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.161048,0.401308,0.006119,-3.847468,-5.527053,1,-11.054107,49.499491,3.490063,44.405,3,42.613911,56.317828
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",62981.54,1590746.93,1653728.47,3.808457,96.191543,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.504346,0.000000,0.000000,0.000000,-36.446237,-46.191543,-1,-92.383086,30.585681,3.512893,0.000,4,23.655239,37.437476
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",22154.32,625402.87,647557.19,3.421214,96.578786,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,11.704708,0.000000,0.000000,0.000000,-56.738332,-46.578786,-1,-93.157571,20.772985,3.560753,0.000,5,13.776562,27.692205

In [118]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.000000,0.000000,0.000000,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.520,1,39.568068,53.708686,0.065
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.030,2,30.486193,44.646098,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.195947,1,0,46.957206,0.161048,46.963324,0.161048,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.161048,0.401308,0.006119,-3.847468,-5.527053,1,-11.054107,49.499491,3.490063,44.405,3,42.613911,56.317828,0.950
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",62981.54,1590746.93,1653728.47,3.808457,96.191543,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.504346,0.000000,0.000000,0.000000,-36.446237,-46.191543,-1,-92.383086,30.585681,3.512893,0.000,4,23.655239,37.437476,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",22154.32,625402.87,647557.19,3.421214,96.578786,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,11.704708,0.000000,0.000000,0.000000,-56.738332,-46.578786,-1,-93.157571,20.772985,3.560753,0.000,5,13.776562,27.692205,0.000

In [119]:
data.sort_values('tipping_point_prob', ascending=False).head(10)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
193,193,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",3380348.82,1841619.43,5221968.25,64.733232,35.266768,Michigan,MI-10,76.551128,2.316124,5.150984,0.123322,13.269372,29.340000,-2.765891,-2.592362,-2.635744,99.999226,46.657584,0.987401,-9.195947,0,0,45.000000,0.062615,45.000000,0.062615,East North Central,2026,0.0,0.00000,0.00000,26,2610,2,4190.391320,0.062615,0.250230,-1.460326e-07,3.924459,14.733232,0,29.466464,52.149542,3.653920,72.155,194,44.976743,59.250069,3.010
98,98,FL-22,Pia Dandiya,Casey Askar,False,False,FL,22,"DANDIYA, PIA","ASKAR, CASEY",3601978.98,383626.04,3985605.02,90.374710,9.625290,Florida,FL-22,53.931205,26.984941,3.703933,0.199203,13.186062,27.190634,-0.817400,-4.551960,-3.618320,91.180168,44.697986,0.987401,-9.195947,0,0,46.286766,0.183111,44.430149,0.183111,South Atlantic,2026,0.0,0.00000,0.00000,12,1222,6,8167.588214,0.183111,0.427915,-1.856617e+00,1.959306,40.374710,0,80.749420,52.340008,3.657461,73.760,99,45.065615,59.480015,2.935
183,183,ME-02,Matt Dunlap,Paul LePage,False,False,ME,2,"DUNLAP, MATT","LEPAGE, PAUL",2730281.55,1689499.20,4419780.75,61.774140,38.225860,Maine,ME-02,94.623805,1.542589,0.598455,0.552005,0.848532,26.920000,-5.410176,-3.867301,-4.253020,26.830060,45.382645,0.987401,-9.195947,0,0,50.069480,1.355160,46.458349,1.355160,New England,2026,0.0,0.25284,-0.25284,23,2302,3,3816.044378,1.355160,1.164114,-3.611131e+00,0.689907,11.774140,0,23.548280,51.835933,3.673518,69.185,184,44.600457,59.003454,2.825
123,123,IA-03,Sarah Trone Garriott,Zach Nunn,False,True,IA,3,"TRONE GARRIOTT, SARAH","NUNN, ZACH",7230292.81,1415599.19,8645892.00,83.626916,16.373084,Iowa,IA-03,86.341081,5.022950,2.732262,0.063009,3.929259,35.410000,-2.445778,-1.482072,-1.722998,77.628515,47.767874,0.987401,-9.195947,0,1,42.000000,0.000422,48.000000,0.000422,West North Central,2026,0.0,0.00000,0.00000,19,1903,2,6993.461021,0.000422,0.020546,6.000000e+00,5.749950,33.626916,-1,67.253831,52.402549,3.535891,75.395,124,45.385549,59.290577,2.615
37,37,CA-22,Randy Villegas,David Valadao,False,True,CA,22,"VILLEGAS, RANDY","VALADAO, DAVID",5082726.00,2204205.55,7286931.55,69.751252,30.248748,California,CA-22,22.131732,64.469110,4.924433,0.538078,6.308791,6.196120,6.443675,-0.178428,1.477097,85.545753,49.071518,0.987401,-9.195947,0,1,48.000000,0.010894,44.000000,0.010894,Pacific,2026,0.0,0.00000,0.00000,6,622,4,4865.237178,0.010894,0.104374,-4.000000e+00,12.150141,19.751252,-1,39.502504,52.275722,3.512434,74.350,38,45.433682,59.162817,2.600
229,229,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE","BALKCOM, JENNIFER",5040487.66,106191.99,5146679.65,97.936689,2.063311,North Carolina,NC-11,88.740422,3.902084,0.797632,1.120840,3.305854,24.807640,-7.843347,-4.057125,-5.003681,49.294326,45.192821,0.987401,-9.195947,0,0,56.000000,0.848135,43.000000,0.848135,South Atlantic,2026,0.0,0.00000,0.00000,37,3711,3,9591.595118,0.848135,0.920943,-1.300000e+01,-0.811414,47.936689,0,95.873379,53.415326,3.669591,82.155,230,46.190762,60.614223,2.550
206,206,MO-02,Fred Wellman,Ann Wagner,False,True,MO,2,"WELLMAN, FREDERICK PAUL","WAGNER, ANN L.",2040179.50,2354885.63,4395065.13,46.419779,53.580221,Missouri,MO-02,89.786282,2.324956,3.134970,0.061673,3.001461,48.680000,-6.210595,-3.268235,-4.003825,87.342792,45.981711,0.987401,-9.195947,0,1,48.249295,1.741751,45.436131,1.741751,West North Central,2026,0.0,0.00000,0.00000,29,2902,2,2154.795840,1.741751,1.319754,-2.813164e+00,1.188296,-3.580221,-1,-7.160443,51.830734,3.475470,69.870,207,45.066288,58.678698,2.460
71,71,CO-08,Manny Rutinel,Gabe Evans,False,True,CO,8,"RUTINEL, MANNY","EVANS, TIMOTHY GABRIEL JOSEPH",8269828.34,3271309.22,11541137.56,71.655227,28.344773,Colorado,CO-08,61.985014,30.668107,2.797756,0.346752,1.898138,27.960000,0.077260,-0.189970,-0.123163,93.243947,49.059976,0.987401,-9.195947,0,1,46.300000,0.151760,48.000000,0.151760,Mountain,2026,0.0,0.00000,0.00000,8,808,6,5134.471585,0.151760,0.389564,1.700000e+00,8.949621,21.655227,-1,43.310454,53.073891,3.579480,80.640,72,46.105171,60.141882,2.445
386,386,VA-01,Shannon Taylor,Rob Wittman,False,True,VA,1,"TAYLOR, SHANNON LEIGH","WITTMAN, ROBERT J. MR.",3606006.93,1952376.90,5558383.83,64.875098,35.124902,Virginia,VA-01,75.537803,4.124527,4.097593,0.133339,13.351012,46.900000,-5.404597,-1.752158,-2.665268,73.780628,47.497788,0.987401,-9.195947,0,1,47.121167,1.209077,46.014391,1.209077,South Atlantic,2026,0.0,0.00000,0.00000,51,5101,2,4208.778278,1.209077,1.099580,-1.106775e+00,3.865410,14.875098,-1,29.750195,51.723065,3.453838,68.975,387,44.995619,58.470773,2.440
314,314,PA-07,Bob Brooks,Ryan Mackenzie,False,True,PA,7,"BROOKS, BOB","MACKENZIE, RYAN EDWARD",4181508.28,1902194.06,6083702.34,68.732953,31.267047,Pennsylvania,PA-07,75.458946,15.481046,2.435986,0.030199,4.952274,31.050000,-1.956264,-0.869379,-1.141100,81.633883,48.380567,0.987401,-9.195947,0,1,45.002910,0.356270,40.004365,0.356270,Mid-Atlantic,2026,0.0,0.00000,0.00000,42,4207,2,4724.218851,0.356270,0.596884,-4.998545e+00,6.913747,18.732953,-1,37.465906,52.143463,3.567336,72.645,315,45.243244,59.145728,2.425

In [120]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [121]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.000000,0.000000,0.000000,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.520,1,39.568068,53.708686,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.030,2,30.486193,44.646098,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.195947,1,0,46.957206,0.161048,46.963324,0.161048,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.161048,0.401308,0.006119,-3.847468,-5.527053,1,-11.054107,49.499491,3.490063,44.405,3,42.613911,56.317828,0.950,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",62981.54,1590746.93,1653728.47,3.808457,96.191543,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.504346,0.000000,0.000000,0.000000,-36.446237,-46.191543,-1,-92.383086,30.585681,3.512893,0.000,4,23.655239,37.437476,0.000,Safe R,"<b style=""color:#366bbf;"">Lee McInnis (D)</b> ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",22154.32,625402.87,647557.19,3.421214,96.578786,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,11.704708,0.000000,0.000000,0.000000,-56.738332,-46.578786,-1,-93.157571,20.772985,3.560753,0.000,5,13.776562,27.692205,0.000,Safe R,"<b style=""color:#366bbf;"">Amanda Pusczek (D)</..."

In [122]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.000000,0.000000,0.000000,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.520,1,39.568068,53.708686,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.030,2,30.486193,44.646098,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.195947,1,0,46.957206,0.161048,46.963324,0.161048,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.161048,0.401308,0.006119,-3.847468,-5.527053,1,-11.054107,49.499491,3.490063,44.405,3,42.613911,56.317828,0.950,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R)

In [123]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.0,0.0,0.0,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.52,1,39.568068,53.708686,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.0,0.0,0.0,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.03,2,30.486193,44.646098,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,

In [124]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.000000,0.000000,0.000000,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.520,1,39.568068,53.708686,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.030,2,30.486193,44.646098,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.195947,1,0,46.957206,0.161048,46.963324,0.161048,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.161048,0.401308,0.006119,-3.847468,-5.527053,1,-11.054107,49.499491,3.490063,44.405,3,42.613911,56.317828,0.950,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.0

In [125]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.000000,0.000000,0.000000,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.520,1,39.568068,53.708686,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7,82.480,17.5,82.5,17.5%,82.5%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.030,2,30.486193,44.646098,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.970,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.195947,1,0,46.957206,0.161048,46.963324,0.161048,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.161048,0.401308,0.006119,-3.847468,-5.527053,1,-11.054107,49.499491,3.490063,44.405,3,42.613911,56.317828,0.950,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.0,55.595,44.4,55.6,44.4%,55.6%

In [126]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.000000,0.000000,0.000000,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.520,1,39.568068,53.708686,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7,82.480,17.5,82.5,17.5%,82.5%,6.968887
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.030,2,30.486193,44.646098,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.970,0.0,100.0,<1%,>99%,11.478945
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.195947,1,0,46.957206,0.161048,46.963324,0.161048,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.161048,0.401308,0.006119,-3.847468,-5.527053,1,-11.054107,49.499491,3.490063,44.405,3,42.613911,56.317828,0.950,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.0,55.595,44.4,55.6,44.4%,55.6%,13.463410

In [127]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2364393.34,3310044.97,5674438.31,41.667443,58.332557,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.195947,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1736.175794,0.0,0.0,0.0,-3.714658,-8.332557,-1,-16.665114,46.637881,3.601559,17.52,1,39.568068,53.708686,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7,82.48,17.5,82.5,17.5%,82.5%,6.968887,D+7.0
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.195947,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.0,0.0,0.0,-25.678335,-29.987744,0,-59.975488,37.567237,3.632232,0.03,2,30.486193,44.646098,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.97,0.0,100.0,<1%,>99%,11.478945,D+11.5

In [128]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
413    5507
414    5508
415    5401
416    5402
417    5600
Name: geoid, Length: 418, dtype: int64

In [129]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['y_pred'] = np.full(dem_uclen, 100)
dem_uncont['swing_24_to_26'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_24_to_26_swing'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                      x['dem_inc_any'], x['rep_inc_any']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Mike Thompson/Eric J..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Doris Matsui/Mai Van..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Scott Weiner/Connie ..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Lateefah Simon* (D)<..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,True,False,CA,14,6,614,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Aisha Wahab/Melissa ..."

In [130]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['y_pred'] = np.full(rep_uclen, 0)
rep_uncont['swing_24_to_26'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_24_to_26_swing'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                       x['dem_inc_any'], x['rep_inc_any']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0,NaN,NaN,0%,100%,R+100,,"<b style=""color:#366bbf;"">Not Contested (D)</b..."

In [131]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'geoid', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 16)

In [132]:
tab_data = data[['cd', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Bill Hill', 'Kevin Kiley'] else x)
tab_data = tab_data.rename({
    'cd': 'District',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,District,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,AK-AL,Bill Hill (Ind),Nick Begich,Likely R,"<p style=""color:blue;"">17.5%</p>","<p style=""color:red;"">82.5%</p>",R+6.7,D+7.0,0.065
1,AL-01,Clyde Jones Jr.,Jerry Carl,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+24.9,D+11.5,0.000
2,AL-02,Shomari Figures,Rhett Marques,Tossup,"<p style=""color:blue;"">44.4%</p>","<p style=""color:red;"">55.6%</p>",R+1.0,D+13.5,0.950
3,AL-03,Lee McInnis,Mike Rogers,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+38.8,D+8.2,0.000
4,AL-04,Amanda Pusczek,Robert Aderholt,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+58.5,D+8.5,0.000

In [133]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

4.8968626463881915

In [134]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

                 vars           x
0     means_seats_tot  244.039800
1  chamber_win_chance   84.700000
0             sv_bias    4.896863

In [135]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [136]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 435 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Win Probability  Seat Share
0    Democrats             84.7    244.0398
1  Republicans             15.3    190.9602

In [137]:
## Alert when there's a rating change
rating_ts = output_ts[output_ts['type'] == 'chance']
rating_ts['rating'] = rating_ts['y'].map(get_rating)
rating_ts['date'] = pd.to_datetime(rating_ts['date'])
rating_ts.head()

today_date = rating_ts['date'].max()
yesterday = rating_ts[rating_ts['date'] != today_date]['date'].max()

today_ratings = rating_ts[rating_ts['date'] == today_date]
yester_ratings = rating_ts[rating_ts['date'] == yesterday]
compare_df = pd.merge(left=today_ratings, right=yester_ratings, on='geo', how='left', suffixes=['_t', '_y'])
compare_df.head()

,date_t,y_t,geo,type_t,rating_t,date_y,y_y,type_y,rating_y
0,2026-10-24,84.700,US House,chance,Likely D,2026-10-23,84.635,chance,Likely D
1,2026-10-24,17.520,AK-AL,chance,Likely R,2026-10-23,16.645,chance,Likely R
2,2026-10-24,0.030,AL-01,chance,Safe R,2026-10-23,0.030,chance,Safe R
3,2026-10-24,44.405,AL-02,chance,Tossup,2026-10-23,44.265,chance,Tossup
4,2026-10-24,0.000,AL-03,chance,Safe R,2026-10-23,0.000,chance,Safe R

In [138]:
## This is the cell that actually alerts when there's a rating change
if any(compare_df['rating_t'] != compare_df['rating_y']):
    changes_df = compare_df[compare_df['rating_t'] != compare_df['rating_y']][['geo', 'rating_y', 'rating_t']]
    print(changes_df)
else:
    print("No rating changes today!")

       geo       rating_y       rating_t
155  KS-02  Very Likely R       Likely R
401  WA-03       Likely D  Very Likely D

In [139]:
for i in range(changes_df.shape[0]):
    seat = changes_df.iloc[i, :]['geo']
    rating_y = changes_df.iloc[i, :]['rating_y']
    rating_t = changes_df.iloc[i, :]['rating_t']
    print(f'{seat}: {rating_y} --> {rating_t}')

KS-02: Very Likely R --> Likely R
WA-03: Likely D --> Very Likely D

In [140]:
changes_df.shape

(2, 3)

In [141]:
if any(compare_df['rating_t'] != compare_df['rating_y']):
    for i in range(changes_df.shape[0]):
        seat = changes_df.iloc[i, :]['geo']
        rating_y = changes_df.iloc[i, :]['rating_y']
        rating_t = changes_df.iloc[i, :]['rating_t']
        print(f'{seat}: {rating_y} --> {rating_t}')

KS-02: Very Likely R --> Likely R
WA-03: Likely D --> Very Likely D

In [142]:
## Mini-widget: what is the chance of Dems/Reps winning House if X congressional district is won by Dems/Reps?
def det_winner(post, cd, dem_winner=True):
    '''
    :param post: Posterior simulation matrix.
    :param cd: Congressional district.
    :param dem_winner: Whether or not we set Dems or Reps to win `cd`. True if Dem win is fixed, False if Rep win is fixed.
    '''
    winners = []
    seats = []
    post_ut = post.T
    if dem_winner:
        post_ut = post_ut[post_ut[cd] > 0]
    else:
        post_ut = post_ut[post_ut[cd] < 0]
    post_case = post_ut.T
    for i in range(post_case.shape[0]):
        sim = post_case.iloc[:, i]
        dem_seats = np.sum(sim > 0)
        if dem_seats >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
            winners.append(1)
        else: # Republicans win House in this draw
            winners.append(0)
        seats.append(dem_seats)
    dem_win_chance = np.mean(np.array(winners)) * 100
    dem_mean_seats = np.mean(np.array(seats)) + dem_uncont.shape[0]
    return dem_win_chance, dem_mean_seats

cd = 'ME-02'
dem_winner = True
det_winner(post, cd, dem_winner)

(np.float64(98.32535885167464), np.float64(256.3014354066986))

In [143]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')