In [42]:
import warnings
warnings.filterwarnings('ignore')

In [44]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [46]:
pd.set_option('display.max_columns', 100)

In [48]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [50]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        197  Republicans
1        293    Democrats
2        215  Republicans
3        194  Republicans
4        288    Democrats
...      ...          ...
19995    207  Republicans
19996    282    Democrats
19997    241    Democrats
19998    256    Democrats
19999    214  Republicans

[20000 rows x 2 columns]

In [51]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    148      1  0.005  Republicans
1    165      1  0.005  Republicans
2    172      2  0.010  Republicans
3    173      1  0.005  Republicans
4    176      3  0.015  Republicans

In [52]:
np.unique(seat_sims['seats']).shape[0]

185

In [53]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [54]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date           y       geo       type
0  2026-08-30  229.365800  US House      seats
1  2026-08-30   66.120000  US House     chance
2  2026-08-30   22.784344  US House   seats_sd
3  2026-08-30   44.972806     AK-AL     y_pred
4  2026-08-30    3.555839     AK-AL  y_pred_sd

In [55]:
chance_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="House Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser

In [56]:
seats_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 435 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 435]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser

In [57]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [58]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [59]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,19950,19951,19952,19953,19954,19955,19956,19957,19958,19959,19960,19961,19962,19963,19964,19965,19966,19967,19968,19969,19970,19971,19972,19973,19974,19975,19976,19977,19978,19979,19980,19981,19982,19983,19984,19985,19986,19987,19988,19989,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,-8.694526,0.742736,-6.148744,-12.577612,1.011845,-7.092165,2.184466,-8.250718,-0.701971,-0.855479,-6.662323,-3.384946,-4.610076,-6.879040,-1.865624,-2.179784,-4.648134,-0.640961,-1.351533,2.036723,-6.494903,-2.260801,-1.786996,1.507287,1.964162,-7.309510,-1.319694,-4.710867,-2.564443,-3.452810,-3.226507,-9.590118,-1.300110,-2.063409,-0.035383,-8.392067,-10.062292,-3.035292,-1.356632,-1.294680,-1.954735,-3.998234,-2.658220,-6.238039,-5.837869,1.959595,-3.255107,-2.110049,-5.214313,-8.254153,...,-6.227639,-2.446195,-1.919389,-5.931712,-3.879379,-5.097895,-1.842794,-6.058068,4.485667,-2.805004,-7.984111,-8.851347,-2.183418,-6.110435,-1.510849,-6.267942,1.798050,-6.660356,2.114655,-6.212317,-1.515822,-7.362739,-2.175996,-7.988995,-4.379379,-1.145005,-4.709472,-1.834270,-3.785216,-0.375874,-8.010369,0.961438,-9.827632,6.997195,-9.745144,-7.328799,-1.648507,-4.061393,-7.466623,-0.547440,-5.110805,-6.922771,-1.208196,-2.910013,0.103521,-8.028496,-1.217846,-2.985465,-7.886093,-6.126698
AL-01,-19.792812,-4.654640,-18.425250,-19.330891,-7.773127,-16.438667,-6.176948,-19.483567,-7.041161,-10.437728,-16.405052,-14.202932,-11.476664,-7.819164,-12.090374,-12.999292,-11.277499,-11.349584,-14.243683,-12.553268,-17.045294,-9.049922,-11.903249,-8.557930,-5.726992,-17.519415,-7.692589,-17.670045,-15.186188,-11.475748,-17.547066,-19.932558,-13.015025,-13.674867,-11.764611,-12.955639,-17.812570,-12.233339,-14.217466,-3.786869,-12.474921,-12.436329,-10.671805,-15.006859,-18.302589,-7.717381,-18.499350,-9.646336,-12.765581,-15.090354,...,-14.818402,-11.017175,-10.402945,-11.752615,-12.587905,-13.478192,-7.168512,-18.230403,-6.295071,-14.857202,-14.185139,-15.644337,-7.823269,-16.316115,-8.948785,-20.023966,-5.264903,-15.698687,-9.777495,-15.980367,-8.388882,-13.004647,-9.454265,-13.306512,-13.927060,-11.922287,-13.095975,-6.934072,-13.159243,-9.402486,-16.705702,-8.806669,-22.021060,-3.621103,-16.504373,-18.226782,-12.975236,-13.884583,-17.036341,-11.906336,-12.691573,-19.202726,-11.296293,-12.824963,-11.794105,-16.650855,-7.903780,-14.086664,-7.230298,-16.594003
AL-02,-8.532052,7.184132,-5.885469,-4.225760,4.819664,-3.258606,-0.909871,-2.164971,3.720948,0.919880,0.567343,0.201140,-2.565403,-0.991819,-2.188116,-0.486483,1.219458,-1.827007,2.626951,-0.207961,-5.074674,-1.356338,-0.612848,1.437937,3.897105,-6.161021,3.818402,-1.539721,-1.811335,4.912832,0.811539,-3.789345,-3.817775,3.306747,-2.864870,1.001578,-6.378191,-0.935433,-3.025568,3.102734,-0.427435,-0.690798,4.579714,-2.897024,-1.214142,7.602670,-6.250674,0.823124,-1.096698,0.069445,...,3.728640,1.277301,1.016959,1.276115,0.158793,-0.664332,-0.463864,-3.521604,1.137389,-0.278833,-2.336421,-4.176159,1.408842,-7.462523,3.059432,-6.526517,4.219978,-2.608665,2.742624,0.527130,-1.277877,3.992373,4.133394,-1.390268,-3.661981,0.868903,-2.171369,2.553468,2.968257,3.182392,-7.726970,-2.382788,-6.314210,5.381822,-0.680976,4.909047,-0.177889,-3.384993,-2.211888,3.014086,-2.202189,-5.926893,-1.858937,0.646396,4.683360,-3.163679,4.713719,-1.913670,3.529871,-3.582196
AL-03,-23.939877,-16.379919,-25.025981,-26.642602,-16.891320,-22.921799,-14.557381,-18.017301,-16.828646,-18.380258,-17.430928,-20.769420,-19.650942,-14.502539,-19.413348,-17.893801,-21.096326,-21.394208,-21.228566,-15.484341,-24.797530,-17.997019,-18.103416,-12.271327,-12.315304,-26.324719,-14.446888,-24.182851,-23.515805,-19.034961,-21.493054,-23.958241,-15.570369,-21.062864,-15.254683,-17.113775,-24.729459,-17.011330,-21.922514,-17.712361,-21.967962,-20.323541,-17.622367,-22.029997,-21.769122,-15.507825,-21.376074,-17.319230,-20.607230,-27.107188,...,-22.129712,-18.127209,-17.812692,-21.821578,-19.396671,-18.841636,-19.976959,-25.788637,-12.993737,-21.704915,-24.289730,-23.252135,-15.722630,-22.356227,-12.263889,-25.914105,-15.258227,-18.082103,-14.556542,-24.980782,-16.831154,-18.438228,-15.967753,-22.573025,-20.937935,-15.254510,-17.417976,-18.654639,-21.533566,-18.485176,-24.122745,-16.356608,-26.479718,-10.549487,-26.735200,-25.300782,-18.688839,-17.528389,-23.607298,-18.256940,-17.492461,-25.101075,-19.324731,-21.659976,-15.432751,-25.301182,-15.199267,-19.004022,-18.129025,-23.028483
AL-04,-36.018511,-24.699108,-30.221701,-34.706426,-27.247849,-33.317428,-24.099444,-31.492936,-29.903749,-26.239390,-26.377787,-30.177144,-26.031623,-30.233304,-30.374368,-32.185760,-27.422107,-30.842017,-31.496173,-28.606895,-32.894453,-27.740327,-28.129452,-24.499273,-22.829755,-36.312886,-25.323351,-34.632732,-31.828989,-26.976028,-32.524198,-36.477634,-30.815973,-25.191706,-28.932937,-29.613115,-33.240825,-27.322247,-33.424162,-20.567101,-27.792054,-33.005585,-28.875849,-31.300169,-31.787975,-23.051239,-30.309562,-24.857614,-29.060649,-36.522583,...,-30.585131,-26.917242,-26.004606,-30.279529,-27.722974,-28.430410,-30.074717,-34.797151,-22.842239,-29.930662,-34.236020,-31.719340,-26.063894,-30.668296,-26.347822,-37.372437,-25.427398,-31.539444,-28.551382,-29.868588,-28.150049,-28.733983,-24.882845,-31.367999,-32.684758,-29.775968,-28.602722,-25.573619,-27.570402,-25.831439,-33.022253,-26.268776,-37.464600,-25.300614,-32.720056,-33.428195,-29.550373,-28.177959,-33.823147,-27.194187,-29.880918,-34.191233,-30.272055,-31.749196,-24.082376,-32.587692,-27.745485,-31.689979,-27.680474,-32.137213

In [60]:
sim_corr = post_untransp.corr()

In [61]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,...,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.713942,0.479035,0.734582,0.725262,0.715896,0.733068,0.492177,0.735145,0.738137,0.734126,0.737765,0.479921,0.484016,0.483809,0.497709,0.697663,0.719228,0.719965,0.720127,0.736844,0.698115,0.501034,0.507043,0.740280,0.730192,0.566138,0.505748,0.510333,0.503667,0.480658,0.694449,0.558491,0.501958,0.495623,0.700401,0.505132,0.738363,0.731970,0.505561,0.514365,0.704258,0.481574,0.507791,0.479397,0.517812,0.548661,0.506304,0.564701,0.507599,...,0.735016,0.718135,0.542042,0.501007,0.502076,0.702385,0.741221,0.699156,0.529855,0.501887,0.701483,0.520282,0.490436,0.493571,0.488361,0.729871,0.719188,0.719948,0.738927,0.546376,0.501977,0.474083,0.717203,0.728068,0.484159,0.505834,0.734244,0.484297,0.697852,0.527309,0.504432,0.507730,0.481831,0.700888,0.534819,0.480063,0.498950,0.505881,0.565453,0.490788,0.737621,0.536583,0.568880,0.732476,0.738419,0.697348,0.722521,0.731101,0.714283,0.696653
AL-01,0.713942,1.000000,0.486125,0.740754,0.732933,0.725581,0.739466,0.499590,0.738823,0.742814,0.740922,0.743153,0.486145,0.487370,0.495588,0.503123,0.701376,0.723075,0.723665,0.721328,0.739241,0.699966,0.505880,0.510523,0.746283,0.728685,0.569848,0.518033,0.512637,0.507784,0.493398,0.697514,0.566318,0.506638,0.507087,0.705291,0.512177,0.739044,0.732479,0.509077,0.515953,0.700805,0.485442,0.510427,0.483764,0.532039,0.560897,0.513760,0.575924,0.510561,...,0.736747,0.721323,0.556134,0.508818,0.502858,0.699231,0.746130,0.703589,0.541373,0.509448,0.704120,0.525720,0.495803,0.504648,0.493474,0.735319,0.724665,0.723910,0.742167,0.553106,0.513627,0.487783,0.711949,0.729342,0.483521,0.509491,0.741117,0.487435,0.705777,0.533921,0.505381,0.511755,0.485124,0.706736,0.541201,0.487985,0.504302,0.510119,0.573946,0.496750,0.740017,0.545093,0.575393,0.737141,0.746276,0.703748,0.722652,0.742761,0.720573,0.705062
AL-02,0.479035,0.486125,1.000000,0.489834,0.485550,0.477741,0.490983,0.700674,0.487343,0.495603,0.487769,0.496212,0.670127,0.665952,0.674852,0.691392,0.638307,0.475592,0.482529,0.475664,0.493023,0.630902,0.700132,0.706972,0.498264,0.487979,0.579730,0.698080,0.699954,0.520625,0.666521,0.633754,0.569606,0.696041,0.702252,0.635993,0.700268,0.492751,0.484405,0.706376,0.708981,0.635441,0.675448,0.701731,0.669814,0.536727,0.556579,0.704704,0.578157,0.707372,...,0.493793,0.480234,0.552320,0.693958,0.697866,0.631826,0.493191,0.635482,0.543904,0.697233,0.635197,0.534225,0.682765,0.680652,0.675356,0.485325,0.471232,0.478567,0.493217,0.551167,0.691608,0.666591,0.472371,0.485301,0.667402,0.709215,0.490591,0.669832,0.633041,0.540932,0.701677,0.699304,0.678729,0.639715,0.543481,0.663827,0.695178,0.695531,0.578552,0.684090,0.487170,0.544957,0.576858,0.488329,0.493119,0.636086,0.478713,0.493533,0.479122,0.640090
AL-03,0.734582,0.740754,0.489834,1.000000,0.754895,0.739593,0.765080,0.509794,0.753493,0.761230,0.759022,0.759612,0.497601,0.498149,0.500189,0.513969,0.717173,0.737114,0.736013,0.740271,0.760619,0.720258,0.515227,0.517690,0.761935,0.750701,0.577490,0.518051,0.525880,0.523221,0.498709,0.714549,0.571281,0.512177,0.512804,0.724895,0.520748,0.757465,0.751764,0.516590,0.526715,0.719283,0.498138,0.518964,0.495024,0.540714,0.570789,0.519239,0.582003,0.524387,...,0.757161,0.740232,0.558606,0.513598,0.514849,0.715480,0.766258,0.720168,0.543652,0.516001,0.721156,0.535971,0.502880,0.512713,0.502626,0.752546,0.740152,0.738597,0.759991,0.560081,0.514164,0.493041,0.735945,0.745925,0.494162,0.517737,0.758807,0.495848,0.721007,0.543017,0.517025,0.524584,0.489119,0.721106,0.551820,0.491519,0.508639,0.521980,0.581156,0.507517,0.758688,0.555168,0.579791,0.753420,0.761315,0.720782,0.741320,0.756322,0.735514,0.721679
AL-04,0.725262,0.732933,0.485550,0.754895,1.000000,0.731128,0.745419,0.507655,0.749783,0.746225,0.750110,0.749724,0.493112,0.492495,0.500169,0.504602,0.708893,0.727395,0.728954,0.728188,0.752191,0.709019,0.509531,0.517989,0.748649,0.735992,0.569747,0.518261,0.518679,0.514874,0.492811,0.704932,0.571631,0.511717,0.508792,0.715447,0.512836,0.745089,0.735592,0.514408,0.521390,0.712370,0.492053,0.517282,0.482993,0.532661,0.565448,0.513629,0.574723,0.521486,...,0.746088,0.729305,0.550280,0.511321,0.508065,0.708791,0.755402,0.715250,0.543051,0.514386,0.713227,0.525711,0.498825,0.504883,0.497263,0.740063,0.733321,0.727791,0.749113,0.553097,0.515088,0.485412,0.725165,0.739663,0.488373,0.512637,0.750558,0.494104,0.710120,0.537079,0.507403,0.518591,0.490672,0.713353,0.547115,0.489106,0.509780,0.516378,0.571564,0.497249,0.745626,0.547480,0.574620,0.745062,0.748514,0.710680,0.727015,0.745221,0.725687,0.711924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WI-07,0.697348,0.703748,0.636086,0.720782,0.710680,0.702155,0.716431,0.656581,0.717579,0.719322,0.714468,0.724139,0.644385,0.636955,0.646604,0.662352,0.842173,0.697790,0.709856,0.699633,0.720819,0.839324,0.666096,0.675134,0.724295,0.712327,0.552073,0.670752,0.676498,0.499108,0.638908,0.840689,0.546072,0.666403,0.665797,0.843426,0.670586,0.718525,0.708057,0.669515,0.680176,0.842506,0.642957,0.668755,0.638279,0.517346,0.541330,0.675198,0.555216,0.675301,...,0.720501,0.698737,0.532229,0.663326,0.663047,0.839261,0.725054,0.842253,0.522812,0.668156,0.843672,0.509290,0.652862,0.654221,0.652399,0.713594,0.704131,0.701322,0.722526,0.538442,0.669071,0.637342,0.697414,0.713613,0.636683,0.670943,0.721327,0.642485,0.843251,0.521412,0.668040,0.673758,0.642591,0.844937,0.529791,0.640600,0.663408,0.668716,0.556423,0.654259,0.719067,0.530009,0.556582,0.716267,0.724723,1.000000,0.702121,0.721476,0.694532,0.845391
WI-08,0.722521,0.722652,0.478713,0.741320,0.727015,0.718115,0.737301,0.496654,0.743605,0.741622,0.740197,0.743384,0.486613,0.490205,0.488558,0.497199,0.706433,0.723022,0.718538,0.719027,0.741123,0.703391,0.509111,0.506652,0.745168,0.738257,0.569386,0.509720,0.514575,0.510462,0.492543,0.698650,0.564102,0.507597,0.505057,0.705054,0.508334,0.738289,0.731682,0.512073,0.520815,0.705687,0.487154,0.507892,0.484348,0.530069,0.554830,0.511921,0.566247,0.515843,...,0.740677,0.721369,0.552462,0.505834,0.502572,0.702431,0.743997,0.704665,0.539993,0.503844,0.704661,0.525463,0.499297,0.503744,0.492030,0.733468,0.721905,0.723564,0.742134,0.554264,0.511398,0.483645,0.714830,0.730586,0.476424,0.508433,0.742410,0.487691,0.704210,0.531008,0.509340,0.517872,0.489132,0.707521,0.539012,0.484887,0.506813,0.513143,0.570629,0.499353,0.747512,0.557491,0.579650,0.742399,0.746001,0.702121,1.000000,0.735228,0.718455,0.701555
WV-01,0.731101,0.742761,0.493533,0.756322,0.745221,0.736024,0.758380,0.512532,0.750837,0.755373,0.753615,0.756792,0.501161,0.505553,0.504725,0.513054,0.719179,0.730021,0.739265,0.738041,0.754651,0.717780,0.523232,0.524851,0.761642,0.745813,0.580975,0.523665,0.522965,0.514705,0.501545,0.715532,0.573051,0.516976,0.517861,0.722110,0.524299,0.754742,0.745908,0.523255,0.531802,0.721916,0.500270,0.520210,0.493570,0.538442,0.568066,0.522248,0.581107,0.528587,...,0.757305,0.737435,0.562798,0.512732,0.515803,0.718062,0.761160,0.721722,0.548455,0.519841,0.721214,0.533250,0.510445,0.514213,0.502465,0.750935,0.736254,0.737790,0.758723,0.558197,0.521179,0.493727,0.728479,0.748528,0.494341,0.524495,0.758005,0.498828,0.719519,0.543354,0.519859,0.524708,0.494817,0.723019,0.551379,0.498372,0.511894,0.522941,0.581463,0.508148,0.757643,0.559966,0.578676,0.753196,0.760433,0.721476,0.735228,1.000000,0.743930,0.723503
WV-02,0.714283,0.720573,0.479122,0.735514,0.725687,0.715318,0.730499,0.495070,0.737119,0.742262,0.733347,0.743087,0.485022,0.479911,0.487057,0.501703,0.694146,0.719391,0.719486,0.716438,0.737259,0.697492,0.502610,0.510594,0.740355,0.723963,0.565344,0.507160,0.509547,0.508444,0.486079,0.692452,0.566062,0.500242,0.501956,0.698348,0.504822,0.740627,0.728148,0.502009,0.510707,0.697090,0.484882,0.507784,0.479608,0.528245,0.554275,0.508406,0.571611,0.510704,...,0.734970,0.723028,0.547879,0.501370,0.503394,0.698801,0.742405,0.696051,0.538593,0.505014,0.699236,0.524003,0.490818,0.498566,0.491936,0.726704,0.717210,0.718240,0.739454,0.549440,0.507662,0.480773,0.712137,0.726636,0.482426,0.506528,0.740679,0.486513,0.699523,0.530205,0.504503,0.510613,0.479890,0.699012,0.540796,0.486071,0.498799,0.510185,0.573408,0.496887,0.736597,0.546599,0.567680,0.731913,0.739883,0.694532,0.718455,0.743930,1.000000,0.699104
WY-AL,0.696653,0.705062,0.640090,0.721679,0.711924,0.702829,0.715601,0.656630,0.717898,0.722204,0.715775,0.727267,0.646003,0.638253,0.643124,0.661459,0.842451,0.698842,0.708471,0.701236,0.719878,0.839049,0.668851,0.672396,0.724021,0.710700,0.551838,0.673231,0.677621,0.495980,0.640077,0.838903,0.548004,0.664620,0.665475,0.843814,0.668388,0.718045,0.709563,0.666980,0.679310,0.843239,0.644183,0.670550,0.637327,0.515938,0.541989,0.672315,0.554888,0.678349,...,0.723053,0.700314,0.536462,0.663938,0.660766,0.838138,0.727999,0.846947,0.522587,0.668618,0.842685,0.505956,0.652444,0.657601,0.649906,0.711538,0.702427,0.704289,0.721908,0.535816,0.667033,0.636066,0.697779,0.716708,0.640181,0.671180,0.723519,0.643979,0.840428,0.526498,0.668113,0.676533,0.644710,0.844505,0.528010,0.641711,0.661242,0.667745,0.557191,0.649089,0.719554,0.531312,0.557603,0.714811,0.723156,0.845391,0.701555,0.723503,0.699104,1.000000

In [62]:
post.shape

(418, 20000)

In [63]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [64]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:31<00:00, 630.07it/s]

array(['NC-11', 'SC-01', 'MI-07', ..., 'FL-13', 'AZ-02', 'MI-04'],
      shape=(20000,), dtype='<U32')

In [65]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.000000,0.000000,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.000000,0.000000,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.271146,1,0,46.957206,0.230023,46.963324,0.230023,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.230023,0.479608,0.006119,-3.772269,-7.354225,1,-14.708451,49.408207,3.444086,43.120,3,42.615613,56.164594
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.000000,0.000000,-36.371037,-46.255299,-1,-92.510598,30.586324,3.459716,0.000,4,23.862905,37.455252
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,624541.87,640003.87,2.415923,97.584077,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.836683,0.000000,0.000000,0.000000,-56.663133,-47.584077,-1,-95.168154,20.764705,3.504321,0.000,5,13.934491,27.663903

In [66]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.000000,0.000000,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.000000,0.000000,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.271146,1,0,46.957206,0.230023,46.963324,0.230023,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.230023,0.479608,0.006119,-3.772269,-7.354225,1,-14.708451,49.408207,3.444086,43.120,3,42.615613,56.164594,1.250
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.000000,0.000000,-36.371037,-46.255299,-1,-92.510598,30.586324,3.459716,0.000,4,23.862905,37.455252,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,624541.87,640003.87,2.415923,97.584077,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.836683,0.000000,0.000000,0.000000,-56.663133,-47.584077,-1,-95.168154,20.764705,3.504321,0.000,5,13.934491,27.663903,0.000

In [67]:
data.sort_values('tipping_point_prob', ascending=False).head(10)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
193,193,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",2920366.45,1718514.96,4638881.41,62.954109,37.045891,Michigan,MI-10,76.551128,2.316124,5.150984,0.123322,13.269372,29.340000,-2.765891,-2.592362,-2.635744,99.999226,46.657584,0.987401,-9.271146,0,0,45.000000,0.089432,45.000000,0.089432,East North Central,2026,0.0,0.00000,0.00000,26,2610,2,3963.219815,0.089432,0.299052,-1.460326e-07,3.999658,12.954109,0,25.908218,52.037862,3.595858,71.570,194,44.934479,59.129192,3.065
98,98,FL-22,Pia Dandiya,Casey Askar,False,False,FL,22,"DANDIYA, PIA","ASKAR, CASEY",3095902.57,322072.40,3417974.97,90.577099,9.422901,Florida,FL-22,53.931205,26.984941,3.703933,0.199203,13.186062,27.190634,-0.817400,-4.551960,-3.618320,91.180168,44.697986,0.987401,-9.271146,0,0,46.286766,0.243991,44.430149,0.243991,South Atlantic,2026,0.0,0.00000,0.00000,12,1222,6,8204.210851,0.243991,0.493954,-1.856617e+00,2.034506,40.577099,0,81.154198,52.321302,3.599364,74.315,99,45.210686,59.468634,2.990
183,183,ME-02,Matt Dunlap,Paul LePage,False,False,ME,2,"DUNLAP, MATT","LEPAGE, PAUL",2472092.35,1645926.41,4118018.76,60.031109,39.968891,Maine,ME-02,94.623805,1.542589,0.598455,0.552005,0.848532,26.920000,-5.410176,-3.867301,-4.253020,26.830060,45.382645,0.987401,-9.271146,0,0,50.069480,1.856538,46.458349,1.856538,New England,2026,0.0,0.25284,-0.25284,23,2302,3,3603.734105,1.856538,1.362548,-3.611131e+00,0.765106,10.031109,0,20.062219,51.841762,3.598333,69.805,184,44.732149,58.992148,2.965
229,229,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE","BALKCOM, JENNIFER",4742228.95,92169.44,4834398.39,98.093466,1.906534,North Carolina,NC-11,88.740422,3.902084,0.797632,1.120840,3.305854,24.807640,-7.843347,-4.057125,-5.003681,49.294326,45.192821,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.0,0.00000,0.00000,37,3711,3,9622.328108,0.000000,0.000000,0.000000e+00,-0.736215,48.093466,0,96.186932,51.584962,3.613206,66.995,230,44.511526,58.738650,2.850
386,386,VA-01,Shannon Taylor,Rob Wittman,False,True,VA,1,"TAYLOR, SHANNON LEIGH","WITTMAN, ROBERT J. MR.",3265447.34,1867234.51,5132681.85,63.620685,36.379315,Virginia,VA-01,75.537803,4.124527,4.097593,0.133339,13.351012,46.900000,-5.404597,-1.752158,-2.665268,73.780628,47.497788,0.987401,-9.271146,0,1,49.033047,0.569788,46.241737,0.569788,South Atlantic,2026,0.0,0.00000,0.00000,51,5101,2,4047.591531,0.569788,0.754843,-2.791310e+00,3.940610,13.620685,-1,27.241370,51.859145,3.424967,70.830,387,45.161666,58.566845,2.690
273,273,NY-17,Cait Conley,Mike Lawler,False,True,NY,17,"CONLEY, CAIT","LAWLER, MICHAEL VINCENT",8464600.26,3782709.64,12247309.90,69.113955,30.886045,New York,NY-17,70.961924,14.978446,4.840493,0.059866,7.686273,48.490000,2.820018,1.029915,1.477441,87.206472,50.279862,0.987401,-9.271146,0,1,47.754428,0.984578,46.258603,0.984578,Mid-Atlantic,2026,0.0,0.00000,0.00000,36,3617,0,4776.738784,0.984578,0.992259,-1.495825e+00,12.226029,19.113955,-1,38.227910,52.499644,3.495598,76.250,274,45.711055,59.377132,2.670
190,190,MI-07,William Lawrence,Tom Barrett,False,True,MI,7,"LAWRENCE, WILLIAM","BARRETT, THOMAS MORE",3382652.32,4300590.57,7683242.89,44.026362,55.973638,Michigan,MI-07,85.239895,4.803904,1.944855,0.170025,5.279273,36.270000,-2.003691,0.098125,-0.427329,68.756305,49.348071,0.987401,-9.271146,0,1,48.971702,0.108490,46.971702,0.108490,East North Central,2026,0.0,0.00000,0.00000,26,2607,2,1938.320542,0.108490,0.329377,-2.000000e+00,8.416489,-5.973638,-1,-11.947276,52.121982,3.502476,73.155,191,45.259609,59.046841,2.650
289,289,OH-07,Brian Poindexter,Max Miller,False,True,OH,7,"POINDEXTER, BRIAN","MILLER, MAX",2703344.16,992252.30,3695596.46,73.150415,26.849585,Ohio,OH-07,89.432935,3.348946,2.187434,0.068208,3.218146,26.556779,-7.118675,-4.823517,-5.397307,83.893826,44.426429,0.987401,-9.271146,0,1,47.301979,0.135309,39.605340,0.135309,East North Central,2026,0.0,1.00000,-1.00000,39,3907,2,5350.983265,0.135309,0.367844,-7.696639e+00,-1.523467,23.150415,-1,46.300831,52.129574,3.547391,72.545,290,45.119842,59.009554,2.555
314,314,PA-07,Bob Brooks,Ryan Mackenzie,False,True,PA,7,"BROOKS, BOB","MACKENZIE, RYAN EDWARD",3916290.29,1840430.27,5756720.56,68.029883,31.970117,Pennsylvania,PA-07,75.458946,15.481046,2.435986,0.030199,4.952274,31.050000,-1.956264,-0.869379,-1.141100,81.633883,48.380567,0.987401,-9.271146,0,1,45.002910,0.411829,40.004365,0.411829,Mid-Atlantic,2026,0.0,0.00000,0.00000,42,4207,2,4628.065048,0.411829,0.641739,-4.998545e+00,6.988946,18.029883,-1,36.059767,52.102126,3.508325,72.655,315,45.140321,59.011908,2.540
123,123,IA-03,Sarah Trone Garriott,Zach Nunn,False,True,IA,3,"TRONE GARRIOTT, SARAH","NUNN, ZACH",6857610.23,1334009.44,8191619.67,83.714949,16.285051,Iowa,IA-03,86.341081,5.022950,2.732262,0.063009,3.929259,35.410000,-2.445778,-1.482072,-1.722998,77.628515,47.767874,0.987401,-9.271146,0,1,42.000000,0.000603,48.000000,0.000603,West North Central,2026,0.0,0.00000,0.00000,19,1903,2,7008.192688,0.000603,0.024554,6.000000e+00,5.825150,33.714949,-1,67.429898,52.443296,3.498607,75.815,124,45.553285,59.403824,2.495

In [68]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [69]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.000000,0.000000,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.000000,0.000000,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.271146,1,0,46.957206,0.230023,46.963324,0.230023,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.230023,0.479608,0.006119,-3.772269,-7.354225,1,-14.708451,49.408207,3.444086,43.120,3,42.615613,56.164594,1.250,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.000000,0.000000,-36.371037,-46.255299,-1,-92.510598,30.586324,3.459716,0.000,4,23.862905,37.455252,0.000,Safe R,"<b style=""color:#366bbf;"">Lee McInnis (D)</b> ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,624541.87,640003.87,2.415923,97.584077,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.836683,0.000000,0.000000,0.000000,-56.663133,-47.584077,-1,-95.168154,20.764705,3.504321,0.000,5,13.934491,27.663903,0.000,Safe R,"<b style=""color:#366bbf;"">Amanda Pusczek (D)</..."

In [70]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.000000,0.000000,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.000000,0.000000,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.271146,1,0,46.957206,0.230023,46.963324,0.230023,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.230023,0.479608,0.006119,-3.772269,-7.354225,1,-14.708451,49.408207,3.444086,43.120,3,42.615613,56.164594,1.250,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R)

In [71]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.0,0.0,0.0,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.0,0.0,0.0,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,

In [72]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.000000,0.000000,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.8
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.000000,0.000000,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.271146,1,0,46.957206,0.230023,46.963324,0.230023,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.230023,0.479608,0.006119,-3.772269,-7.354225,1,-14.708451,49.408207,3.444086,43.120,3,42.615613,56.164594,1.250,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.2

In [73]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.000000,0.000000,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.8,83.195,16.8,83.2,16.8%,83.2%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.000000,0.000000,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.985,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.271146,1,0,46.957206,0.230023,46.963324,0.230023,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.230023,0.479608,0.006119,-3.772269,-7.354225,1,-14.708451,49.408207,3.444086,43.120,3,42.615613,56.164594,1.250,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.2,56.880,43.1,56.9,43.1%,56.9%

In [74]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.000000,0.000000,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.8,83.195,16.8,83.2,16.8%,83.2%,6.892698
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.000000,0.000000,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.985,0.0,100.0,<1%,>99%,11.404983
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.271146,1,0,46.957206,0.230023,46.963324,0.230023,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.230023,0.479608,0.006119,-3.772269,-7.354225,1,-14.708451,49.408207,3.444086,43.120,3,42.615613,56.164594,1.250,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.2,56.880,43.1,56.9,43.1%,56.9%,13.280842

In [75]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.271146,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.0,0.0,0.0,-3.639459,-10.499110,-1,-20.998221,46.599786,3.552094,16.805,1,39.596011,53.557034,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.8,83.195,16.8,83.2,16.8%,83.2%,6.892698,D+6.9
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.271146,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.0,0.0,0.0,-25.603136,-30.821117,0,-61.642234,37.530256,3.556309,0.015,2,30.623327,44.528073,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.985,0.0,100.0,<1%,>99%,11.404983,D+11.4

In [76]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
413    5507
414    5508
415    5401
416    5402
417    5600
Name: geoid, Length: 418, dtype: int64

In [77]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['y_pred'] = np.full(dem_uclen, 100)
dem_uncont['swing_24_to_26'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_24_to_26_swing'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                      x['dem_inc_any'], x['rep_inc_any']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Mike Thompson/Eric J..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Doris Matsui/Mai Van..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Scott Weiner/Connie ..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Lateefah Simon* (D)<..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,True,False,CA,14,6,614,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Aisha Wahab/Melissa ..."

In [78]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['y_pred'] = np.full(rep_uclen, 0)
rep_uncont['swing_24_to_26'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_24_to_26_swing'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                       x['dem_inc_any'], x['rep_inc_any']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0,NaN,NaN,0%,100%,R+100,,"<b style=""color:#366bbf;"">Not Contested (D)</b..."

In [79]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'geoid', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 16)

In [80]:
tab_data = data[['cd', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Bill Hill', 'Kevin Kiley'] else x)
tab_data = tab_data.rename({
    'cd': 'District',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,District,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,AK-AL,Bill Hill (Ind),Nick Begich,Likely R,"<p style=""color:blue;"">16.8%</p>","<p style=""color:red;"">83.2%</p>",R+6.8,D+6.9,0.065
1,AL-01,Clyde Jones Jr.,Jerry Carl,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+24.9,D+11.4,0.000
2,AL-02,Shomari Figures,Rhett Marques,Tossup,"<p style=""color:blue;"">43.1%</p>","<p style=""color:red;"">56.9%</p>",R+1.2,D+13.3,1.250
3,AL-03,Lee McInnis,Mike Rogers,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+38.8,D+8.2,0.000
4,AL-04,Amanda Pusczek,Robert Aderholt,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+58.5,D+8.5,0.000

In [81]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

5.195422142156401

In [82]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

   Unnamed: 0                vars           x
0         0.0     means_seats_tot  242.446750
1         1.0  chamber_win_chance   84.075000
0         NaN             sv_bias    5.195422

In [83]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [84]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 435 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Unnamed: 0_x  Win Probability  Unnamed: 0_y  Seat Share
0    Democrats           1.0           84.075           0.0   242.44675
1  Republicans          99.0           15.925         435.0   192.55325

In [85]:
## Alert when there's a rating change
rating_ts = output_ts[output_ts['type'] == 'chance']
rating_ts['rating'] = rating_ts['y'].map(get_rating)
rating_ts['date'] = pd.to_datetime(rating_ts['date'])
rating_ts.head()

today_date = rating_ts['date'].max()
yesterday = rating_ts[rating_ts['date'] != today_date]['date'].max()

today_ratings = rating_ts[rating_ts['date'] == today_date]
yester_ratings = rating_ts[rating_ts['date'] == yesterday]
compare_df = pd.merge(left=today_ratings, right=yester_ratings, on='geo', how='left', suffixes=['_t', '_y'])
compare_df.head()

,date_t,y_t,geo,type_t,rating_t,date_y,y_y,type_y,rating_y
0,2026-10-20,84.075,US House,chance,Likely D,2026-10-19,83.840,chance,Likely D
1,2026-10-20,16.805,AK-AL,chance,Likely R,2026-10-19,16.880,chance,Likely R
2,2026-10-20,0.015,AL-01,chance,Safe R,2026-10-19,0.015,chance,Safe R
3,2026-10-20,43.120,AL-02,chance,Tossup,2026-10-19,43.185,chance,Tossup
4,2026-10-20,0.000,AL-03,chance,Safe R,2026-10-19,0.000,chance,Safe R

In [86]:
## This is the cell that actually alerts when there's a rating change
if any(compare_df['rating_t'] != compare_df['rating_y']):
    changes_df = compare_df[compare_df['rating_t'] != compare_df['rating_y']][['geo', 'rating_y', 'rating_t']]
    print(changes_df)
else:
    print("No rating changes today!")

       geo  rating_y       rating_t
372  TX-28  Likely D  Very Likely D

In [87]:
for i in range(changes_df.shape[0]):
    seat = changes_df.iloc[i, :]['geo']
    rating_y = changes_df.iloc[i, :]['rating_y']
    rating_t = changes_df.iloc[i, :]['rating_t']
    print(f'{seat}: {rating_y} --> {rating_t}')

TX-28: Likely D --> Very Likely D

In [88]:
changes_df.shape

(1, 3)

In [89]:
## Mini-widget: what is the chance of Dems/Reps winning House if X congressional district is won by Dems/Reps?
def det_winner(post, cd, dem_winner=True):
    '''
    :param post: Posterior simulation matrix.
    :param cd: Congressional district.
    :param dem_winner: Whether or not we set Dems or Reps to win `cd`. True if Dem win is fixed, False if Rep win is fixed.
    '''
    winners = []
    seats = []
    post_ut = post.T
    if dem_winner:
        post_ut = post_ut[post_ut[cd] > 0]
    else:
        post_ut = post_ut[post_ut[cd] < 0]
    post_case = post_ut.T
    for i in range(post_case.shape[0]):
        sim = post_case.iloc[:, i]
        dem_seats = np.sum(sim > 0)
        if dem_seats >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
            winners.append(1)
        else: # Republicans win House in this draw
            winners.append(0)
        seats.append(dem_seats)
    dem_win_chance = np.mean(np.array(winners)) * 100
    dem_mean_seats = np.mean(np.array(seats)) + dem_uncont.shape[0]
    return dem_win_chance, dem_mean_seats

cd = 'TX-23'
dem_winner = True
det_winner(post, cd, dem_winner)

(np.float64(99.76076555023924), np.float64(260.07416267942585))

In [90]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')