In [33]:
import warnings
warnings.filterwarnings('ignore')

In [35]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [37]:
pd.set_option('display.max_columns', 100)

In [39]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [41]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        206  Republicans
1        224    Democrats
2        233    Democrats
3        216  Republicans
4        200  Republicans
...      ...          ...
19995    229    Democrats
19996    228    Democrats
19997    220    Democrats
19998    220    Democrats
19999    223    Democrats

[20000 rows x 2 columns]

In [43]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    110      1  0.005  Republicans
1    146      1  0.005  Republicans
2    149      1  0.005  Republicans
3    156      1  0.005  Republicans
4    157      1  0.005  Republicans

In [45]:
np.unique(seat_sims['seats']).shape[0]

191

In [47]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner', 
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [49]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date           y       geo       type
0  2026-08-30  229.365800  US House      seats
1  2026-08-30   66.120000  US House     chance
2  2026-08-30   22.784344  US House   seats_sd
3  2026-08-30   44.972806     AK-AL     y_pred
4  2026-08-30    3.555839     AK-AL  y_pred_sd

In [50]:
chance_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white')
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="House Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser

In [51]:
seats_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 435 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white')
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 435]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser

In [52]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [53]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [54]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,19950,19951,19952,19953,19954,19955,19956,19957,19958,19959,19960,19961,19962,19963,19964,19965,19966,19967,19968,19969,19970,19971,19972,19973,19974,19975,19976,19977,19978,19979,19980,19981,19982,19983,19984,19985,19986,19987,19988,19989,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,-4.265479,-5.273206,-3.163926,-8.059741,-10.465307,1.586323,-1.638952,-3.971619,-6.903973,-4.772783,-5.215459,-6.236369,-5.002804,-4.035669,-3.514433,-7.734364,-3.539791,-5.678821,-4.530348,-6.382573,-5.085143,-2.565881,-5.832807,-7.085042,-5.341548,-2.910247,-4.939697,-3.092010,-9.759606,-4.644176,-7.437541,-6.510615,-5.130396,-10.087077,-5.410862,-8.086002,-2.640969,-12.541473,2.222491,-11.505824,5.974008,3.381912,2.679288,-7.294651,-3.741840,-3.832076,-2.847376,-3.706431,-5.697293,-1.465081,...,-4.915147,-8.529490,-0.418914,-11.226455,-0.276909,-5.643989,-4.480255,-6.307038,-2.712089,-5.490004,-4.284803,-0.708131,-8.157911,-0.169364,-7.120945,-5.898326,-3.105005,-2.341602,-3.978254,-11.002489,0.583623,-0.544818,-9.008212,-4.961742,-4.667738,-10.794978,-8.272185,-3.199628,-7.580397,-1.618121,-7.590814,0.078249,-7.080597,-1.167869,-0.252977,-8.016264,-1.575995,-6.575924,-3.187121,-7.090106,-7.917125,-6.143197,-14.370173,-5.307903,-1.489203,-3.375803,-3.858301,-4.957950,-4.418815,-6.740838
AL-01,-16.275203,-15.678736,-13.910225,-15.459013,-17.432595,-11.744095,-15.952259,-14.374908,-12.350605,-13.693938,-13.199091,-11.270486,-21.230981,-11.001675,-15.844351,-11.854369,-12.123577,-10.090737,-16.358497,-12.890696,-13.328598,-12.047039,-13.930125,-14.847275,-12.616931,-14.637650,-13.010208,-10.263994,-13.917799,-13.414823,-15.069574,-12.137955,-16.924994,-20.302141,-9.402187,-17.519655,-12.464233,-24.562482,-4.435106,-23.026413,-4.747222,-4.993187,-9.900149,-15.946689,-14.751102,-15.714760,-11.010770,-11.369348,-11.855987,-12.185261,...,-15.934569,-16.401401,-7.844567,-22.486426,-8.213074,-15.934251,-13.099893,-13.928819,-12.592923,-9.395110,-14.190255,-10.910484,-17.872358,-11.754237,-17.570041,-12.484015,-11.296767,-10.079549,-16.631155,-18.906251,-9.325669,-10.686375,-20.443642,-15.042156,-13.626003,-18.331266,-16.139624,-13.218427,-13.538714,-8.777028,-18.240372,-8.221057,-16.304473,-8.619972,-7.170821,-17.231646,-10.511041,-15.688934,-10.613434,-12.164344,-17.971547,-16.655624,-22.035362,-17.671715,-12.566344,-14.776536,-17.102939,-15.412964,-12.722008,-15.918544
AL-02,-6.054674,0.454645,-3.937702,-1.758328,-2.621841,-3.128208,0.968382,-5.954942,-1.712837,-3.880236,1.375318,-8.931912,1.317109,-4.596847,4.696020,-8.920737,0.857873,-2.998700,-4.173949,-3.648629,-0.103759,-7.121644,-5.643409,-0.327939,-4.847783,0.694497,-0.052257,-5.929769,2.382891,-4.467269,-2.275553,-2.659744,-7.438248,-6.693107,2.980922,-8.539686,3.174098,-6.887503,-0.779266,-6.488015,0.514424,-0.104160,-1.962544,-0.960257,3.745824,-4.481871,2.032700,-1.891137,-4.694597,-0.101203,...,-1.161366,-2.473595,-3.346237,-3.562114,1.016679,-6.337872,-3.184205,0.487279,-6.442590,2.323580,-3.333535,-1.439328,-4.596651,-1.364568,-3.067620,-0.145954,-0.489158,1.210682,-0.606225,-2.396928,7.146088,1.202817,-6.592592,-2.740348,0.012963,-5.153705,-0.866417,1.109138,-2.335412,-1.425231,-2.111386,-2.213492,-0.434808,0.454192,2.476632,-2.360217,-0.501954,1.161066,-5.676143,-1.171647,-6.125465,-8.244549,-7.806588,-2.542145,-3.371582,1.686599,-4.660747,-4.580007,-2.157248,-5.033263
AL-03,-21.029291,-20.360177,-19.723154,-22.141159,-28.801301,-15.823677,-18.134040,-21.600309,-23.180794,-21.295600,-20.574379,-18.551699,-22.434731,-21.553417,-22.305512,-18.460600,-22.856760,-19.765542,-20.612937,-20.679117,-22.950547,-19.894574,-21.034574,-23.400119,-23.767180,-16.215477,-21.452169,-19.127534,-23.006366,-19.495673,-22.976993,-23.141866,-21.532690,-25.496775,-20.459399,-22.809187,-19.479618,-26.175922,-11.758183,-27.288976,-12.328566,-10.538736,-18.126451,-24.065817,-18.923278,-21.576883,-18.721695,-17.921310,-19.619798,-17.082635,...,-15.759042,-24.336965,-16.060223,-28.228485,-14.542744,-23.320866,-17.719688,-22.823908,-22.786577,-20.245625,-23.743285,-16.915148,-22.145115,-17.414750,-22.520389,-21.543954,-17.636580,-19.529393,-22.240699,-26.877661,-16.337041,-16.302695,-25.300483,-21.153375,-19.477423,-25.737890,-23.618527,-14.142874,-25.041102,-16.922501,-25.318226,-14.053188,-20.749940,-14.308610,-13.433800,-22.775530,-16.015441,-20.930586,-18.444984,-22.920508,-24.452333,-23.962702,-28.142683,-25.141080,-16.420155,-22.596096,-20.013200,-21.092364,-23.859066,-21.150472
AL-04,-30.901917,-33.326485,-25.397848,-31.784879,-37.739517,-26.397510,-27.759023,-29.162961,-32.235546,-30.588855,-34.394196,-29.181236,-30.722285,-27.312640,-32.060962,-32.107538,-29.235793,-26.636870,-30.727092,-30.259102,-27.927971,-31.813817,-31.148598,-30.853899,-32.351823,-28.661052,-29.779038,-30.853130,-33.403275,-27.602815,-29.631849,-33.571358,-31.526061,-35.183681,-31.220519,-32.392699,-29.704727,-38.855394,-25.092366,-36.149603,-22.647788,-23.790073,-28.093851,-33.120267,-29.041808,-29.714550,-25.243607,-29.456098,-33.622600,-25.137737,...,-29.768857,-31.602070,-27.507066,-38.269538,-22.971198,-32.495454,-30.873854,-29.876149,-33.389198,-30.492703,-29.863442,-28.818955,-33.452513,-25.486185,-33.364028,-33.476876,-32.181608,-26.223151,-32.534326,-35.700304,-26.530544,-26.880750,-33.054711,-31.410155,-27.893914,-32.712770,-31.735234,-27.449136,-33.053116,-25.344619,-32.177499,-23.104171,-31.637882,-28.554181,-22.412333,-34.139565,-25.870320,-28.690903,-28.164114,-29.926242,-35.941426,-38.516564,-40.604493,-30.825101,-27.467084,-32.281049,-32.500877,-31.982222,-27.568799,-30.313208

In [55]:
sim_corr = post_untransp.corr()

In [56]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,...,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.725826,0.502850,0.747801,0.739860,0.728433,0.742793,0.508955,0.745396,0.752107,0.745658,0.745245,0.509107,0.511936,0.512309,0.522642,0.711025,0.729126,0.730282,0.727297,0.752501,0.714092,0.524583,0.533013,0.756319,0.741110,0.593840,0.522042,0.526897,0.528226,0.503357,0.710224,0.586912,0.519816,0.519630,0.714201,0.521053,0.751492,0.743913,0.527626,0.526908,0.712866,0.501729,0.526849,0.501790,0.550243,0.572159,0.525854,0.585146,0.526835,...,0.748931,0.731360,0.564848,0.517709,0.530434,0.712594,0.752397,0.708010,0.555538,0.528788,0.710468,0.548147,0.514992,0.502131,0.511078,0.742048,0.726728,0.731456,0.754014,0.566936,0.525853,0.502473,0.728477,0.745180,0.501563,0.530153,0.747702,0.504353,0.711137,0.546677,0.530104,0.526197,0.505442,0.710176,0.559053,0.502674,0.524170,0.518390,0.592923,0.514490,0.745687,0.568325,0.588452,0.744405,0.749891,0.710312,0.727950,0.742815,0.729257,0.712121
AL-01,0.725826,1.000000,0.510856,0.754601,0.746885,0.732928,0.746215,0.523248,0.746995,0.755740,0.748355,0.751534,0.516256,0.517932,0.520913,0.533521,0.717920,0.731571,0.740448,0.732680,0.753445,0.711233,0.529509,0.541921,0.757266,0.741355,0.592733,0.530103,0.535888,0.539632,0.510784,0.712371,0.593218,0.527907,0.530916,0.718793,0.526083,0.749085,0.743595,0.529938,0.529788,0.715004,0.514667,0.530301,0.506939,0.553675,0.576462,0.531086,0.591721,0.534660,...,0.747601,0.734758,0.575668,0.527881,0.537724,0.711865,0.754265,0.714972,0.558459,0.540019,0.715974,0.554079,0.517700,0.510115,0.516724,0.745144,0.727989,0.733033,0.755880,0.569779,0.531677,0.509866,0.729781,0.746354,0.510101,0.535064,0.749302,0.512989,0.713123,0.550017,0.535286,0.530012,0.518063,0.714688,0.560718,0.509448,0.526282,0.524342,0.598478,0.514476,0.743221,0.569827,0.591686,0.746661,0.756617,0.716195,0.731445,0.745347,0.730250,0.715983
AL-02,0.502850,0.510856,1.000000,0.521257,0.517589,0.497992,0.525297,0.710515,0.523096,0.520228,0.518446,0.523958,0.694682,0.686651,0.692940,0.713539,0.653136,0.501858,0.511216,0.503891,0.524808,0.650295,0.717953,0.721717,0.523594,0.514092,0.603995,0.719906,0.724561,0.554447,0.690503,0.657300,0.603657,0.713682,0.713308,0.658375,0.714891,0.523716,0.516088,0.718177,0.721702,0.654900,0.692287,0.715847,0.686094,0.573974,0.588702,0.723045,0.608085,0.720931,...,0.516792,0.511540,0.583643,0.715892,0.716317,0.649685,0.524040,0.658350,0.575535,0.719241,0.653803,0.556722,0.698207,0.696793,0.693808,0.519462,0.508240,0.505836,0.523037,0.578367,0.712954,0.688625,0.506913,0.519029,0.682903,0.722751,0.527817,0.690405,0.657985,0.561989,0.717207,0.720799,0.695092,0.653399,0.572920,0.688795,0.712897,0.713111,0.608331,0.700403,0.519736,0.575426,0.610229,0.519511,0.521519,0.658296,0.506937,0.512928,0.497500,0.652607
AL-03,0.747801,0.754601,0.521257,1.000000,0.772424,0.752597,0.774671,0.532065,0.771490,0.773923,0.767979,0.770463,0.522506,0.528123,0.526659,0.535159,0.735540,0.750710,0.757572,0.753842,0.773561,0.731588,0.537106,0.548061,0.772278,0.765411,0.607341,0.538420,0.540434,0.547358,0.518347,0.732515,0.604704,0.539476,0.536175,0.736476,0.538201,0.770283,0.766368,0.537074,0.539515,0.734027,0.524243,0.539234,0.517642,0.568940,0.586798,0.539660,0.605691,0.543851,...,0.770374,0.758046,0.581527,0.538794,0.545802,0.731128,0.776355,0.732735,0.573160,0.544908,0.736401,0.564999,0.531424,0.521691,0.523518,0.763750,0.752947,0.753138,0.780241,0.583153,0.540278,0.517279,0.750849,0.766338,0.517452,0.541878,0.773641,0.518875,0.732008,0.562976,0.540172,0.540764,0.525316,0.733039,0.572012,0.518172,0.537169,0.535638,0.607672,0.524149,0.768379,0.586002,0.603059,0.769358,0.775413,0.735806,0.753957,0.767996,0.745461,0.735503
AL-04,0.739860,0.746885,0.517589,0.772424,1.000000,0.744588,0.756825,0.528384,0.762460,0.764422,0.760537,0.758919,0.515480,0.520007,0.523969,0.532916,0.724616,0.743815,0.749753,0.741584,0.761817,0.722073,0.530370,0.543146,0.762757,0.752698,0.600674,0.531969,0.533520,0.540180,0.512322,0.721422,0.598585,0.526851,0.532828,0.728557,0.529320,0.763332,0.756473,0.530585,0.536555,0.724880,0.516482,0.532695,0.510838,0.556196,0.581964,0.530863,0.592919,0.538971,...,0.759882,0.746832,0.576078,0.531561,0.541035,0.717783,0.765774,0.723382,0.563229,0.539088,0.724100,0.557885,0.524678,0.519245,0.518016,0.755130,0.741162,0.740965,0.766883,0.569679,0.534346,0.514974,0.741625,0.759895,0.508507,0.536779,0.764773,0.510439,0.721162,0.555864,0.533458,0.533804,0.521076,0.725395,0.565594,0.513028,0.529588,0.527799,0.602243,0.519488,0.755281,0.578903,0.600443,0.760229,0.765678,0.725748,0.742702,0.759538,0.739909,0.724494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WI-07,0.710312,0.716195,0.658296,0.735806,0.725748,0.710286,0.734653,0.673461,0.736063,0.737075,0.734282,0.735016,0.669403,0.664569,0.668683,0.687269,0.855216,0.713719,0.720488,0.715637,0.736336,0.851423,0.689102,0.695916,0.737401,0.728420,0.580135,0.692045,0.692001,0.525399,0.659438,0.853352,0.579127,0.687542,0.686866,0.856555,0.684902,0.737257,0.729574,0.687091,0.694968,0.855477,0.662711,0.688221,0.662501,0.548142,0.567460,0.691355,0.580997,0.696775,...,0.735009,0.719698,0.560114,0.686716,0.691863,0.850254,0.739216,0.853218,0.550001,0.692005,0.853473,0.539563,0.674277,0.668139,0.666421,0.731692,0.716529,0.713632,0.739678,0.560375,0.692204,0.657298,0.714965,0.728510,0.659664,0.694350,0.739927,0.659092,0.852540,0.539183,0.692365,0.690191,0.670611,0.852346,0.549833,0.658908,0.687912,0.683719,0.590429,0.671612,0.730209,0.561088,0.583267,0.728988,0.739201,1.000000,0.715191,0.732795,0.709306,0.855018
WI-08,0.727950,0.731445,0.506937,0.753957,0.742702,0.732428,0.749134,0.517497,0.752222,0.754574,0.751559,0.750462,0.511150,0.520937,0.517481,0.525481,0.714028,0.731352,0.737692,0.737619,0.752847,0.714846,0.528386,0.538308,0.755513,0.743986,0.596665,0.526901,0.534780,0.533029,0.508714,0.712991,0.591554,0.524193,0.525886,0.717643,0.527019,0.751517,0.748924,0.526423,0.529452,0.714096,0.510486,0.530634,0.507266,0.554984,0.578319,0.528466,0.591984,0.534496,...,0.755896,0.734142,0.572230,0.529946,0.537067,0.713808,0.759684,0.714869,0.559587,0.533331,0.714841,0.551080,0.526917,0.515093,0.513296,0.747284,0.728388,0.736196,0.759740,0.576413,0.532669,0.508408,0.736796,0.747425,0.507370,0.532716,0.751642,0.506137,0.715603,0.553695,0.536527,0.529134,0.513894,0.715331,0.565713,0.509652,0.530382,0.521128,0.596105,0.518099,0.751767,0.582483,0.599137,0.757790,0.759474,0.715191,1.000000,0.748189,0.733176,0.716177
WV-01,0.742815,0.745347,0.512928,0.767996,0.759538,0.747892,0.763277,0.529770,0.766830,0.768749,0.767756,0.766593,0.522222,0.529051,0.524919,0.535407,0.734565,0.748250,0.752900,0.750134,0.769580,0.731714,0.535812,0.549559,0.772312,0.757621,0.601210,0.536843,0.542317,0.542684,0.515314,0.728686,0.597166,0.538028,0.533622,0.734252,0.536406,0.765344,0.760318,0.537093,0.540370,0.730108,0.518491,0.534639,0.511088,0.565604,0.584727,0.536642,0.597764,0.544464,...,0.770946,0.746483,0.580437,0.534685,0.545381,0.725750,0.774277,0.731531,0.566239,0.542259,0.730163,0.564043,0.529048,0.519330,0.519908,0.762680,0.748153,0.748871,0.772971,0.578686,0.541502,0.514842,0.748350,0.766137,0.516173,0.540958,0.773258,0.515369,0.727224,0.564833,0.540863,0.540931,0.524140,0.732300,0.567882,0.513952,0.538007,0.529821,0.606882,0.522518,0.762352,0.586884,0.602484,0.769531,0.770866,0.732795,0.748189,1.000000,0.755630,0.734096
WV-02,0.729257,0.730250,0.497500,0.745461,0.739909,0.728532,0.745734,0.509827,0.747736,0.754281,0.744225,0.745651,0.504285,0.508722,0.504395,0.517285,0.708120,0.729584,0.736709,0.732265,0.750308,0.707927,0.519255,0.528197,0.755968,0.739182,0.588461,0.517725,0.526586,0.526591,0.494484,0.704120,0.584389,0.517591,0.515105,0.708112,0.520815,0.750617,0.743751,0.516405,0.522084,0.708581,0.497700,0.521392,0.497671,0.553117,0.575018,0.519178,0.584356,0.524663,...,0.747666,0.731237,0.569519,0.521605,0.525061,0.705048,0.750234,0.705189,0.559169,0.526527,0.706981,0.555321,0.507954,0.501116,0.501261,0.746094,0.729329,0.732330,0.755501,0.567298,0.520996,0.494945,0.734060,0.746414,0.496736,0.521535,0.749237,0.500488,0.703271,0.544893,0.520484,0.523935,0.507515,0.705980,0.559995,0.498765,0.518141,0.512846,0.598071,0.507435,0.744806,0.572133,0.589952,0.747845,0.752550,0.709306,0.733176,0.755630,1.000000,0.707679
WY-AL,0.712121,0.715983,0.652607,0.735503,0.724494,0.711561,0.735363,0.665611,0.736424,0.737578,0.733020,0.735154,0.664215,0.660005,0.664703,0.682616,0.852727,0.713222,0.721428,0.717319,0.736030,0.846228,0.683207,0.689136,0.737033,0.725417,0.577140,0.685310,0.687116,0.526009,0.652450,0.846529,0.575991,0.681602,0.678928,0.854025,0.678371,0.732989,0.727850,0.680406,0.687742,0.851634,0.656484,0.683160,0.653188,0.542618,0.561048,0.685932,0.575046,0.690044,...,0.736158,0.719598,0.558196,0.679290,0.688897,0.844789,0.739789,0.855150,0.545971,0.687553,0.853322,0.534501,0.667663,0.659995,0.660941,0.730826,0.716548,0.715510,0.737778,0.552722,0.683751,0.651245,0.714015,0.729998,0.651463,0.686888,0.741319,0.654515,0.850013,0.538257,0.683973,0.684839,0.663135,0.852072,0.547540,0.654092,0.678641,0.677763,0.581278,0.666554,0.730944,0.557308,0.579298,0.728657,0.739710,0.855018,0.716177,0.734096,0.707679,1.000000

In [57]:
post.shape

(422, 20000)

In [58]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [59]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:33<00:00, 603.48it/s]

array(['NY-17', 'FL-25', 'PA-08', ..., 'PA-10', 'MI-07', 'FL-22'],
      shape=(20000,), dtype='<U32')

In [60]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.000000,0.000000,0.000000,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.000000,0.000000,0.000000,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-6.56666,1,0,45.599529,0.339529,45.799765,0.339529,East South Central,2026,0.0,0.0,0.0,1,102,1,917.110424,0.339529,0.582692,0.200235,-6.476755,-19.716169,1,-39.432338,47.958259,3.533152,27.90,3,41.053690,54.917600
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,1,18.397008,0.000000,0.000000,0.000000,-39.075524,-45.710827,-1,-91.421653,29.475654,3.530271,0.00,4,22.595513,36.422670
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,2,8.220432,0.000000,0.000000,0.000000,-59.367619,-47.132870,-1,-94.265741,19.758688,3.558614,0.00,5,12.812360,26.757494

In [61]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.000000,0.000000,0.000000,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.000000,0.000000,0.000000,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-6.56666,1,0,45.599529,0.339529,45.799765,0.339529,East South Central,2026,0.0,0.0,0.0,1,102,1,917.110424,0.339529,0.582692,0.200235,-6.476755,-19.716169,1,-39.432338,47.958259,3.533152,27.90,3,41.053690,54.917600,1.240
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,1,18.397008,0.000000,0.000000,0.000000,-39.075524,-45.710827,-1,-91.421653,29.475654,3.530271,0.00,4,22.595513,36.422670,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,2,8.220432,0.000000,0.000000,0.000000,-59.367619,-47.132870,-1,-94.265741,19.758688,3.558614,0.00,5,12.812360,26.757494,0.000

In [62]:
data.sort_values('tipping_point_prob', ascending=False).head(10)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
233,233,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE",no_match,2799701.44,0.00,2799701.44,100.000000,0.000000,North Carolina,NC-11,88.740422,3.902084,0.797632,1.120840,3.305854,24.807640,-7.843347,-4.057125,-5.003681,49.294326,45.192821,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.0,0.000000,0.000000,37,3711,2,10000.000000,0.000000,0.000000,0.000000e+00,-3.440701,50.000000,0,100.000000,50.607294,3.705562,56.770,234,43.345858,57.879755,3.155
197,197,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",1135198.13,1290223.21,2425421.34,46.804162,53.195838,Michigan,MI-10,76.551128,2.316124,5.150984,0.123322,13.269372,29.340000,-2.765891,-2.592362,-2.635744,99.999226,46.657584,0.987401,-6.56666,0,0,45.000000,0.473498,45.000000,0.473498,East North Central,2026,0.0,0.000000,0.000000,26,2610,0,2190.629568,0.473498,0.688112,-1.460326e-07,1.295172,-3.195838,0,-6.391676,50.306440,3.688675,53.120,198,43.055395,57.562253,2.945
98,98,FL-22,Pia Dandiya,Casey Askar,False,False,FL,22,"DANDIYA, PIA","ASKAR, CASEY",1965051.29,57760.00,2022811.29,97.144568,2.855432,Florida,FL-22,53.931205,26.984941,3.703933,0.199203,13.186062,27.190634,-0.817400,-4.551960,-3.618320,91.180168,44.697986,0.987401,-6.56666,0,0,50.000000,0.371574,50.000000,0.371574,South Atlantic,2026,0.0,0.000000,0.000000,12,1222,6,9437.067100,0.371574,0.609568,0.000000e+00,-0.669981,47.144568,0,94.289136,51.439186,3.686502,65.170,99,44.235851,58.728483,2.815
37,37,CA-22,Randy Villegas,David Valadao,False,True,CA,22,"VILLEGAS, RANDY","VALADAO, DAVID",2396295.54,1423592.37,3819887.91,62.732090,37.267910,California,CA-22,22.131732,64.469110,4.924433,0.538078,6.308791,6.196120,6.443675,-0.178428,1.477097,85.545753,49.071518,0.987401,-6.56666,0,1,48.000000,0.082381,44.000000,0.082381,Pacific,2026,0.0,0.000000,0.000000,6,622,5,3935.315176,0.082381,0.287021,-4.000000e+00,9.520854,12.732090,-1,25.464181,50.669147,3.501778,57.620,38,43.781076,57.579654,2.805
187,187,ME-02,Matt Dunlap,Paul LePage,False,False,ME,2,"DUNLAP, MATT","LEPAGE, PAUL",1181075.25,1418549.45,2599624.70,45.432529,54.567471,Maine,ME-02,94.623805,1.542589,0.598455,0.552005,0.848532,26.920000,-5.410176,-3.867301,-4.253020,26.830060,45.382645,0.987401,-6.56666,0,0,48.971709,0.205248,48.006269,0.205248,New England,2026,0.0,0.252840,-0.252840,23,2302,2,2064.114706,0.205248,0.453044,-9.654400e-01,-1.939380,-4.567471,0,-9.134942,49.659919,3.682139,46.145,188,42.436074,56.900198,2.760
277,277,NY-17,Cait Conley,Mike Lawler,False,True,NY,17,"CONLEY, CAIT","LAWLER, MICHAEL VINCENT",3706160.25,3186004.97,6892165.22,53.773526,46.226474,New York,NY-17,70.961924,14.978446,4.840493,0.059866,7.686273,48.490000,2.820018,1.029915,1.477441,87.206472,50.279862,0.987401,-6.56666,0,1,45.156078,0.330701,49.869935,0.330701,Mid-Atlantic,2026,0.0,0.000000,0.000000,36,3617,0,2891.592088,0.330701,0.575066,4.713858e+00,9.521542,3.773526,-1,7.547052,50.602163,3.525155,56.905,278,43.692534,57.588255,2.565
194,194,MI-07,William Lawrence,Tom Barrett,False,True,MI,7,"LAWRENCE, WILLIAM","BARRETT, THOMAS MORE",1065694.20,3350486.21,4416180.41,24.131582,75.868418,Michigan,MI-07,85.239895,4.803904,1.944855,0.170025,5.279273,36.270000,-2.003691,0.098125,-0.427329,68.756305,49.348071,0.987401,-6.56666,0,1,48.971702,0.574397,46.971702,0.574397,East North Central,2026,0.0,0.000000,0.000000,26,2607,2,582.333253,0.574397,0.757890,-2.000000e+00,5.712002,-25.868418,-1,-51.736836,50.522468,3.571607,55.705,195,43.520581,57.573090,2.555
84,84,FL-07,Bale Dalton,Ryan Elijah,False,False,FL,7,"DALTON, BALE","ELIJAH, RYAN",1196852.72,221855.46,1418708.18,84.362150,15.637850,Florida,FL-07,66.558362,19.398792,2.991603,0.123627,9.057449,25.552545,-5.072419,-5.558666,-5.437104,94.888595,43.691280,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.0,0.000000,0.000000,12,1207,0,7116.972318,0.000000,0.000000,0.000000e+00,-4.307549,34.362150,0,68.724300,49.545542,3.687504,44.895,85,42.363530,56.831431,2.500
191,191,MI-04,Sean McCann,Bill Huizenga,False,True,MI,4,"MCCANN, SEAN","HUIZENGA, WILLIAM P",2274399.15,1669140.88,3943540.03,57.674047,42.325953,Michigan,MI-04,81.841543,6.185553,1.807923,0.201856,7.596136,31.760000,-4.277760,-2.060635,-2.614916,69.598890,47.189311,0.987401,-6.56666,0,1,47.987567,0.047969,45.006214,0.047969,East North Central,2026,0.0,0.416862,-0.416862,26,2604,2,3326.295755,0.047969,0.219019,-2.981353e+00,1.336827,7.674047,-1,15.348095,49.892883,3.493295,48.850,192,43.096852,56.811544,2.495
390,390,VA-01,Shannon Taylor,Rob Wittman,False,True,VA,1,"TAYLOR, SHANNON LEIGH","WITTMAN, ROBERT J. MR.",1687926.35,1442542.81,3130469.16,53.919277,46.080723,Virginia,VA-01,75.537803,4.124527,4.097593,0.133339,13.351012,46.900000,-5.404597,-1.752158,-2.665268,73.780628,47.497788,0.987401,-6.56666,0,1,42.000000,0.002989,45.999999,0.002989,South Atlantic,2026,0.0,0.000000,0.000000,51,5101,0,2907.288474,0.002989,0.054673,4.000000e+00,1.236123,3.919277,-1,7.838555,49.708315,3.507613,46.415,391,42.781173,56.522582,2.485

In [63]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [64]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.000000,0.000000,0.000000,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085,Very Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.000000,0.000000,0.000000,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-6.56666,1,0,45.599529,0.339529,45.799765,0.339529,East South Central,2026,0.0,0.0,0.0,1,102,1,917.110424,0.339529,0.582692,0.200235,-6.476755,-19.716169,1,-39.432338,47.958259,3.533152,27.90,3,41.053690,54.917600,1.240,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1356433.59,1417220.64,4.289173,95.710827,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,1,18.397008,0.000000,0.000000,0.000000,-39.075524,-45.710827,-1,-91.421653,29.475654,3.530271,0.00,4,22.595513,36.422670,0.000,Safe R,"<b style=""color:#366bbf;"">Lee McInnis (D)</b> ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,523823.01,539285.01,2.867130,97.132870,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,2,8.220432,0.000000,0.000000,0.000000,-59.367619,-47.132870,-1,-94.265741,19.758688,3.558614,0.00,5,12.812360,26.757494,0.000,Safe R,"<b style=""color:#366bbf;"">Amanda Pusczek (D)</..."

In [65]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.000000,0.000000,0.000000,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085,Very Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.000000,0.000000,0.000000,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-6.56666,1,0,45.599529,0.339529,45.799765,0.339529,East South Central,2026,0.0,0.0,0.0,1,102,1,917.110424,0.339529,0.582692,0.200235,-6.476755,-19.716169,1,-39.432338,47.958259,3.533152,27.90,3,41.053690,54.917600,1.240,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R)

In [66]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.0,0.0,0.0,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085,Very Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.0,0.0,0.0,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,

In [67]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.000000,0.000000,0.000000,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085,Very Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+9.9
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.000000,0.000000,0.000000,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+27.8
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-6.56666,1,0,45.599529,0.339529,45.799765,0.339529,East South Central,2026,0.0,0.0,0.0,1,102,1,917.110424,0.339529,0.582692,0.200235,-6.476755,-19.716169,1,-39.432338,47.958259,3.533152,27.90,3,41.053690,54.917600,1.240,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+4.1

In [68]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.000000,0.000000,0.000000,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085,Very Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+9.9,91.71,8.3,91.7,8.3%,91.7%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.000000,0.000000,0.000000,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+27.8,100.00,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-6.56666,1,0,45.599529,0.339529,45.799765,0.339529,East South Central,2026,0.0,0.0,0.0,1,102,1,917.110424,0.339529,0.582692,0.200235,-6.476755,-19.716169,1,-39.432338,47.958259,3.533152,27.90,3,41.053690,54.917600,1.240,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+4.1,72.10,27.9,72.1,27.9%,72.1%

In [69]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.000000,0.000000,0.000000,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085,Very Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+9.9,91.71,8.3,91.7,8.3%,91.7%,3.746339
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.000000,0.000000,0.000000,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+27.8,100.00,0.0,100.0,<1%,>99%,8.504337
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",490903.40,1130104.85,1621008.25,30.283831,69.716169,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-6.56666,1,0,45.599529,0.339529,45.799765,0.339529,East South Central,2026,0.0,0.0,0.0,1,102,1,917.110424,0.339529,0.582692,0.200235,-6.476755,-19.716169,1,-39.432338,47.958259,3.533152,27.90,3,41.053690,54.917600,1.240,Lean R,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+4.1,72.10,27.9,72.1,27.9%,72.1%,10.380946

In [70]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",1264611.09,2784023.76,4048634.85,31.235494,68.764506,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-6.56666,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,1,975.656077,0.0,0.0,0.0,-6.343945,-18.764506,-1,-37.529012,45.026607,3.606322,8.29,1,37.963060,52.141530,0.085,Very Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+9.9,91.71,8.3,91.7,8.3%,91.7%,3.746339,D+3.7
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",83967.63,674069.54,758037.17,11.076981,88.923019,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-6.56666,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,1,122.699498,0.0,0.0,0.0,-28.307623,-38.923019,0,-77.846039,36.079932,3.626315,0.00,2,28.978859,43.219775,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+27.8,100.00,0.0,100.0,<1%,>99%,8.504337,D+8.5

In [71]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
417    5507
418    5508
419    5401
420    5402
421    5600
Name: geoid, Length: 422, dtype: int64

In [72]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['y_pred'] = np.full(dem_uclen, 100)
dem_uncont['swing_24_to_26'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_24_to_26_swing'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                      x['dem_inc_any'], x['rep_inc_any']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Mike Thompson/Eric J..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Doris Matsui/Mai Van..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Scott Weiner/Connie ..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Lateefah Simon* (D)<..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,False,False,CA,14,6,614,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Aisha Wahab/Melissa ..."

In [73]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['y_pred'] = np.full(rep_uclen, 0)
rep_uncont['swing_24_to_26'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_24_to_26_swing'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                       x['dem_inc_any'], x['rep_inc_any']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0,NaN,NaN,0%,100%,R+100,,"<b style=""color:#366bbf;"">Not Contested (D)</b..."

In [74]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'geoid', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 16)

In [75]:
tab_data = data[['cd', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Bill Hill', 'Kevin Kiley'] else x)
tab_data = tab_data.rename({
    'cd': 'District',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,District,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,AK-AL,Bill Hill (Ind),Nick Begich,Very Likely R,"<p style=""color:blue;"">8.3%</p>","<p style=""color:red;"">91.7%</p>",R+9.9,D+3.7,0.085
1,AL-01,Clyde Jones Jr.,Jerry Carl,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+27.8,D+8.5,0.000
2,AL-02,Shomari Figures,Rhett Marques,Lean R,"<p style=""color:blue;"">27.9%</p>","<p style=""color:red;"">72.1%</p>",R+4.1,D+10.4,1.240
3,AL-03,Lee McInnis,Mike Rogers,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+41.0,D+6.0,0.000
4,AL-04,Amanda Pusczek,Robert Aderholt,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+60.5,D+6.5,0.000

In [76]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

5.352072164072947

In [77]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

   Unnamed: 0                vars           x
0         0.0     means_seats_tot  229.953250
1         1.0  chamber_win_chance   66.245000
0         NaN             sv_bias    5.352072

In [78]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [79]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 435 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Unnamed: 0_x  Win Probability  Unnamed: 0_y  Seat Share
0    Democrats           1.0           66.245           0.0   229.95325
1  Republicans          99.0           33.755         435.0   205.04675

In [80]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')