In [47]:
import warnings
warnings.filterwarnings('ignore')

In [48]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [49]:
pd.set_option('display.max_columns', 100)

In [50]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [51]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        261    Democrats
1        217  Republicans
2        249    Democrats
3        241    Democrats
4        229    Democrats
...      ...          ...
19995    299    Democrats
19996    213  Republicans
19997    207  Republicans
19998    270    Democrats
19999    230    Democrats

[20000 rows x 2 columns]

In [52]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    163      1  0.005  Republicans
1    166      1  0.005  Republicans
2    168      1  0.005  Republicans
3    169      1  0.005  Republicans
4    171      1  0.005  Republicans

In [53]:
np.unique(seat_sims['seats']).shape[0]

189

In [54]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [55]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date           y       geo       type
0  2026-08-30  229.365800  US House      seats
1  2026-08-30   66.120000  US House     chance
2  2026-08-30   22.784344  US House   seats_sd
3  2026-08-30   44.972806     AK-AL     y_pred
4  2026-08-30    3.555839     AK-AL  y_pred_sd

In [56]:
chance_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="House Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser.add_vline(x=pd.to_datetime('2026-10-22').timestamp() * 1000, line_width=1, line_color='black',
                          annotation_text='Poll average methodology update', annotation_position='top right')
chance_time_ser

In [57]:
seats_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 435 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 435]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser.add_vline(x=pd.to_datetime('2026-10-22').timestamp() * 1000, line_width=1, line_color='black',
                          annotation_text='Poll average methodology update', annotation_position='top right')
seats_time_ser

In [58]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [59]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [60]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,19950,19951,19952,19953,19954,19955,19956,19957,19958,19959,19960,19961,19962,19963,19964,19965,19966,19967,19968,19969,19970,19971,19972,19973,19974,19975,19976,19977,19978,19979,19980,19981,19982,19983,19984,19985,19986,19987,19988,19989,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,0.290464,-4.763811,-2.765577,-7.651245,-4.437788,-0.085321,-2.907764,-4.477645,-2.633585,-5.493719,0.240482,1.889354,1.177028,-9.061929,6.128796,0.302911,-5.970734,-3.107202,-0.234031,-0.158929,-6.772882,-7.942584,0.723187,-6.670971,-6.570084,-1.628721,-3.002809,-5.351073,-1.978066,-10.020168,-0.980786,-5.318387,-6.147661,1.477838,-2.943619,-4.004596,-5.608461,-5.530105,-2.867096,0.316883,-10.435808,-1.767295,-7.519301,-4.113337,-1.643520,-6.611364,-1.573681,-5.265390,-3.899686,-5.129961,...,-4.445519,-5.235127,-2.444385,-2.628024,-6.183949,-1.761336,-3.494097,-2.563971,-1.493620,-0.449904,-2.592229,-0.652705,-9.852035,2.643915,-3.224689,-6.520618,-0.291236,-1.659040,-1.674295,-4.204266,-3.645494,-4.745447,-2.427209,-6.668672,-2.767606,-3.499705,-0.415562,-4.964702,-0.465441,-7.421460,-1.739026,-3.907207,-2.516074,0.603054,-0.547487,-0.607779,-1.035043,-4.259181,-1.648209,-1.713566,-7.499612,2.726768,0.975951,-4.816544,-3.525710,2.704999,-10.389867,-9.152720,-3.665211,-4.397488
AL-01,-8.647245,-13.503705,-11.606001,-14.170057,-11.263946,-7.336357,-12.187697,-12.323793,-11.989798,-13.744609,-11.341554,-12.006361,-9.060335,-14.487986,-3.813544,-9.343439,-12.639049,-11.908272,-15.984233,-8.578973,-16.519214,-15.982899,-6.205275,-19.574502,-14.964319,-8.629225,-13.372173,-15.959600,-11.755002,-17.862299,-11.190854,-15.253150,-19.244968,-9.121419,-12.849601,-12.780492,-13.783923,-18.209742,-14.579553,-4.380150,-20.054143,-9.149214,-14.655021,-12.125212,-12.987787,-18.019461,-10.633487,-14.372958,-11.260205,-11.998369,...,-12.211797,-11.332119,-13.312613,-9.308704,-12.630371,-12.371142,-11.921705,-14.376856,-13.806439,-8.941087,-9.503252,-9.988613,-17.494550,-8.648769,-10.178793,-20.193019,-4.059942,-13.201375,-16.544310,-16.189570,-10.027449,-12.788402,-13.773428,-10.042337,-12.494110,-14.512820,-9.902470,-14.805342,-9.758232,-14.828780,-8.671695,-13.820894,-14.226922,-8.585268,-7.248291,-8.900807,-10.835081,-13.845709,-15.288863,-12.686396,-14.276838,-10.568570,-12.251120,-11.051168,-16.865893,-6.046644,-17.008749,-18.723546,-7.948935,-13.874556
AL-02,-0.560985,-0.448640,1.054838,1.493515,-4.385048,-3.902030,-2.152882,-1.048035,3.514337,-2.409290,0.065601,0.865988,0.942685,0.778335,-5.556683,-4.328249,4.624267,-4.718258,-1.076677,5.290043,-1.437299,-2.193275,2.336676,-4.088767,0.975457,-0.994117,5.988860,-2.696110,3.230228,-3.044469,0.679612,1.041947,-6.721227,2.230609,0.380762,-0.299324,-2.095272,-4.870951,-4.332010,8.955409,-8.300506,1.752484,-2.084262,-2.199891,-2.820422,1.336567,0.091122,-2.323635,-1.576737,6.087302,...,0.410768,0.403838,-0.995232,-0.178962,-0.173392,1.384424,4.176418,-9.163640,-7.518377,2.078837,0.576724,-2.642711,2.475783,-2.577699,-1.453595,-1.972145,0.889343,1.160807,1.080160,-2.286150,2.450182,-0.081680,1.277321,-2.709728,-9.411654,-1.181473,-0.795064,-0.654309,-0.164695,1.165624,-4.250166,-1.787755,-0.242024,-1.556111,1.304990,4.364324,2.677441,-2.318650,1.522475,1.674363,-1.421798,4.628110,11.115068,-6.670728,4.464443,4.527946,-2.069957,-5.595842,3.137150,-4.502909
AL-03,-16.193770,-23.156579,-18.571501,-22.455515,-21.605704,-15.216984,-19.950531,-14.780413,-20.827661,-20.921503,-15.523398,-16.576274,-14.666829,-21.028272,-11.763944,-14.421136,-22.679841,-21.299648,-20.015503,-15.376468,-23.281199,-23.764985,-15.303811,-21.638766,-22.461674,-17.566863,-20.076821,-23.653277,-20.372755,-25.192236,-16.956548,-17.379822,-22.436736,-14.411539,-20.351134,-13.787010,-22.317238,-20.377778,-20.767764,-15.873646,-29.082553,-19.891117,-20.581203,-18.808476,-19.710605,-23.625696,-15.918936,-21.871041,-18.003561,-22.388875,...,-19.214864,-20.402254,-19.045798,-18.358562,-20.708316,-16.227030,-20.773412,-21.405855,-21.230770,-16.509880,-19.233876,-16.357615,-25.427365,-13.632243,-13.779062,-26.661669,-14.182262,-17.473145,-23.498207,-20.693799,-19.402542,-21.288288,-17.048861,-22.081368,-19.236688,-15.745287,-14.059764,-23.856089,-17.507922,-25.121891,-16.842463,-18.579528,-18.333529,-15.158877,-17.683411,-16.491626,-19.527498,-17.792120,-20.420651,-16.678390,-20.300717,-12.703438,-16.982739,-22.501649,-21.421938,-15.097479,-22.979361,-24.075560,-17.164907,-20.799159
AL-04,-24.210037,-31.292455,-28.204056,-31.986326,-28.220899,-24.021148,-29.255736,-28.803002,-31.787412,-26.612580,-26.242210,-26.897061,-25.695604,-34.147332,-20.809753,-26.221758,-32.063430,-29.567635,-30.701108,-26.754213,-30.935999,-31.206476,-24.332051,-31.812067,-32.532640,-28.697153,-29.592723,-33.346747,-29.088736,-32.009798,-25.946696,-31.355927,-34.528460,-22.812240,-29.947418,-25.538737,-30.899476,-32.850267,-32.482377,-20.925557,-35.841723,-29.888581,-32.204600,-26.677039,-30.273999,-31.426179,-25.978701,-31.912105,-26.350857,-30.553256,...,-30.456376,-29.239585,-29.209383,-27.630524,-29.458090,-25.384050,-30.115154,-30.588084,-29.452454,-25.360419,-30.128237,-25.902437,-35.433181,-24.776919,-25.796457,-39.663713,-25.207354,-31.629373,-34.856231,-29.698560,-29.817633,-32.142200,-28.727662,-29.166044,-31.594388,-31.732801,-26.510751,-28.836494,-26.147634,-30.702136,-27.337844,-28.308717,-33.379170,-28.425999,-25.159597,-25.888172,-28.462220,-29.374312,-29.985940,-26.866135,-31.980802,-24.623518,-28.550585,-36.417306,-29.313053,-23.201483,-36.677041,-36.850417,-27.119759,-29.586346

In [61]:
sim_corr = post_untransp.corr()

In [62]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,...,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.723913,0.484307,0.742425,0.733007,0.718815,0.741451,0.498688,0.737336,0.746663,0.742707,0.739237,0.486976,0.486341,0.485193,0.505256,0.700710,0.720701,0.729761,0.725804,0.739896,0.703231,0.505305,0.516792,0.747400,0.738681,0.569017,0.507246,0.513488,0.514983,0.482550,0.698903,0.571790,0.506773,0.502712,0.701534,0.509554,0.748822,0.733788,0.510502,0.512694,0.704201,0.486787,0.510435,0.486477,0.525205,0.549626,0.511143,0.566138,0.511675,...,0.737473,0.718473,0.547430,0.510124,0.514963,0.701666,0.749469,0.700478,0.528827,0.503759,0.701564,0.535344,0.500957,0.487615,0.500114,0.733993,0.723105,0.724281,0.742869,0.551634,0.510015,0.482745,0.721721,0.739072,0.485997,0.511796,0.739791,0.482601,0.697798,0.531493,0.512018,0.513388,0.489285,0.702412,0.543475,0.487277,0.504948,0.512096,0.576330,0.497587,0.739098,0.544898,0.575466,0.739246,0.746635,0.697995,0.720847,0.736996,0.720581,0.698438
AL-01,0.723913,1.000000,0.494158,0.750387,0.742457,0.722414,0.745499,0.505136,0.745049,0.749879,0.744897,0.747993,0.493992,0.489181,0.488909,0.512338,0.708697,0.729682,0.733208,0.729248,0.745455,0.706632,0.510394,0.516646,0.749014,0.736878,0.565617,0.512930,0.519116,0.519753,0.493595,0.703646,0.569144,0.509322,0.509623,0.709779,0.513266,0.748948,0.734038,0.513599,0.518473,0.707313,0.488820,0.516026,0.487069,0.530088,0.547648,0.514898,0.569288,0.513544,...,0.742316,0.721833,0.550604,0.515251,0.518688,0.702266,0.751205,0.708163,0.539748,0.509277,0.709696,0.537253,0.499650,0.497058,0.500513,0.740129,0.725542,0.730521,0.747961,0.547905,0.509031,0.488553,0.725616,0.737673,0.492460,0.513819,0.742799,0.492758,0.705844,0.534681,0.514898,0.518194,0.488694,0.709758,0.538163,0.490670,0.508421,0.515166,0.580302,0.503711,0.746665,0.544522,0.572996,0.741916,0.751467,0.711819,0.719540,0.745914,0.726025,0.708859
AL-02,0.484307,0.494158,1.000000,0.506129,0.499073,0.486889,0.509673,0.704141,0.495619,0.505523,0.496230,0.502046,0.683784,0.677070,0.683385,0.700776,0.641644,0.487266,0.494336,0.490465,0.505648,0.639923,0.705636,0.713600,0.509569,0.502789,0.583471,0.705518,0.705679,0.526979,0.672547,0.644455,0.584616,0.703984,0.704723,0.645179,0.707119,0.510187,0.501982,0.711545,0.715114,0.646396,0.680202,0.705197,0.678456,0.552357,0.568576,0.710305,0.584733,0.712812,...,0.503073,0.492582,0.559802,0.705846,0.701943,0.642125,0.510932,0.639913,0.552660,0.701609,0.647477,0.550026,0.690179,0.684129,0.687951,0.501613,0.485202,0.495099,0.501861,0.561128,0.702458,0.676448,0.490088,0.502544,0.675076,0.712966,0.503194,0.680273,0.645272,0.542572,0.707899,0.707025,0.678690,0.645817,0.559658,0.670960,0.699665,0.706190,0.590217,0.694423,0.501578,0.557409,0.589357,0.500964,0.503330,0.646173,0.481956,0.505848,0.491271,0.643655
AL-03,0.742425,0.750387,0.506129,1.000000,0.761410,0.748186,0.773691,0.521282,0.765214,0.769680,0.763569,0.768955,0.505856,0.503244,0.500790,0.524231,0.724303,0.744541,0.746155,0.748765,0.765810,0.726180,0.525161,0.531201,0.768769,0.759454,0.582116,0.525435,0.533733,0.531166,0.503764,0.722532,0.584413,0.522172,0.524044,0.729623,0.525282,0.765883,0.753897,0.527699,0.531156,0.723773,0.501553,0.527606,0.502916,0.545662,0.566688,0.527420,0.582029,0.531895,...,0.761876,0.740929,0.563300,0.532424,0.530759,0.721105,0.773197,0.727202,0.547773,0.522651,0.727788,0.551170,0.515238,0.509691,0.515733,0.755021,0.740884,0.742552,0.768943,0.560086,0.521853,0.498025,0.744234,0.759539,0.504483,0.528192,0.765391,0.499013,0.723818,0.547645,0.527430,0.532889,0.504128,0.725562,0.561725,0.499683,0.523375,0.530878,0.591679,0.516662,0.762952,0.563871,0.587802,0.763857,0.768788,0.729775,0.741417,0.762012,0.745988,0.726656
AL-04,0.733007,0.742457,0.499073,0.761410,1.000000,0.737180,0.755311,0.512364,0.753570,0.756738,0.757520,0.755082,0.493855,0.498839,0.494833,0.516204,0.716778,0.735347,0.738314,0.738089,0.759466,0.716012,0.516599,0.525127,0.756701,0.746799,0.571971,0.521584,0.522037,0.521813,0.496936,0.713725,0.575856,0.515856,0.515644,0.720275,0.517778,0.757409,0.743791,0.524028,0.525061,0.716553,0.496063,0.522556,0.493464,0.535554,0.556609,0.515398,0.572301,0.525018,...,0.749370,0.732573,0.552686,0.527715,0.526732,0.713194,0.758679,0.719480,0.544438,0.516999,0.719531,0.542759,0.511141,0.502078,0.506247,0.747051,0.735477,0.739817,0.758277,0.554869,0.515969,0.493740,0.735218,0.753797,0.494313,0.522129,0.754454,0.493092,0.714256,0.542108,0.518585,0.525339,0.499708,0.717203,0.552047,0.497394,0.516822,0.523146,0.582700,0.508540,0.753338,0.553882,0.577748,0.753293,0.755769,0.716291,0.730673,0.750462,0.731825,0.717129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WI-07,0.697995,0.711819,0.646173,0.729775,0.716291,0.707584,0.723758,0.663192,0.724787,0.728481,0.725405,0.728126,0.654994,0.653345,0.651729,0.673929,0.850335,0.708827,0.714030,0.710395,0.730836,0.846712,0.678075,0.684238,0.729799,0.720816,0.556122,0.677004,0.683353,0.513118,0.647179,0.847906,0.561953,0.679464,0.676516,0.850873,0.678167,0.728905,0.717764,0.681991,0.683119,0.848935,0.651606,0.678545,0.646458,0.525183,0.540017,0.685575,0.559663,0.681772,...,0.725943,0.706914,0.533640,0.679347,0.680791,0.845422,0.729891,0.849255,0.522873,0.674848,0.851343,0.519563,0.663283,0.656112,0.663339,0.719399,0.708009,0.709326,0.730919,0.536528,0.676672,0.649015,0.705292,0.721560,0.647232,0.681583,0.727073,0.648584,0.850288,0.520581,0.681849,0.682366,0.651109,0.851738,0.535139,0.647919,0.673981,0.679948,0.566031,0.666328,0.723287,0.535145,0.559721,0.722217,0.730727,1.000000,0.704426,0.726620,0.706879,0.851924
WI-08,0.720847,0.719540,0.481956,0.741417,0.730673,0.717352,0.739374,0.496874,0.746524,0.747520,0.741928,0.745229,0.483619,0.489954,0.486921,0.501651,0.705689,0.726507,0.728412,0.726303,0.742669,0.709504,0.509017,0.511842,0.745138,0.738721,0.559347,0.505277,0.515734,0.511862,0.488816,0.701701,0.563461,0.506999,0.501976,0.706407,0.510393,0.745188,0.732866,0.512389,0.514521,0.704801,0.485077,0.511490,0.488996,0.525314,0.544345,0.512080,0.560954,0.513991,...,0.739370,0.721614,0.548709,0.514372,0.513741,0.703713,0.744152,0.707590,0.531168,0.506392,0.706062,0.527349,0.500977,0.493676,0.503253,0.734679,0.720732,0.724579,0.744122,0.543753,0.507096,0.480854,0.724712,0.735123,0.482692,0.508357,0.742329,0.487956,0.703690,0.529711,0.510786,0.517434,0.486729,0.705899,0.540347,0.483060,0.507101,0.515293,0.573714,0.499344,0.743297,0.556641,0.577901,0.744081,0.746389,0.704426,1.000000,0.738797,0.721752,0.703972
WV-01,0.736996,0.745914,0.505848,0.762012,0.750462,0.741026,0.763448,0.515797,0.756982,0.765722,0.760902,0.763197,0.509535,0.509825,0.500342,0.522088,0.724088,0.741655,0.749464,0.750799,0.763245,0.723467,0.525040,0.533286,0.766141,0.753167,0.583910,0.523550,0.530028,0.529822,0.507121,0.718634,0.581795,0.522939,0.521436,0.727245,0.526858,0.761319,0.750194,0.531429,0.528688,0.724509,0.503055,0.527667,0.503038,0.546277,0.564367,0.524399,0.579074,0.532685,...,0.760499,0.739164,0.568010,0.528125,0.532517,0.717899,0.765373,0.723973,0.550549,0.523767,0.723273,0.549126,0.515663,0.507919,0.514581,0.754893,0.741466,0.740129,0.764907,0.562996,0.523595,0.498794,0.735281,0.757321,0.501110,0.534896,0.761923,0.499500,0.721894,0.545253,0.523370,0.532452,0.507987,0.725783,0.560022,0.501514,0.524062,0.529898,0.595628,0.517469,0.759574,0.566091,0.586284,0.760042,0.768555,0.726620,0.738797,1.000000,0.748905,0.725711
WV-02,0.720581,0.726025,0.491271,0.745988,0.731825,0.721829,0.740823,0.501175,0.739842,0.747839,0.741003,0.748851,0.496180,0.495562,0.488628,0.507560,0.706534,0.725858,0.731170,0.728538,0.743264,0.709034,0.510443,0.522919,0.747733,0.735773,0.566894,0.511588,0.519646,0.513424,0.492050,0.702412,0.567796,0.511037,0.507822,0.706925,0.511828,0.748657,0.732197,0.514521,0.514100,0.705101,0.488920,0.517946,0.489287,0.531639,0.549929,0.513893,0.567660,0.518123,...,0.744135,0.726919,0.546799,0.516218,0.517602,0.704070,0.748078,0.707726,0.537111,0.509043,0.709506,0.537154,0.501314,0.494371,0.502598,0.735946,0.718264,0.724134,0.747949,0.546893,0.511243,0.488804,0.722687,0.738227,0.495054,0.513632,0.746303,0.490302,0.705978,0.534553,0.512980,0.519266,0.492284,0.709445,0.539762,0.487696,0.509748,0.515746,0.577301,0.504202,0.743721,0.547848,0.567159,0.738234,0.742708,0.706879,0.721752,0.748905,1.000000,0.709459
WY-AL,0.698438,0.708859,0.643655,0.726656,0.717129,0.707047,0.723161,0.663598,0.724143,0.730174,0.723664,0.730553,0.653703,0.652108,0.645618,0.670409,0.850182,0.707474,0.711180,0.712585,0.727504,0.847218,0.677600,0.680512,0.729127,0.721078,0.552921,0.678275,0.684147,0.507483,0.651024,0.846408,0.558270,0.675887,0.670651,0.851004,0.675740,0.728245,0.719801,0.676192,0.680277,0.850063,0.651733,0.679096,0.646368,0.520639,0.539009,0.678749,0.557187,0.682154,...,0.726804,0.707081,0.533486,0.677214,0.677968,0.844917,0.732503,0.853253,0.520770,0.674496,0.850391,0.517837,0.660914,0.650371,0.657865,0.718909,0.704801,0.711410,0.730610,0.533039,0.672706,0.647262,0.708497,0.723801,0.647875,0.678094,0.729767,0.647743,0.848272,0.521279,0.679071,0.683823,0.654330,0.851031,0.531358,0.646503,0.671340,0.679562,0.563724,0.664154,0.725136,0.531943,0.558417,0.716934,0.727071,0.851924,0.703972,0.725711,0.709459,1.000000

In [63]:
post.shape

(418, 20000)

In [64]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [65]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:32<00:00, 623.89it/s]

array(['ME-02', 'PA-08', 'FL-07', ..., 'OH-15', 'CO-04', 'MI-07'],
      shape=(20000,), dtype='<U32')

In [66]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.000000,0.000000,0.000000,-3.738711,-10.947674,-1,-21.895348,46.520450,3.601410,16.645,1,39.457825,53.594350
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.702388,-29.987744,0,-59.975488,37.556610,3.632234,0.030,2,30.475629,44.635696
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.171894,1,0,46.957206,0.166507,46.963324,0.166507,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.166507,0.408053,0.006119,-3.871521,-5.527053,1,-11.054107,49.488434,3.490064,44.265,3,42.602044,56.305934
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.000000,0.000000,-36.470289,-46.255299,-1,-92.510598,30.572451,3.512897,0.000,4,23.641995,37.424658
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,625402.87,640864.87,2.412677,97.587323,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.821011,0.000000,0.000000,0.000000,-56.762385,-47.587323,-1,-95.174646,20.721169,3.560778,0.000,5,13.723382,27.643306

In [67]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.000000,0.000000,0.000000,-3.738711,-10.947674,-1,-21.895348,46.520450,3.601410,16.645,1,39.457825,53.594350,0.065
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.702388,-29.987744,0,-59.975488,37.556610,3.632234,0.030,2,30.475629,44.635696,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.171894,1,0,46.957206,0.166507,46.963324,0.166507,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.166507,0.408053,0.006119,-3.871521,-5.527053,1,-11.054107,49.488434,3.490064,44.265,3,42.602044,56.305934,1.030
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.000000,0.000000,-36.470289,-46.255299,-1,-92.510598,30.572451,3.512897,0.000,4,23.641995,37.424658,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,625402.87,640864.87,2.412677,97.587323,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.821011,0.000000,0.000000,0.000000,-56.762385,-47.587323,-1,-95.174646,20.721169,3.560778,0.000,5,13.723382,27.643306,0.000

In [68]:
data.sort_values('tipping_point_prob', ascending=False).head(10)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
193,193,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",3380348.82,1841619.43,5221968.25,64.733232,35.266768,Michigan,MI-10,76.551128,2.316124,5.150984,0.123322,13.269372,29.340000,-2.765891,-2.592362,-2.635744,99.999226,46.657584,0.987401,-9.171894,0,0,45.000000,0.064737,45.000000,0.064737,East North Central,2026,0.0,0.00000,0.00000,26,2610,2,4190.391320,0.064737,0.254435,-1.460326e-07,3.900406,14.733232,0,29.466464,52.136626,3.653923,72.030,194,44.963896,59.237158,3.055
98,98,FL-22,Pia Dandiya,Casey Askar,False,False,FL,22,"DANDIYA, PIA","ASKAR, CASEY",3095902.57,383626.04,3479528.61,88.974770,11.025230,Florida,FL-22,53.931205,26.984941,3.703933,0.199203,13.186062,27.190634,-0.817400,-4.551960,-3.618320,91.180168,44.697986,0.987401,-9.171894,0,0,46.286766,0.189318,44.430149,0.189318,South Atlantic,2026,0.0,0.00000,0.00000,12,1222,6,7916.509657,0.189318,0.435107,-1.856617e+00,1.935254,38.974770,0,77.949540,52.277960,3.657190,73.240,99,45.005784,59.416506,2.810
183,183,ME-02,Matt Dunlap,Paul LePage,False,False,ME,2,"DUNLAP, MATT","LEPAGE, PAUL",2730281.55,1689499.20,4419780.75,61.774140,38.225860,Maine,ME-02,94.623805,1.542589,0.598455,0.552005,0.848532,26.920000,-5.410176,-3.867301,-4.253020,26.830060,45.382645,0.987401,-9.171894,0,0,50.069480,1.401094,46.458349,1.401094,New England,2026,0.0,0.25284,-0.25284,23,2302,3,3816.044378,1.401094,1.183678,-3.611131e+00,0.665854,11.774140,0,23.548280,51.838628,3.673648,69.215,184,44.602507,59.007514,2.795
123,123,IA-03,Sarah Trone Garriott,Zach Nunn,False,True,IA,3,"TRONE GARRIOTT, SARAH","NUNN, ZACH",7230292.81,1334009.44,8564302.25,84.423606,15.576394,Iowa,IA-03,86.341081,5.022950,2.732262,0.063009,3.929259,35.410000,-2.445778,-1.482072,-1.722998,77.628515,47.767874,0.987401,-9.171894,0,1,42.000000,0.000436,48.000000,0.000436,West North Central,2026,0.0,0.00000,0.00000,19,1903,2,7127.345293,0.000436,0.020891,6.000000e+00,5.725897,34.423606,-1,68.847213,52.423833,3.536036,75.560,124,45.400187,59.307722,2.615
37,37,CA-22,Randy Villegas,David Valadao,False,True,CA,22,"VILLEGAS, RANDY","VALADAO, DAVID",4723984.35,2041081.96,6765066.31,69.829092,30.170908,California,CA-22,22.131732,64.469110,4.924433,0.538078,6.308791,6.196120,6.443675,-0.178428,1.477097,85.545753,49.071518,0.987401,-9.171894,0,1,48.000000,0.011263,44.000000,0.011263,Pacific,2026,0.0,0.00000,0.00000,6,622,4,4876.102033,0.011263,0.106128,-4.000000e+00,12.126089,19.829092,-1,39.658183,52.267885,3.512430,74.295,38,45.425751,59.155219,2.600
229,229,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE","BALKCOM, JENNIFER",5040487.66,106191.99,5146679.65,97.936689,2.063311,North Carolina,NC-11,88.740422,3.902084,0.797632,1.120840,3.305854,24.807640,-7.843347,-4.057125,-5.003681,49.294326,45.192821,0.987401,-9.171894,0,0,56.000000,0.876883,43.000000,0.876883,South Atlantic,2026,0.0,0.00000,0.00000,37,3711,3,9591.595118,0.876883,0.936420,-1.300000e+01,-0.835467,47.936689,0,95.873379,53.438564,3.669912,82.345,230,46.208723,60.628456,2.485
314,314,PA-07,Bob Brooks,Ryan Mackenzie,False,True,PA,7,"BROOKS, BOB","MACKENZIE, RYAN EDWARD",4181508.28,1902194.06,6083702.34,68.732953,31.267047,Pennsylvania,PA-07,75.458946,15.481046,2.435986,0.030199,4.952274,31.050000,-1.956264,-0.869379,-1.141100,81.633883,48.380567,0.987401,-9.171894,0,1,45.002910,0.368346,40.004365,0.368346,Mid-Atlantic,2026,0.0,0.00000,0.00000,42,4207,2,4724.218851,0.368346,0.606915,-4.998545e+00,6.889694,18.732953,-1,37.465906,52.140994,3.567353,72.625,315,45.241328,59.142793,2.485
71,71,CO-08,Manny Rutinel,Gabe Evans,False,True,CO,8,"RUTINEL, MANNY","EVANS, TIMOTHY GABRIEL JOSEPH",7611412.22,3271309.22,10882721.44,69.940339,30.059661,Colorado,CO-08,61.985014,30.668107,2.797756,0.346752,1.898138,27.960000,0.077260,-0.189970,-0.123163,93.243947,49.059976,0.987401,-9.171894,0,1,46.300000,0.156904,48.000000,0.156904,Mountain,2026,0.0,0.00000,0.00000,8,808,6,4891.650958,0.156904,0.396112,1.700000e+00,8.925569,19.940339,-1,39.880677,52.996274,3.579227,80.075,72,46.026556,60.065016,2.465
206,206,MO-02,Fred Wellman,Ann Wagner,False,True,MO,2,"WELLMAN, FREDERICK PAUL","WAGNER, ANN L.",1833464.54,2354885.63,4188350.17,43.775340,56.224660,Missouri,MO-02,89.786282,2.324956,3.134970,0.061673,3.001461,48.680000,-6.210595,-3.268235,-4.003825,87.342792,45.981711,0.987401,-9.171894,0,1,48.249295,1.800788,45.436131,1.800788,West North Central,2026,0.0,0.00000,0.00000,29,2902,2,1916.280419,1.800788,1.341935,-2.813164e+00,1.164244,-6.224660,-1,-12.449319,51.788351,3.475873,69.495,207,45.034983,58.646292,2.455
273,273,NY-17,Cait Conley,Mike Lawler,False,True,NY,17,"CONLEY, CAIT","LAWLER, MICHAEL VINCENT",8464600.26,3971573.10,12436173.36,68.064348,31.935652,New York,NY-17,70.961924,14.978446,4.840493,0.059866,7.686273,48.490000,2.820018,1.029915,1.477441,87.206472,50.279862,0.987401,-9.171894,0,1,47.754428,0.827496,46.258603,0.827496,Mid-Atlantic,2026,0.0,0.00000,0.00000,36,3617,0,4632.755410,0.827496,0.909668,-1.495825e+00,12.126776,18.064348,-1,36.128695,52.585152,3.528169,76.915,274,45.712645,59.524123,2.435

In [69]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [70]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.000000,0.000000,0.000000,-3.738711,-10.947674,-1,-21.895348,46.520450,3.601410,16.645,1,39.457825,53.594350,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.702388,-29.987744,0,-59.975488,37.556610,3.632234,0.030,2,30.475629,44.635696,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.171894,1,0,46.957206,0.166507,46.963324,0.166507,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.166507,0.408053,0.006119,-3.871521,-5.527053,1,-11.054107,49.488434,3.490064,44.265,3,42.602044,56.305934,1.030,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.000000,0.000000,-36.470289,-46.255299,-1,-92.510598,30.572451,3.512897,0.000,4,23.641995,37.424658,0.000,Safe R,"<b style=""color:#366bbf;"">Lee McInnis (D)</b> ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,625402.87,640864.87,2.412677,97.587323,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.821011,0.000000,0.000000,0.000000,-56.762385,-47.587323,-1,-95.174646,20.721169,3.560778,0.000,5,13.723382,27.643306,0.000,Safe R,"<b style=""color:#366bbf;"">Amanda Pusczek (D)</..."

In [71]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.000000,0.000000,0.000000,-3.738711,-10.947674,-1,-21.895348,46.520450,3.601410,16.645,1,39.457825,53.594350,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.702388,-29.987744,0,-59.975488,37.556610,3.632234,0.030,2,30.475629,44.635696,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.171894,1,0,46.957206,0.166507,46.963324,0.166507,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.166507,0.408053,0.006119,-3.871521,-5.527053,1,-11.054107,49.488434,3.490064,44.265,3,42.602044,56.305934,1.030,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R)

In [72]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.0,0.0,0.0,-3.738711,-10.947674,-1,-21.895348,46.52045,3.601410,16.645,1,39.457825,53.594350,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.0,0.0,0.0,-25.702388,-29.987744,0,-59.975488,37.55661,3.632234,0.030,2,30.475629,44.635696,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,

In [73]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.000000,0.000000,0.000000,-3.738711,-10.947674,-1,-21.895348,46.520450,3.601410,16.645,1,39.457825,53.594350,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.0
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.702388,-29.987744,0,-59.975488,37.556610,3.632234,0.030,2,30.475629,44.635696,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.171894,1,0,46.957206,0.166507,46.963324,0.166507,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.166507,0.408053,0.006119,-3.871521,-5.527053,1,-11.054107,49.488434,3.490064,44.265,3,42.602044,56.305934,1.030,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.0

In [74]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.000000,0.000000,0.000000,-3.738711,-10.947674,-1,-21.895348,46.520450,3.601410,16.645,1,39.457825,53.594350,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.0,83.355,16.6,83.4,16.6%,83.4%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.702388,-29.987744,0,-59.975488,37.556610,3.632234,0.030,2,30.475629,44.635696,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.970,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.171894,1,0,46.957206,0.166507,46.963324,0.166507,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.166507,0.408053,0.006119,-3.871521,-5.527053,1,-11.054107,49.488434,3.490064,44.265,3,42.602044,56.305934,1.030,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.0,55.735,44.3,55.7,44.3%,55.7%

In [75]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.000000,0.000000,0.000000,-3.738711,-10.947674,-1,-21.895348,46.520450,3.601410,16.645,1,39.457825,53.594350,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.0,83.355,16.6,83.4,16.6%,83.4%,6.734025
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.000000,0.000000,0.000000,-25.702388,-29.987744,0,-59.975488,37.556610,3.632234,0.030,2,30.475629,44.635696,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.970,0.0,100.0,<1%,>99%,11.457693
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",1114009.06,1390904.93,2504913.99,44.472947,55.527053,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.171894,1,0,46.957206,0.166507,46.963324,0.166507,East South Central,2026,0.0,0.0,0.0,1,102,5,1977.842975,0.166507,0.408053,0.006119,-3.871521,-5.527053,1,-11.054107,49.488434,3.490064,44.265,3,42.602044,56.305934,1.030,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.0,55.735,44.3,55.7,44.3%,55.7%,13.441295

In [76]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3310044.97,5430961.94,39.052326,60.947674,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.171894,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1525.084178,0.0,0.0,0.0,-3.738711,-10.947674,-1,-21.895348,46.52045,3.601410,16.645,1,39.457825,53.594350,0.065,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+7.0,83.355,16.6,83.4,16.6%,83.4%,6.734025,D+6.7
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",184951.75,739240.65,924192.40,20.012256,79.987744,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.171894,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,400.490394,0.0,0.0,0.0,-25.702388,-29.987744,0,-59.975488,37.55661,3.632234,0.030,2,30.475629,44.635696,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.9,99.970,0.0,100.0,<1%,>99%,11.457693,D+11.5

In [77]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
413    5507
414    5508
415    5401
416    5402
417    5600
Name: geoid, Length: 418, dtype: int64

In [78]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['y_pred'] = np.full(dem_uclen, 100)
dem_uncont['swing_24_to_26'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_24_to_26_swing'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                      x['dem_inc_any'], x['rep_inc_any']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Mike Thompson/Eric J..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Doris Matsui/Mai Van..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Scott Weiner/Connie ..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Lateefah Simon* (D)<..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,True,False,CA,14,6,614,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Aisha Wahab/Melissa ..."

In [79]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['y_pred'] = np.full(rep_uclen, 0)
rep_uncont['swing_24_to_26'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_24_to_26_swing'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                       x['dem_inc_any'], x['rep_inc_any']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0,NaN,NaN,0%,100%,R+100,,"<b style=""color:#366bbf;"">Not Contested (D)</b..."

In [80]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'geoid', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 16)

In [81]:
tab_data = data[['cd', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Bill Hill', 'Kevin Kiley'] else x)
tab_data = tab_data.rename({
    'cd': 'District',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,District,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,AK-AL,Bill Hill (Ind),Nick Begich,Likely R,"<p style=""color:blue;"">16.6%</p>","<p style=""color:red;"">83.4%</p>",R+7.0,D+6.7,0.065
1,AL-01,Clyde Jones Jr.,Jerry Carl,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+24.9,D+11.5,0.000
2,AL-02,Shomari Figures,Rhett Marques,Tossup,"<p style=""color:blue;"">44.3%</p>","<p style=""color:red;"">55.7%</p>",R+1.0,D+13.4,1.030
3,AL-03,Lee McInnis,Mike Rogers,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+38.9,D+8.2,0.000
4,AL-04,Amanda Pusczek,Robert Aderholt,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+58.6,D+8.4,0.000

In [82]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

4.898641534994358

In [83]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

                 vars           x
0     means_seats_tot  243.796350
1  chamber_win_chance   84.635000
0             sv_bias    4.898642

In [84]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [85]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 435 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Win Probability  Seat Share
0    Democrats           84.635   243.79635
1  Republicans           15.365   191.20365

In [86]:
## Alert when there's a rating change
rating_ts = output_ts[output_ts['type'] == 'chance']
rating_ts['rating'] = rating_ts['y'].map(get_rating)
rating_ts['date'] = pd.to_datetime(rating_ts['date'])
rating_ts.head()

today_date = rating_ts['date'].max()
yesterday = rating_ts[rating_ts['date'] != today_date]['date'].max()

today_ratings = rating_ts[rating_ts['date'] == today_date]
yester_ratings = rating_ts[rating_ts['date'] == yesterday]
compare_df = pd.merge(left=today_ratings, right=yester_ratings, on='geo', how='left', suffixes=['_t', '_y'])
compare_df.head()

,date_t,y_t,geo,type_t,rating_t,date_y,y_y,type_y,rating_y
0,2026-10-23,84.635,US House,chance,Likely D,2026-10-22,85.315,chance,Likely D
1,2026-10-23,16.645,AK-AL,chance,Likely R,2026-10-22,17.300,chance,Likely R
2,2026-10-23,0.030,AL-01,chance,Safe R,2026-10-22,0.030,chance,Safe R
3,2026-10-23,44.265,AL-02,chance,Tossup,2026-10-22,44.205,chance,Tossup
4,2026-10-23,0.000,AL-03,chance,Safe R,2026-10-22,0.000,chance,Safe R

In [87]:
## This is the cell that actually alerts when there's a rating change
if any(compare_df['rating_t'] != compare_df['rating_y']):
    changes_df = compare_df[compare_df['rating_t'] != compare_df['rating_y']][['geo', 'rating_y', 'rating_t']]
    print(changes_df)
else:
    print("No rating changes today!")

       geo       rating_y       rating_t
67   CO-03         Lean R         Tilt R
254  NV-01         Safe D  Very Likely D
401  WA-03  Very Likely D       Likely D

In [88]:
for i in range(changes_df.shape[0]):
    seat = changes_df.iloc[i, :]['geo']
    rating_y = changes_df.iloc[i, :]['rating_y']
    rating_t = changes_df.iloc[i, :]['rating_t']
    print(f'{seat}: {rating_y} --> {rating_t}')

CO-03: Lean R --> Tilt R
NV-01: Safe D --> Very Likely D
WA-03: Very Likely D --> Likely D

In [89]:
changes_df.shape

(3, 3)

In [90]:
if any(compare_df['rating_t'] != compare_df['rating_y']):
    for i in range(changes_df.shape[0]):
        seat = changes_df.iloc[i, :]['geo']
        rating_y = changes_df.iloc[i, :]['rating_y']
        rating_t = changes_df.iloc[i, :]['rating_t']
        print(f'{seat}: {rating_y} --> {rating_t}')

CO-03: Lean R --> Tilt R
NV-01: Safe D --> Very Likely D
WA-03: Very Likely D --> Likely D

In [91]:
## Mini-widget: what is the chance of Dems/Reps winning House if X congressional district is won by Dems/Reps?
def det_winner(post, cd, dem_winner=True):
    '''
    :param post: Posterior simulation matrix.
    :param cd: Congressional district.
    :param dem_winner: Whether or not we set Dems or Reps to win `cd`. True if Dem win is fixed, False if Rep win is fixed.
    '''
    winners = []
    seats = []
    post_ut = post.T
    if dem_winner:
        post_ut = post_ut[post_ut[cd] > 0]
    else:
        post_ut = post_ut[post_ut[cd] < 0]
    post_case = post_ut.T
    for i in range(post_case.shape[0]):
        sim = post_case.iloc[:, i]
        dem_seats = np.sum(sim > 0)
        if dem_seats >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
            winners.append(1)
        else: # Republicans win House in this draw
            winners.append(0)
        seats.append(dem_seats)
    dem_win_chance = np.mean(np.array(winners)) * 100
    dem_mean_seats = np.mean(np.array(seats)) + dem_uncont.shape[0]
    return dem_win_chance, dem_mean_seats

cd = 'MI-07'
dem_winner = True
det_winner(post, cd, dem_winner)

(np.float64(92.82296650717703), np.float64(250.46172248803828))

In [92]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')