In [91]:
import warnings
warnings.filterwarnings('ignore')

In [92]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [93]:
pd.set_option('display.max_columns', 100)

In [94]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [95]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        197  Republicans
1        294    Democrats
2        214  Republicans
3        194  Republicans
4        288    Democrats
...      ...          ...
19995    208  Republicans
19996    283    Democrats
19997    240    Democrats
19998    257    Democrats
19999    214  Republicans

[20000 rows x 2 columns]

In [96]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    148      1  0.005  Republicans
1    165      1  0.005  Republicans
2    173      3  0.015  Republicans
3    176      2  0.010  Republicans
4    177      3  0.015  Republicans

In [97]:
np.unique(seat_sims['seats']).shape[0]

183

In [98]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [99]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date           y       geo       type
0  2026-08-30  229.365800  US House      seats
1  2026-08-30   66.120000  US House     chance
2  2026-08-30   22.784344  US House   seats_sd
3  2026-08-30   44.972806     AK-AL     y_pred
4  2026-08-30    3.555839     AK-AL  y_pred_sd

In [100]:
chance_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="House Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser

In [101]:
seats_over_time = output_ts[(output_ts['geo'] == 'US House') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 435 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-08-30'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 435]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser

In [102]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [103]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [104]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,19950,19951,19952,19953,19954,19955,19956,19957,19958,19959,19960,19961,19962,19963,19964,19965,19966,19967,19968,19969,19970,19971,19972,19973,19974,19975,19976,19977,19978,19979,19980,19981,19982,19983,19984,19985,19986,19987,19988,19989,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,-8.626718,0.811486,-6.080858,-12.509700,1.079411,-7.022766,2.252692,-8.182968,-0.633474,-0.786523,-6.594074,-3.317423,-4.542679,-6.810639,-1.798707,-2.112772,-4.578311,-0.573033,-1.283336,2.105820,-6.425834,-2.193407,-1.718551,1.575477,2.033057,-7.241650,-1.250431,-4.643193,-2.497774,-3.384672,-3.157218,-9.521513,-1.232755,-1.993676,0.032883,-8.323200,-9.994170,-2.966546,-1.288402,-1.225402,-1.885423,-3.929447,-2.589564,-6.168907,-5.767817,2.026869,-3.187057,-2.041776,-5.145446,-8.184938,...,-6.157969,-2.378000,-1.849405,-5.862937,-3.810978,-5.028286,-1.775524,-5.991078,4.555645,-2.736189,-7.915338,-8.782577,-2.114582,-6.042500,-1.443346,-6.199033,1.867521,-6.590458,2.183621,-6.144901,-1.449346,-7.292484,-2.107404,-7.920880,-4.309551,-1.076413,-4.641064,-1.765441,-3.716675,-0.307383,-7.942102,1.028942,-9.758420,7.065825,-9.676542,-7.259921,-1.579999,-3.993727,-7.398145,-0.480330,-5.040703,-6.854071,-1.138723,-2.840953,0.173016,-7.959778,-1.149514,-2.917186,-7.818377,-6.058740
AL-01,-19.725004,-4.585890,-18.357364,-19.262979,-7.705561,-16.369268,-6.108722,-19.415817,-6.972664,-10.368773,-16.336803,-14.135409,-11.409267,-7.750763,-12.023456,-12.932280,-11.207676,-11.281657,-14.175487,-12.484170,-16.976225,-8.982528,-11.834804,-8.489740,-5.658096,-17.451555,-7.623326,-17.602371,-15.119519,-11.407610,-17.477777,-19.863953,-12.947670,-13.605134,-11.696346,-12.886772,-17.744448,-12.164593,-14.149236,-3.717592,-12.405610,-12.367542,-10.603149,-14.937727,-18.232537,-7.650106,-18.431300,-9.578063,-12.696714,-15.021139,...,-14.748731,-10.948980,-10.332961,-11.683840,-12.519504,-13.408583,-7.101242,-18.163413,-6.225093,-14.788387,-14.116365,-15.575566,-7.754433,-16.248180,-8.881282,-19.955057,-5.195432,-15.628789,-9.708529,-15.912951,-8.322407,-12.934393,-9.385673,-13.238397,-13.857232,-11.853694,-13.027566,-6.865244,-13.090703,-9.333996,-16.637435,-8.739165,-21.951848,-3.552474,-16.435771,-18.157904,-12.906727,-13.816916,-16.967862,-11.839226,-12.621472,-19.134026,-11.226820,-12.755903,-11.724610,-16.582138,-7.835448,-14.018385,-7.162582,-16.526045
AL-02,-8.470166,7.246890,-5.826614,-4.168915,4.882071,-3.201026,-0.845391,-2.109730,3.782014,0.981224,0.628299,0.261848,-2.506278,-0.936512,-2.125639,-0.422317,1.276832,-1.766217,2.689893,-0.146241,-5.014490,-1.296124,-0.552190,1.498129,3.958088,-6.100860,3.878413,-1.478454,-1.754169,4.974382,0.872312,-3.731401,-3.756553,3.367894,-2.805595,1.063120,-6.319672,-0.874632,-2.961991,3.164941,-0.363559,-0.632352,4.642993,-2.838133,-1.158770,7.665403,-6.188664,0.884222,-1.033666,0.131141,...,3.788491,1.336927,1.080616,1.339102,0.220113,-0.602217,-0.404697,-3.462436,1.199722,-0.220169,-2.273360,-4.113182,1.465712,-7.397229,3.117053,-6.459906,4.277685,-2.551048,2.801130,0.587644,-1.220392,4.055275,4.196336,-1.332676,-3.600857,0.929202,-2.110282,2.615745,3.025610,3.242019,-7.670956,-2.324709,-6.250445,5.442034,-0.618067,4.966301,-0.116391,-3.326862,-2.152409,3.074718,-2.141943,-5.866705,-1.797225,0.707260,4.745485,-3.103215,4.773985,-1.853980,3.590871,-3.520947
AL-03,-23.872070,-16.311170,-24.958095,-26.574689,-16.823754,-22.852400,-14.489155,-17.949550,-16.760149,-18.311303,-17.362679,-20.701897,-19.583545,-14.434138,-19.346431,-17.826789,-21.026503,-21.326280,-21.160370,-15.415243,-24.728460,-17.929625,-18.034971,-12.203137,-12.246408,-26.256859,-14.377625,-24.115178,-23.449136,-18.966823,-21.423765,-23.889636,-15.503014,-20.993131,-15.186418,-17.044908,-24.661337,-16.942584,-21.854284,-17.643083,-21.898650,-20.254754,-17.553711,-21.960865,-21.699070,-15.440550,-21.308025,-17.250957,-20.538363,-27.037973,...,-22.060042,-18.059014,-17.742708,-21.752803,-19.328270,-18.772027,-19.909689,-25.721647,-12.923759,-21.636100,-24.220957,-23.183364,-15.653794,-22.288292,-12.196386,-25.845196,-15.188755,-18.012206,-14.487576,-24.913366,-16.764678,-18.367974,-15.899161,-22.504910,-20.868107,-15.185918,-17.349567,-18.585811,-21.465026,-18.416686,-24.054478,-16.289104,-26.410505,-10.480857,-26.666597,-25.231903,-18.620330,-17.460722,-23.538820,-18.189830,-17.422359,-25.032374,-19.255258,-21.590916,-15.363256,-25.232465,-15.130935,-18.935744,-18.061308,-22.960525
AL-04,-35.950703,-24.630358,-30.153815,-34.638513,-27.180283,-33.248029,-24.031218,-31.425186,-29.835252,-26.170434,-26.309538,-30.109621,-25.964226,-30.164903,-30.307450,-32.118748,-27.352284,-30.774090,-31.427977,-28.537797,-32.825384,-27.672933,-28.061007,-24.431083,-22.760860,-36.245026,-25.254087,-34.565059,-31.762320,-26.907890,-32.454909,-36.409029,-30.748618,-25.121974,-28.864671,-29.544248,-33.172703,-27.253501,-33.355933,-20.497823,-27.722742,-32.936798,-28.807193,-31.231037,-31.717923,-22.983964,-30.241513,-24.789341,-28.991782,-36.453368,...,-30.515460,-26.849047,-25.934622,-30.210755,-27.654572,-28.360801,-30.007447,-34.730161,-22.772261,-29.861847,-34.167247,-31.650570,-25.995058,-30.600361,-26.280319,-37.303528,-25.357927,-31.469547,-28.482416,-29.801173,-28.083573,-28.663729,-24.814253,-31.299884,-32.614931,-29.707376,-28.534313,-25.504791,-27.501862,-25.762949,-32.953986,-26.201272,-37.395388,-25.231984,-32.651454,-33.359316,-29.481865,-28.110292,-33.754669,-27.127077,-29.810817,-34.122532,-30.202582,-31.680136,-24.012882,-32.518974,-27.677153,-31.621700,-27.612758,-32.069255

In [105]:
sim_corr = post_untransp.corr()

In [106]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,...,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.713942,0.479028,0.734582,0.725261,0.715896,0.733070,0.492181,0.735145,0.738145,0.734127,0.737767,0.479926,0.484024,0.483815,0.497712,0.697664,0.719231,0.719967,0.720129,0.736845,0.698119,0.501036,0.507048,0.740282,0.730209,0.566143,0.505754,0.510337,0.503671,0.480664,0.694454,0.558495,0.501962,0.495628,0.700402,0.505137,0.738366,0.731973,0.505567,0.514371,0.704261,0.481577,0.507795,0.479402,0.517816,0.548664,0.506309,0.564703,0.507604,...,0.735017,0.718137,0.542047,0.501188,0.502080,0.702390,0.741222,0.699158,0.529861,0.501884,0.701448,0.520288,0.490440,0.493573,0.488365,0.729872,0.719188,0.719950,0.738959,0.546425,0.501983,0.474090,0.717225,0.728177,0.484159,0.505839,0.734244,0.484299,0.697856,0.527313,0.504438,0.507733,0.481827,0.700889,0.534825,0.480066,0.498957,0.505884,0.565458,0.490793,0.737654,0.536587,0.568887,0.732478,0.738421,0.697349,0.722601,0.731101,0.714282,0.696652
AL-01,0.713942,1.000000,0.486129,0.740752,0.732929,0.725579,0.739466,0.499589,0.738821,0.742811,0.740922,0.743152,0.486143,0.487362,0.495589,0.503120,0.701375,0.723072,0.723666,0.721328,0.739240,0.699967,0.505877,0.510523,0.746282,0.728685,0.569847,0.518033,0.512636,0.507784,0.493399,0.697516,0.566317,0.506635,0.507086,0.705290,0.512176,0.739039,0.732479,0.509078,0.515954,0.700805,0.485440,0.510426,0.483763,0.532038,0.560897,0.513759,0.575921,0.510561,...,0.736746,0.721322,0.556133,0.508998,0.502857,0.699233,0.746128,0.703588,0.541373,0.509443,0.704205,0.525721,0.495805,0.504645,0.493473,0.735318,0.724662,0.723909,0.742170,0.553114,0.513630,0.487784,0.711953,0.729445,0.483517,0.509493,0.741114,0.487432,0.705779,0.533919,0.505382,0.511758,0.485137,0.706734,0.541199,0.487983,0.504305,0.510117,0.573945,0.496749,0.740018,0.545083,0.575393,0.737141,0.746275,0.703746,0.722682,0.742759,0.720571,0.705058
AL-02,0.479028,0.486129,1.000000,0.489831,0.485543,0.477736,0.490980,0.700684,0.487335,0.495591,0.487764,0.496212,0.670141,0.665950,0.674860,0.691398,0.638313,0.475587,0.482537,0.475661,0.493019,0.630896,0.700142,0.706974,0.498262,0.488000,0.579731,0.698082,0.699961,0.520629,0.666528,0.633759,0.569609,0.696050,0.702261,0.635994,0.700272,0.492730,0.484403,0.706382,0.708995,0.635439,0.675458,0.701737,0.669826,0.536730,0.556585,0.704710,0.578163,0.707377,...,0.493794,0.480232,0.552319,0.694204,0.697873,0.631823,0.493190,0.635488,0.543899,0.697233,0.635162,0.534221,0.682775,0.680659,0.675366,0.485325,0.471225,0.478566,0.493233,0.551222,0.691616,0.666600,0.472372,0.485364,0.667409,0.709223,0.490591,0.669843,0.633049,0.540932,0.701677,0.699314,0.678745,0.639721,0.543472,0.663838,0.695183,0.695535,0.578555,0.684098,0.487190,0.544950,0.576863,0.488328,0.493113,0.636091,0.478680,0.493543,0.479111,0.640098
AL-03,0.734582,0.740752,0.489831,1.000000,0.754892,0.739591,0.765080,0.509794,0.753491,0.761229,0.759021,0.759611,0.497598,0.498146,0.500190,0.513966,0.717172,0.737112,0.736015,0.740271,0.760618,0.720259,0.515224,0.517690,0.761935,0.750709,0.577490,0.518051,0.525879,0.523221,0.498711,0.714552,0.571279,0.512175,0.512804,0.724895,0.520748,0.757462,0.751765,0.516591,0.526717,0.719283,0.498137,0.518963,0.495024,0.540714,0.570789,0.519238,0.582001,0.524387,...,0.757160,0.740231,0.558605,0.513786,0.514848,0.715483,0.766256,0.720168,0.543652,0.515994,0.721199,0.535972,0.502882,0.512711,0.502626,0.752545,0.740150,0.738596,0.760002,0.560104,0.514167,0.493042,0.735951,0.746021,0.494158,0.517738,0.758805,0.495845,0.721008,0.543016,0.517026,0.524586,0.489120,0.721105,0.551819,0.491518,0.508642,0.521979,0.581156,0.507517,0.758701,0.555161,0.579792,0.753420,0.761314,0.720780,0.741362,0.756320,0.735512,0.721676
AL-04,0.725261,0.732929,0.485543,0.754892,1.000000,0.731125,0.745417,0.507653,0.749779,0.746224,0.750108,0.749722,0.493108,0.492491,0.500168,0.504597,0.708891,0.727392,0.728953,0.728187,0.752188,0.709019,0.509526,0.517987,0.748647,0.735998,0.569743,0.518259,0.518676,0.514871,0.492811,0.704934,0.571627,0.511713,0.508790,0.715445,0.512833,0.745086,0.735592,0.514407,0.521390,0.712370,0.492049,0.517279,0.482991,0.532658,0.565445,0.513626,0.574718,0.521484,...,0.746086,0.729304,0.550277,0.511495,0.508062,0.708793,0.755399,0.715248,0.543050,0.514377,0.713264,0.525710,0.498823,0.504879,0.497260,0.740061,0.733317,0.727789,0.749127,0.553121,0.515088,0.485411,0.725177,0.739772,0.488366,0.512635,0.750555,0.494100,0.710121,0.537076,0.507403,0.518588,0.490672,0.713350,0.547112,0.489103,0.509781,0.516374,0.571561,0.497246,0.745640,0.547472,0.574619,0.745061,0.748513,0.710678,0.727078,0.745218,0.725684,0.711920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WI-07,0.697349,0.703746,0.636091,0.720780,0.710678,0.702154,0.716431,0.656581,0.717577,0.719320,0.714468,0.724138,0.644384,0.636949,0.646605,0.662351,0.842173,0.697788,0.709859,0.699634,0.720819,0.839326,0.666095,0.675135,0.724295,0.712330,0.552074,0.670753,0.676498,0.499109,0.638910,0.840690,0.546072,0.666401,0.665798,0.843426,0.670587,0.718522,0.708058,0.669517,0.680177,0.842506,0.642957,0.668756,0.638280,0.517346,0.541332,0.675199,0.555215,0.675302,...,0.720501,0.698738,0.532230,0.663554,0.663047,0.839263,0.725053,0.842253,0.522814,0.668149,0.843688,0.509293,0.652863,0.654220,0.652400,0.713594,0.704129,0.701322,0.722531,0.538455,0.669075,0.637344,0.697415,0.713701,0.636681,0.670946,0.721326,0.642484,0.843251,0.521412,0.668041,0.673762,0.642603,0.844937,0.529791,0.640600,0.663410,0.668716,0.556425,0.654259,0.719071,0.530002,0.556585,0.716268,0.724721,1.000000,0.702151,0.721475,0.694530,0.845389
WI-08,0.722601,0.722682,0.478680,0.741362,0.727078,0.718297,0.737288,0.496641,0.743669,0.741772,0.740228,0.743397,0.486645,0.490199,0.488599,0.497221,0.706391,0.723204,0.718649,0.719094,0.741252,0.703514,0.509215,0.506741,0.745253,0.738339,0.569465,0.509776,0.514679,0.510475,0.492632,0.698725,0.564191,0.507675,0.505112,0.705053,0.508359,0.738451,0.731685,0.512113,0.520775,0.705810,0.487183,0.507983,0.484404,0.530162,0.554927,0.512019,0.566394,0.515914,...,0.740654,0.721392,0.552495,0.506009,0.502615,0.702556,0.744092,0.704640,0.540045,0.503865,0.704782,0.525459,0.499244,0.503655,0.492192,0.733533,0.721949,0.723607,0.742277,0.554389,0.511484,0.483708,0.714939,0.730854,0.476500,0.508492,0.742478,0.487757,0.704315,0.531020,0.509407,0.517943,0.489140,0.707518,0.539087,0.484922,0.506844,0.513224,0.570690,0.499428,0.747627,0.557621,0.579673,0.742425,0.746073,0.702151,1.000000,0.735281,0.718607,0.701572
WV-01,0.731101,0.742759,0.493543,0.756320,0.745218,0.736022,0.758379,0.512532,0.750834,0.755381,0.753614,0.756791,0.501165,0.505556,0.504725,0.513052,0.719178,0.730019,0.739265,0.738041,0.754650,0.717782,0.523229,0.524851,0.761641,0.745810,0.580973,0.523665,0.522964,0.514704,0.501546,0.715534,0.573049,0.516973,0.517860,0.722109,0.524298,0.754739,0.745908,0.523256,0.531803,0.721917,0.500268,0.520209,0.493570,0.538440,0.568065,0.522247,0.581104,0.528586,...,0.757304,0.737435,0.562797,0.512970,0.515802,0.718065,0.761159,0.721721,0.548455,0.519838,0.721130,0.533251,0.510445,0.514210,0.502464,0.750933,0.736252,0.737789,0.758747,0.558223,0.521181,0.493728,0.728497,0.748638,0.494337,0.524495,0.758003,0.498825,0.719520,0.543352,0.519860,0.524708,0.494826,0.723017,0.551379,0.498370,0.511896,0.522939,0.581462,0.508148,0.757661,0.559963,0.578676,0.753196,0.760432,0.721475,0.735281,1.000000,0.743927,0.723500
WV-02,0.714282,0.720571,0.479111,0.735512,0.725684,0.715316,0.730498,0.495069,0.737116,0.742265,0.733346,0.743088,0.485023,0.479909,0.487057,0.501700,0.694145,0.719391,0.719484,0.716437,0.737258,0.697493,0.502606,0.510593,0.740354,0.723974,0.565342,0.507160,0.509546,0.508443,0.486080,0.692454,0.566060,0.500242,0.501955,0.698347,0.504821,0.740627,0.728148,0.502010,0.510708,0.697090,0.484879,0.507783,0.479607,0.528244,0.554269,0.508405,0.571608,0.510703,...,0.734969,0.723028,0.547878,0.501559,0.503393,0.698804,0.742404,0.696050,0.538593,0.505007,0.699203,0.524004,0.490812,0.498563,0.491935,0.726703,0.717208,0.718239,0.739482,0.549481,0.507659,0.480774,0.712160,0.726755,0.482421,0.506523,0.740676,0.486510,0.699524,0.530203,0.504504,0.510603,0.479888,0.699010,0.540795,0.486069,0.498802,0.510183,0.573407,0.496886,0.736621,0.546597,0.567680,0.731913,0.739883,0.694530,0.718607,0.743927,1.000000,0.699100
WY-AL,0.696652,0.705058,0.640098,0.721676,0.711920,0.702826,0.715599,0.656629,0.717894,0.722201,0.715773,0.727265,0.646000,0.638245,0.643123,0.661455,0.842450,0.698837,0.708472,0.701235,0.719875,0.839050,0.668848,0.672394,0.724019,0.710698,0.551834,0.673229,0.677618,0.495978,0.640077,0.838904,0.548000,0.664616,0.665473,0.843813,0.668386,0.718040,0.709562,0.666979,0.679309,0.843239,0.644180,0.670547,0.637325,0.515935,0.541988,0.672313,0.554883,0.678347,...,0.723051,0.700312,0.536459,0.664191,0.660764,0.838139,0.727997,0.846946,0.522586,0.668612,0.842700,0.505955,0.652443,0.657598,0.649904,0.711535,0.702424,0.704287,0.721909,0.535821,0.667035,0.636065,0.697777,0.716791,0.640177,0.671181,0.723516,0.643976,0.840428,0.526494,0.668112,0.676536,0.644721,0.844504,0.528006,0.641708,0.661242,0.667743,0.557188,0.649087,0.719554,0.531300,0.557602,0.714810,0.723153,0.845389,0.701572,0.723500,0.699100,1.000000

In [107]:
post.shape

(418, 20000)

In [108]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [109]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:31<00:00, 633.58it/s]

array(['MN-01', 'TX-23', 'IA-02', ..., 'IN-05', 'TX-35', 'OH-15'],
      shape=(20000,), dtype='<U32')

In [110]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.00000,0.000000,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.625390
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.00000,0.000000,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.597240
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.42628,1,0,46.957206,0.222482,46.963324,0.222482,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.222482,0.47168,0.006119,-3.617135,-7.354225,1,-14.708451,49.468430,3.444066,43.730,3,42.676939,56.226325
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.00000,0.000000,-36.215904,-46.255299,-1,-92.510598,30.654822,3.459702,0.000,4,23.931362,37.524250
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,624541.87,640003.87,2.415923,97.584077,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.836683,0.000000,0.00000,0.000000,-56.507999,-47.584077,-1,-95.168154,20.833203,3.504292,0.000,5,14.002603,27.731955

In [111]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.00000,0.000000,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.625390,0.085
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.00000,0.000000,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.597240,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.42628,1,0,46.957206,0.222482,46.963324,0.222482,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.222482,0.47168,0.006119,-3.617135,-7.354225,1,-14.708451,49.468430,3.444066,43.730,3,42.676939,56.226325,1.215
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.00000,0.000000,-36.215904,-46.255299,-1,-92.510598,30.654822,3.459702,0.000,4,23.931362,37.524250,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,624541.87,640003.87,2.415923,97.584077,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.836683,0.000000,0.00000,0.000000,-56.507999,-47.584077,-1,-95.168154,20.833203,3.504292,0.000,5,14.002603,27.731955,0.000

In [112]:
data.sort_values('tipping_point_prob', ascending=False).head(10)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
193,193,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",2920366.45,1718514.96,4638881.41,62.954109,37.045891,Michigan,MI-10,76.551128,2.316124,5.150984,0.123322,13.269372,29.340000,-2.765891,-2.592362,-2.635744,99.999226,46.657584,0.987401,-9.42628,0,0,45.000000,0.086500,45.000000,0.086500,East North Central,2026,0.0,0.00000,0.00000,26,2610,2,3963.219815,0.086500,0.294109,-1.460326e-07,4.154792,12.954109,0,25.908218,52.103265,3.595864,72.250,194,44.999803,59.193937,3.125
98,98,FL-22,Pia Dandiya,Casey Askar,False,False,FL,22,"DANDIYA, PIA","ASKAR, CASEY",3095902.57,322072.40,3417974.97,90.577099,9.422901,Florida,FL-22,53.931205,26.984941,3.703933,0.199203,13.186062,27.190634,-0.817400,-4.551960,-3.618320,91.180168,44.697986,0.987401,-9.42628,0,0,46.286766,0.235992,44.430149,0.235992,South Atlantic,2026,0.0,0.00000,0.00000,12,1222,6,8204.210851,0.235992,0.485790,-1.856617e+00,2.189639,40.577099,0,81.154198,52.381959,3.599343,74.875,99,45.270832,59.528546,2.890
183,183,ME-02,Matt Dunlap,Paul LePage,False,False,ME,2,"DUNLAP, MATT","LEPAGE, PAUL",2472092.35,1645926.41,4118018.76,60.031109,39.968891,Maine,ME-02,94.623805,1.542589,0.598455,0.552005,0.848532,26.920000,-5.410176,-3.867301,-4.253020,26.830060,45.382645,0.987401,-9.42628,0,0,50.069480,1.795674,46.458349,1.795674,New England,2026,0.0,0.25284,-0.25284,23,2302,3,3603.734105,1.795674,1.340028,-3.611131e+00,0.920240,10.031109,0,20.062219,51.869739,3.598175,70.110,184,44.755083,59.019532,2.845
289,289,OH-07,Brian Poindexter,Max Miller,False,True,OH,7,"POINDEXTER, BRIAN","MILLER, MAX",2703344.16,992252.30,3695596.46,73.150415,26.849585,Ohio,OH-07,89.432935,3.348946,2.187434,0.068208,3.218146,26.556779,-7.118675,-4.823517,-5.397307,83.893826,44.426429,0.987401,-9.42628,0,1,47.301979,0.130874,39.605340,0.130874,East North Central,2026,0.0,1.00000,-1.00000,39,3907,2,5350.983265,0.130874,0.361764,-7.696639e+00,-1.368334,23.150415,-1,46.300831,52.175551,3.547401,72.970,290,45.162600,59.054504,2.635
386,386,VA-01,Shannon Taylor,Rob Wittman,False,True,VA,1,"TAYLOR, SHANNON LEIGH","WITTMAN, ROBERT J. MR.",3265447.34,1867234.51,5132681.85,63.620685,36.379315,Virginia,VA-01,75.537803,4.124527,4.097593,0.133339,13.351012,46.900000,-5.404597,-1.752158,-2.665268,73.780628,47.497788,0.987401,-9.42628,0,1,49.033047,0.551108,46.241737,0.551108,South Atlantic,2026,0.0,0.00000,0.00000,51,5101,2,4047.591531,0.551108,0.742367,-2.791310e+00,4.095743,13.620685,-1,27.241370,51.901885,3.424925,71.305,387,45.205354,58.610019,2.605
314,314,PA-07,Bob Brooks,Ryan Mackenzie,False,True,PA,7,"BROOKS, BOB","MACKENZIE, RYAN EDWARD",3916290.29,1840430.27,5756720.56,68.029883,31.970117,Pennsylvania,PA-07,75.458946,15.481046,2.435986,0.030199,4.952274,31.050000,-1.956264,-0.869379,-1.141100,81.633883,48.380567,0.987401,-9.42628,0,1,45.002910,0.398328,40.004365,0.398328,Mid-Atlantic,2026,0.0,0.00000,0.00000,42,4207,2,4628.065048,0.398328,0.631132,-4.998545e+00,7.144080,18.029883,-1,36.059767,52.149661,3.508316,73.100,315,45.185024,59.062270,2.595
190,190,MI-07,William Lawrence,Tom Barrett,False,True,MI,7,"LAWRENCE, WILLIAM","BARRETT, THOMAS MORE",3382652.32,4300590.57,7683242.89,44.026362,55.973638,Michigan,MI-07,85.239895,4.803904,1.944855,0.170025,5.279273,36.270000,-2.003691,0.098125,-0.427329,68.756305,49.348071,0.987401,-9.42628,0,1,48.971702,0.104933,46.971702,0.104933,East North Central,2026,0.0,0.00000,0.00000,26,2607,2,1938.320542,0.104933,0.323933,-2.000000e+00,8.571622,-5.973638,-1,-11.947276,52.182455,3.502461,73.685,191,45.320346,59.107233,2.520
229,229,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE","BALKCOM, JENNIFER",4742228.95,92169.44,4834398.39,98.093466,1.906534,North Carolina,NC-11,88.740422,3.902084,0.797632,1.120840,3.305854,24.807640,-7.843347,-4.057125,-5.003681,49.294326,45.192821,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.0,0.00000,0.00000,37,3711,3,9622.328108,0.000000,0.000000,0.000000e+00,-0.581081,48.093466,0,96.186932,51.653460,3.613194,67.740,230,44.578881,58.805698,2.505
37,37,CA-22,Randy Villegas,David Valadao,False,True,CA,22,"VILLEGAS, RANDY","VALADAO, DAVID",4723984.35,2041081.96,6765066.31,69.829092,30.170908,California,CA-22,22.131732,64.469110,4.924433,0.538078,6.308791,6.196120,6.443675,-0.178428,1.477097,85.545753,49.071518,0.987401,-9.42628,0,1,48.000000,0.015050,44.000000,0.015050,Pacific,2026,0.0,0.00000,0.00000,6,622,4,4876.102033,0.015050,0.122677,-4.000000e+00,12.380474,19.829092,-1,39.658183,52.354243,3.461559,75.390,38,45.517989,59.128345,2.485
123,123,IA-03,Sarah Trone Garriott,Zach Nunn,False,True,IA,3,"TRONE GARRIOTT, SARAH","NUNN, ZACH",6857610.23,1334009.44,8191619.67,83.714949,16.285051,Iowa,IA-03,86.341081,5.022950,2.732262,0.063009,3.929259,35.410000,-2.445778,-1.482072,-1.722998,77.628515,47.767874,0.987401,-9.42628,0,1,42.000000,0.000583,48.000000,0.000583,West North Central,2026,0.0,0.00000,0.00000,19,1903,2,7008.192688,0.000583,0.024149,6.000000e+00,5.980283,33.714949,-1,67.429898,52.511804,3.498620,76.405,124,45.620777,59.473574,2.470

In [113]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [114]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.00000,0.000000,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.625390,0.085,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.00000,0.000000,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.597240,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.42628,1,0,46.957206,0.222482,46.963324,0.222482,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.222482,0.47168,0.006119,-3.617135,-7.354225,1,-14.708451,49.468430,3.444066,43.730,3,42.676939,56.226325,1.215,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",60787.05,1562494.77,1623281.82,3.744701,96.255299,Alabama,AL-03,74.925713,2.047228,0.853803,0.164703,19.752354,15.301623,-22.977818,-22.768849,-22.821092,48.894607,26.481097,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,103,5,14.022785,0.000000,0.00000,0.000000,-36.215904,-46.255299,-1,-92.510598,30.654822,3.459702,0.000,4,23.931362,37.524250,0.000,Safe R,"<b style=""color:#366bbf;"">Lee McInnis (D)</b> ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",15462.00,624541.87,640003.87,2.415923,97.584077,Alabama,AL-04,86.997080,3.646458,0.489492,0.174054,6.737716,13.622184,-33.634273,-32.744762,-32.967139,33.245792,16.505184,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,104,3,5.836683,0.000000,0.00000,0.000000,-56.507999,-47.584077,-1,-95.168154,20.833203,3.504292,0.000,5,14.002603,27.731955,0.000,Safe R,"<b style=""color:#366bbf;"">Amanda Pusczek (D)</..."

In [115]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.00000,0.000000,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.625390,0.085,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.00000,0.000000,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.597240,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.42628,1,0,46.957206,0.222482,46.963324,0.222482,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.222482,0.47168,0.006119,-3.617135,-7.354225,1,-14.708451,49.468430,3.444066,43.730,3,42.676939,56.226325,1.215,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R)

In [116]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.0,0.0,0.0,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.62539,0.085,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.0,0.0,0.0,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.59724,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,

In [117]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.00000,0.000000,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.625390,0.085,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.00000,0.000000,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.597240,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.8
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.42628,1,0,46.957206,0.222482,46.963324,0.222482,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.222482,0.47168,0.006119,-3.617135,-7.354225,1,-14.708451,49.468430,3.444066,43.730,3,42.676939,56.226325,1.215,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.1

In [118]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.00000,0.000000,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.625390,0.085,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7,82.730,17.3,82.7,17.3%,82.7%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.00000,0.000000,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.597240,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.8,99.985,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.42628,1,0,46.957206,0.222482,46.963324,0.222482,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.222482,0.47168,0.006119,-3.617135,-7.354225,1,-14.708451,49.468430,3.444066,43.730,3,42.676939,56.226325,1.215,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.1,56.270,43.7,56.3,43.7%,56.3%

In [119]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.000000,0.000000,0.000000,0.000000,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.000000,0.00000,0.000000,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.625390,0.085,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7,82.730,17.3,82.7,17.3%,82.7%,7.029694
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.000000,0.000000,0.000000,0.000000,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.000000,0.00000,0.000000,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.597240,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.8,99.985,0.0,100.0,<1%,>99%,11.541980
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",982156.04,1320899.88,2303055.92,42.645775,57.354225,Alabama,AL-02,53.493739,2.691740,1.032138,0.183181,40.524512,16.170153,-6.640350,-6.482160,-6.521708,56.333429,42.767786,0.987401,-9.42628,1,0,46.957206,0.222482,46.963324,0.222482,East South Central,2026,0.0,0.0,0.0,1,102,5,1818.662104,0.222482,0.47168,0.006119,-3.617135,-7.354225,1,-14.708451,49.468430,3.444066,43.730,3,42.676939,56.226325,1.215,Tossup,"<b style=""color:#366bbf;"">Shomari Figures* (D)...",(R),AL-02,(D),False,True,Flip,R+1.1,56.270,43.7,56.3,43.7%,56.3%,13.401288

In [120]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,state,district_x,cvap_white_pct,cvap_hisp_pct,cvap_aapi_pct,cvap_natam_pct,cvap_black_pct,college,lean_20,lean_24,pvi,urban_pct,dem_2p_24,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,fips,geoid,demo_cluster,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",2120916.97,3248372.14,5369289.11,39.500890,60.499110,Alaska,AK-00,64.463948,6.051383,6.481397,12.640423,3.077471,30.750000,-7.531684,-6.096509,-6.455302,64.899487,43.153437,0.987401,-9.42628,0,1,0.0,0.0,0.0,0.0,Pacific,2026,0.0,0.0,0.0,2,200,5,1560.320289,0.0,0.0,0.0,-3.484325,-10.499110,-1,-20.998221,46.668284,3.552111,17.270,1,39.663773,53.62539,0.085,Likely R,"<b style=""color:#792ba6;"">Bill Hill (I)</b> vs...",(R),AK-AL,(R),True,False,,R+6.7,82.730,17.3,82.7,17.3%,82.7%,7.029694,D+7.0
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",174437.62,735091.98,909529.60,19.178883,80.821117,Alabama,AL-01,69.156017,2.677114,1.299003,0.469439,24.385648,17.996871,-17.482017,-17.422182,-17.437141,68.324941,31.827764,0.987401,-9.42628,0,0,0.0,0.0,0.0,0.0,East South Central,2026,0.0,0.0,0.0,1,101,5,367.829562,0.0,0.0,0.0,-25.448003,-30.821117,0,-61.642234,37.598754,3.556293,0.015,2,30.692222,44.59724,0.000,Safe R,"<b style=""color:#366bbf;"">Clyde Jones Jr. (D)<...",(R),AL-01,(R),True,False,,R+24.8,99.985,0.0,100.0,<1%,>99%,11.541980,D+11.5

In [121]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
413    5507
414    5508
415    5401
416    5402
417    5600
Name: geoid, Length: 418, dtype: int64

In [122]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['y_pred'] = np.full(dem_uclen, 100)
dem_uncont['swing_24_to_26'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_24_to_26_swing'] = np.full(dem_uclen, float('nan')) # Placeholder
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                      x['dem_inc_any'], x['rep_inc_any']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Mike Thompson/Eric J..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Doris Matsui/Mai Van..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Scott Weiner/Connie ..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Lateefah Simon* (D)<..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,True,False,CA,14,6,614,Safe D,100,100,NaN,NaN,100%,0%,D+100,,"<b style=""color:#366bbf;"">Aisha Wahab/Melissa ..."

In [123]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['y_pred'] = np.full(rep_uclen, 0)
rep_uncont['swing_24_to_26'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_24_to_26_swing'] = np.full(rep_uclen, float('nan')) # Placeholder
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                                       x['dem_inc_any'], x['rep_inc_any']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,y_pred,swing_24_to_26,disp_24_to_26_swing,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0,NaN,NaN,0%,100%,R+100,,"<b style=""color:#366bbf;"">Not Contested (D)</b..."

In [124]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'geoid', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 16)

In [125]:
tab_data = data[['cd', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Bill Hill', 'Kevin Kiley'] else x)
tab_data = tab_data.rename({
    'cd': 'District',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,District,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,AK-AL,Bill Hill (Ind),Nick Begich,Likely R,"<p style=""color:blue;"">17.3%</p>","<p style=""color:red;"">82.7%</p>",R+6.7,D+7.0,0.085
1,AL-01,Clyde Jones Jr.,Jerry Carl,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+24.8,D+11.5,0.000
2,AL-02,Shomari Figures,Rhett Marques,Tossup,"<p style=""color:blue;"">43.7%</p>","<p style=""color:red;"">56.3%</p>",R+1.1,D+13.4,1.215
3,AL-03,Lee McInnis,Mike Rogers,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+38.7,D+8.3,0.000
4,AL-04,Amanda Pusczek,Robert Aderholt,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+58.3,D+8.7,0.000

In [126]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

5.2197494394168835

In [127]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

                 vars           x
0     means_seats_tot  243.456150
1  chamber_win_chance   84.450000
0             sv_bias    5.219749

In [128]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [129]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 435 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Win Probability  Seat Share
0    Democrats            84.45   243.45615
1  Republicans            15.55   191.54385

In [130]:
## Alert when there's a rating change
rating_ts = output_ts[output_ts['type'] == 'chance']
rating_ts['rating'] = rating_ts['y'].map(get_rating)
rating_ts['date'] = pd.to_datetime(rating_ts['date'])
rating_ts.head()

today_date = rating_ts['date'].max()
yesterday = rating_ts[rating_ts['date'] != today_date]['date'].max()

today_ratings = rating_ts[rating_ts['date'] == today_date]
yester_ratings = rating_ts[rating_ts['date'] == yesterday]
compare_df = pd.merge(left=today_ratings, right=yester_ratings, on='geo', how='left', suffixes=['_t', '_y'])
compare_df.head()

,date_t,y_t,geo,type_t,rating_t,date_y,y_y,type_y,rating_y
0,2026-10-21,84.450,US House,chance,Likely D,2026-10-20,84.075,chance,Likely D
1,2026-10-21,17.270,AK-AL,chance,Likely R,2026-10-20,16.805,chance,Likely R
2,2026-10-21,0.015,AL-01,chance,Safe R,2026-10-20,0.015,chance,Safe R
3,2026-10-21,43.730,AL-02,chance,Tossup,2026-10-20,43.120,chance,Tossup
4,2026-10-21,0.000,AL-03,chance,Safe R,2026-10-20,0.000,chance,Safe R

In [131]:
## This is the cell that actually alerts when there's a rating change
if any(compare_df['rating_t'] != compare_df['rating_y']):
    changes_df = compare_df[compare_df['rating_t'] != compare_df['rating_y']][['geo', 'rating_y', 'rating_t']]
    print(changes_df)
else:
    print("No rating changes today!")

       geo       rating_y  rating_t
38   CA-22         Lean D  Likely D
60   CA-48  Very Likely D    Safe D
89   FL-12  Very Likely R  Likely R
90   FL-13         Lean R    Tossup
102  FL-25       Likely D    Tossup
163  KY-06         Tossup    Tilt D
207  MO-02         Tossup    Tilt D
228  NC-09       Likely R    Lean R
254  NV-01  Very Likely D    Safe D

In [132]:
for i in range(changes_df.shape[0]):
    seat = changes_df.iloc[i, :]['geo']
    rating_y = changes_df.iloc[i, :]['rating_y']
    rating_t = changes_df.iloc[i, :]['rating_t']
    print(f'{seat}: {rating_y} --> {rating_t}')

CA-22: Lean D --> Likely D
CA-48: Very Likely D --> Safe D
FL-12: Very Likely R --> Likely R
FL-13: Lean R --> Tossup
FL-25: Likely D --> Tossup
KY-06: Tossup --> Tilt D
MO-02: Tossup --> Tilt D
NC-09: Likely R --> Lean R
NV-01: Very Likely D --> Safe D

In [133]:
changes_df.shape

(9, 3)

In [139]:
## Mini-widget: what is the chance of Dems/Reps winning House if X congressional district is won by Dems/Reps?
def det_winner(post, cd, dem_winner=True):
    '''
    :param post: Posterior simulation matrix.
    :param cd: Congressional district.
    :param dem_winner: Whether or not we set Dems or Reps to win `cd`. True if Dem win is fixed, False if Rep win is fixed.
    '''
    winners = []
    seats = []
    post_ut = post.T
    if dem_winner:
        post_ut = post_ut[post_ut[cd] > 0]
    else:
        post_ut = post_ut[post_ut[cd] < 0]
    post_case = post_ut.T
    for i in range(post_case.shape[0]):
        sim = post_case.iloc[:, i]
        dem_seats = np.sum(sim > 0)
        if dem_seats >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
            winners.append(1)
        else: # Republicans win House in this draw
            winners.append(0)
        seats.append(dem_seats)
    dem_win_chance = np.mean(np.array(winners)) * 100
    dem_mean_seats = np.mean(np.array(seats)) + dem_uncont.shape[0]
    return dem_win_chance, dem_mean_seats

cd = 'MI-07'
dem_winner = True
det_winner(post, cd, dem_winner)

(np.float64(97.36842105263158), np.float64(251.1578947368421))

In [135]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')