In [51]:
import warnings
warnings.filterwarnings('ignore')

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import fuzz, process

In [53]:
pd.set_option('display.max_columns', 500)

In [54]:
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "Virgin Islands, U.S.": "VI",
} 

abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))
# https://gist.github.com/rogerallen/1583593

In [55]:
url = "https://www.nytimes.com/newsgraphics/polls/senate.csv"
polls = pd.read_csv(url)
polls.to_csv('../../2026_data/polls/senate.csv')
polls = polls[
    (polls['state'] != 'US') &
    (polls['stage'] == 'general')
]
polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,methodology,transparency_score,state,start_date,end_date,sponsor_candidate_id,sponsor_candidate,sponsor_candidate_party,question_id,sample_size,population,subpopulation,population_full,tracking,created_at,notes,url,url_article,url_topline,url_crosstab,source,internal,partisan,cycle,office_type,seat_name,seat_number,election_date,stage,party,pct,answer,candidate_name,candidate_id,race_id,ranked_choice_round,ranked_choice_reallocated,ranked_choice_final,nationwide_match,hypothetical
0,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,6.60,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN
1,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,0.35,Someone else,Someone else,d23503df-ca4b-41e0-807f-67f2629609ac,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN
2,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,REP,46.67,Marshall,Roger Marshall,5d350fbc-1056-423e-8032-665e437473f4,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN
3,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,DEM,46.39,Hamilton,Adam Hamilton,f2d2510d-5dfe-41c1-902e-c09ed183166b,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN
4,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,66d8ad19-aca9-4a2b-8411-c89f000791c3,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,5.52,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN

In [56]:
polls = polls.replace({'James Davis': 'Jamie Davis'})

In [57]:
polls_pivot = pd.pivot_table(data=polls, values='pct', index=['poll_id', 'question_id', 'state'], columns='candidate_name', aggfunc='first')
polls_pivot = polls_pivot.reset_index()
polls_pivot.head()

candidate_name,poll_id,question_id,state,Aaron Day,Abdul El-Sayed,Adam Hamilton,Alani Bankhead,Alexander Vindman,Allen Buckley,Amy McGrath,Andy Barr,Angie Craig,Angie Nixon,Ann Diener,Annie Andrews,Ashley Hinson,Ashley Moody,Barry Moore,Ben Ray Luján,Beto O’Rourke,Bill Hagerty,Bill Huizenga,Bill Redpath,Brad Raffensperger,Brian Bengs,Brian Kemp,Buddy Carter,Camencia Ford,Charles Booker,Charles D. Baker,Chris Pappas,Chris Sununu,Christine Lopez,Christopher Miklos,Chuck Conboy,Cindy Burbank,Cindy Hyde-Smith,Colin Allred,Curtis Stinnett,Dan Innis,Dan J. Sullivan,Dan Kleban,Dan Osborn,Dan Sullivan,Daniel Cameron,Darline Graham,David Graham,David Roth,Derek Dooley,Don Brown,Don't know,Don't know/Someone else,Don't know/Would not vote,Douglas Marsh,Dustin Darden,Ed Markey,Edmond LaPlante,Edmond Laplante,Everett Wess,Frank Edelblut,Generic Candidate,Generic Democrat,Generic Republican,Gerald Heikes,Glenn Youngkin,Graham Platner,Gregory Levy,Gretchen Whitmer,Haley Stevens,Hallie Shoffner,Hans Truelson,Hector Mujica,Jack Reed,Jackie Norris,James Risch,James Ryan,James Talarico,Jamie Davis,Janet Mills,Jasmine Crockett,Jeanne Logan Morrow,Jeanne Shaheen,Jeff Wadlin,Jennifer Jenkins,Jim Priest,Joaquin Castro,Joe Tache,John Cornyn,John Deaton,John Fetterman,John King,John Sununu,John Warren,Jon Husted,Jon Ossoff,Joni Ernst,Jordan Wood,Josh Turek,Joshua Cain,Julia Letlow,Julian Beaudion,Kasie Whitener,Kelly Loeffler,Ken Paxton,Kevin Hern,Kurt Alme,Kyle Austin,Lara Trump,Larry Marker,Lindsey Graham,Lydia Christensen,Mallory McMorrow,Marisa Simonetti,Marjorie Taylor Greene,Mark Hackett,Mark Lynch,Mark Sanford,Mark Warner,Marquita Bradshaw,Mary Peltola,Matt Giovonizzi,Matt Loesby,Michael Bahry,Michael Dublin,Michael Whatley,Michele Tafoya,Mike Collins,Mike Marvin,Mike Rogers,Mike Rounds,N'Kiyla Jasmine Thomas,Nancy Mace,Natalie Fleming,Nate Morris,Nathan Sage,Neil Gillespie,Neither,Nirav Shah,Noah Taylor,None/other,Other named candidates,Pamela Evette,Patrick Schmidt,Peggy Flanagan,Pete Buttigieg,Pete Ricketts,Ralph Norman,Raymond McKay,Rebecca Whiting,Reilly Neill,Rich McCormick,Robin Richards,Roger Marshall,Ron Meinhardt,Roy Cooper,Russell Fry,Scott Brown,Scott Colom,Seth Bodnar,Seth Moulton,Sevier White,Shannon Bray,Shenna Bellows,Sherrod Brown,Shiva Ayyadurai,Sidney Hill,Someone else,Steve Daines,Susan Collins,Ted Brown,Thom Tillis,Thomas Laehn,Tim Harris,Tim Ryan,Timothy Long,Todd Achilles,Tom Cotton,Tom Jandron,Trey Gowdy,Troy Jackson,Ty Pinkins,Walter Kristy,Wesley Hunt,William J. Forbes,Would not vote,Zach Wahls
0,006eec7f-5ceb-4b68-8c21-658e35d6bb9a,8371ba4e-f777-48e0-a65b-904ffc8ff19c,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,007278d5-49cd-4aa2-9400-8c95c5fc50c5,071b6561-2fc5-4c00-98dd-4119da46c8d9,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,007278d5-49cd-4aa2-9400-8c95c5fc50c5,5afce063-c336-43c7-b41b-5766cd1221de,MI,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02747cb8-c9f8-4c09-b283-67fcf0ec90b0,0b89445f-5182-43eb-9b9d-9e803fb08d93,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,03c7e817-549b-4951-9dbe-e32ca29e4962,0e9cf369-afd2-4271-8759-49f5e11f7bcd,ME,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
candinfo_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTZTum7NEaS6hvniyNJbDTWLDY0rATtgR5yXV2EUbtt6ubRPqv1sVH3PdJM3rgAzS_ak_XSgxLtaq3-/pub?output=csv'
candinfo = pd.read_csv(candinfo_url)

In [59]:
dem_uncont = candinfo[candinfo['rep_cand'] == 'Not Contested']
rep_uncont = candinfo[candinfo['dem_cand'] == 'Not Contested']
candinfo = candinfo[(candinfo['dem_cand'] != 'Not Contested') &
    (candinfo['rep_cand'] != 'Not Contested')]
candinfo['state_po'] = candinfo['state'].astype(str).map(us_state_to_abbrev)
candinfo.head()

,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po
0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL
1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK
2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR
3,Colorado,John Hickenlooper,Mark Baisley,True,False,D,CO
4,Delaware,Chris Coons,Michael Katz,True,False,D,DE

In [60]:
tp_candinfo = pd.read_csv('../../2026_data/third_party_cands_senate_2026.csv')
tp_candinfo['state_po'] = tp_candinfo['state'].map(us_state_to_abbrev)
tp_candinfo.head()

     state   candidate_name party   party_name state_po
0  Florida   Neil Gillespie   IND  Independent       FL
1     Ohio        Greg Levy   IND  Independent       OH
2     Ohio  William Redpath   LIB  Libertarian       OH
3   Alaska  Dan J. Sullivan   REP   Republican       AK
4   Alaska    Gerald Heikes   REP   Republican       AK

In [61]:
dem_uncont.shape, rep_uncont.shape

((0, 6), (0, 6))

In [62]:
candinfo_transp = candinfo.set_index(['state_po']).T
candinfo_transp.head()

state_po,AL,AK,AR,CO,DE,FL,GA,ID,IL,IA,KS,KY,LA,ME,MA,MI,MN,MS,MT,NE,NH,NJ,NM,NC,OH,OK,OR,RI,SC,SD,TN,TX,VA,WV,WY
state,Alabama,Alaska,Arkansas,Colorado,Delaware,Florida,Georgia,Idaho,Illinois,Iowa,Kansas,Kentucky,Louisiana,Maine,Massachusetts,Michigan,Minnesota,Mississippi,Montana,Nebraska,New Hampshire,New Jersey,New Mexico,North Carolina,Ohio,Oklahoma,Oregon,Rhode Island,South Carolina,South Dakota,Tennessee,Texas,Virginia,West Virginia,Wyoming
dem_cand,Everett Weiss,Mary Peltola,Hallie Shoffner,John Hickenlooper,Chris Coons,Angie Nixon,Jon Ossoff,Todd Achilles,Juliana Stratton,Josh Turek,Adam Hamilton,Charles Booker,Jamie Davis,Troy Jackson,Ed Markey,Abdul El-Sayed,Peggy Flanagan,Scott Colom,Seth Bodnar,Dan Osborn,Chris Pappas,Cory Booker,Ben Ray Lujan,Roy Cooper,Sherrod Brown,N'Kiyla Thomas,Jeff Merkley,Jack Reed,Annie Andrews,Brian Bengs,Marquita Bradshaw,James Talarico,Mark Warner,Rachel Fetty Anderson,James W. Byrd
rep_cand,Barry Moore,Dan S. Sullivan,Tom Cotton,Mark Baisley,Michael Katz,Ashley Moody,Mike Collins,Jim Risch,Don Tracy,Ashley Hinson,Roger Marshall,Andy Barr,Julia Letlow,Susan Collins,John Deaton,Mike J. Rogers,Michele Tafoya,Cindy Hyde-Smith,Kurt Alme,Pete Ricketts,John Sununu,Justin Murphy,Larry Marker,Michael Whatley,Jon Husted,Kevin Hern,David Brock Smith,Raymond McKay,Darline Graham,Mike Rounds,Bill Hagerty,Ken Paxton,Bert Mizusawa,Shelley Moore Capito,Harriet Hageman
dem_inc_any,False,False,False,True,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,False,False
rep_inc_any,False,True,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,True,False,False,True,False

In [63]:
tp_transp = tp_candinfo.set_index(['state_po']).T
tp_transp.head()

state_po,FL,OH,OH,AK,AK,AR,CO,CO,CO,CO,ID,ID,IL,IA,KS,KY,MA,MA,MI,MI,MI,MI,MN,MN,MS,MT,MT,NE,NE,NE,NH,NJ,NJ,NC,NC,OK,OK,OK,OR,OR,RI,SC,SC,LA,LA,LA,LA,LA,LA,LA,LA,TX,WV
state,Florida,Ohio,Ohio,Alaska,Alaska,Arkansas,Colorado,Colorado,Colorado,Colorado,Idaho,Idaho,Illinois,Iowa,Kansas,Kentucky,Massachusetts,Massachusetts,Michigan,Michigan,Michigan,Michigan,Minnesota,Minnesota,Mississippi,Montana,Montana,Nebraska,Nebraska,Nebraska,New Hampshire,New Jersey,New Jersey,North Carolina,North Carolina,Oklahoma,Oklahoma,Oklahoma,Oregon,Oregon,Rhode Island,South Carolina,South Carolina,Louisiana,Louisiana,Louisiana,Louisiana,Louisiana,Louisiana,Louisiana,Louisiana,Texas,West Virginia
candidate_name,Neil Gillespie,Greg Levy,William Redpath,Dan J. Sullivan,Gerald Heikes,Jeff Wadlin,Christopher Baum,Bob Chew,Blake Huber,Adam Withrow,Natalie Fleming,Matt Loesby,Whitfield Harrington Jr.,Thomas Laehn,David Graham,Christopher Campbell,Shiva Ayyadurai,Joe Tache,Lydia Christensen,Walter P. Kristy,Tim Long,Douglas P. Marsh,Marisa Simonetti,Rebecca Whiting,Ty Pinkins,Alani Bankhead,Kyle Austin,Chuck Conboy,Mike Marvin,Robin Richards,Edmond LaPlante,Veronica Fernandez,Joanne Kuniansky,Shannon Bray,Michael Dublin,Ron Meinhardt,Curtis Stinnett,Sevier White,Gary Lyndon Dye,Brett Smith,Michael Bahry,Mark Hackett,Kasie Whitener,Tharon Chandler,Andrew Gerena,Jeremy Hearn,Robert Jones,James Macon III,Yoshi Matthews,David Sutman Jr.,Catherine Whitson,Ted Brown,S. Marshall Wilson
party,IND,IND,LIB,REP,REP,LIB,APPR,FOR,LIB,UNI,IND,LIB,IND,LIB,LIB,IND,IND,PSL,LIB,NLP,TXP,GRN,IND,LIB,IND,DEM,LIB,AFP,LMN,WPP,CON,IND,SWP,LIB,GRN,IND,IND,LIB,LIB,PGP,IND,CON,LIB,IND,IND,IND,IND,IND,IND,IND,IND,LIB,CON
party_name,Independent,Independent,Libertarian,Republican,Republican,Libertarian,Approval Voting,Forward,Libertarian,Unity,Independent,Libertarian,Independent,Libertarian,Libertarian,Independent,Independent,Socialism and Liberation,Libertarian,Natural Law,U.S. Taxpayers,Green,Independent,Libertarian,Independent,Democratic,Libertarian,America First,Legal Marijuana Now,Working People,Constitution,Independent,Socialist Workers,Libertarian,Green,Independent,Independent,Libertarian,Libertarian,Pacific Green,Independent,Constitution,Libertarian,Independent,Independent,Independent,Independent,Independent,Independent,Independent,Independent,Libertarian,Constitution

In [64]:
rel_pollids = []
rel_questionids = []
fuzzymatches = []

for st in candinfo['state_po']:
    df = polls[polls['state'] == st]
    dem_cand = candinfo_transp.loc['dem_cand', st]
    rep_cand = candinfo_transp.loc['rep_cand', st]
    dem_fuzzymatch = process.extractOne(dem_cand, np.unique(df[df['party'].isin(['DEM', 'OTH', 'IND'])]['candidate_name']), scorer=fuzz.token_sort_ratio, score_cutoff=80)
    rep_fuzzymatch = process.extractOne(rep_cand, np.unique(df[df['party'].isin(['REP', 'OTH', 'IND'])]['candidate_name']), scorer=fuzz.token_sort_ratio, score_cutoff=80)
    if dem_fuzzymatch is None or rep_fuzzymatch is None:
        if dem_cand == "N'Kiyla Thomas":
            dem_fuzzymatch = ("N'Kiyla Jasmine Thomas", 100, 0)
        else:
            continue
    if rep_fuzzymatch[0] == 'Dan J. Sullivan':
        rep_fuzzymatch = ('Dan Sullivan', 100, 0)

    df = pd.pivot_table(df, values='pct', index=['poll_id', 'question_id', 'state'], columns='candidate_name', aggfunc='first').reset_index()
    
    if dem_fuzzymatch is not None:
        df = df[~df[dem_fuzzymatch[0]].isna()]
    if rep_fuzzymatch is not None:
        df = df[~df[rep_fuzzymatch[0]].isna()]
    pollids = np.unique(df['poll_id'])
    questionids = np.unique(df['question_id'])
    rel_pollids.extend(pollids)
    rel_questionids.extend(questionids)
    fuzzymatches.append(dem_fuzzymatch[0])
    fuzzymatches.append(rep_fuzzymatch[0])

    ## for debugging purposes
    print(f'{st} | {dem_cand} -- {dem_fuzzymatch[0]} | {rep_cand} -- {rep_fuzzymatch[0]} | Relevant polls: {len(pollids)}')

AL | Everett Weiss -- Everett Wess | Barry Moore -- Barry Moore | Relevant polls: 2
AK | Mary Peltola -- Mary Peltola | Dan S. Sullivan -- Dan Sullivan | Relevant polls: 21
AR | Hallie Shoffner -- Hallie Shoffner | Tom Cotton -- Tom Cotton | Relevant polls: 4
FL | Angie Nixon -- Angie Nixon | Ashley Moody -- Ashley Moody | Relevant polls: 10
GA | Jon Ossoff -- Jon Ossoff | Mike Collins -- Mike Collins | Relevant polls: 16
ID | Todd Achilles -- Todd Achilles | Jim Risch -- James Risch | Relevant polls: 7
IA | Josh Turek -- Josh Turek | Ashley Hinson -- Ashley Hinson | Relevant polls: 23
KS | Adam Hamilton -- Adam Hamilton | Roger Marshall -- Roger Marshall | Relevant polls: 10
KY | Charles Booker -- Charles Booker | Andy Barr -- Andy Barr | Relevant polls: 2
LA | Jamie Davis -- Jamie Davis | Julia Letlow -- Julia Letlow | Relevant polls: 2
ME | Troy Jackson -- Troy Jackson | Susan Collins -- Susan Collins | Relevant polls: 18
MA | Ed Markey -- Ed Markey | John Deaton -- John Deaton | Relevant polls: 11
MI | Abdul El-Sayed -- Abdul El-Sayed | Mike J. Rogers -- Mike Rogers | Relevant polls: 42
MN | Peggy Flanagan -- Peggy Flanagan | Michele Tafoya -- Michele Tafoya | Relevant polls: 10
MS | Scott Colom -- Scott Colom | Cindy Hyde-Smith -- Cindy Hyde-Smith | Relevant polls: 2
MT | Seth Bodnar -- Seth Bodnar | Kurt Alme -- Kurt Alme | Relevant polls: 13
NE | Dan Osborn -- Dan Osborn | Pete Ricketts -- Pete Ricketts | Relevant polls: 10
NH | Chris Pappas -- Chris Pappas | John Sununu -- John Sununu | Relevant polls: 21
NM | Ben Ray Lujan -- Ben Ray Luján | Larry Marker -- Larry Marker | Relevant polls: 1
NC | Roy Cooper -- Roy Cooper | Michael Whatley -- Michael Whatley | Relevant polls: 39
OH | Sherrod Brown -- Sherrod Brown | Jon Husted -- Jon Husted | Relevant polls: 27
OK | N'Kiyla Thomas -- N'Kiyla Jasmine Thomas | Kevin Hern -- Kevin Hern | Relevant polls: 1
RI | Jack Reed -- Jack Reed | Raymond McKay -- Raymond McKay | Relevant polls: 4
SC | Annie Andrews -- Annie Andrews | Darline Graham -- Darline Graham | Relevant polls: 5
SD | Brian Bengs -- Brian Bengs | Mike Rounds -- Mike Rounds | Relevant polls: 8
TN | Marquita Bradshaw -- Marquita Bradshaw | Bill Hagerty -- Bill Hagerty | Relevant polls: 1
TX | James Talarico -- James Talarico | Ken Paxton -- Ken Paxton | Relevant polls: 44

In [65]:
tp_candinfo

,state,candidate_name,party,party_name,state_po
0,Florida,Neil Gillespie,IND,Independent,FL
1,Ohio,Greg Levy,IND,Independent,OH
2,Ohio,William Redpath,LIB,Libertarian,OH
3,Alaska,Dan J. Sullivan,REP,Republican,AK
4,Alaska,Gerald Heikes,REP,Republican,AK
5,Arkansas,Jeff Wadlin,LIB,Libertarian,AR
6,Colorado,Christopher Baum,APPR,Approval Voting,CO
7,Colorado,Bob Chew,FOR,Forward,CO
8,Colorado,Blake Huber,LIB,Libertarian,CO
9,Colorado,Adam Withrow,UNI,Unity,CO
10,Idaho,Natalie Fleming,IND,Independent,ID
11,Idaho,Matt Loesby,LIB,Libertarian,ID
12,Illinois,Whitfield Harrington Jr.,IND,Independent,IL
13,Iowa,Thomas Laehn,LIB,Libertarian,IA
14,Kansas,David Graham,LIB,Libertarian,KS
15,Kentucky,Christopher Campbell,IND,Independent,KY
16,Massachusetts,Shiva Ayyadurai,IND,Independent,MA
17,Massachusetts,Joe Tache,PSL,Socialism and Liberation,MA
18,Michigan,Lydia Christensen,LIB,Libertarian,MI
19,Michigan,Walter P. Kristy,NLP,Natural Law,MI
20,Michigan,Tim Long,TXP,U.S. Taxpayers,MI
21,Michigan,Douglas P. Marsh,GRN,Green,MI
22,Minnesota,Marisa Simonetti,IND,Independent,MN
23,Minnesota,Rebecca Whiting,LIB,Libertarian,MN
24,Mississippi,Ty Pinkins,IND,Independent,MS
25,Montana,Alani Bankhead,DEM,Democratic,MT
26,Montana,Kyle Austin,LIB,Libertarian,MT
27,Nebraska,Chuck Conboy,AFP,America First,NE
28,Nebraska,Mike Marvin,LMN,Legal Marijuana Now,NE
29,Nebraska,Robin Richards,WPP,Working People,NE
30,New Hampshire,Edmond LaPlante,CON,Constitution,NH
31,New Jersey,Veronica Fernandez,IND,Independent,NJ
32,New Jersey,Joanne Kuniansky,SWP,Socialist Workers,NJ
33,North Carolina,Shannon Bray,LIB,Libertarian,NC
34,North Carolina,Michael Dublin,GRN,Green,NC
35,Oklahoma,Ron Meinhardt,IND,Independent,OK
36,Oklahoma,Curtis Stinnett,IND,Independent,OK
37,Oklahoma,Sevier White,LIB,Libertarian,OK
38,Oregon,Gary Lyndon Dye,LIB,Libertarian,OR
39,Oregon,Brett Smith,PGP,Pacific Green,OR
40,Rhode Island,Michael Bahry,IND,Independent,RI
41,South Carolina,Mark Hackett,CON,Constitution,SC
42,South Carolina,Kasie Whitener,LIB,Libertarian,SC
43,Louisiana,Tharon Chandler,IND,Independent,LA
44,Louisiana,Andrew Gerena,IND,Independent,LA
45,Louisiana,Jeremy Hearn,IND,Independent,LA
46,Louisiana,Robert Jones,IND,Independent,LA
47,Louisiana,James Macon III,IND,Independent,LA
48,Louisiana,Yoshi Matthews,IND,Independent,LA
49,Louisiana,David Sutman Jr.,IND,Independent,LA
50,Louisiana,Catherine Whitson,IND,Independent,LA
51,Texas,Ted Brown,LIB,Libertarian,TX
52,West Virginia,S. Marshall Wilson,CON,Constitution,WV

In [66]:
tp_fuzzymatches = []

for st in np.unique(tp_candinfo['state_po']):
    state_df = polls[polls['state'] == st]
    candidates = tp_candinfo[tp_candinfo['state_po'] == st]['candidate_name'].values

    for cand in candidates:
        df = state_df.copy()
        fuzzymatch = process.extractOne(cand, np.unique(df['candidate_name'].astype(str), equal_nan=True), 
                                        scorer=fuzz.token_sort_ratio, score_cutoff=80)
        if fuzzymatch is None:
            continue
    
        df = pd.pivot_table(df, values='pct', index=['poll_id', 'question_id', 'state'], columns='candidate_name', aggfunc='first').reset_index()
        
        if fuzzymatch is not None:
            df = df[~df[fuzzymatch[0]].isna()]
        pollids = np.unique(df['poll_id'])
        questionids = np.unique(df['question_id'])
        tp_fuzzymatches.append(fuzzymatch[0])

        ## for debugging purposes
        print(f'{st} | {cand} -- {fuzzymatch[0]} | Relevant polls: {len(pollids)}')

AK | Dan J. Sullivan -- Dan J. Sullivan | Relevant polls: 6
AK | Gerald Heikes -- Gerald Heikes | Relevant polls: 8
AR | Jeff Wadlin -- Jeff Wadlin | Relevant polls: 2
FL | Neil Gillespie -- Neil Gillespie | Relevant polls: 1
IA | Thomas Laehn -- Thomas Laehn | Relevant polls: 8
ID | Natalie Fleming -- Natalie Fleming | Relevant polls: 4
ID | Matt Loesby -- Matt Loesby | Relevant polls: 5
KS | David Graham -- David Graham | Relevant polls: 7
MA | Shiva Ayyadurai -- Shiva Ayyadurai | Relevant polls: 1
MA | Joe Tache -- Joe Tache | Relevant polls: 3
MI | Lydia Christensen -- Lydia Christensen | Relevant polls: 7
MI | Walter P. Kristy -- Walter Kristy | Relevant polls: 5
MI | Tim Long -- Timothy Long | Relevant polls: 7
MI | Douglas P. Marsh -- Douglas Marsh | Relevant polls: 7
MN | Marisa Simonetti -- Marisa Simonetti | Relevant polls: 6
MN | Rebecca Whiting -- Rebecca Whiting | Relevant polls: 6
MS | Ty Pinkins -- Ty Pinkins | Relevant polls: 2
MT | Alani Bankhead -- Alani Bankhead | Relevant polls: 11
MT | Kyle Austin -- Kyle Austin | Relevant polls: 8
NC | Shannon Bray -- Shannon Bray | Relevant polls: 10
NC | Michael Dublin -- Michael Dublin | Relevant polls: 8
NE | Chuck Conboy -- Chuck Conboy | Relevant polls: 1
NE | Mike Marvin -- Mike Marvin | Relevant polls: 1
NE | Robin Richards -- Robin Richards | Relevant polls: 1
NH | Edmond LaPlante -- Edmond LaPlante | Relevant polls: 1
OH | Greg Levy -- Gregory Levy | Relevant polls: 5
OK | Ron Meinhardt -- Ron Meinhardt | Relevant polls: 1
OK | Curtis Stinnett -- Curtis Stinnett | Relevant polls: 1
OK | Sevier White -- Sevier White | Relevant polls: 1
RI | Michael Bahry -- Michael Bahry | Relevant polls: 2
SC | Mark Hackett -- Mark Hackett | Relevant polls: 1
SC | Kasie Whitener -- Kasie Whitener | Relevant polls: 2
TX | Ted Brown -- Ted Brown | Relevant polls: 17

In [67]:
tp_fuzzymatches

['Dan J. Sullivan',
 'Gerald Heikes',
 'Jeff Wadlin',
 'Neil Gillespie',
 'Thomas Laehn',
 'Natalie Fleming',
 'Matt Loesby',
 'David Graham',
 'Shiva Ayyadurai',
 'Joe Tache',
 'Lydia Christensen',
 'Walter Kristy',
 'Timothy Long',
 'Douglas Marsh',
 'Marisa Simonetti',
 'Rebecca Whiting',
 'Ty Pinkins',
 'Alani Bankhead',
 'Kyle Austin',
 'Shannon Bray',
 'Michael Dublin',
 'Chuck Conboy',
 'Mike Marvin',
 'Robin Richards',
 'Edmond LaPlante',
 'Gregory Levy',
 'Ron Meinhardt',
 'Curtis Stinnett',
 'Sevier White',
 'Michael Bahry',
 'Mark Hackett',
 'Kasie Whitener',
 'Ted Brown']

In [68]:
len(rel_pollids), len(rel_questionids)

(354, 412)

In [69]:
mask = ((polls['poll_id'].isin(rel_pollids)) &
       (polls['question_id'].isin(rel_questionids)))

rel_polls = polls[mask]
rel_polls.head(3)

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,methodology,transparency_score,state,start_date,end_date,sponsor_candidate_id,sponsor_candidate,sponsor_candidate_party,question_id,sample_size,population,subpopulation,population_full,tracking,created_at,notes,url,url_article,url_topline,url_crosstab,source,internal,partisan,cycle,office_type,seat_name,seat_number,election_date,stage,party,pct,answer,candidate_name,candidate_id,race_id,ranked_choice_round,ranked_choice_reallocated,ranked_choice_final,nationwide_match,hypothetical
0,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,6.60,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN
1,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,0.35,Someone else,Someone else,d23503df-ca4b-41e0-807f-67f2629609ac,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN
2,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,REP,46.67,Marshall,Roger Marshall,5d350fbc-1056-423e-8032-665e437473f4,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN

In [70]:
## Discern whether question_id corresponds to inclusion of third party or not
tp_flags = {}

for pid in rel_pollids:
    df = rel_polls[rel_polls['poll_id'] == pid]
    # polls_pivot = pd.pivot_table(rel_polls, index=['poll_id', 'question_id', 'state'], columns='candidate_name', aggfunc='first').reset_index()
    # print(polls_pivot)
    quest_cand_combos = pd.DataFrame(df[['question_id', 'candidate_name', 'state']].value_counts()).reset_index()
    for quest in np.unique(quest_cand_combos['question_id']):
        temp = quest_cand_combos[quest_cand_combos['question_id'] == quest]
        setdiffer = np.setdiff1d(np.unique(temp['candidate_name']), np.append(np.array(fuzzymatches), np.array(["Don't know", "Don't know/Someone else", "Don't know/Would not vote", 
                                                             'Someone else', 'Would not vote', 'Neither', 'None/other'])))
        tpdiffer = np.setdiff1d(setdiffer, np.append(np.array(tp_fuzzymatches), "Other named candidates"))
        if setdiffer.shape[0] == 0:
            tp_flags.update({quest: 'head_to_head'})
        elif tpdiffer.shape[0] == 0:
            tp_flags.update({quest: 'third_party'})
        else:
            print(setdiffer, np.unique(temp['state']), quest) ## debug purposes
            tp_flags.update({quest: 'hypothetical'})

['Dustin Darden' 'Gerald Heikes'] ['AK'] 8aa5813e-aa33-41b3-b9ff-804fa852a76b
['Dustin Darden' 'Gerald Heikes'] ['AK'] 5bbc261a-4169-4f2a-ac99-97c87ff361a8
['James Ryan' 'Sidney Hill'] ['AK'] 02c8d060-e4fe-4cee-8e43-aca3cb1e74ac
['James Ryan'] ['AK'] 8ad3d2c2-6e7d-4d87-b6f3-ca8a57f8c5ea
['Ann Diener' 'Christopher Miklos'] ['AK'] 4fbeb64f-fbf1-4985-bbe8-35029cadcc44
['Allen Buckley'] ['GA'] e4e8615f-9864-482a-9569-ad14a1ffb78d
['David Roth'] ['ID'] a7a35d59-fc2f-4ee7-9670-dd18cbaad2e9
['David Roth' 'Matt Loesby' 'Natalie Fleming'] ['ID'] bcf7bc7f-bd97-4037-9999-9536c18f1fab
['David Roth' 'Matt Loesby' 'Natalie Fleming'] ['ID'] daff86b9-af5f-4064-a641-19e32257bf81
['Reilly Neill' 'Tom Jandron'] ['MT'] 24edf953-4cc3-49d3-99f6-f86ac43ad3b6
['Edmond Laplante' 'Matt Giovonizzi' 'Tim Harris'] ['NH'] 0b88de69-f360-443a-bb14-c0a037c1e3d6
['Aaron Day' 'Christine Lopez' 'Edmond LaPlante' 'Jeanne Logan Morrow'
 'Tim Harris'] ['NH'] c75b4bc8-eda8-4398-8de1-d68c16b85e36
['Edmond Laplante'] ['NH'] e218d656-69f5-475c-bf9d-4fda9a20f4dc
['Edmond Laplante'] ['NH'] 078645fe-eb48-4089-8bee-ecb0989fd623
['Bill Redpath' 'Gregory Levy'] ['OH'] f6c2367f-cb72-48df-81ee-93281bece8bf
['Bill Redpath' 'Gregory Levy'] ['OH'] 9e01bbfd-04a8-45e2-8137-83ac6989a363
['Bill Redpath'] ['OH'] ed3b67af-251b-4362-9d0c-2790a0cbcd13
['Bill Redpath' 'Gregory Levy'] ['OH'] f376cdbb-8197-42c7-84ef-ce0bf9c65963
['Bill Redpath' 'Gregory Levy'] ['OH'] 01f67637-26fa-4037-acfe-0a978733e961
['Bill Redpath' 'Gregory Levy'] ['OH'] 217e39c2-fe21-43b0-b82d-3efc29d43434
['Julian Beaudion'] ['SD'] 4b72d24b-64ea-46b8-99f5-96eed8ada09d
['Generic Candidate'] ['TN'] 7e58356a-9faa-46a9-9cfe-f834d3aecec1
['Generic Candidate'] ['TN'] fad3e2cd-cc71-448c-9eea-35b0b3ed10c0
['Camencia Ford' 'Hans Truelson' 'Joshua Cain' 'Ted Brown'] ['TX'] 19eafb34-41c3-47c6-b14d-9932ed38a499

In [71]:
rel_polls['cands_polled_type'] = rel_polls['question_id'].map(tp_flags)
rel_polls = rel_polls[~(rel_polls['cands_polled_type'] == 'hypothetical')]
rel_polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,methodology,transparency_score,state,start_date,end_date,sponsor_candidate_id,sponsor_candidate,sponsor_candidate_party,question_id,sample_size,population,subpopulation,population_full,tracking,created_at,notes,url,url_article,url_topline,url_crosstab,source,internal,partisan,cycle,office_type,seat_name,seat_number,election_date,stage,party,pct,answer,candidate_name,candidate_id,race_id,ranked_choice_round,ranked_choice_reallocated,ranked_choice_final,nationwide_match,hypothetical,cands_polled_type
0,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,6.60,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN,head_to_head
1,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,0.35,Someone else,Someone else,d23503df-ca4b-41e0-807f-67f2629609ac,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN,head_to_head
2,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,REP,46.67,Marshall,Roger Marshall,5d350fbc-1056-423e-8032-665e437473f4,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN,head_to_head
3,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,f80026a3-26be-4a94-8b93-10e314fce54b,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,DEM,46.39,Hamilton,Adam Hamilton,f2d2510d-5dfe-41c1-902e-c09ed183166b,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN,head_to_head
4,be8c4cbb-f0fa-41c9-860b-2f425d3e4829,92215ea1-dfa7-4284-a40b-477b73739ee6,The New York Times/Siena University,NaN,NaN,The New York Times/Siena University,448.0,The New York Times/Siena College,NaN,NaN,Live Phone,NaN,KS,9/22/26,9/30/26,NaN,NaN,NaN,66d8ad19-aca9-4a2b-8411-c89f000791c3,605.0,lv,NaN,lv,NaN,10/3/26 05:00,NaN,https://www.nytimes.com/interactive/2026/10/03...,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,5.52,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,5cb51572-4167-49a2-b7a6-eec3fa3a1945,NaN,False,False,NaN,NaN,third_party

In [72]:
rel_polls = rel_polls[rel_polls['candidate_name'].isin(np.append(np.array(fuzzymatches), "Alani Bankhead"))]

In [73]:
rel_polls.shape

(787, 51)

In [74]:
np.unique(rel_polls['candidate_name'].astype(str))

array(['Abdul El-Sayed', 'Adam Hamilton', 'Alani Bankhead', 'Andy Barr',
       'Angie Nixon', 'Annie Andrews', 'Ashley Hinson', 'Ashley Moody',
       'Barry Moore', 'Ben Ray Luján', 'Brian Bengs', 'Charles Booker',
       'Chris Pappas', 'Cindy Hyde-Smith', 'Dan Osborn', 'Dan Sullivan',
       'Darline Graham', 'Ed Markey', 'Everett Wess', 'Hallie Shoffner',
       'Jack Reed', 'James Risch', 'James Talarico', 'Jamie Davis',
       'John Deaton', 'John Sununu', 'Jon Husted', 'Jon Ossoff',
       'Josh Turek', 'Julia Letlow', 'Ken Paxton', 'Kevin Hern',
       'Kurt Alme', 'Larry Marker', 'Mary Peltola', 'Michael Whatley',
       'Michele Tafoya', 'Mike Collins', 'Mike Rogers', 'Mike Rounds',
       "N'Kiyla Jasmine Thomas", 'Peggy Flanagan', 'Pete Ricketts',
       'Raymond McKay', 'Roger Marshall', 'Roy Cooper', 'Scott Colom',
       'Seth Bodnar', 'Sherrod Brown', 'Susan Collins', 'Todd Achilles',
       'Tom Cotton', 'Troy Jackson'], dtype=object)

In [75]:
rel_polls.to_csv('transformed/relevent_senate_polls.csv')