In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import pyreadr
import joblib
from datetime import datetime, timedelta

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [3]:
pd.set_option('display.max_columns', 100)

In [4]:
dem_uncont = 34
rep_uncont = 31

In [5]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont)
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 51 else 'Republicans')
seat_sims

      seats       winner
0        53    Democrats
1        55    Democrats
2        47  Republicans
3        54    Democrats
4        47  Republicans
...     ...          ...
7995     50  Republicans
7996     51    Democrats
7997     53    Democrats
7998     50  Republicans
7999     53    Democrats

[8000 rows x 2 columns]

In [6]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 51 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 51 else (100-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count     pct       winner
0     37      1  0.0125  Republicans
1     38      1  0.0125  Republicans
2     40      2  0.0250  Republicans
3     41      3  0.0375  Republicans
4     42     12  0.1500  Republicans

In [7]:
np.unique(seat_sims['seats']).shape[0]

27

In [8]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=50.5, line_width=1, line_color='black', annotation_text='51 seats required for Dem majority', 
                    annotation_position='top right')
sims_hist

In [9]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date          y        geo       type
0  2026-09-27  51.348375  US Senate      seats
1  2026-09-27  58.600000  US Senate     chance
2  2026-09-27   3.816193  US Senate   seats_sd
3  2026-09-27  38.771876         AL     y_pred
4  2026-09-27   3.537242         AL  y_pred_sd

In [10]:
chance_over_time = output_ts[(output_ts['geo'] == 'US Senate') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-09-27'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="Senate Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser

In [11]:
seats_over_time = output_ts[(output_ts['geo'] == 'US Senate') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 100 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-09-27'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser

In [12]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [13]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [14]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,7950,7951,7952,7953,7954,7955,7956,7957,7958,7959,7960,7961,7962,7963,7964,7965,7966,7967,7968,7969,7970,7971,7972,7973,7974,7975,7976,7977,7978,7979,7980,7981,7982,7983,7984,7985,7986,7987,7988,7989,7990,7991,7992,7993,7994,7995,7996,7997,7998,7999
AL,-7.854150,-13.973938,-12.140471,-12.230877,-9.885232,-13.732759,-11.713263,-5.519907,-12.594323,-17.681925,-1.339991,-13.501137,-11.316455,-11.870951,-12.507085,-9.607762,-9.830792,-12.875683,-10.210172,-7.748198,-13.160801,-9.048563,-7.283437,-9.557560,-9.321904,-14.483844,-14.078050,-8.453864,-13.249651,-13.184208,-10.655873,-12.227986,-11.834551,-8.295880,-16.391224,-15.355407,-8.261826,-11.060536,-8.963734,-12.960652,-10.741494,-9.151208,-14.316091,-10.811467,-13.007542,-13.550501,-13.182626,-15.401765,-7.997137,-11.844655,...,-11.911740,-11.180767,-10.326054,-15.460856,-7.615467,-11.687009,-13.286907,-8.176921,-12.633391,-8.550921,-16.509167,-16.560809,-10.826073,-7.541575,-17.706383,-7.458157,-16.638144,-3.427477,-12.561241,-8.870290,-11.830775,-10.254919,-4.652134,-21.847986,-3.250551,-14.588560,-12.224595,-13.538075,-8.533982,-12.622184,-11.181872,-12.902663,-11.264045,-8.333093,-16.982017,-12.806424,-11.421461,-19.064459,-10.596769,-10.235108,-10.949415,-14.575280,-10.743018,-10.730991,-12.486869,-13.557058,-15.151426,-10.178241,-12.995983,-12.487676
AK,1.200232,6.309055,0.545130,6.230118,-0.444938,5.283471,5.516327,5.789173,0.036291,-5.008417,11.516342,0.967320,-0.345185,7.234498,-0.114866,3.682188,6.259546,5.332018,0.228679,3.467102,7.572146,4.797620,2.971373,5.761576,5.625073,1.931267,2.973551,4.292276,-0.325896,2.095477,3.997002,6.369875,7.664549,8.944605,3.406222,0.295364,4.307355,0.597671,-0.413330,3.873558,-0.712286,4.343633,7.706779,4.620136,3.229584,-1.147739,1.591593,3.695637,2.715552,5.098991,...,4.574937,3.435376,10.644314,0.375949,8.199442,3.224201,1.959032,4.271907,-0.854084,11.166787,3.015890,-0.291862,7.644908,3.961168,4.357086,2.211380,5.399126,2.851402,0.074261,7.890187,2.407685,4.033524,8.836707,0.859038,4.425561,-1.582862,7.183665,5.393899,4.478368,1.389946,-2.504887,5.729568,-0.044046,6.633773,2.261229,3.705649,3.933146,7.784499,4.705840,4.644235,0.591147,4.836885,4.527888,0.829890,4.509004,1.665282,2.338961,1.275757,4.100447,2.332298
AR,-9.857304,-11.798437,-8.146757,-10.881217,-9.649928,-7.751389,-8.975653,-5.523021,-13.856050,-13.890842,-0.879658,-11.507691,-12.398030,-6.990332,-11.867732,-10.503169,-9.867237,-8.238621,-10.612289,-7.004656,-10.979950,-10.610282,-6.773283,-7.035614,-11.185219,-8.619568,-11.066769,-7.650314,-11.038421,-10.865981,-8.214240,-8.835054,-6.354758,-7.150128,-13.195606,-12.635519,-5.981869,-9.506637,-11.002159,-10.029415,-10.125488,-6.045895,-11.928978,-13.702851,-12.405642,-10.611427,-8.751656,-13.683046,-10.452838,-11.606923,...,-12.616324,-11.090006,-7.693209,-13.230196,-3.453592,-12.053819,-12.509057,-11.180264,-9.929760,-3.760578,-14.306851,-11.860215,-7.911581,-7.317419,-13.236014,-4.396536,-15.247295,-0.893823,-8.959904,-8.244182,-11.387583,-6.008359,-4.533636,-15.191852,-3.051490,-16.171004,-8.851658,-15.802758,-4.921197,-9.480998,-8.840137,-10.562308,-9.380969,-2.260656,-17.145882,-9.379241,-7.430569,-12.122218,-5.633668,-11.905046,-10.901221,-10.379541,-8.453123,-6.707449,-10.860817,-13.184668,-16.835717,-11.041695,-7.287296,-10.461681
CO,11.626591,12.406747,7.480875,14.331795,9.086782,12.770709,14.572069,13.464748,11.039547,7.362246,13.531685,14.020656,11.135529,16.398554,8.146108,15.877603,13.935930,12.021409,7.032021,6.298475,13.158845,18.915664,10.121130,16.657017,13.908051,11.703747,11.529450,20.279165,7.946498,13.742831,14.302153,10.683010,9.600421,10.706734,11.986562,6.034693,16.539133,11.428954,15.645949,9.430424,13.275708,12.253827,11.886196,13.824584,10.819703,11.957413,7.874972,11.338866,12.616594,9.759886,...,14.035710,8.864087,17.637392,10.461621,13.442411,7.137512,11.873533,11.748270,7.518570,17.017584,8.172021,7.265338,16.332882,9.874773,12.057885,11.458257,10.671834,10.990794,15.685547,11.983956,10.953828,10.858663,14.170028,11.595010,11.790781,18.887383,15.914829,9.747779,11.810383,9.681836,9.221151,9.024564,14.699201,17.169550,6.746975,12.119062,12.975080,5.416342,15.697285,8.046340,16.109907,8.802772,5.625554,15.910664,10.611430,11.028019,14.490454,16.131141,10.673493,14.986157
DE,13.184648,16.234840,9.542615,16.723556,9.553712,13.138684,15.662215,15.052385,11.521900,10.951420,17.168833,16.127657,15.795651,11.731251,11.074601,10.920992,12.438031,16.590505,9.841966,11.222169,16.541247,17.022361,16.825368,15.978773,15.334397,9.367594,12.419407,18.416061,7.705700,14.569169,14.995116,13.078931,12.409134,13.087425,9.281093,9.416481,14.572683,13.619782,14.390883,9.385401,15.161886,11.444429,12.346961,13.240293,11.897679,12.227748,10.595387,12.056383,14.206316,12.182807,...,16.160934,10.410889,17.066772,11.682477,14.874995,8.130358,14.738230,10.728748,10.025078,22.334665,10.310629,9.774730,17.601752,11.696073,14.156803,12.154954,13.014216,12.969972,15.034069,15.666411,12.869578,14.337521,13.695466,12.331573,12.650468,14.154143,14.074374,11.214885,14.472689,14.790952,9.745558,11.631406,14.344582,19.524342,8.004157,16.657578,17.204850,10.852823,16.872084,6.797717,20.438388,8.581344,8.140368,16.548789,13.445963,13.871921,15.430438,16.145060,9.804354,18.115358

In [15]:
sim_corr = post_untransp.corr()

In [16]:
sim_corr.head()

,AL,AK,AR,CO,DE,FL,GA,ID,IL,IA,KS,KY,LA,ME,MA,MI,MN,MS,MT,NE,NH,NJ,NM,NC,OH,OK,OR,RI,SC,SD,TN,TX,VA,WV,WY
AL,1.000000,0.517153,0.739622,0.490356,0.497023,0.704447,0.532355,0.737095,0.705893,0.741787,0.735426,0.540504,0.750442,0.736289,0.520058,0.733665,0.707710,0.743114,0.701219,0.723870,0.501831,0.506825,0.504945,0.703183,0.506250,0.757973,0.507494,0.485163,0.491322,0.510058,0.556547,0.700664,0.506593,0.740696,0.738523
AK,0.517153,1.000000,0.518658,0.521700,0.526145,0.506835,0.557281,0.524849,0.504716,0.521513,0.520332,0.568568,0.524543,0.522974,0.561210,0.511578,0.499248,0.517721,0.495035,0.516239,0.560880,0.540082,0.554200,0.498828,0.553476,0.522584,0.548120,0.549805,0.537286,0.544050,0.598550,0.506626,0.544409,0.521406,0.520706
AR,0.739622,0.518658,1.000000,0.487269,0.500045,0.703939,0.527401,0.737196,0.698908,0.741227,0.737488,0.537749,0.741976,0.733871,0.522224,0.727772,0.699360,0.725577,0.692464,0.722399,0.508665,0.500903,0.501057,0.705099,0.505076,0.744141,0.502003,0.494237,0.495798,0.515997,0.557100,0.701978,0.498900,0.735641,0.734972
CO,0.490356,0.521700,0.487269,1.000000,0.708955,0.653974,0.550823,0.497877,0.653553,0.502561,0.486843,0.549412,0.503726,0.486999,0.536927,0.486976,0.642598,0.493889,0.652752,0.477703,0.710160,0.715801,0.719160,0.646972,0.705223,0.499857,0.710444,0.699374,0.699354,0.530096,0.571442,0.655883,0.703971,0.496900,0.494086
DE,0.497023,0.526145,0.500045,0.708955,1.000000,0.667168,0.543588,0.504390,0.664348,0.507582,0.499023,0.547863,0.503284,0.502493,0.548414,0.501069,0.663475,0.499155,0.663535,0.489182,0.718599,0.725933,0.727950,0.661207,0.715310,0.515761,0.710011,0.710493,0.709692,0.520695,0.577989,0.660852,0.719035,0.499497,0.509386

In [17]:
post.shape

(35, 8000)

In [18]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 51 - dem_uncont: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (51 - dem_uncont)
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (100 - seats_won_dem - dem_uncont - rep_uncont) - (50 - rep_uncont)
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [19]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|████████████████████████████████████████████████████████████████████████████| 8000/8000 [00:04<00:00, 1803.30it/s]

array(['TX', 'MI', 'MI', ..., 'AK', 'WY', 'MI'],
      shape=(8000,), dtype='<U32')

In [20]:
data = pd.read_csv('../../model_output/senate_predictions.csv')
data.head()

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.000000,0.0,0.000000,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.000000,0.0,0.000000,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",3607337.20,3519012.62,7126349.82,50.619704,49.380296,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.271146,0,1,40.559163,1.097524,49.986449,1.097524,West South Central,2026,0.000000,0.0,0.000000,5,Senate,2562.354455,1.097524,1.047628,9.427286,-21.349897,0.619704,-1,1.239408,40.462462,3.570865,0.3750,3,33.369096,47.412741
3,3,Colorado,John Hickenlooper,Mark Baisley,True,False,D,CO,"HICKENLOOPER, JOHN W.","BAISLEY, MARK",6544626.24,134935.30,6679561.54,97.979878,2.020122,5.964568,55.646542,73.317129,2.765032,16.968086,3.741915,0.400190,45.698090,4966936,806778,5773714,86.026707,13.973293,0.987401,-9.271146,1,0,0.000000,0.000000,0.000000,0.000000,Mountain,2026,0.367879,0.0,0.367879,0,Senate,9600.056470,0.000000,0.000000,0.000000,21.200282,47.979878,1,95.959756,61.979784,3.504059,99.9625,4,55.191186,68.882026
4,4,Delaware,Chris Coons,Michael Katz,True,False,D,DE,"COONS, CHRISTOPHER A.","KATZ, MICHAEL S DR.",2154241.44,47086.60,2201328.04,97.860991,2.139009,8.011194,57.479236,66.185281,3.007143,6.848324,21.107845,0.148276,35.764628,817817,172131,989948,82.612117,17.387883,0.987401,-9.271146,1,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.000000,0.0,0.000000,2,Senate,9576.773603,0.000000,0.000000,0.000000,25.293535,47.860991,1,95.721982,63.482018,3.504484,99.9875,5,56.643592,70.438546

In [21]:
data['tipping_point_prob'] = data['state_po'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.000000,0.0,0.000000,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.000000,0.0,0.000000,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",3607337.20,3519012.62,7126349.82,50.619704,49.380296,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.271146,0,1,40.559163,1.097524,49.986449,1.097524,West South Central,2026,0.000000,0.0,0.000000,5,Senate,2562.354455,1.097524,1.047628,9.427286,-21.349897,0.619704,-1,1.239408,40.462462,3.570865,0.3750,3,33.369096,47.412741,0.0000
3,3,Colorado,John Hickenlooper,Mark Baisley,True,False,D,CO,"HICKENLOOPER, JOHN W.","BAISLEY, MARK",6544626.24,134935.30,6679561.54,97.979878,2.020122,5.964568,55.646542,73.317129,2.765032,16.968086,3.741915,0.400190,45.698090,4966936,806778,5773714,86.026707,13.973293,0.987401,-9.271146,1,0,0.000000,0.000000,0.000000,0.000000,Mountain,2026,0.367879,0.0,0.367879,0,Senate,9600.056470,0.000000,0.000000,0.000000,21.200282,47.979878,1,95.959756,61.979784,3.504059,99.9625,4,55.191186,68.882026,0.0875
4,4,Delaware,Chris Coons,Michael Katz,True,False,D,DE,"COONS, CHRISTOPHER A.","KATZ, MICHAEL S DR.",2154241.44,47086.60,2201328.04,97.860991,2.139009,8.011194,57.479236,66.185281,3.007143,6.848324,21.107845,0.148276,35.764628,817817,172131,989948,82.612117,17.387883,0.987401,-9.271146,1,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.000000,0.0,0.000000,2,Senate,9576.773603,0.000000,0.000000,0.000000,25.293535,47.860991,1,95.721982,63.482018,3.504484,99.9875,5,56.643592,70.438546,0.2250

In [22]:
data.sort_values('tipping_point_prob', ascending=False).head(5)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
31,31,Texas,James Talarico,Ken Paxton,False,False,R,TX,"TALARICO, JAMES","PAXTON, WARREN KENNETH JR.",1.223184e+08,19010028.69,1.413284e+08,86.549039,13.450961,-5.916874,43.060966,48.286718,4.530331,31.642337,13.173480,0.180615,33.823334,24400697,4744808,29145505,83.720275,16.279725,0.987401,-9.271146,0,0,48.768721,8.380769,47.095092,8.380769,West South Central,2026,0.0,0.25284,-0.25284,6,Senate,7490.736143,8.380769,2.894956,-1.673629,-2.562602,36.549039,0,73.098078,50.574458,3.631845,56.4125,32,43.491861,57.795133,11.7875
15,15,Michigan,Abdul El-Sayed,Mike J. Rogers,False,False,D,MI,"EL-SAYED, ABDUL","ROGERS, MICHAEL J",3.966690e+07,13745116.90,5.341202e+07,74.265873,25.734127,-0.192456,49.278763,77.709102,2.333008,4.148895,12.968600,0.319413,32.445883,7404258,2673073,10077331,73.474395,26.525605,0.987401,-9.271146,0,0,47.649223,7.738056,45.594133,7.738056,East North Central,2026,0.0,0.00000,0.00000,2,Senate,5515.419849,7.738056,2.781736,-2.055090,8.886234,24.265873,0,48.531745,50.431596,3.541234,54.8750,16,43.647162,57.427879,11.0250
24,24,Ohio,Sherrod Brown,Jon Husted,False,True,R,OH,"BROWN, SHERROD","HUSTED, JON",5.161800e+07,9297757.80,6.091576e+07,84.736696,15.263304,-5.266554,44.343385,80.925356,1.708882,3.291326,11.486903,0.076606,31.487184,9001099,2798349,11799448,76.284069,23.715931,0.987401,-9.271146,0,1,47.600419,3.513656,44.836909,3.513656,East North Central,2026,0.0,0.00000,0.00000,2,Senate,7180.307625,3.513656,1.874475,-2.763511,-1.261961,34.736696,-1,69.473392,50.761863,3.468887,58.5750,25,43.865122,57.617102,9.4250
13,13,Maine,Troy Jackson,Susan Collins,False,True,R,ME,"JACKSON, TROY DALE","COLLINS, SUSAN M.",1.899327e+07,14243558.18,3.323683e+07,57.145254,42.854746,3.820912,53.544306,94.249770,0.897865,1.689465,0.930085,0.342309,36.189622,526309,836050,1362359,38.632181,61.367819,0.987401,-9.271146,0,1,48.848822,6.138607,47.242320,6.138607,New England,2026,0.0,0.00000,0.00000,3,Senate,3265.580032,6.138607,2.477621,-1.606502,16.912971,7.145254,-1,14.290508,49.596826,3.574047,45.4375,14,42.629807,56.560339,9.2375
9,9,Iowa,Josh Turek,Ashley Hinson,False,False,R,IA,"TUREK, JOSHUA","ARENHOLZ, ASHLEY HINSON",1.803372e+07,7126406.47,2.516013e+07,71.675794,28.324206,-6.092833,43.277201,88.847514,1.696738,4.401391,3.028533,0.168574,31.423453,2014831,1175538,3190369,63.153541,36.846459,0.987401,-9.271146,0,0,46.262874,7.317478,46.541061,7.317478,West North Central,2026,0.0,0.00000,0.00000,3,Senate,5137.419509,7.317478,2.705084,0.278187,-2.914520,21.675794,0,43.351589,49.323872,3.521165,41.8000,10,42.344980,56.194954,8.7500

In [23]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Dan Osborn', 'Brian Bengs', 'Todd Achilles', 'Seth Bodnar']
    indie_r = []
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [24]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.000000,0.0,0.000000,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b..."
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.000000,0.0,0.000000,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>..."
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",3607337.20,3519012.62,7126349.82,50.619704,49.380296,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.271146,0,1,40.559163,1.097524,49.986449,1.097524,West South Central,2026,0.000000,0.0,0.000000,5,Senate,2562.354455,1.097524,1.047628,9.427286,-21.349897,0.619704,-1,1.239408,40.462462,3.570865,0.3750,3,33.369096,47.412741,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<..."
3,3,Colorado,John Hickenlooper,Mark Baisley,True,False,D,CO,"HICKENLOOPER, JOHN W.","BAISLEY, MARK",6544626.24,134935.30,6679561.54,97.979878,2.020122,5.964568,55.646542,73.317129,2.765032,16.968086,3.741915,0.400190,45.698090,4966936,806778,5773714,86.026707,13.973293,0.987401,-9.271146,1,0,0.000000,0.000000,0.000000,0.000000,Mountain,2026,0.367879,0.0,0.367879,0,Senate,9600.056470,0.000000,0.000000,0.000000,21.200282,47.979878,1,95.959756,61.979784,3.504059,99.9625,4,55.191186,68.882026,0.0875,Safe D,"<b style=""color:#366bbf;"">John Hickenlooper* (..."
4,4,Delaware,Chris Coons,Michael Katz,True,False,D,DE,"COONS, CHRISTOPHER A.","KATZ, MICHAEL S DR.",2154241.44,47086.60,2201328.04,97.860991,2.139009,8.011194,57.479236,66.185281,3.007143,6.848324,21.107845,0.148276,35.764628,817817,172131,989948,82.612117,17.387883,0.987401,-9.271146,1,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.000000,0.0,0.000000,2,Senate,9576.773603,0.000000,0.000000,0.000000,25.293535,47.860991,1,95.721982,63.482018,3.504484,99.9875,5,56.643592,70.438546,0.2250,Safe D,"<b style=""color:#366bbf;"">Chris Coons* (D)</b>..."

In [25]:
data['projected_winner'] = data['chance'].map(lambda x: 'D' if x > 50 else 'R')
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.0,0.0,0.0,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.0,0.0,0.0,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",3607337.20,3519012.62,7126349.82,50.619704,49.380296,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.271146,0,1,40.559163,1.097524,49.986449,1.097524,West South Central,2026,0.0,0.0,0.0,5,Senate,2562.354455,1.097524,1.047628,9.427286,-21.349897,0.619704,-1,1.239408,40.462462,3.570865,0.3750,3,33.369096,47.412741,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R

In [26]:
data['hold'] = data['projected_winner'] ==  data['current_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.0,0.0,0.0,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.0,0.0,0.0,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip

In [27]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.0,0.0,0.0,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.6
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.0,0.0,0.0,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+7.6
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",3607337.20,3519012.62,7126349.82,50.619704,49.380296,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.271146,0,1,40.559163,1.097524,49.986449,1.097524,West South Central,2026,0.0,0.0,0.0,5,Senate,2562.354455,1.097524,1.047628,9.427286,-21.349897,0.619704,-1,1.239408,40.462462,3.570865,0.3750,3,33.369096,47.412741,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R,True,False,,R+19.1

In [28]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.0,0.0,0.0,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.6,99.9500,0.0,100.0,<1%,>99%
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.0,0.0,0.0,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+7.6,13.1875,86.8,13.2,86.8%,13.2%
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",3607337.20,3519012.62,7126349.82,50.619704,49.380296,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.271146,0,1,40.559163,1.097524,49.986449,1.097524,West South Central,2026,0.0,0.0,0.0,5,Senate,2562.354455,1.097524,1.047628,9.427286,-21.349897,0.619704,-1,1.239408,40.462462,3.570865,0.3750,3,33.369096,47.412741,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R,True,False,,R+19.1,99.6250,0.4,99.6,<1%,>99%

In [29]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.0,0.0,0.0,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.6,99.9500,0.0,100.0,<1%,>99%,8.297731
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.0,0.0,0.0,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+7.6,13.1875,86.8,13.2,86.8%,13.2%,21.246362
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",3607337.20,3519012.62,7126349.82,50.619704,49.380296,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.271146,0,1,40.559163,1.097524,49.986449,1.097524,West South Central,2026,0.0,0.0,0.0,5,Senate,2562.354455,1.097524,1.047628,9.427286,-21.349897,0.619704,-1,1.239408,40.462462,3.570865,0.3750,3,33.369096,47.412741,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R,True,False,,R+19.1,99.6250,0.4,99.6,<1%,>99%,12.264910

In [30]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",46243.62,2792410.06,2838653.68,1.629069,98.370931,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.271146,0,0,34.166127,0.964259,55.164080,0.964259,East South Central,2026,0.0,0.0,0.0,5,Senate,2.653865,0.964259,0.981967,20.997954,-20.355296,-48.370931,0,-96.741863,38.708253,3.542059,0.0500,1,31.863420,45.782649,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.6,99.9500,0.0,100.0,<1%,>99%,8.297731,D+8.3
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DAN",28810579.02,5435989.45,34246568.47,84.126908,15.873092,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.271146,0,1,49.705689,3.664593,46.541347,3.664593,Pacific,2026,0.0,0.0,0.0,5,Senate,7077.336586,3.664593,1.914313,-3.164341,-3.639459,34.126908,-1,68.253815,53.776619,3.399992,86.8125,2,47.154383,60.563191,3.6875,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+7.6,13.1875,86.8,13.2,86.8%,13.2%,21.246362,D+21.2

In [31]:
tab_data = data[['state', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Dan Osborn', 'Brian Bengs', 
                                                                                              'Todd Achilles', 'Seth Bodnar'] else x)
tab_data = tab_data.rename({
    'state': 'State',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,State,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,Alabama,Everett Weiss,Barry Moore,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+22.6,D+8.3,0.0000
1,Alaska,Mary Peltola,Dan S. Sullivan,Likely D,"<p style=""color:blue;"">86.8%</p>","<p style=""color:red;"">13.2%</p>",D+7.6,D+21.2,3.6875
2,Arkansas,Hallie Shoffner,Tom Cotton,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+19.1,D+12.3,0.0000
3,Colorado,John Hickenlooper,Mark Baisley,Safe D,"<p style=""color:blue;"">>99%</p>","<p style=""color:red;""><1%</p>",D+24.0,D+12.7,0.0875
4,Delaware,Chris Coons,Michael Katz,Safe D,"<p style=""color:blue;"">>99%</p>","<p style=""color:red;""><1%</p>",D+27.0,D+12.0,0.2250

In [32]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

8.122229653621131

In [33]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

                 vars          x
0     means_seats_tot  51.529375
1  chamber_win_chance  57.875000
0             sv_bias   8.122230

In [34]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [35]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 100 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Win Probability  Seat Share
0    Democrats           57.875   51.529375
1  Republicans           42.125   48.470625

In [36]:
incl_cols = ['state', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = data[incl_cols]

In [37]:
rating_ts = output_ts[output_ts['type'] == 'chance']
rating_ts['rating'] = rating_ts['y'].map(get_rating)
rating_ts['date'] = pd.to_datetime(rating_ts['date'])
rating_ts.head()

         date        y        geo    type    rating
1  2026-09-27  58.6000  US Senate  chance    Tossup
5  2026-09-27   0.0500         AL  chance    Safe R
10 2026-09-27  79.8875         AK  chance  Likely D
15 2026-09-27   0.1250         AR  chance    Safe R
20 2026-09-27  99.9625         CO  chance    Safe D

In [38]:
## Alert when there's a rating change
today_date = rating_ts['date'].max()
yesterday = rating_ts[rating_ts['date'] != today_date]['date'].max()

today_ratings = rating_ts[rating_ts['date'] == today_date]
yester_ratings = rating_ts[rating_ts['date'] == yesterday]
compare_df = pd.merge(left=today_ratings, right=yester_ratings, on='geo', how='left', suffixes=['_t', '_y'])
compare_df.head()

,date_t,y_t,geo,type_t,rating_t,date_y,y_y,type_y,rating_y
0,2026-10-20,57.8750,US Senate,chance,Tossup,2026-10-19,57.6125,chance,Tossup
1,2026-10-20,0.0500,AL,chance,Safe R,2026-10-19,0.0500,chance,Safe R
2,2026-10-20,86.8125,AK,chance,Likely D,2026-10-19,86.7125,chance,Likely D
3,2026-10-20,0.3750,AR,chance,Safe R,2026-10-19,0.4000,chance,Safe R
4,2026-10-20,99.9625,CO,chance,Safe D,2026-10-19,99.9625,chance,Safe D

In [39]:
## This is the cell that actually alerts when there's a rating change
if any(compare_df['rating_t'] != compare_df['rating_y']):
    changes_df = compare_df[compare_df['rating_t'] != compare_df['rating_y']][['geo', 'rating_y', 'rating_t']]
    print(changes_df)
else:
    print("No rating changes today!")

   geo       rating_y rating_t
24  NC  Very Likely D   Safe D

In [40]:
for i in range(changes_df.shape[0]):
    seat = changes_df.iloc[i, :]['geo']
    rating_y = changes_df.iloc[i, :]['rating_y']
    rating_t = changes_df.iloc[i, :]['rating_t']
    print(f'{seat}: {rating_y} --> {rating_t}')

NC: Very Likely D --> Safe D

In [41]:
if any(compare_df['rating_t'] != compare_df['rating_y']):
    print(changes_df.shape)

(1, 3)

In [42]:
## Mini-widget: what is the chance of Dems/Reps winning Senate if X state is won by Dems/Reps?
def det_winner(post, state, dem_winner=True):
    '''
    :param post: Posterior simulation matrix.
    :param state: Congressional district.
    :param dem_winner: Whether or not we set Dems or Reps to win `state`. True if Dem win is fixed, False if Rep win is fixed.
    '''
    winners = []
    seats = []
    post_ut = post.T
    if dem_winner:
        post_ut = post_ut[post_ut[state] > 0]
    else:
        post_ut = post_ut[post_ut[state] < 0]
    post_case = post_ut.T
    for i in range(post_case.shape[0]):
        sim = post_case.iloc[:, i]
        dem_seats = np.sum(sim > 0)
        if dem_seats >= 51 - dem_uncont: # Democrats win House in this draw
            winners.append(1)
        else: # Republicans win House in this draw
            winners.append(0)
        seats.append(dem_seats)
    dem_win_chance = np.mean(np.array(winners)) * 100
    dem_mean_seats = np.mean(np.array(seats)) + dem_uncont
    return dem_win_chance, dem_mean_seats

st = 'TX'
dem_winner = True
cond_win_chance, cond_seats = det_winner(post, st, dem_winner)
print(f'If Dems {'win' if dem_winner else 'lose'} {st}-SEN, they have a {cond_win_chance:.1f}% chance of winning the chamber overall, with mean projected seats of {cond_seats:.1f}')

If Dems win TX-SEN, they have a 91.4% chance of winning the chamber overall, with mean projected seats of 53.2

In [43]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')