In [354]:
import warnings
warnings.filterwarnings('ignore')

In [355]:
import pandas as pd
import numpy as np
import pyreadr
import joblib
from datetime import datetime, timedelta

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

from dash import Dash, html, dcc, dash_table, Input, Output, callback
import dash_bootstrap_components as dbc

In [356]:
pd.set_option('display.max_columns', 100)

In [357]:
dem_uncont = 34
rep_uncont = 31

In [358]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont)
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 51 else 'Republicans')
seat_sims

      seats       winner
0        54    Democrats
1        55    Democrats
2        47  Republicans
3        54    Democrats
4        48  Republicans
...     ...          ...
7995     51    Democrats
7996     52    Democrats
7997     53    Democrats
7998     50  Republicans
7999     53    Democrats

[8000 rows x 2 columns]

In [359]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 51 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 51 else (100-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count     pct       winner
0     37      1  0.0125  Republicans
1     38      1  0.0125  Republicans
2     40      3  0.0375  Republicans
3     41      3  0.0375  Republicans
4     42     14  0.1750  Republicans

In [360]:
np.unique(seat_sims['seats']).shape[0]

26

In [361]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'}, template='plotly_white')
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=50.5, line_width=1, line_color='black', annotation_text='51 seats required for Dem majority', 
                    annotation_position='top right')
sims_hist

In [362]:
output_ts = pd.read_csv('model_output/output_over_time.csv')
output_ts.head()

         date          y        geo       type
0  2026-09-27  51.348375  US Senate      seats
1  2026-09-27  58.600000  US Senate     chance
2  2026-09-27   3.816193  US Senate   seats_sd
3  2026-09-27  38.771876         AL     y_pred
4  2026-09-27   3.537242         AL  y_pred_sd

In [363]:
chance_over_time = output_ts[(output_ts['geo'] == 'US Senate') &
                             (output_ts['type'] == 'chance')]
chance_over_time['rep_chance'] = chance_over_time['y'].map(lambda x: 100 - x)
chance_over_time = chance_over_time.rename({'y': 'Democrats', 'rep_chance': 'Republicans'}, axis=1)
chance_time_ser = px.line(chance_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                         color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
chance_time_ser.update_traces(hovertemplate="%{y:.1f}%")
chance_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-09-27'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Win Probability (%)',
    title=dict(text="Senate Win Probability Over Time"),
    hovermode="x",
    showlegend=False
)
chance_time_ser

In [364]:
seats_over_time = output_ts[(output_ts['geo'] == 'US Senate') &
                             (output_ts['type'] == 'seats')]
seats_over_time['rep_seats'] = seats_over_time['y'].map(lambda x: 100 - x)
seats_over_time = seats_over_time.rename({'y': 'Democrats', 'rep_seats': 'Republicans'}, axis=1)
seats_time_ser = px.line(seats_over_time, x='date', y=['Democrats', 'Republicans'], template='plotly_white',
                        color_discrete_map={'Democrats': '#004b97', 'Republicans': '#c71e1d'},)
seats_time_ser.update_traces(hovertemplate="%{y:.1f}")
seats_time_ser.update_layout(
    xaxis=dict(range=[pd.to_datetime('2026-09-27'), pd.to_datetime('2026-11-10')]),
    yaxis=dict(range=[0, 100]),
    xaxis_title='Date',
    yaxis_title='Average Seats Over All Simulations',
    title=dict(text="Projected Seats Over Time"),
    hovermode="x",
    showlegend=False
)
seats_time_ser

In [365]:
joblib.dump(sims_hist, 'display_data/sims_histogram.pkl')
joblib.dump(chance_time_ser, 'display_data/chance_time_ser.pkl')
joblib.dump(seats_time_ser, 'display_data/seats_time_ser.pkl')

['display_data/seats_time_ser.pkl']

In [366]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [367]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,...,7950,7951,7952,7953,7954,7955,7956,7957,7958,7959,7960,7961,7962,7963,7964,7965,7966,7967,7968,7969,7970,7971,7972,7973,7974,7975,7976,7977,7978,7979,7980,7981,7982,7983,7984,7985,7986,7987,7988,7989,7990,7991,7992,7993,7994,7995,7996,7997,7998,7999
AL,-7.911023,-13.984344,-12.173404,-12.216492,-9.896995,-13.737980,-11.764253,-5.614302,-12.692900,-17.651110,-1.435628,-13.608681,-11.442940,-11.907322,-12.478934,-9.593643,-9.897753,-12.901727,-10.306562,-7.801926,-13.193407,-9.107815,-7.286199,-9.655156,-9.344554,-14.525706,-14.105231,-8.465130,-13.338383,-13.160427,-10.646930,-12.215709,-11.869245,-8.372599,-16.396712,-15.402491,-8.217818,-11.170165,-9.051580,-12.889996,-10.883753,-9.187179,-14.298111,-10.905187,-13.138445,-13.627917,-13.241027,-15.468215,-7.987885,-11.819279,...,-11.954713,-11.247955,-10.394150,-15.447037,-7.652229,-11.770194,-13.338982,-8.213871,-12.689725,-8.538524,-16.545173,-16.580591,-10.881223,-7.579482,-17.784332,-7.445578,-16.695337,-3.417169,-12.653410,-8.915463,-11.934614,-10.294155,-4.679683,-21.879548,-3.324794,-14.726003,-12.269201,-13.596783,-8.572626,-12.653472,-11.233995,-12.928193,-11.322572,-8.332430,-17.017305,-12.838565,-11.446946,-19.061798,-10.687709,-10.211115,-11.044072,-14.619523,-10.833291,-10.741227,-12.511520,-13.577095,-15.201148,-10.299442,-13.002936,-12.524589
AK,0.561419,5.719099,-0.013226,5.632591,-0.858522,4.714143,5.139777,5.510389,-0.451355,-5.523178,10.970859,0.484870,-0.965773,6.600181,-0.718452,3.243449,5.787468,4.807163,-0.290429,2.917657,6.919102,4.398603,2.414784,5.193770,4.831341,1.577872,2.530553,3.597933,-0.829880,1.765679,3.582127,5.762356,7.115828,8.414152,2.960867,-0.045820,3.619561,0.232840,-0.905610,3.244057,-1.057896,3.692598,7.069887,4.240116,2.734464,-1.554285,1.054371,3.103798,2.288527,4.421498,...,4.110667,3.015645,10.091973,-0.333519,7.626849,2.863003,1.294741,3.667706,-1.347320,10.550766,2.420621,-0.857277,7.082800,3.355084,3.924711,1.596988,5.062583,2.124970,-0.607921,7.554235,1.664966,3.340055,8.605123,0.158162,4.178098,-2.351453,6.354971,5.075081,3.554026,1.060704,-3.136842,5.400496,-0.717933,5.998195,1.865289,3.074587,3.330348,7.349972,4.079107,4.035491,0.201292,4.351651,3.966511,0.403248,4.123114,0.845884,1.803401,0.649914,3.607338,1.754075
AR,-11.307754,-13.064791,-9.450457,-12.124043,-10.912621,-9.124024,-10.162641,-6.711111,-15.348185,-15.060643,-2.299673,-12.831378,-13.698339,-8.199814,-13.176592,-11.819382,-11.154299,-9.658197,-12.027529,-8.364697,-12.348568,-11.795337,-8.128974,-8.293234,-12.536875,-9.944203,-12.372692,-9.016456,-12.358328,-12.130756,-9.494227,-10.226033,-7.632960,-8.392830,-14.573119,-14.036808,-7.301478,-10.844148,-12.360984,-11.437902,-11.492729,-7.372788,-13.163955,-15.014510,-13.656631,-11.854831,-9.978295,-14.957661,-11.861683,-12.813863,...,-13.856075,-12.488473,-9.125523,-14.467658,-4.861848,-13.320789,-13.691138,-12.424842,-11.279530,-4.980102,-15.622712,-13.206994,-9.228859,-8.578978,-14.517347,-5.709743,-16.477713,-2.184718,-10.321722,-9.584492,-12.867188,-7.376385,-5.896249,-16.511169,-4.358894,-17.498947,-10.158576,-17.173560,-6.306776,-10.766549,-10.180952,-11.895640,-10.624002,-3.479000,-18.545119,-10.650119,-8.682513,-13.433445,-7.065819,-13.109725,-12.160809,-11.722210,-9.611342,-8.161032,-12.323332,-14.348330,-17.991338,-12.278277,-8.722822,-11.800891
CO,11.559744,12.341165,7.414564,14.266166,9.020675,12.703621,14.506164,13.397101,10.971701,7.297048,13.464743,13.951934,11.068322,16.331350,8.081359,15.812385,13.869419,11.954086,6.965232,6.232787,13.091822,18.849213,10.055282,16.590893,13.842916,11.637470,11.463626,20.213806,7.880582,13.677242,14.236515,10.618159,9.534926,10.639189,11.920367,5.967128,16.474432,11.362132,15.578861,9.364844,13.209057,12.188224,11.820412,13.757983,10.754504,11.891195,7.808658,11.273233,12.550997,9.694435,...,13.968174,8.797953,17.570829,10.397545,13.376075,7.071776,11.807830,11.682089,7.451533,16.951464,8.106579,7.199405,16.267997,9.808414,11.990091,11.392720,10.604285,10.925294,15.619091,11.918200,10.886975,10.793343,14.102761,11.528397,11.724401,18.820654,15.848182,9.681142,11.743898,9.616365,9.154193,8.959646,14.633414,17.103984,6.680546,12.052412,12.907944,5.350304,15.631168,7.982416,16.042872,8.736524,5.559478,15.844693,10.542838,10.964174,14.425073,16.066674,10.608670,14.920430
DE,13.159610,16.209473,9.519754,16.696887,9.527329,13.120489,15.635699,15.033804,11.499351,10.925373,17.143016,16.108476,15.772547,11.706057,11.047704,10.894061,12.410738,16.568701,9.817276,11.196606,16.516135,17.000064,16.800326,15.951610,15.305354,9.342312,12.393581,18.388381,7.680439,14.546384,14.971972,13.054336,12.386807,13.063353,9.260115,9.395208,14.546285,13.594129,14.369561,9.357603,15.142151,11.418734,12.321906,13.214088,11.868334,12.200323,10.570717,12.029831,14.180646,12.154472,...,16.141327,10.383595,17.042436,11.655967,14.851457,8.104670,14.712436,10.703669,10.002586,22.308611,10.283010,9.748741,17.577153,11.667272,14.132515,12.127698,12.995150,12.939174,15.008071,15.643201,12.842707,14.310011,13.672660,12.306098,12.627585,14.129539,14.048712,11.190337,14.445712,14.769077,9.718556,11.608586,14.317989,19.496654,7.982385,16.632291,17.182702,10.832955,16.849613,6.769189,20.413545,8.561009,8.114517,16.525255,13.426023,13.842752,15.403550,16.115090,9.777774,18.089246

In [368]:
sim_corr = post_untransp.corr()

In [369]:
sim_corr.head()

,AL,AK,AR,CO,DE,FL,GA,ID,IL,IA,KS,KY,LA,ME,MA,MI,MN,MS,MT,NE,NH,NJ,NM,NC,OH,OK,OR,RI,SC,SD,TN,TX,VA,WV,WY
AL,1.000000,0.516826,0.740077,0.490251,0.497239,0.706621,0.531764,0.737171,0.705875,0.744573,0.738037,0.541074,0.751775,0.735731,0.523119,0.734752,0.708658,0.743836,0.702203,0.724929,0.502756,0.506880,0.506295,0.705545,0.506997,0.758500,0.507747,0.490726,0.491584,0.511958,0.557453,0.701879,0.506580,0.741236,0.739034
AK,0.516826,1.000000,0.516975,0.521430,0.525157,0.500168,0.558825,0.526970,0.505381,0.518091,0.518876,0.566381,0.524039,0.506060,0.560807,0.511517,0.499612,0.517281,0.498565,0.516327,0.561912,0.539311,0.554297,0.497967,0.552371,0.521052,0.547248,0.549566,0.538381,0.541728,0.597673,0.508217,0.544358,0.520648,0.519499
AR,0.740077,0.516975,1.000000,0.487471,0.499997,0.703786,0.527681,0.736310,0.698991,0.741650,0.737760,0.537176,0.742278,0.729467,0.523757,0.729045,0.700611,0.725888,0.694171,0.721438,0.508940,0.500483,0.501561,0.705675,0.504618,0.744311,0.501844,0.497016,0.495429,0.515387,0.557063,0.701883,0.498882,0.735950,0.735080
CO,0.490251,0.521430,0.487471,1.000000,0.708954,0.654082,0.550445,0.497577,0.652938,0.503368,0.487423,0.549409,0.503937,0.483400,0.538072,0.487111,0.642952,0.493862,0.653700,0.477316,0.709999,0.715795,0.719360,0.647697,0.705452,0.499916,0.710490,0.702426,0.699016,0.530766,0.571429,0.656021,0.703961,0.496862,0.494060
DE,0.497239,0.525157,0.499997,0.708954,1.000000,0.667558,0.542921,0.504030,0.663927,0.508846,0.499927,0.547757,0.503502,0.500080,0.549075,0.501427,0.663424,0.499235,0.664730,0.489275,0.718546,0.725937,0.728297,0.661532,0.715569,0.515669,0.710038,0.712794,0.709213,0.521142,0.577945,0.661621,0.719021,0.499429,0.509314

In [370]:
post.shape

(35, 8000)

In [371]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 51 - dem_uncont: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (51 - dem_uncont)
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (100 - seats_won_dem - dem_uncont - rep_uncont) - (50 - rep_uncont)
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [372]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|████████████████████████████████████████████████████████████████████████████| 8000/8000 [00:06<00:00, 1331.36it/s]

array(['AK', 'MI', 'KS', ..., 'IA', 'WY', 'AK'],
      shape=(8000,), dtype='<U32')

In [373]:
data = pd.read_csv('../../model_output/senate_predictions.csv')
data.head()

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.000000,0.0,0.000000,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.0500,1,31.852544,45.736514
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.000000,0.0,0.000000,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.9250,2,46.583501,60.048456
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",2247891.01,3174164.47,5422055.48,41.458281,58.541719,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.146374,0,1,38.189521,0.354297,49.190029,0.354297,West South Central,2026,0.000000,0.0,0.000000,5,Senate,1718.789084,0.354297,0.595229,11.000508,-21.474669,-8.541719,-1,-17.083438,39.138676,3.567954,0.1250,3,32.038330,46.038712
3,3,Colorado,John Hickenlooper,Mark Baisley,True,False,D,CO,"HICKENLOOPER, JOHN W.","BAISLEY, MARK",5806791.50,134872.30,5941663.80,97.730058,2.269942,5.964568,55.646542,73.317129,2.765032,16.968086,3.741915,0.400190,45.698090,4966936,806778,5773714,86.026707,13.973293,0.987401,-9.146374,1,0,0.000000,0.000000,0.000000,0.000000,Mountain,2026,0.367879,0.0,0.367879,0,Senate,9551.164309,0.000000,0.000000,0.000000,21.075509,47.730058,1,95.460117,61.913688,3.504034,99.9625,4,55.125405,68.817978
4,4,Delaware,Chris Coons,Michael Katz,True,False,D,DE,"COONS, CHRISTOPHER A.","KATZ, MICHAEL S DR.",1989694.63,29805.27,2019499.90,98.524126,1.475874,8.011194,57.479236,66.185281,3.007143,6.848324,21.107845,0.148276,35.764628,817817,172131,989948,82.612117,17.387883,0.987401,-9.146374,1,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.000000,0.0,0.000000,2,Senate,9707.003443,0.000000,0.000000,0.000000,25.168763,48.524126,1,97.048252,63.456915,3.504479,99.9875,5,56.617808,70.413755

In [374]:
data['tipping_point_prob'] = data['state_po'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.000000,0.0,0.000000,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.0500,1,31.852544,45.736514,0.0000
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.000000,0.0,0.000000,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.9250,2,46.583501,60.048456,5.2375
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",2247891.01,3174164.47,5422055.48,41.458281,58.541719,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.146374,0,1,38.189521,0.354297,49.190029,0.354297,West South Central,2026,0.000000,0.0,0.000000,5,Senate,1718.789084,0.354297,0.595229,11.000508,-21.474669,-8.541719,-1,-17.083438,39.138676,3.567954,0.1250,3,32.038330,46.038712,0.0000
3,3,Colorado,John Hickenlooper,Mark Baisley,True,False,D,CO,"HICKENLOOPER, JOHN W.","BAISLEY, MARK",5806791.50,134872.30,5941663.80,97.730058,2.269942,5.964568,55.646542,73.317129,2.765032,16.968086,3.741915,0.400190,45.698090,4966936,806778,5773714,86.026707,13.973293,0.987401,-9.146374,1,0,0.000000,0.000000,0.000000,0.000000,Mountain,2026,0.367879,0.0,0.367879,0,Senate,9551.164309,0.000000,0.000000,0.000000,21.075509,47.730058,1,95.460117,61.913688,3.504034,99.9625,4,55.125405,68.817978,0.1375
4,4,Delaware,Chris Coons,Michael Katz,True,False,D,DE,"COONS, CHRISTOPHER A.","KATZ, MICHAEL S DR.",1989694.63,29805.27,2019499.90,98.524126,1.475874,8.011194,57.479236,66.185281,3.007143,6.848324,21.107845,0.148276,35.764628,817817,172131,989948,82.612117,17.387883,0.987401,-9.146374,1,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.000000,0.0,0.000000,2,Senate,9707.003443,0.000000,0.000000,0.000000,25.168763,48.524126,1,97.048252,63.456915,3.504479,99.9875,5,56.617808,70.413755,0.6250

In [375]:
data.sort_values('tipping_point_prob', ascending=False).head(5)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
15,15,Michigan,Abdul El-Sayed,Mike J. Rogers,False,False,D,MI,"EL-SAYED, ABDUL","ROGERS, MICHAEL J",14408058.06,6831818.66,21239876.72,67.834942,32.165058,-0.192456,49.278763,77.709102,2.333008,4.148895,12.968600,0.319413,32.445883,7404258,2673073,10077331,73.474395,26.525605,0.987401,-9.146374,0,0,48.108888,8.934967,45.729013,8.934967,East North Central,2026,0.0,0.00000,0.00000,2,Senate,4601.579360,8.934967,2.989142,-2.379875,8.761462,17.834942,0,35.669884,50.428443,3.539398,54.9500,16,43.648313,57.438005,10.5375
9,9,Iowa,Josh Turek,Ashley Hinson,False,False,R,IA,"TUREK, JOSHUA","ARENHOLZ, ASHLEY HINSON",5835816.67,5267628.55,11103445.22,52.558612,47.441388,-6.092833,43.277201,88.847514,1.696738,4.401391,3.028533,0.168574,31.423453,2014831,1175538,3190369,63.153541,36.846459,0.987401,-9.146374,0,0,46.647197,5.240247,46.135733,5.240247,West North Central,2026,0.0,0.00000,0.00000,3,Senate,2762.407675,5.240247,2.289159,-0.511465,-3.039293,2.558612,0,5.117224,49.690356,3.515228,45.6000,10,42.699716,56.569823,9.5750
31,31,Texas,James Talarico,Ken Paxton,False,False,R,TX,"TALARICO, JAMES","PAXTON, WARREN KENNETH JR.",65585741.88,9020177.98,74605919.86,87.909568,12.090432,-5.916874,43.060966,48.286718,4.530331,31.642337,13.173480,0.180615,33.823334,24400697,4744808,29145505,83.720275,16.279725,0.987401,-9.146374,0,0,49.111350,7.371759,44.875863,7.371759,West South Central,2026,0.0,0.25284,-0.25284,6,Senate,7728.092153,7.371759,2.715098,-4.235488,-2.687374,37.909568,0,75.819136,51.886390,3.629676,70.1000,32,44.811968,59.107795,9.3000
24,24,Ohio,Sherrod Brown,Jon Husted,False,True,R,OH,"BROWN, SHERROD","HUSTED, JON",31146133.40,6280012.05,37426145.45,83.220254,16.779746,-5.266554,44.343385,80.925356,1.708882,3.291326,11.486903,0.076606,31.487184,9001099,2798349,11799448,76.284069,23.715931,0.987401,-9.146374,0,1,48.922377,3.215125,44.698919,3.215125,East North Central,2026,0.0,0.00000,0.00000,2,Senate,6925.610718,3.215125,1.793077,-4.223457,-1.386734,33.220254,-1,66.440509,51.164409,3.468234,63.5750,25,44.268179,58.010902,9.0375
28,28,South Carolina,Annie Andrews,Darline Graham,False,False,R,SC,"ANDREWS, ANNIE","GRAHAM, DARLINE",10677209.93,299782.64,10976992.57,97.268991,2.731009,-8.282832,40.938317,67.144996,1.378347,4.124393,24.827438,0.196629,32.129153,3477869,1640556,5118425,67.948031,32.051969,0.987401,-9.146374,0,0,44.596019,1.458879,45.788282,1.458879,South Atlantic,2026,0.0,0.00000,0.00000,5,Senate,9461.256637,1.458879,1.207841,1.192263,-7.419291,47.268991,0,94.537982,49.527087,3.547285,44.5375,29,42.530940,56.471414,8.5875

In [376]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand, dem_inc_any, rep_inc_any):
    indie_d = ['Dan Osborn', 'Brian Bengs', 'Todd Achilles', 'Seth Bodnar']
    indie_r = []
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (I)'
        dem_color = '#792ba6'
    else:
        dem_lab = dem_cand + f'{'*' if dem_inc_any == True else ''}' + ' (D)'
        dem_color = '#366bbf'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (I)'
        rep_color = '#792ba6'
    else:
        rep_lab = rep_cand + f'{'*' if rep_inc_any == True else ''}' + ' (R)'
        rep_color = '#e63929'

    return f'<b style="color:{dem_color};">' + dem_lab + f'</b> vs <b style="color:{rep_color};">' + rep_lab + '</b>'

In [377]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand'],
                                                                                                          x['dem_inc_any'], x['rep_inc_any']), axis=1)
data.head()

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.000000,0.0,0.000000,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.0500,1,31.852544,45.736514,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b..."
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.000000,0.0,0.000000,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.9250,2,46.583501,60.048456,5.2375,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>..."
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",2247891.01,3174164.47,5422055.48,41.458281,58.541719,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.146374,0,1,38.189521,0.354297,49.190029,0.354297,West South Central,2026,0.000000,0.0,0.000000,5,Senate,1718.789084,0.354297,0.595229,11.000508,-21.474669,-8.541719,-1,-17.083438,39.138676,3.567954,0.1250,3,32.038330,46.038712,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<..."
3,3,Colorado,John Hickenlooper,Mark Baisley,True,False,D,CO,"HICKENLOOPER, JOHN W.","BAISLEY, MARK",5806791.50,134872.30,5941663.80,97.730058,2.269942,5.964568,55.646542,73.317129,2.765032,16.968086,3.741915,0.400190,45.698090,4966936,806778,5773714,86.026707,13.973293,0.987401,-9.146374,1,0,0.000000,0.000000,0.000000,0.000000,Mountain,2026,0.367879,0.0,0.367879,0,Senate,9551.164309,0.000000,0.000000,0.000000,21.075509,47.730058,1,95.460117,61.913688,3.504034,99.9625,4,55.125405,68.817978,0.1375,Safe D,"<b style=""color:#366bbf;"">John Hickenlooper* (..."
4,4,Delaware,Chris Coons,Michael Katz,True,False,D,DE,"COONS, CHRISTOPHER A.","KATZ, MICHAEL S DR.",1989694.63,29805.27,2019499.90,98.524126,1.475874,8.011194,57.479236,66.185281,3.007143,6.848324,21.107845,0.148276,35.764628,817817,172131,989948,82.612117,17.387883,0.987401,-9.146374,1,0,0.000000,0.000000,0.000000,0.000000,South Atlantic,2026,0.000000,0.0,0.000000,2,Senate,9707.003443,0.000000,0.000000,0.000000,25.168763,48.524126,1,97.048252,63.456915,3.504479,99.9875,5,56.617808,70.413755,0.6250,Safe D,"<b style=""color:#366bbf;"">Chris Coons* (D)</b>..."

In [378]:
data['projected_winner'] = data['chance'].map(lambda x: 'D' if x > 50 else 'R')
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.0,0.0,0.0,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.050,1,31.852544,45.736514,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.0,0.0,0.0,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.925,2,46.583501,60.048456,5.2375,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",2247891.01,3174164.47,5422055.48,41.458281,58.541719,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.146374,0,1,38.189521,0.354297,49.190029,0.354297,West South Central,2026,0.0,0.0,0.0,5,Senate,1718.789084,0.354297,0.595229,11.000508,-21.474669,-8.541719,-1,-17.083438,39.138676,3.567954,0.125,3,32.038330,46.038712,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R

In [379]:
data['hold'] = data['projected_winner'] ==  data['current_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.0,0.0,0.0,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.050,1,31.852544,45.736514,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.0,0.0,0.0,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.925,2,46.583501,60.048456,5.2375,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip

In [380]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.0,0.0,0.0,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.050,1,31.852544,45.736514,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.7
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.0,0.0,0.0,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.925,2,46.583501,60.048456,5.2375,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+6.5
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",2247891.01,3174164.47,5422055.48,41.458281,58.541719,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.146374,0,1,38.189521,0.354297,49.190029,0.354297,West South Central,2026,0.0,0.0,0.0,5,Senate,1718.789084,0.354297,0.595229,11.000508,-21.474669,-8.541719,-1,-17.083438,39.138676,3.567954,0.125,3,32.038330,46.038712,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R,True,False,,R+21.7

In [381]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.0,0.0,0.0,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.050,1,31.852544,45.736514,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.7,99.950,0.0,100.0,<1%,>99%
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.0,0.0,0.0,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.925,2,46.583501,60.048456,5.2375,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+6.5,17.075,82.9,17.1,82.9%,17.1%
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",2247891.01,3174164.47,5422055.48,41.458281,58.541719,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.146374,0,1,38.189521,0.354297,49.190029,0.354297,West South Central,2026,0.0,0.0,0.0,5,Senate,1718.789084,0.354297,0.595229,11.000508,-21.474669,-8.541719,-1,-17.083438,39.138676,3.567954,0.125,3,32.038330,46.038712,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R,True,False,,R+21.7,99.875,0.1,99.9,<1%,>99%

In [382]:
data['swing_24_to_26'] = data['y_pred'].astype(float).map(lambda x: x - (100 - x)) - data['dem_2p_24'].astype(float).map(lambda x: x - (100 - x))
data.head(3)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.0,0.0,0.0,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.050,1,31.852544,45.736514,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.7,99.950,0.0,100.0,<1%,>99%,8.216054
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.0,0.0,0.0,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.925,2,46.583501,60.048456,5.2375,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+6.5,17.075,82.9,17.1,82.9%,17.1%,20.181814
2,2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,R,AR,"SHOFFNER, HALLIE","COTTON, THOMAS",2247891.01,3174164.47,5422055.48,41.458281,58.541719,-15.310522,34.330007,76.101134,1.188369,4.906064,14.703453,0.372273,25.731605,1670677,1340847,3011524,55.476131,44.523869,0.987401,-9.146374,0,1,38.189521,0.354297,49.190029,0.354297,West South Central,2026,0.0,0.0,0.0,5,Senate,1718.789084,0.354297,0.595229,11.000508,-21.474669,-8.541719,-1,-17.083438,39.138676,3.567954,0.125,3,32.038330,46.038712,0.0000,Safe R,"<b style=""color:#366bbf;"">Hallie Shoffner (D)<...",R,True,False,,R+21.7,99.875,0.1,99.9,<1%,>99%,9.617339

In [383]:
data['disp_24_to_26_swing'] = data['swing_24_to_26'].map(lambda x: f'D+{x:.1f}' if x > 0 else f'R+{abs(x):.1f}')
data.head(2)

,...1,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,current_party,state_po,fec_dem_fuzzymatch,fec_rep_fuzzymatch,dem_funds,rep_funds,2p_funds,dem_funds_2p_pct,rep_funds_2p_pct,pvi,dem_2p_24,cvap_white_pct,cvap_aapi_pct,cvap_hisp_pct,cvap_black_pct,cvap_natam_pct,college,urban,rural,total,urban_pct,rural_pct,polarization,generic_ballot_avg,dem_inc_dummy,rep_inc_dummy,dem_poll_avg,dem_effn,rep_poll_avg,rep_effn,census_region,year,dem_scandal_score,rep_scandal_score,net_scandal_score,demo_cluster,chamber,dem_funds_2p_pct_sqrd,effn,sqrt_effn,poll_margin,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance,swing_24_to_26,disp_24_to_26_swing
0,0,Alabama,Everett Weiss,Barry Moore,False,False,R,AL,"WESS, EVERETT W","MOORE, FELIX BARRY",9911.40,2615610.48,2625521.88,0.377502,99.622498,-14.813221,34.559388,67.988934,1.025329,2.777706,25.742051,0.294693,28.369787,2900880,2123399,5024279,57.737240,42.262760,0.987401,-9.146374,0,0,32.999181,0.560745,53.994266,0.560745,East South Central,2026,0.0,0.0,0.0,5,Senate,0.142508,0.560745,0.748829,20.995085,-20.480068,-49.622498,0,-99.244996,38.667415,3.540083,0.050,1,31.852544,45.736514,0.0000,Safe R,"<b style=""color:#366bbf;"">Everett Weiss (D)</b...",R,True,False,,R+22.7,99.950,0.0,100.0,<1%,>99%,8.216054,D+8.2
1,1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,R,AK,"PELTOLA, MARY","SULLIVAN, DANIEL J",16257753.91,8435.00,16266188.91,99.948144,0.051856,-6.455302,43.153437,64.463948,6.481397,6.051383,3.077471,12.640423,31.669629,475967,257424,733391,64.899487,35.100513,0.987401,-9.146374,0,1,48.974227,2.806404,47.234091,2.806404,Pacific,2026,0.0,0.0,0.0,5,Senate,9989.631483,2.806404,1.675232,-1.740137,-3.764231,49.948144,-1,99.896288,53.244344,3.403738,82.925,2,46.583501,60.048456,5.2375,Likely D,"<b style=""color:#366bbf;"">Mary Peltola (D)</b>...",D,False,True,Flip,D+6.5,17.075,82.9,17.1,82.9%,17.1%,20.181814,D+20.2

In [384]:
tab_data = data[['state', 'dem_cand', 'rep_cand', 'rating', 'disp_dem_chance', 'disp_rep_chance', 'projected_2p_margin', 'disp_24_to_26_swing',
                 'tipping_point_prob']]
for party in ['dem', 'rep']:
    tab_data[f'disp_{party}_chance'] = tab_data[f'disp_{party}_chance'].map(lambda x: f'<p style="color:{'blue' if party == 'dem' else 'red'};">{x}</p>')
    tab_data[f'{party}_cand'] = tab_data[f'{party}_cand'].map(lambda x: f'{x} (Ind)' if x in ['Dan Osborn', 'Brian Bengs', 
                                                                                              'Todd Achilles', 'Seth Bodnar'] else x)
tab_data = tab_data.rename({
    'state': 'State',
    'dem_cand': 'Democrat',
    'rep_cand': 'Republican',
    'rating': 'Rating',
    'disp_dem_chance': 'Dem Chance',
    'disp_rep_chance': 'Rep Chance',
    'projected_2p_margin': 'Projected Margin',
    'tipping_point_prob': 'Tipping Point Chance',
    'disp_24_to_26_swing': 'Swing from 2024 Pres'
}, axis=1)
tab_data.head()

,State,Democrat,Republican,Rating,Dem Chance,Rep Chance,Projected Margin,Swing from 2024 Pres,Tipping Point Chance
0,Alabama,Everett Weiss,Barry Moore,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+22.7,D+8.2,0.0000
1,Alaska,Mary Peltola,Dan S. Sullivan,Likely D,"<p style=""color:blue;"">82.9%</p>","<p style=""color:red;"">17.1%</p>",D+6.5,D+20.2,5.2375
2,Arkansas,Hallie Shoffner,Tom Cotton,Safe R,"<p style=""color:blue;""><1%</p>","<p style=""color:red;"">>99%</p>",R+21.7,D+9.6,0.0000
3,Colorado,John Hickenlooper,Mark Baisley,Safe D,"<p style=""color:blue;"">>99%</p>","<p style=""color:red;""><1%</p>",D+23.8,D+12.5,0.1375
4,Delaware,Chris Coons,Michael Katz,Safe D,"<p style=""color:blue;"">>99%</p>","<p style=""color:red;""><1%</p>",D+26.9,D+12.0,0.6250

In [385]:
data['rep_pred'] = data['y_pred'].map(lambda x: 100 - x)
data['projected_2p_margin_number'] = data['rep_pred'] - data['y_pred']
data['proj_seat_lean'] = data['projected_2p_margin_number'] - data['generic_ballot_avg']
sv_bias = float(data.sort_values('tipping_point_prob', ascending=False).reset_index().loc[0, 'proj_seat_lean']) # Seats-votes bias, + = R, - = D
sv_bias

8.28948816327146

In [386]:
topline_stats = pd.read_csv('display_data/topline_stats.csv')
if 'sv_bias' in topline_stats['vars'].values:
    topline_stats = topline_stats[topline_stats['vars'] != 'sv_bias']
topline_stats = pd.concat([topline_stats, pd.DataFrame({'vars': ['sv_bias'], 'x': sv_bias})], axis=0)
topline_stats.to_csv('display_data/topline_stats.csv')
topline_stats

                 vars          x
0     means_seats_tot  51.678875
1  chamber_win_chance  61.487500
0             sv_bias   8.289488

In [387]:
mean_seats_tot = topline_stats[topline_stats['vars'] == 'means_seats_tot']['x'].values[0]
chamber_win_chance = topline_stats[topline_stats['vars'] == 'chamber_win_chance']['x'].values[0]

In [388]:
chances = topline_stats[topline_stats['vars'] == 'chamber_win_chance'].set_index(['vars']).T
chances['Republicans'] = chances['chamber_win_chance'].map(lambda x: 100 - x)
chances = chances.rename({'chamber_win_chance': 'Democrats'}, axis=1).T.reset_index()
chances = chances.rename({'x': 'Win Probability'}, axis=1)
seats = topline_stats[topline_stats['vars'] == 'means_seats_tot'].set_index(['vars']).T
seats['Republicans'] = seats['means_seats_tot'].map(lambda x: 100 - x)
seats = seats.rename({'means_seats_tot': 'Democrats'}, axis=1).T.reset_index().rename({'x': 'Seat Share'}, axis=1)
summary_stats = pd.merge(left=chances, right=seats, on='vars', how='inner').rename({'vars': 'Party'}, axis=1)
summary_stats.to_csv('display_data/summary_stats.csv')
summary_stats

         Party  Win Probability  Seat Share
0    Democrats          61.4875   51.678875
1  Republicans          38.5125   48.321125

In [389]:
incl_cols = ['state', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'y_pred', 'flip_indic', 'matchup', 'swing_24_to_26', 'disp_24_to_26_swing']
disp_data = data[incl_cols]

In [390]:
rating_ts = output_ts[output_ts['type'] == 'chance']
rating_ts['rating'] = rating_ts['y'].map(get_rating)
rating_ts['date'] = pd.to_datetime(rating_ts['date'])
rating_ts.head()

         date        y        geo    type    rating
1  2026-09-27  58.6000  US Senate  chance    Tossup
5  2026-09-27   0.0500         AL  chance    Safe R
10 2026-09-27  79.8875         AK  chance  Likely D
15 2026-09-27   0.1250         AR  chance    Safe R
20 2026-09-27  99.9625         CO  chance    Safe D

In [391]:
## Alert when there's a rating change
today_date = rating_ts['date'].max()
yesterday = rating_ts[rating_ts['date'] != today_date]['date'].max()

today_ratings = rating_ts[rating_ts['date'] == today_date]
yester_ratings = rating_ts[rating_ts['date'] == yesterday]
compare_df = pd.merge(left=today_ratings, right=yester_ratings, on='geo', how='left', suffixes=['_t', '_y'])
compare_df.head()

,date_t,y_t,geo,type_t,rating_t,date_y,y_y,type_y,rating_y
0,2026-10-06,61.4875,US Senate,chance,Tilt D,2026-10-05,59.3625,chance,Tossup
1,2026-10-06,0.0500,AL,chance,Safe R,2026-10-05,0.0500,chance,Safe R
2,2026-10-06,82.9250,AK,chance,Likely D,2026-10-05,82.9625,chance,Likely D
3,2026-10-06,0.1250,AR,chance,Safe R,2026-10-05,0.1250,chance,Safe R
4,2026-10-06,99.9625,CO,chance,Safe D,2026-10-05,99.9625,chance,Safe D

In [392]:
## This is the cell that actually alerts when there's a rating change
if any(compare_df['rating_t'] != compare_df['rating_y']):
    changes_df = compare_df[compare_df['rating_t'] != compare_df['rating_y']][['geo', 'rating_y', 'rating_t']]
    print(changes_df)
else:
    print("No rating changes today!")

          geo       rating_y rating_t
0   US Senate         Tossup   Tilt D
11         KS         Lean R   Tilt R
21         NH  Very Likely D   Safe D
32         TX         Tilt D   Lean D

In [393]:
if any(compare_df['rating_t'] != compare_df['rating_y']):
    print(changes_df.shape)

(4, 3)

In [394]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
tab_data.to_csv('display_data/table_display_data.csv')
data.to_csv('display_data/all_data.csv')